### PR TITLE
Check class type to account for the reason enum being “-1”

### LINKED ISSUE #998: SDL Proxy crash happens when receiving SDLOnAppInterfaceUnregistered notification with reason -1 (INVALID_ENUM)
### Bug Report
SDL Proxy crash happens at following line when the ‘reason” is -1.
https://github.com/smartdevicelink/sdl_ios/blob/6.0.0-rc.2/SmartDeviceLink/SDLLifecycleManager.m#L672

Proxy expects that it contains string value, however, it contains integer value -1 and causes crash.

We need one of following fix.
1. Add type check in Proxy.
2. Fix Core not to send -1.

Default value of this ‘reason’ in SDL Core is -1 (INVALID_ENUM). 
https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/application_manager_impl.cc#L167

INVALID_ENUM is not defined in AppInterfaceUnregisteredReason in MOBILE_API.xml. 
https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L401
Therefore, I think it is good to fix SDL Core not to send -1. But I cannot judge which is better.

Backtrace
> Thread 4 name:  Dispatch queue: com.sdl.lifecycle
> Thread 4 Crashed:
> 0   libsystem_kernel.dylib        	0x00000001845dd348 __pthread_kill + 8
> 1   libsystem_pthread.dylib       	0x00000001846f1344 pthread_kill$VARIANT$mp + 396
> 2   libsystem_c.dylib             	0x000000018454cfb8 abort + 140
> 3   libc++abi.dylib               	0x0000000183cec068 __cxa_bad_cast + 0
> 4   libc++abi.dylib               	0x0000000183cec210 default_unexpected_handler+ 8720 () + 0
> 5   libobjc.A.dylib               	0x0000000183d14810 _objc_terminate+ 34832 () + 124
> 6   libc++abi.dylib               	0x0000000183d0454c std::__terminate(void (*)+ 107852 ()) + 16
> 7   libc++abi.dylib               	0x0000000183d03ea8 __cxxabiv1::exception_cleanup_func+ 106152 (_Unwind_Reason_Code, _Unwind_Exception*) + 0
> 8   libobjc.A.dylib               	0x0000000183d1465c _objc_exception_destructor+ 34396 (void*) + 0
> 9   CoreFoundation                	0x0000000184ad31c8 __methodDescriptionForSelector + 0
> 10  CoreFoundation                	0x0000000184acb6b0 ___forwarding___ + 1380
> 11  CoreFoundation                	0x00000001849b101c _CF_forwarding_prep_0 + 92
> 12  SmartDeviceLink               	0x0000000104e30e6c -[SDLLifecycleManager sdl_remoteHardwareDidUnregister:] + 642668 (SDLLifecycleManager.m:672)
> 13  SmartDeviceLink               	0x0000000104e3099c __51-[SDLLifecycleManager remoteHardwareDidUnregister:]_block_invoke + 641436 (SDLLifecycleManager.m:657)
> 14  libdispatch.dylib             	0x0000000184449088 _dispatch_call_block_and_release + 24
> 15  libdispatch.dylib             	0x0000000184449048 _dispatch_client_callout + 16
> 16  libdispatch.dylib             	0x0000000184452e48 _dispatch_queue_serial_drain$VARIANT$mp + 528
> 17  libdispatch.dylib             	0x00000001844537d8 _dispatch_queue_invoke$VARIANT$mp + 340
> 18  libdispatch.dylib             	0x0000000184454200 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 400
> 19  libdispatch.dylib             	0x000000018445c4a0 _dispatch_workloop_worker_thread$VARIANT$mp + 644
> 20  libsystem_pthread.dylib       	0x00000001846eefd0 _pthread_wqthread + 932
> 21  libsystem_pthread.dylib       	0x00000001846eec20 start_wqthread + 4
> 
> 

##### Reproduction Steps
1. Register SDL iOS app to SDL Core
2. Unregister app at HU

##### Expected Behavior
SDL iOS app does not crash

##### Observed Behavior
SDL iOS app crashes

##### OS & Version Information
* iOS Version: all
* SDL iOS Version: 6.0.0 rc2
* Testing Against: Our internal HU devboard and internal testing HS app

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #998

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Unregistering was tested, but not with "-1", because I was unable to replicate that.

### Summary
Checks the type of data the unregister reason is before attempting to read it.

##### Bug Fixes
* Fix an unregister reason of "-1" crashing the library.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by t-yoshii** [comment]
Hi @joeljfischer , thank you very much for creating fix!
I confirmed this fix is effective with reason -1. I tested this commit with Xevo's internal HU.

File: SmartDeviceLink/SDLLifecycleManager.m [hunk 1]
```diff
@@ -669,7 +669,7 @@ - (void)sdl_remoteHardwareDidUnregister:(SDLRPCNotificationNotification *)notifi
         [self.lifecycleStateMachine transitionToState:SDLLifecycleStateStopped];
     } else if ([self.lifecycleStateMachine isCurrentState:SDLLifecycleStateStopped]) {
         return;
-    } else if ([appUnregisteredNotification.reason isEqualToEnum:SDLAppInterfaceUnregisteredReasonAppUnauthorized]) {
+    } else if ([appUnregisteredNotification.reason isKindOfClass:[NSString class]] && [appUnregisteredNotification.reason isEqualToEnum:SDLAppInterfaceUnregisteredReasonAppUnauthorized]) {
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLLifecycleManager.m]: There should be a comment saying that the class check is a hax to fix a Core bug.
