### PR TITLE
Bugfix/issue 1633 open sub menu

### LINKED ISSUE #1633: Default cellID value passed in during openSubMenu method call
##### Bug Report
If you recreate and pass in a `SDLMenuCell` with submenu that already exists in the current default SDL `menu` to the `SDLMenuManager`'s `openSubMenu:` method, the request will fail as it will use the default `cellID` value of `UINT32_MAX` (4294967295). We should add a check for the default `cellID` value and return `NO` with an error message when this happens.

##### Reproduction Steps
1. Connect app to sdl_core and launch the SDL app. Send a `SDLMenuCell` with submenu to the built-in SDL menu.
2. Recreate the same `SDLMenuCell` with submenu and pass it into a `openSubMenu:` call.
3. Observe behavior.

##### Expected Behavior
`openSubMenu` should catch error and return `NO`

##### Observed Behavior
sdl_core (debug mode) shuts down.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.6.0rc-1
* Testing Against: sdl_core (commit: d2331b066ebb30305f1a5df644511f0f72a2381f (HEAD -> release/6.1.0)) and sdl_hmi (commit cd3da85cdb7240a7b5f88d016dea7604158642b1 (HEAD -> Master)

### PR DESCRIPTION
**Pull request by jshivabeharry**
Fixes #1633 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Created a unit test to check when a submenu item is added to the menu and the same recreated cell is opened with openSubmenu it performs a successful transaction and is able to send an RPC.

#### Core Tests
In manticore I created a function that returns a menu with a submenu. I Added this menu into the screen managers menu property. I then called the function again to recreate the same menu cell inside a ```openSubMenu``` call. Before, it would fail with an error due to the default cell ID set to ```UINT32_MAX```, after changes it would successfully open the menu cell.

Core version / branch / commit hash / module tested against: sdl_core 8.1.0 (manticore)
HMI name / version / branch / commit hash / module tested against: generic_hmi 0.12.0 (manticore)

### Summary
- Added check for a clone cell in ```openMenu```
- Added additional unit test in ```SDLMenuManagerSpec.m```

##### Breaking Changes
* NA

##### Enhancements
* NA

##### Bug Fixes
* Fixes ```openMenu``` and ```openSubMenu``` calls when trying to open a copied cell

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 1]
```diff
@@ -227,6 +227,16 @@ - (BOOL)openMenu:(nullable SDLMenuCell *)cell {
         return NO;
     }
 
+    // Check for cloned cell
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:230]:
```suggestion
    // Check if a passed cell is a "re-created" cell without a cellID. If it is, then try to find the equivalent cell and use it instead
```

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 2]
```diff
@@ -227,6 +227,16 @@ - (BOOL)openMenu:(nullable SDLMenuCell *)cell {
...
+    if (cell != nil) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:231]:
```suggestion
    if (cell != nil && cell.cellId == UINT32_MAX) {
```

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 3]
```diff
@@ -227,6 +227,16 @@ - (BOOL)openMenu:(nullable SDLMenuCell *)cell {
...
+        for(id clonedCell in self.menuCells) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:232]:
```suggestion
        for (SDLMenuCell *headUnitCell in self.menuCells) {
```

Make sure to be as specific as possible

File: SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m [hunk 4]
```diff
@@ -269,6 +269,17 @@ @interface SDLMenuManager()
                     expect(canSendRPC).to(equal(YES));
                 });
 
+                // should queue an open menu operation for a copied submenu cell
+                it(@"should queue an open menu operation for a copied submenu cell", ^ {
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m:273]: Tests that are added for a bug fix like this should fail before the fix is applied. This one passes.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]
