### PR TITLE
Fixed "potential null dereference" warnings

### LINKED ISSUE #1988: Fix "Potential null dereference" warnings
### Bug Report
In Xcode there are three "Potential null dereference" warnings in the project on buildtime.

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: Branch Develop
* Testing Against: N/A

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1988 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Added additional nil check before setting the error variable

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* N/A

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLProtocol.m [hunk 1]
```diff
@@ -305,7 +305,7 @@ - (BOOL)sendRPC:(SDLRPCMessage *)message encrypted:(BOOL)encryption error:(NSErr
     // Convert the message dictionary to JSON and return early if it fails
     NSError *jsonError = nil;
     NSData *jsonData = [NSJSONSerialization dataWithJSONObject:[message serializeAsDictionary:(Byte)[SDLGlobals sharedGlobals].protocolVersion.major] options:kNilOptions error:&jsonError];
-    if (jsonError != nil) {
+    if (jsonError != nil && error != nil) {
         SDLLogE(@"Error encoding JSON data: %@", jsonError);
         *error = jsonError;
         return NO;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLProtocol.m:311]: This should still print the error and return NO if `error == nil`

File: SmartDeviceLink/private/SDLProtocol.m [hunk 2]
```diff
@@ -382,7 +382,7 @@ - (BOOL)sendRPC:(SDLRPCMessage *)message encrypted:(BOOL)encryption error:(NSErr
     // If the message should be encrypted, encrypt the payloads
     if (encryption) {
         BOOL success = [self sdl_encryptProtocolMessages:protocolMessages error:error];
-        if (!success) {
+        if (!success && error != nil) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLProtocol.m:385]: I don't think this change is necessary

File: SmartDeviceLink/private/SDLProtocol.m [hunk 3]
```diff
@@ -410,7 +410,7 @@ - (BOOL)sdl_encryptProtocolMessages:(NSArray<SDLProtocolMessage *> *)protocolMes
         NSData *encryptedMessagePayload = [self.securityManager encryptData:message.payload withError:&encryptError];
 
         // If the encryption failed, pass back the error and return false
-        if (encryptedMessagePayload.length == 0 || encryptError != nil) {
+        if ((encryptedMessagePayload.length == 0 || encryptError != nil) && error != nil) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLProtocol.m:413]: See above about still needing to return even if `error == nil`

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]
