### PR TITLE
Fixed the soft button operation not finishing if no image or text buttons sent

### LINKED ISSUE #1294: SDLSoftButtonReplaceOperation finish operation not called if no image buttons or text buttons uploaded
### Bug Report
The `SDLSoftButtonReplaceOperation` is never finished if the head unit does not support soft button images and some of the soft buttons do not have text (i.e. they are image only). So if other operations are added to the `transactionQueue` in the `SDLSoftButtonManager`, they never execute.

##### Reproduction Steps
1. Connect the Swift sdl_ios example app to Manticore via TCP transport
1. Make the `hmiLevel` `FULL` by selecting the app icon

##### Expected Behavior
All the soft buttons appear. 

##### Observed Behavior
No soft buttons ever appear.
What happens is that:
1. The RAI `displayCapabilities` is `nil` so no soft buttons are sent in the first `SDLSoftButtonReplaceOperation` added to the queue. This is because the example app has image-only soft buttons. 
1. When the app sends a `SetDisplayLayout` request, the soft button manager adds a new `SDLSoftButtonReplaceOperation` to the transaction queue with the new display capabilities but the operation never executes.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.2
* Testing Against: Manticore

##### Test Case, Sample Code, and / or Example App
Swift sdl_ios example app.

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #1294 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Test cases added

### Summary
The `SDLSoftButtonReplaceOperation` is never finished if the head unit does not support soft button images and some of the soft buttons do not have text (i.e. they are image only). So if other operations are added to the `transactionQueue` in the `SDLSoftButtonManager`, they never execute.

##### Bug Fixes
* Fixed the soft button operation not finishing if no image or text buttons sent by the operation.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLSoftButtonReplaceOperation.m [hunk 1]
```diff
@@ -56,11 +56,17 @@ - (void)start {
         SDLLogW(@"Soft button images are not supported. Attempting to send text-only soft buttons. If any button does not contain text, no buttons will be sent.");
 
         // Send text buttons if all the soft buttons have text
-        [self sdl_sendCurrentStateTextOnlySoftButtonsWithCompletionHandler:^{}];
+        __weak typeof(self) weakself = self;
+        [self sdl_sendCurrentStateTextOnlySoftButtonsWithCompletionHandler:^(BOOL success) {
+            if (!success) {
+                SDLLogE(@"Head unit does not support images and some of the soft buttons do not have text, so none of the buttons will be sent.");
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSoftButtonReplaceOperation.m]: Isn't this redundant with the warning at L224?

Comment (NicoleYarroch) [reply SmartDeviceLink/SDLSoftButtonReplaceOperation.m]: I don't think so. The warning on L224 can be benign if the head unit supports images but the library can't send the text only buttons because not all buttons have text (i.e. eventually the image + text buttons will be sent). This error is only printed if the head unit does not support images and the library can't send text-only buttons.
