### PR TITLE
Upload HTTP System Request Data Correctly

### LINKED ISSUE #364: Support for the HTTP requestType is missing
### Bug Report
HTTP RequestType support is missing - this is required for unencrypted policy table updates to work in SDL Core.

##### Reproduction Steps
https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m#L314-L326

##### Expected Behavior
Working on it.... I don't know yet

##### Observed Behavior
Requests are just dropped

### PR DESCRIPTION
**Pull request by justinjdickow**
Fixes #364 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

Our previous update to this did not properly handle the data that was being sent over from core to be delivered to the server. The previous method we used, which was `uploadForBodyDataDictionary:URLString:completionHandler` assumed a format for the data dictionary that is not the same as is being used in the HTTP request.

I created a new method to handle this particular case properly... :-1:

### CODE REVIEW

File: SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m [hunk 1]
```diff
@@ -436,15 +436,12 @@ - (void)handleSystemRequestHTTP:(SDLOnSystemRequest *)request {
     }
     
     NSError *error = nil;
-    NSDictionary *body = [NSJSONSerialization JSONObjectWithData:request.bulkData options:kNilOptions error:&error];
     if (error) {
```
Comment (joeljfischer) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m]: Error literally cannot be anything but nil here.

**Comment by justinjdickow** [comment]
:+1:
