### PR TITLE
Fixed file manager race condition

### LINKED ISSUE #1264: 'SDLManagerDelegate`s are not called if the data session is established successfully but the lifecycle manager does not transition to state ready
### Bug Report
The app's `SDLManagerDelegate`s are not called if the data session is established successfully but the lifecycle manager never ends up in state `SDLLifecycleStateReady`. 

This appears to be some sort of race condition in the lifecycle manager. The lifecycle manager was stuck in state `SDLLifecycleStateSettingUpManagers` so even though Core was sending notifications the app did not get the notifications because the lifecycle manager never finished setting up. 

##### Reproduction Steps
1. Race condition. I only had it happen once.  

##### Expected Behavior
If the lifecycle manager errors out when setting up, the data session should be destroyed and re-created.

##### Observed Behavior
The data session stays open, but the app does not get notifications from Core. This means the SDL app UI is empty. 

##### OS & Version Information
* iOS Version: 12.1.4
* SDL iOS Version: 6.2
* Testing Against: SYNC 3.4 

##### Test Case, Sample Code, and / or Example App
Swift example app in the SDL_iOS library

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #1264 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
* Unit tests added

### Summary
* Fixed the file manager adding file uploads to the transaction queue after the file manager transitioned to state shutdown. The operation would never finish so any uploads added after the file manager transitioned back to the ready state would not run. 

##### Breaking Changes
* n/a

##### Bug Fixes
* Fixed the file manager adding file uploads to the transaction queue after the file manager has shutdown. 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLFileManager.m [hunk 1]
```diff
@@ -526,11 +524,28 @@ - (float)sdl_uploadPercentage:(float)totalBytes uploadedBytes:(float)uploadedByt
  *  @return                 True if the file still needs to be (re)sent to Core; false if not.
  */
 - (BOOL)sdl_canFileBeUploadedAgain:(nullable SDLFile *)file maxUploadCount:(UInt8)maxUploadCount failedFileUploadsCount:(NSMutableDictionary<SDLFileName *, NSNumber<SDLUInt> *> *)failedFileUploadsCount {
-    if (!file || [self hasUploadedFile:file]) {
+    if (![self.currentState isEqualToString:SDLFileManagerStateReady]) {
+        SDLLogE(@"File named %@ failed to upload. The file manager has shutdown so the file will not be sent again.", file.name);
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLFileManager.m]: Make this a warning. Change string to `File named %@ failed to upload. The file manager has shutdown so the file upload will not retry.`

File: SmartDeviceLink/SDLFileManager.m [hunk 2]
```diff
@@ -526,11 +524,28 @@ - (float)sdl_uploadPercentage:(float)totalBytes uploadedBytes:(float)uploadedByt
...
+        return NO;
+    }
+
+    if (!file) {
+        SDLLogE(@"File named %@ can not be uploaded because it is not a valid file.", file.name);
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLFileManager.m]: The `%@, file.name` won't work here because the file doesn't exist!

File: SmartDeviceLink/SDLFileManager.m [hunk 3]
```diff
@@ -526,11 +524,28 @@ - (float)sdl_uploadPercentage:(float)totalBytes uploadedBytes:(float)uploadedByt
...
+        return NO;
+    }
+
+    if ([self hasUploadedFile:file]) {
+        SDLLogE(@"File named %@ has already been uploaded.", file.name);
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLFileManager.m]: This should be a debug message, maybe a warning at the most.

File: SmartDeviceLink/SDLFileManager.m (hunk 1 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLFileManager.m]: Fixed

File: SmartDeviceLink/SDLFileManager.m (hunk 3 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLFileManager.m]: Fixed

File: SmartDeviceLink/SDLFileManager.m (hunk 2 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLFileManager.m]: Fixed
