### PR TITLE
Fix SDLShow initializer crash

### LINKED ISSUE #966: SDLShow initializer will crash if SDLMetadataType is nil
### Bug Report
If `SDLShow initWithMainField1:(nullable NSString *)mainField1 mainField1Type:(nullable SDLMetadataType)mainField1Type mainField2:(nullable NSString *)mainField2 mainField2Type:(nullable SDLMetadataType)mainField2Type alignment:(nullable SDLTextAlignment)alignment` is called with a nil `mainField1(/2)Type`, a crash will occur, even though those parameters are listed as nullable.

##### Reproduction Steps
1. Call `initWithMainField1:(nullable NSString *)mainField1 mainField1Type:(nullable SDLMetadataType)mainField1Type mainField2:(nullable NSString *)mainField2 mainField2Type:(nullable SDLMetadataType)mainField2Type alignment:(nullable SDLTextAlignment)alignment` with `nil` `mainField1Type`.

##### Expected Behavior
The method returns successfully without that parameter set

##### Observed Behavior
An exception crash occurs

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: v5.3.0 WIP
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #966 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
New unit tests for some initializers added to Show, including this case

### Summary
Fix SDLShow initializer `initWithMainField1:mainField1Type:mainField2:mainField2Type:alignment:` failing with nil `type`s.

##### Bug Fixes
* Fix SDLShow initializer `initWithMainField1:mainField1Type:mainField2:mainField2Type:alignment:` failing with nil `type`s.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLShowSpec.m [hunk 1]
```diff
@@ -110,6 +76,115 @@
         expect(testRequest.customPresets).to(beNil());
         expect(testRequest.metadataTags).to(beNil());
     });
+
+    fdescribe(@"initializing", ^{
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLShowSpec.m]: Remove the *f* from`fdescribe`.

File: SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLShowSpec.m [hunk 2]
```diff
@@ -110,6 +76,115 @@
...
+            expect(testShow.alignment).to(equal(testAlignment));
+            expect(testShow.statusBar).to(beNil());
+            expect(testShow.mediaClock).to(beNil());
+            expect(testShow.mediaTrack).to(beNil());
+            expect(testShow.graphic).to(beNil());
+            expect(testShow.secondaryGraphic).to(beNil());
+            expect(testShow.softButtons).to(beNil());
+            expect(testShow.customPresets).to(beNil());
+            expect(testShow.metadataTags.mainField1).to(equal(testType1));
+            expect(testShow.metadataTags.mainField2).to(equal(testType2));
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLShowSpec.m]:
```
expect(testShow.metadataTags.mainField1).to(equal(testType1));
expect(testShow.metadataTags.mainField2).to(equal(testType2));
```

These two test case are failing
