### PR TITLE
Change SDLLockScreenViewController modalPresentationStyle

### LINKED ISSUE #1794: Update SDLLockScreenViewController to be `modalPresentationStyle` == `UIModalPresentationFullScreen` by default
### Bug Report
The default presentation style, automatic, is dismissible in iOS 13 / 14, so we need to use `.fullscreen` by default for custom lock screens.

##### Reproduction Steps
1. Create a subclass of `SDLLockScreenViewController` and set it to be the custom lock screen
2. Present the lock screen

##### Expected Behavior
The lock screen is not dismissible and appears full-screen.

##### Observed Behavior
The lock screen is dismissible and appears non-full-screen

##### OS & Version Information
* iOS Version: 14.0.1
* SDL iOS Version: 7.0.0-develop
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1794 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Changed SDLLockScreenViewController modalPresentationStyle that was dismissed by default in case the user haven't set one.

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Changed SDLLockScreenViewController modalPresentationStyle that was dismissed by default in case the user haven't set one.

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/public/SDLLockScreenViewController.m [hunk 1]
```diff
@@ -33,6 +33,11 @@ @interface SDLLockScreenViewController ()
 
 @implementation SDLLockScreenViewController
 
+- (void)awakeFromNib {
+    [super awakeFromNib];
+    self.modalPresentationStyle = UIModalPresentationFullScreen;
+}
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLLockScreenViewController.m:39]: Override the `modalPresentationStyle` method instead of this

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/public/SDLLockScreenViewController.h [hunk 2]
```diff
@@ -16,6 +16,11 @@ NS_ASSUME_NONNULL_BEGIN
 /// A block that can be used to close the lockscreen when the user swipes on the lockscreen. Override this in your own custom view controllers if you build a custom lock screen.
 typedef void (^SwipeGestureCallbackBlock)(void);
 
+/**
+ *  The SDL Lock Screen's presentation style.
+ */
+@property(nonatomic, assign) UIModalPresentationStyle modalPresentationStyle;
+
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLLockScreenViewController.h:23]: This is not correct. You are not re-defining a property, you are overriding it. Did you test this? I don't think this would work.

```suggestion
```

File: SmartDeviceLink/public/SDLLockScreenViewController.m [hunk 3]
```diff
@@ -32,6 +32,7 @@ @interface SDLLockScreenViewController ()
 
 
 @implementation SDLLockScreenViewController
+@synthesize modalPresentationStyle = _modalPresentationStyle;
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLLockScreenViewController.m:35]: This is not correct. Did you test this? I don't think it would work

```suggestion
```

File: SmartDeviceLink/public/SDLLockScreenViewController.m [hunk 4]
```diff
@@ -61,6 +62,10 @@ - (UIStatusBarStyle)preferredStatusBarStyle {
     return useWhiteIcon ? UIStatusBarStyleLightContent : UIStatusBarStyleDefault;
 }
 
+- (UIModalPresentationStyle)modalPresentationStyle {
+    return _modalPresentationStyle;
+}
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLLockScreenViewController.m:67]: This is not correct. You are not trying to re-define it, you're trying to override it.

```suggestion
- (UIModalPresentationStyle)modalPresentationStyle {
    return UIModalPresentationFullScreen;
}
```

File: SmartDeviceLink/public/SDLLockScreenViewController.m [hunk 5]
```diff
@@ -87,6 +92,18 @@ - (void)setLockedLabelText:(NSString *_Nullable)lockedLabelText {
...
+        if (modalPresentationStyle == UIModalPresentationAutomatic) {
+            _modalPresentationStyle = UIModalPresentationFullScreen;
+        } else {
+            _modalPresentationStyle = modalPresentationStyle;
+        }
+    } else {
+        _modalPresentationStyle = modalPresentationStyle;
+    }
+}
+
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLLockScreenViewController.m:106]: This seems unnecessary to me. We just override it to be `UIModalPresentationFullScreen`. The dev should be subclassing this and can override it if they want something different.

```suggestion
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]
You're still doing a lot of unnecessary work. Please just do what I mentioned here.

File: SmartDeviceLink/public/SDLLockScreenViewController.h (hunk 2 above)
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLLockScreenViewController.h:23]: This is not correct. You are not re-defining a property, you should be overriding it.

```suggestion
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]
