### PR TITLE
Make system capability manager thread safe

### LINKED ISSUE #1709: The SystemCapabilityManager needs to be made thread safe
### Bug Report
Experienced a crash due to the `capabilityObservers` dictionary being mutated while being enumerated. Access to the  `capabilityObservers`, `subscriptionStatus` and `appServicesCapabilitiesDictionary` dictionaries should be made thread safe.

##### Reproduction Steps
1. This is a race condition so it will be difficult to reproduce. I've only had this crash happen once.
```
2020-07-13 08:03:40.106712-0400 SDL_Smoke_Tests[3814:62891] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSArrayM: 0x6000008f1e60> was mutated while being enumerated.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3cf0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ba89b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e39e10 +[__NSFastEnumerationEnumerator allocWithZone:] + 0
	3   SmartDeviceLink                     0x00000001023b7fa4 -[SDLSystemCapabilityManager sdl_callObserversForUpdate:error:handler:] + 1076
	4   SmartDeviceLink                     0x00000001023ba178 -[SDLSystemCapabilityManager sdl_registerResponse:] + 1928
	5   CoreFoundation                      0x00007fff23d67dcc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x00007fff23d67245 _CFXRegistrationPost1 + 421
	7   CoreFoundation                      0x00007fff23d66fb1 ___CFXNotificationPost_block_invoke + 193
	8   CoreFoundation                      0x00007fff23e64513 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1795
	9   CoreFoundation                      0x00007fff23d66906 _CFXNotificationPost + 950
	10  SmartDeviceLink                     0x00000001023092c2 -[SDLNotificationDispatcher postRPCResponseNotification:response:] + 178
	11  SmartDeviceLink                     0x00000001022d04f4 -[SDLLifecycleProtocolHandler sdl_sendCallbackForMessage:] + 660
	12  SmartDeviceLink                     0x00000001022d0130 -[SDLLifecycleProtocolHandler onProtocolMessageReceived:] + 656
	13  SmartDeviceLink                     0x0000000102336fd7 -[SDLProtocol onProtocolMessageReceived:] + 1079
	14  SmartDeviceLink                     0x000000010233bf5f -[SDLProtocolReceivedMessageRouter sdl_dispatchProtocolMessage:] + 175
	15  SmartDeviceLink                     0x000000010233be52 -[SDLProtocolReceivedMessageRouter handleReceivedMessage:] + 194
	16  SmartDeviceLink                     0x0000000102333c78 -[SDLProtocol sdl_processMessages] + 2712
	17  SmartDeviceLink                     0x00000001023331c7 -[SDLProtocol sdl_handleBytesFromTransport:] + 343
	18  SmartDeviceLink                     0x000000010232db9f -[SDLProtocol onDataReceived:] + 63
	19  SmartDeviceLink                     0x00000001023bfe6a -[SDLTCPTransport sdl_readFromStream] + 1978
	20  SmartDeviceLink                     0x00000001023bf0ff -[SDLTCPTransport stream:handleEvent:] + 783
	21  CoreFoundation                      0x00007fff23db8727 _signalEventSync + 247
	22  CoreFoundation                      0x00007fff23db57bb _cfstream_solo_signalEventSync + 267
	23  CoreFoundation                      0x00007fff23db5663 _CFStreamSignalEvent + 499
	24  CFNetwork                           0x00007fff2302c68c _CFStreamErrorFromCFError + 139730
	25  CFNetwork                           0x00007fff23033b49 _CFStreamErrorFromCFError + 169615
	26  CoreFoundation                      0x00007fff23da842d __CFSocketPerformV0 + 1181
	27  CoreFoundation                      0x00007fff23da0d31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	28  CoreFoundation                      0x00007fff23da0c5c __CFRunLoopDoSource0 + 76
	29  CoreFoundation                      0x00007fff23da0434 __CFRunLoopDoSources0 + 180
	30  CoreFoundation                      0x00007fff23d9b02e __CFRunLoopRun + 974
	31  CoreFoundation                      0x00007fff23d9a944 CFRunLoopRunSpecific + 404
	32  Foundation                          0x00007fff25939c71 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 211
	33  SmartDeviceLink                     0x00000001023be404 -[SDLTCPTransport sdl_tcpTransportEventLoop] + 2180
	34  Foundation                          0x00007fff2594f9eb __NSThread__start__ + 1047
	35  libsystem_pthread.dylib             0x00007fff51c0c109 _pthread_start + 148
	36  libsystem_pthread.dylib             0x00007fff51c07b8b thread_start + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

##### Expected Behavior
No crash

##### Observed Behavior
App crashed 

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.7
* Testing Against: Manticore (Core v6.1.1, Generic HMI v0.8.1)

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #1709

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Existing unit tests were run. No additional tests added since the system capability manager was made thread safe. 

#### Core Tests
Connected and reconnected to Manticore many times.

Core version / branch / commit hash / module tested against: Manticore (Core v6.1.1)
HMI name / version / branch / commit hash / module tested against: Manticore (Generic HMI v0.8.1)

### Summary
Fixed crash occurring in the System Capability Manager due to a dictionary being mutated during enumeration. 

##### Bug Fixes
* Dictionaries in the System Capability Manager are now thread safe. 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLSystemCapabilityManager.m [hunk 1]
```diff
@@ -801,6 +792,48 @@ - (void)sdl_hmiStatusNotification:(SDLRPCNotificationNotification *)notification
...
+    __block NSMutableDictionary<SDLSystemCapabilityType, NSMutableArray<SDLSystemCapabilityObserver *> *> *dict = nil;
+    [self sdl_runSyncOnQueue:^{
+        dict = self->_capabilityObservers;
+    }];
+
+    return dict;
+}
+
+- (NSMutableDictionary<SDLSystemCapabilityType, NSNumber<SDLBool> *> *)subscriptionStatus {
+    __block  NSMutableDictionary<SDLSystemCapabilityType, NSNumber<SDLBool> *> *dict = nil;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSystemCapabilityManager.m:820]:
```suggestion
    __block NSMutableDictionary<SDLSystemCapabilityType, NSNumber<SDLBool> *> *dict = nil;
```

File: SmartDeviceLink/SDLSystemCapabilityManager.m [hunk 2]
```diff
@@ -801,6 +792,48 @@ - (void)sdl_hmiStatusNotification:(SDLRPCNotificationNotification *)notification
...
+        dispatch_sync(self.readWriteQueue, block);
+    }
+}
+
+#pragma mark Getters
+
+- (NSMutableDictionary<SDLSystemCapabilityType, NSMutableArray<SDLSystemCapabilityObserver *> *> *)capabilityObservers {
+    __block NSMutableDictionary<SDLSystemCapabilityType, NSMutableArray<SDLSystemCapabilityObserver *> *> *dict = nil;
+    [self sdl_runSyncOnQueue:^{
+        dict = self->_capabilityObservers;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSystemCapabilityManager.m:813]: Why are you using `->` instead of `.`?

File: SmartDeviceLink/SDLSystemCapabilityManager.m [hunk 3]
```diff
@@ -128,14 +136,15 @@ - (void)stop {
     _videoStreamingCapability = nil;
     _remoteControlCapability = nil;
     _seatLocationCapability = nil;
-    _appServicesCapabilitiesDictionary = [NSMutableDictionary dictionary];
 
     _supportsSubscriptions = NO;
-    [_capabilityObservers removeAllObjects];
-    [_subscriptionStatus removeAllObjects];
+    [self sdl_runSyncOnQueue:^{
+        self->_appServicesCapabilitiesDictionary = [NSMutableDictionary dictionary];
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSystemCapabilityManager.m:142]: Why are you using `->` instead of `.`?

File: SmartDeviceLink/SDLSystemCapabilityManager.m (hunk 2 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLSystemCapabilityManager.m:812]: If you access the variable within its own getter using `self.`, it causes infinite recursion.

File: SmartDeviceLink/SDLSystemCapabilityManager.m [hunk 4]
```diff
@@ -584,15 +550,27 @@ - (BOOL)subscribeToCapabilityType:(SDLSystemCapabilityType)type withObserver:(id
...
 
     SDLSystemCapabilityObserver *observerObject = [[SDLSystemCapabilityObserver alloc] initWithObserver:observer selector:selector];
+
+    id<NSObject> subscribedObserver = [self sdl_subscribeToCapabilityType:type observerObject:observerObject];
+    return subscribedObserver == nil ? NO : YES;
+}
+
+/// Helper method for subscribing to a system capability type
+/// @param type The SystemCapabilityType that will be subscribed
+/// @param observerObject An object that can be used to unsubscribe the block. If nil, the subscription was not succesful.
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLSystemCapabilityManager.m:560]: Fixed

File: SmartDeviceLink/SDLSystemCapabilityManager.m [hunk 5]
```diff
@@ -128,14 +136,15 @@ - (void)stop {
...
-    _appServicesCapabilitiesDictionary = [NSMutableDictionary dictionary];
 
     _supportsSubscriptions = NO;
-    [_capabilityObservers removeAllObjects];
-    [_subscriptionStatus removeAllObjects];
+    [self sdl_runSyncOnQueue:^{
+        self->_appServicesCapabilitiesDictionary = [NSMutableDictionary dictionary];
+        [self->_capabilityObservers removeAllObjects];
+        [self->_subscriptionStatus removeAllObjects];
+    }];
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLSystemCapabilityManager.m]: Fixed.

File: SmartDeviceLink/SDLSystemCapabilityManager.m (hunk 4 above)
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLSystemCapabilityManager.m:560]: Fixed.

File: SmartDeviceLink/SDLSystemCapabilityManager.m [hunk 6]
```diff
@@ -603,25 +581,71 @@ - (BOOL)subscribeToCapabilityType:(SDLSystemCapabilityType)type withObserver:(id
...
+                    [self.capabilityObservers[key] removeObject:observer];
+                }];
+            }
+
+            // If we no longer have any observers for that type, remove the array
+            if (self.capabilityObservers[key].count == 0) {
+                [self sdl_runSyncOnQueue:^{
+                    [self.capabilityObservers removeObjectForKey:key];
+                }];
+            }
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLSystemCapabilityManager.m]: Fixed.

File: SmartDeviceLink/SDLSystemCapabilityManager.m (hunk 3 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLSystemCapabilityManager.m]: If you access the variable within its own getter using self., it causes infinite recursion.
