### PR TITLE
Bugfix/control frame payload init crash

### LINKED ISSUE #715: Control frame payload initWithData method Crash
### Bug Report
An incorrect if statement was allowing data that had no contents to proceed to a parsing method. Replacing this with `if (data.length > 0) {}` correctly checks the data.

##### Reproduction Steps
1. Using the example video streaming app configured for SDL_iOS v4.7, starting the video service caused this crash

##### Expected Behavior
1. The app does not crash

##### OS & Version Information
* iOS Version: 10.3.3
* SDL iOS Version: 4.7
* Testing Against: TDK through relay app

### PR DESCRIPTION
**Pull request by brettywhite**
Fixes #715 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
added in unit test methods to test initialization with nil data

### Summary
Modifying the if statement from `if (data != nil) {}` to `if (data.length > 0) {}` fixed the issue. This change was made to all the classes with that method in the Control Frame Payloads folder

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLinkTests/ProtocolSpecs/ControlFramePayloadSpecs/SDLControlFramePayloadNakSpec.m [hunk 1]
```diff
@@ -54,4 +54,19 @@
     });
 });
 
+describe(@"Test nil data", ^{
+    __block SDLControlFramePayloadNak *testPayload = nil;
+    __block NSData *testData = nil;
+
+    beforeEach(^{
+
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProtocolSpecs/ControlFramePayloadSpecs/SDLControlFramePayloadNakSpec.m]: Unneeded blank line on these tests
