### PR TITLE
Fixes related to auxillary

### LINKED ISSUE #1938: Fix Spelling of auxillary in SDLStaticIconName
### Bug Report
The spelling of "auxillary" needs to be fixed in five places (including an actual type name) in the SDLStaticIconName.h file. 

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: N/A
* Testing Against: N/A

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1938 

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: Branch develop
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Fixed spelling of auxillary in SDLStaticIconName

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* N/A

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/public/SDLStaticIconName.h [hunk 1]
```diff
@@ -56,7 +56,12 @@ extern SDLStaticIconName const SDLStaticIconNameAudiobookNarrator;
 /**
  * Static icon auxillary audio
  */
-extern SDLStaticIconName const SDLStaticIconNameAuxillaryAudio;
+extern SDLStaticIconName const SDLStaticIconNameAuxillaryAudio __deprecated;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLStaticIconName.h:59]:
```suggestion
extern SDLStaticIconName const SDLStaticIconNameAuxillaryAudio __deprecated_msg("Use SDLStaticIconNameAuxiliaryAudio instead");
```

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
Requested a deprecated message be added.

File: SmartDeviceLink/public/SDLStaticIconName.h [hunk 2]
```diff
@@ -56,7 +56,12 @@ extern SDLStaticIconName const SDLStaticIconNameAudiobookNarrator;
 /**
  * Static icon auxillary audio
```
Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLStaticIconName.h:57]:
```suggestion
 * Static icon auxiliary audio
```

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
One little thing I missed in the first review.

**Review by NicoleYarroch — APPROVED** [review]
