### PR TITLE
2093 - Soft button manager image upload fix

### LINKED ISSUE #2093: ScreenManager Tries to Upload Soft Button Images on Sync 2.0
### Bug Summary

It seems the ScreenManager tries to upload images on Sync 2 even if the dynamic images are not supported. That doesn't crash the app but it just sends RPCs when there is no need for that.

See the equivalent Java Suite issue for more details: https://github.com/smartdevicelink/sdl_java_suite/issues/1738

### Reproduction Steps

1. Run SDL app on Sync 2 TDK
2. Use the `SoftButtonManager` to set buttons with images

Expected Behavior:
Images for the buttons shouldn't be uploaded because the TDK doesn't support dynamic images.

Observed Behavior:
`SoftButtonManager` tries to upload the images then fail

### iOS Version(s)

_No response_

### sdl_ios Version

7.4.0

### Testing Environment(s)

```markdown
* Ford Sync 2.0 TDK
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #2093 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit test added for `softButtonCapabilities.imageSupported = YES` and `displayCapabilities.graphicEnabled = NO`, as well as visa-versa.

#### Core Tests
Tested that existing behavior continues to

Core version / branch / commit hash / module tested against: Sync 3.4 TDK (19353_DEVTEST)
HMI name / version / branch / commit hash / module tested against: Sync 3.4 TDK (19353_DEVTEST)

### Summary
This PR works around a bug when connecting to Sync 2.0 head units that causes the app to attempt to upload soft button images that will never work. This wastes bandwidth and time.

The issues happens because Sync 2.0 doesn't support `softButtonCapabilities`, so the library assumes all capabilities are available. However, Sync 2.0 does report that all graphics are unsupported in `RAIR.displayCapabilities.graphicSupported`.

##### Bug Fixes
* Fixes attempted uploads of image data on SDL 2.0

### Tasks Remaining:
n/a

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by FrankElias77 — CHANGES_REQUESTED** [review]
**iOS App: SmokeTester
SDL Version: Branch Develop
SYNC Version: 2.0**
</br>
### **BUG #1**
If we send 2 softButtons, one with a staticImage and the other with a dynamicImage both buttons will not be displayed on HMI

**STEPS:**
1.Send [softButtonWithStaticImageA, softButtonWithDynamicImageA]

**Expected Behavior:**
Both buttons displayed on HMI

**Observed Behavior:**
No buttons displayed
</br>
### **BUG #2**
If we send 1 softButton with a dynamicImage, button will not be displayed on HMI

**STEPS:**
1.Send [softButtonWithDynamicImageA]

**Expected Behavior:**
Button displayed on HMI

**Observed Behavior:**
No button displayed
</br>
### **BUG #3**
If we send 1 softButton that has 2 or more states, where every state contain a staticImage, button will not be displayed on HMI

**STEPS:**
1.Send [softButtonWithStaticImageAnd2States]

**Expected Behavior:**
Button displayed on HMI

**Observed Behavior:**
No button displayed

**Review by FrankElias77 — APPROVED** [review]

File: SmartDeviceLink/private/SDLSoftButtonManager.m [hunk 1]
```diff
@@ -48,6 +49,7 @@ @interface SDLSoftButtonManager()
 @property (weak, nonatomic) id<SDLConnectionManagerType> connectionManager;
 @property (weak, nonatomic) SDLFileManager *fileManager;
 @property (weak, nonatomic) SDLSystemCapabilityManager *systemCapabilityManager;
+@property (assign, nonatomic) BOOL graphicsSupported;
```
Comment (FrankElias77) [inline SmartDeviceLink/private/SDLSoftButtonManager.m:52]:
```suggestion
@property (assign, nonatomic) BOOL isDynamicGraphicSupported;
```

File: SmartDeviceLink/private/SDLSoftButtonReplaceOperation.m [hunk 2]
```diff
@@ -23,6 +24,7 @@
 @interface SDLSoftButtonReplaceOperation ()
 
 @property (strong, nonatomic, nullable) SDLSoftButtonCapabilities *softButtonCapabilities;
+@property (assign, nonatomic) BOOL graphicsEnabled;
```
Comment (FrankElias77) [inline SmartDeviceLink/private/SDLSoftButtonReplaceOperation.m:27]:
```suggestion
@property (assign, nonatomic) BOOL isDynamicGraphicSupported;
```

File: SmartDeviceLink/private/SDLSoftButtonReplaceOperation.h [hunk 3]
```diff
@@ -38,7 +38,7 @@ NS_ASSUME_NONNULL_BEGIN
  @param mainField1 The primary text field of the system template
  @return The operation
  */
-- (instancetype)initWithConnectionManager:(id<SDLConnectionManagerType>)connectionManager fileManager:(SDLFileManager *)fileManager capabilities:(nullable SDLSoftButtonCapabilities *)capabilities softButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects mainField1:(NSString *)mainField1;
+- (instancetype)initWithConnectionManager:(id<SDLConnectionManagerType>)connectionManager fileManager:(SDLFileManager *)fileManager capabilities:(nullable SDLSoftButtonCapabilities *)capabilities graphicsEnabled:(BOOL)graphicsEnabled softButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects mainField1:(NSString *)mainField1;
```
Comment (FrankElias77) [inline SmartDeviceLink/private/SDLSoftButtonReplaceOperation.h:41]:
```suggestion
- (instancetype)initWithConnectionManager:(id<SDLConnectionManagerType>)connectionManager fileManager:(SDLFileManager *)fileManager capabilities:(nullable SDLSoftButtonCapabilities *)capabilities isDynamicGraphicSupported:(BOOL)isDynamicGraphicSupported softButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects mainField1:(NSString *)mainField1;
```

File: SmartDeviceLink/private/SDLSoftButtonReplaceOperation.m [hunk 4]
```diff
@@ -33,13 +35,14 @@ @interface SDLSoftButtonReplaceOperation ()
 
 @implementation SDLSoftButtonReplaceOperation
 
-- (instancetype)initWithConnectionManager:(id<SDLConnectionManagerType>)connectionManager fileManager:(SDLFileManager *)fileManager capabilities:(nullable SDLSoftButtonCapabilities *)capabilities softButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects mainField1:(NSString *)mainField1 {
+- (instancetype)initWithConnectionManager:(id<SDLConnectionManagerType>)connectionManager fileManager:(SDLFileManager *)fileManager capabilities:(nullable SDLSoftButtonCapabilities *)capabilities graphicsEnabled:(BOOL)graphicsEnabled softButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects mainField1:(NSString *)mainField1 {
```
Comment (FrankElias77) [inline SmartDeviceLink/private/SDLSoftButtonReplaceOperation.m:38]:
```suggestion
- (instancetype)initWithConnectionManager:(id<SDLConnectionManagerType>)connectionManager fileManager:(SDLFileManager *)fileManager capabilities:(nullable SDLSoftButtonCapabilities *)capabilities isDynamicGraphicSupported:(BOOL)isDynamicGraphicSupported softButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects mainField1:(NSString *)mainField1 {
```

File: SmartDeviceLinkTests/SDLSoftButtonReplaceOperationSpec.m [hunk 5]
```diff
@@ -140,7 +144,7 @@
 
             beforeEach(^{
                 testSoftButtonObjects = @[buttonWithText];
-                testOp = [[SDLSoftButtonReplaceOperation alloc] initWithConnectionManager:testConnectionManager fileManager:testFileManager capabilities:capabilities softButtonObjects:testSoftButtonObjects mainField1:testMainField1];
+                testOp = [[SDLSoftButtonReplaceOperation alloc] initWithConnectionManager:testConnectionManager fileManager:testFileManager capabilities:capabilities graphicsEnabled:dynamicGraphicsEnabled softButtonObjects:testSoftButtonObjects mainField1:testMainField1];
```
Comment (FrankElias77) [inline SmartDeviceLinkTests/SDLSoftButtonReplaceOperationSpec.m:147]:
```suggestion
                testOp = [[SDLSoftButtonReplaceOperation alloc] initWithConnectionManager:testConnectionManager fileManager:testFileManager capabilities:capabilities isDynamicGraphicSupported:dynamicGraphicsEnabled softButtonObjects:testSoftButtonObjects mainField1:testMainField1];
```

**Review by FrankElias77 — CHANGES_REQUESTED** [review]
Update var `graphicsEnabled` -> `isDynamicGraphicSupported`, to align with the java suite PR.
I suggested the changes where the var is defined, the remaining changes should be noticeable when xcode flags the errors for using an unknown var

**Review by FrankElias77 — APPROVED** [review]
