### PR TITLE
Fixed session creation failing due to no background task

### LINKED ISSUE #1316: A new transport session is not created if a background task is not ongoing
### Bug Report
If app on device is closed when trying to create a connection with the SDL enabled accessory: 
1. The connection attempt can fail if the background task is not started.
2. The reconnection attempt can fail due to the background task being destroyed in the dealloc method of the `SDLIAPTransport` object. 

##### Reproduction Steps
1. Configure 13 apps with v.6.3 of the library 
2. Connect the phone to SYNC 3.4 TDK with BT
3. Go to apps tab and wait for all 13 apps to show up
  
##### Expected Behavior
All 13 apps show up on the SDL HMI.

##### Observed Behavior
Between 1 and 3 apps will sometimes fail to show up. From the logs it looks like the background task expires, so even though a reconnection attempt should be made by the lifecycle manager, nothing happens. 

##### OS & Version Information
* iOS Version: 12.1.4
* SDL iOS Version: 6.3
* Testing Against: SYNC 3.4 TDK (Build 19126_DEVTEST) + iPhone XS Max (iOS 12.1.4)

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #1316

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
* Smoke tests done with 13 apps

### Summary
1. If the app is not in the foreground when the `SDLIAPTransport` is created, a background task is now started.
2. The background task is no longer destroyed when the transport is deallocated. If the app on the device is not open, this stopped reconnection attempts since code execution stops when the background task is destroyed. 
3. Removed unnecessary listening for `EAAccessory` connections in the `SDLProxy` class.

##### Bug Fixes
* Fixed new transport sessions not being created if a background task is not ongoing.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLIAPTransport.m [hunk 1]
```diff
@@ -63,20 +68,21 @@ - (instancetype)init {
...
     if (self.backgroundTaskId != UIBackgroundTaskInvalid) {
         SDLLogV(@"A background task is already running. No need to start a background task.");
         return;
     }
 
+    __weak typeof(self) weakself = self;
     self.backgroundTaskId = [[UIApplication sharedApplication] beginBackgroundTaskWithName:BackgroundTaskName expirationHandler:^{
         SDLLogD(@"Background task expired");
-        [self sdl_backgroundTaskEnd];
+        [weakself sdl_backgroundTaskEnd];
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLIAPTransport.m]: This, combined with removing it from `dealloc` would cause the background task to never end if `SDLIAPTransport` is deallocated. If we don't call `sdl_backgroundTaskEnd`, then iOS will discover that we don't end our background tasks and will start preventing us from using background time. We need to call `sdl_backgroundTaskEnd` when we're close to expiring.

We may need to move this to another class that won't be dealloced.

Comment (NicoleYarroch) [reply SmartDeviceLink/SDLIAPTransport.m]: Fixed. Moved the background task logic to the lifecycle manager.

File: SmartDeviceLink/SDLLifecycleManager.m [hunk 2]
```diff
@@ -219,6 +222,9 @@ - (void)didEnterStateStarted {
                                             tcpPort:@(self.configuration.lifecycleConfig.tcpDebugPort).stringValue
                           secondaryTransportManager:self.secondaryTransportManager];
     } else {
+        // start a background task so a session can be established even when the app is backgrounded.
+        [self sdl_backgroundTaskStart];
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLifecycleManager.m]: I think this should always run when we are running SDL, not just in iAP.

File: SmartDeviceLink/SDLLifecycleManager.m [hunk 3]
```diff
@@ -829,6 +841,50 @@ - (void)videoServiceProtocolDidUpdateFromOldProtocol:(nullable SDLProtocol *)old
     }
 }
 
+#pragma mark - Background Task
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLifecycleManager.m]: I'm going back and forth on whether this is code bloat. I think this code (and the property) should be in a new class that only manages the background task. It can be then held as a property by the lifecycle manager and started and stopped when the lifecycle manager is started and stopped.

File: SmartDeviceLink/SDLManager.m [hunk 4]
```diff
@@ -164,6 +164,12 @@ - (void)unsubscribeFromRPC:(SDLNotificationName)rpcName withObserver:(id)observe
     [[NSNotificationCenter defaultCenter] removeObserver:observer name:rpcName object:nil];
 }
 
+#pragma mark - Lifecycle Destruction
+
+- (void)dealloc {
+    _lifecycleManager = nil;
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLManager.m]: Fixed. Removed

File: SmartDeviceLink/SDLLifecycleManager.m [hunk 5]
```diff
@@ -72,6 +72,8 @@
 SDLLifecycleState *const SDLLifecycleStateUnregistering = @"Unregistering";
 SDLLifecycleState *const SDLLifecycleStateReady = @"Ready";
 
+NSString *const BackgroundTaskIAPTransportName = @"com.sdl.transport.iap.backgroundTask";
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLifecycleManager.m]: Fixed. Renamed

File: SmartDeviceLink/SDLLifecycleManager.m (hunk 3 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLifecycleManager.m]: Made new class called `SDLBackgroundTaskManager`

File: SmartDeviceLink/SDLLifecycleManager.m [hunk 6]
```diff
@@ -829,6 +843,12 @@ - (void)videoServiceProtocolDidUpdateFromOldProtocol:(nullable SDLProtocol *)old
     }
 }
 
+#pragma mark - Lifecycle Destruction
+
+- (void)dealloc {
+    [self.backgroundTaskManager endBackgroundTask];
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLifecycleManager.m]: I think this can just be moved to the `backgroundTaskManager` dealloc.

File: SmartDeviceLink/SDLLifecycleManager.m (hunk 2 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLifecycleManager.m]: Fixed

File: SmartDeviceLink/SDLLifecycleManager.m (hunk 6 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLifecycleManager.m]: Fixed
