### PR TITLE
Fixed random failures in SDLVoiceCommandManagerSpec due to operations being canceled

### LINKED ISSUE #2001: Random failures in `SDLVoiceCommandManagerSpec` due to operations being canceled
### Bug Report
There are random failures in `SDLVoiceCommandManager` due to existing operations being canceled when new voice commands are set. Whether or not the tests past depends on whether the operation "finishes" after being canceled before the test case is checked. 

##### Reproduction Steps
Execute SDLVoiceCommandManagerSpec `when new voice commands are set` `should queue another operation` test with breakpoints

##### Expected Behavior
Current operation is canceled

##### Observed Behavior
Current operation is not canceled

##### OS & Version Information
* iOS Version: xcode 12.5
* SDL iOS Version: 7.1.1 develop
* Testing Against: N/A

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #2001 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Canceled the current executing operation when a new operation is added

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Canceled the current executing operation when a new operation is added

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLVoiceCommandManager.m [hunk 1]
```diff
@@ -137,7 +137,12 @@ - (void)setVoiceCommands:(NSArray<SDLVoiceCommand *> *)voiceCommands {
         [weakSelf sdl_updatePendingOperationsWithNewCurrentVoiceCommands:newCurrentVoiceCommands];
     }];
 
-    [self.transactionQueue cancelAllOperations];
+    for (NSOperation *operation in self.transactionQueue.operations) {
+        if (operation.isExecuting && !operation.isFinished && !operation.isCancelled) {
+            [operation cancel];
+            break;
+        }
+    }
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLVoiceCommandManager.m:145]: This seems incorrect. You have changed cancelling all operations to only change the executing one. So if you have operations:

```
Op1 - executing
Op2 - waiting
```

And add Op3, this code used to:

```
Op1 - canceled
Op2 - canceled
Op3 - waiting
```

The next op to execute would be op 3, correctly. With your change:

```
Op1 - cancelled
Op2 - waiting
Op3- waiting
```

As you can see, this is incorrect.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 2]
```diff
@@ -105,94 +105,108 @@ + (BOOL)sdl_arePendingVoiceCommandsUnique:(NSArray<SDLVoiceCommand *> *)voiceCom
...
                 testManager.voiceCommands = testVCArray;
             });
 
-            // should only have one operation
-            it(@"should only have one operation", ^{
+            // should properly update a command
+            it(@"should properly update a command", ^{
+                expect(testManager.voiceCommands.firstObject.commandId).to(equal(VoiceCommandIdMin));
                 expect(testManager.transactionQueue.operations).to(haveCount(1));
+                expect(testManager.transactionQueue.operations.firstObject.isExecuting).to(equal(false));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:134]:
```suggestion
                expect(testManager.transactionQueue.operations.firstObject.isExecuting).to(beFalse());
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 3]
```diff
@@ -105,94 +105,108 @@ + (BOOL)sdl_arePendingVoiceCommandsUnique:(NSArray<SDLVoiceCommand *> *)voiceCom
...
             });
-        });
 
-        // when new voice commands are set
-        describe(@"when new voice commands are set", ^{
-            beforeEach(^{
-                testManager.voiceCommands = @[testVoiceCommand2];
-            });
+            // when new voice commands is identical to the existing ones
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:137]:
```suggestion
            // when new voice commands are identical to the existing ones
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 4]
```diff
@@ -105,94 +105,108 @@ + (BOOL)sdl_arePendingVoiceCommandsUnique:(NSArray<SDLVoiceCommand *> *)voiceCom
...
-                expect(testManager.transactionQueue.operations).to(haveCount(2));
+                // should only have one operation
+                it(@"should only have one operation", ^{
+                    expect(testManager.transactionQueue.operations).to(haveCount(1));
+                });
             });
 
-            // when the first operation finishes and updates the current voice commands
-            describe(@"when the first operation finishes and updates the current voice commands", ^{
+            // when new voice commands are set
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:149]:
```suggestion
            // when new voice commands are different from the existing ones
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 5]
```diff
@@ -105,94 +105,108 @@ + (BOOL)sdl_arePendingVoiceCommandsUnique:(NSArray<SDLVoiceCommand *> *)voiceCom
...
+                describe(@"when the first operation finishes and updates the current voice commands", ^{
+                    beforeEach(^{
+                        testManager.transactionQueue.suspended = NO;
+
+                        SDLVoiceCommandUpdateOperation *firstOp = testManager.transactionQueue.operations[0];
+                        firstOp.currentVoiceCommands = [@[testVoiceCommand2] mutableCopy];
+                        [firstOp finishOperation];
+                    });
+
+                    // should update the second operation
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:170]:
```suggestion
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 6]
```diff
@@ -105,94 +105,108 @@ + (BOOL)sdl_arePendingVoiceCommandsUnique:(NSArray<SDLVoiceCommand *> *)voiceCom
...
+            describe(@"when new voice commands are different from the existing ones", ^{
                 beforeEach(^{
-                    SDLVoiceCommandUpdateOperation *firstOp = testManager.transactionQueue.operations[0];
-                    firstOp.currentVoiceCommands = [@[testVoiceCommand2] mutableCopy];
-                    [firstOp finishOperation];
+                    testManager.voiceCommands = @[testVoiceCommand2];
+                });
 
-                    [NSThread sleepForTimeInterval:0.5];
+                // should queue another operation
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:155]:
```suggestion
```

This isn't necessary because it's a single it in the group

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 7]
```diff
@@ -105,94 +105,108 @@ + (BOOL)sdl_arePendingVoiceCommandsUnique:(NSArray<SDLVoiceCommand *> *)voiceCom
     });
 
     // updating voice commands
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:107]:
```suggestion
    // when the hmi is ready
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 8]
```diff
@@ -105,94 +105,108 @@ + (BOOL)sdl_arePendingVoiceCommandsUnique:(NSArray<SDLVoiceCommand *> *)voiceCom
...
             newHMIStatus.windowID = @(SDLPredefinedWindowsDefaultWindow);
 
             SDLRPCNotificationNotification *notification = [[SDLRPCNotificationNotification alloc] initWithName:SDLDidChangeHMIStatusNotification object:nil rpcNotification:newHMIStatus];
             [[NSNotificationCenter defaultCenter] postNotification:notification];
 
-            testManager.voiceCommands = testVCArray;
         });
 
         // should properly update a command
         it(@"should properly update a command", ^{
```
[the remark this answers is not in the document]
Comment (FrankElias77) [reply SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m]: Can you please be more specific, do you mean the description for `it`?

[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m]: I meant the name of the describe I believe?

**Review by joeljfischer — APPROVED** [review]
