### PR TITLE
Hit test for a single tap now checked on main thread

### LINKED ISSUE #1207: Using the haptic input feature freezes the app when a single tap is detected
### Bug Report
When using the haptic input feature to detect the tapped view in a navigation app, the app freezes whenever a single tap is detected. This is because the library does not check on main thread if a view was tapped.

##### Reproduction Steps
1. Create a navigation app with some `UIViews` in the `rootViewController` (Make sure to send a SDLDidUpdateProjectionView notification to the library)
1. Connect to Core
1. Perform a single tap on a view on the SDL app

##### Expected Behavior
The touch manager should notify the subscriber right away that a view was tapped.

##### Observed Behavior
The app freezes for a few seconds before the notification is sent by the touch manager.

In the `SDLFocusableItemLocator` class, the `viewForPoint:` method should check if a tap is inside a view on the main thread.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.2
* Testing Against: SYNC 3 and SDL_Core 5.1.0 + sdl_hmi

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #1207 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Test cases for the `SDLTouchManager` were updated.

### Summary
Checking if a single tap is inside a `UIView` no longer causes the app to freeze for a few seconds. All checking is now done on the main thread.

##### Breaking Changes
* n/a

##### Bug Fixes
* Checking if a single tap is inside a `UIView` no longer causes the app to freeze for a few seconds. All checking is now done on the main thread.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by NicoleYarroch** [comment]
After doing more testing, I realized that only the single tap touch was not being hit tested on the main thread. I added a HAX to perform the hit test on the main thread and then notify the delegate on the background thread.

File: SmartDeviceLink/SDLTouchManager.m [hunk 1]
```diff
@@ -420,12 +420,34 @@ - (void)sdl_initializeSingleTapTimerAtPoint:(CGPoint)point {
...
+                [strongSelf.touchEventDelegate touchManager:strongSelf didReceiveSingleTapForView:selectedView atPoint:point];
+            }];
         }
     });
 }
 
+/**
+ *  HAX to preserve the thread on which the delegate is notified for single taps; returning on the main thread would be a breaking change. All other touch gestures currently notify the delegate on the main thread. The single tap timer runs on a background thread so when a single tap is detected the hit test needs to be done on the main thread and then the result is returned on a background thread.
+ *
+ * Checks if a single tap is inside a view. As the single tap timer is run on a background thread, the check is done on a main thread and then the result is returned on a background thread. This is done to ma
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLTouchManager.m]: Unfinished sentence

File: SmartDeviceLink/SDLTouchManager.m [hunk 2]
```diff
@@ -420,12 +420,34 @@ - (void)sdl_initializeSingleTapTimerAtPoint:(CGPoint)point {
...
+ *
+ *  @param point            Screen coordinates of the tap gesture
+ *  @param hitViewHandler   A handler that returns the view the point is inside of; nil if the point does not lie inside a view
+ */
+- (void)sdl_getSingleTapHitView:(CGPoint)point hitViewHandler:(nullable void (^)(UIView * __nullable hitView))hitViewHandler {
+    if (!self.hitTester) {
+        return hitViewHandler(nil);
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLTouchManager.m]: Need to check if `hitViewHandler` exists since it's nullable.

File: SmartDeviceLink/SDLTouchManager.m [hunk 3]
```diff
@@ -420,12 +420,34 @@ - (void)sdl_initializeSingleTapTimerAtPoint:(CGPoint)point {
...
+    }
+
+    dispatch_async(dispatch_get_main_queue(), ^{
+        UIView *hitView = [self.hitTester viewForPoint:point];
+        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
+            return hitViewHandler(hitView);
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLTouchManager.m]: See above

File: SmartDeviceLink/SDLTouchManager.m (hunk 2 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLTouchManager.m]: Fixed. Added check.

File: SmartDeviceLink/SDLTouchManager.m (hunk 1 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLTouchManager.m]: Fixed. Removed.

File: SmartDeviceLink/SDLTouchManager.m (hunk 3 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLTouchManager.m]: Fixed. Added check.
