### PR TITLE
Truncated the generated `SDLArtwork` filename to 16 characters

### LINKED ISSUE #976: Generated syncFileName for SDLArtwork is rejected on certain SDL core implementations.
### Bug Report
When creating SDLArtwork without explicitly specifying a file name, the file upload fails on certain Sync3 head units.  Based on a quick investigation, it appears this has to do with the length of the `syncFileName` - anything greater than 29 characters is rejected.  From the slack convo: " what you are experiencing is a limitation of the QNX file system. (sync uses this)."

Although this isn't technically a big (255 is the limit in the spec,) because a decent percentage of SDL core implementations are likely running on QNX it would be helpful for this library to produce filename that won't be rejected on upload.

##### Reproduction Steps
1. Create an SDLArtwork from a UIImage using one of the initializers that doesn't specify a name.
2. Set this artwork instance as the SDL app's `appIcon`.
3. Attempt to connect to a SYNC3 head unit running on QNX.

##### Expected Behavior
App icon will display under app name on HMI display.

##### Observed Behavior
Placeholder image is displayed under the app name on HMI display.

##### OS & Version Information
* iOS Version: 11.2.6
* SDL iOS Version: 5.2
* Testing Against: SYNC3 v3.0 TDK

##### Test Case, Sample Code, and / or Example App
There may be better ways to ensure uniqueness, but as a quick POC truncating the MD5 resolves the issue:
```Objective-C
@implementation SDLArtwork
. . .
+ (NSString *)sdl_md5HashFromNSData:(NSData *)data {
    . . .
    for (int i = 0; i < 14; i += 1) {
        [formattedHash appendFormat:@"%02x", hash[i]];
    }
    return formattedHash;
}
```

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #976 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Test cases added to the *SDLArtworkSpec*

### Summary
 A MD5 hash always creates a string with 32 characters (128-bits). Due to some implementations of Core not following the spec, file names that are too long are being rejected. To try to accommodate this setup, hashed file names are now being truncated to 16 characters.

##### Bug Fixes
* Automatically generated `SDLArtwork` file names are now truncated to 16 characters to accommodate file systems that reject files names with 32 characters.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLArtwork.m [hunk 1]
```diff
@@ -105,7 +107,8 @@ + (NSString *)sdl_md5HashFromNSData:(NSData *)data {
     unsigned char hash[CC_MD5_DIGEST_LENGTH];
     CC_MD5([data bytes], (CC_LONG)[data length], hash);
     NSMutableString *formattedHash = [NSMutableString stringWithCapacity:CC_MD5_DIGEST_LENGTH * 2];
-    for (int i = 0; i < CC_MD5_DIGEST_LENGTH; i += 1) {
+    // HAX: To shorten the string to 16 characters, the loop has been shortened to 8 fom 16.
+    for (int i = 0; i < 8; i += 1) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLArtwork.m]: Should this be `for (int i = 0; i < CC_MD5_DIGEST_LENGTH / 2; i += 1) {`?

File: SmartDeviceLink/SDLArtwork.m [hunk 2]
```diff
@@ -105,7 +107,8 @@ + (NSString *)sdl_md5HashFromNSData:(NSData *)data {
     unsigned char hash[CC_MD5_DIGEST_LENGTH];
     CC_MD5([data bytes], (CC_LONG)[data length], hash);
     NSMutableString *formattedHash = [NSMutableString stringWithCapacity:CC_MD5_DIGEST_LENGTH * 2];
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLArtwork.m]: Should this be shortened?

File: SmartDeviceLink/SDLArtwork.m (hunk 1 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLArtwork.m]: Fixed

File: SmartDeviceLink/SDLArtwork.m (hunk 2 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLArtwork.m]: Fixed
