### PR TITLE
Let developer override the default custom video encoder settings when not set by the video streaming capability 

### LINKED ISSUE #1950: Custom encoder settings can not override default video encoder settings
### Bug Report
With the implementation of evolution proposal [SDL-0323](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0323-align-VideoStreamingParameter-with-capability.md), the custom video encoder settings set by the developer can only override the existing video encoder settings if the value is less than what has been set in the existing settings. However, if the `VideoStreamingCapability` returned by the module does not contain a `maxBitrate ` or `preferredFPS`, then the default video encoder settings are used. This means that the developer can not set a `maxBitrate ` or `preferredFPS` greater than the default video encoder settings. 

The library defined default video encoder settings:
```
_defaultVideoEncoderSettings = @{
                                 (__bridge NSString *)kVTCompressionPropertyKey_ProfileLevel: (__bridge NSString *)kVTProfileLevel_H264_Baseline_AutoLevel,
                                 (__bridge NSString *)kVTCompressionPropertyKey_RealTime: @YES,
                                 (__bridge NSString *)kVTCompressionPropertyKey_ExpectedFrameRate: @15,
                                 (__bridge NSString *)kVTCompressionPropertyKey_AverageBitRate: @600000,
                                 };
```

##### Reproduction Steps
1. Set a custom video encoder setting of 60 fps in the `SDLStreamingMediaConfiguration`. 
    `streamingMediaConfig.customVideoEncoderSettings = [kVTCompressionPropertyKey_ExpectedFrameRate as String: 60]`
2. Connect to a module that returns a `VideoStreamingCapability` with `preferredFPS` set to `nil`.

##### Expected Behavior
The video encoder object should be created with an `ExpectedFrameRate` of 60:
```
{
    AverageBitRate = 600000;
    ExpectedFrameRate = 15;
    ProfileLevel = "H264_Baseline_AutoLevel";
    RealTime = 1;
}
```

##### Observed Behavior
The video encoder object is created with an `ExpectedFrameRate` of 15, which is the default video encoder setting. Since 15 is default frame rate, the developer should be able to override the value with their preferred setting. 

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 7.1
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #1950

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit tests were added to the _SDLStreamingVideoLifecycleManagerSpec_ to test overriding the custom video encoder settings.

##### Frames Per Second
- [x] Tested returning a `preferredFPS` in the `VideoStreamingCapability` larger than the value set by the `ExpectedFrameRate` set by the developer. The `ExpectedFrameRate` should be used by the video encoder.
- [x] Tested returning a `preferredFPS` in the `VideoStreamingCapability` smaller than the value set by the `ExpectedFrameRate` set by the developer. The `preferredFPS` should be used by the video encoder.
- [x] Tested returning a `nil` `preferredFPS` in the `VideoStreamingCapability`. The `ExpectedFrameRate` should be used by the video encoder.
- [x] Tested returning a `nil` `preferredFPS` in the `VideoStreamingCapability` and not setting an `ExpectedFrameRate`. The video encoder should use the default value.
##### Bitrate
- [x] Tested returning a `maxBitrate` in the `VideoStreamingCapability` larger than the value set by the `AverageBitRate` set by the developer. The `AverageBitRate` should be used by the video encoder.
- [x] Tested returning a `maxBitrate` in the `VideoStreamingCapability` smaller than the value set by the `AverageBitRate` set by the developer. The `maxBitrate` should be used by the video encoder.
- [x] Tested returning a `nil` `maxBitrate ` in the `VideoStreamingCapability`. The `AverageBitRate ` should be used by the video encoder.
- [x] Tested returning a `nil` `maxBitrate ` in the `VideoStreamingCapability` and not setting an `AverageBitRate `. The video encoder should use the default value.
##### Updating the `VideoStreamingCapability` midstream
- [x] Tested updating the `VideoStreamingCapability` mid-stream and made sure the video encoder used the `preferredFPS` and `maxBitrate` in the `VideoStreamingCapability` if the parent `VideoStreamingCapability` contains the values but not the `VideoStreamingCapability.additionalVideoStreamingCapabilities`.

Core version / branch / commit hash / module tested against: 
* commit 40cf3dc7afdab7384c7a0f43336c7a88665db240 (HEAD -> release/7.1.0-RC1, origin/release/7.1.0-RC1)

HMI name / version / branch / commit hash / module tested against: 
* commit c04f179ca7bd51296ebd35a0b24ff3644c442826 (HEAD -> release/5.5.0, origin/release/5.5.0)

### Summary
Fixed a bug where the developer was not able to set their own custom video encoder settings if the `VideoStreamingCapability` returns a `nil` value for the respective setting.

##### Bug Fixes
* Fixed the developer not being able to set their own custom video encoder settings for `ExpectedFrameRate` or `AverageBitRate` if the `VideoStreamingCapability` returned by the module has a `nil` value for `preferredFPS` or `maxBitrate`. 
* Fixed the `SDLStreamingVideoLifecycleManager` not using the `VideoStreamingCapability`'s `preferredFPS` or `maxBitrate` if the root `VideoStreamingCapability` contained the `preferredFPS` or `maxBitrate` properties but not the `VideoStreamingCapability.additionalVideoStreamingCapabilities` (i.e. the child now inherit's the parent's `preferredFPS` and/or `maxBitrate` properties)

### Tasks Remaining:
- [x] Test with sdl_core

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by joeljfischer — CHANGES_REQUESTED** [review]
In `SDLStreamingVideoLifecycleManagerSpec` `after sending GetSystemCapabilities / and receiving an error response / and receiving a response` (which also seems like a mixup on the nesting of test blocks?), there's no checks for max bitrate or preferred FPS. It appears that the changes in `sdl_applyVideoCapabilityWhileStarting:` are not tested.

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 1]
```diff
@@ -1113,200 +1115,305 @@ - (instancetype)shortCopy;
...
+                testNilVideoStreamingCapability.videoStreamingCapability = nil;
 
-QuickSpecBegin(SDLStreamingVideoLifecycleManagerSpec_GetSystemCapabilities)
+                [streamingLifecycleManager sdl_videoStreamingCapabilityDidUpdate:testNilVideoStreamingCapability];
+            });
 
-const NSInteger testScaledWidth = roundf((float)testVSCResolutionWidth/testVSCScale);
-const NSInteger testScaledHeight = roundf((float)testVSCResolutionHeight/testVSCScale);
-const CGSize testSize = CGSizeMake(testVSCResolutionWidth, testVSCResolutionHeight);
+            it(@"should use the library's default values in lieu of a VideoStreamingCapability", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m:1137]:
```suggestion
            it(@"should use the library's default values", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 2]
```diff
@@ -1113,200 +1115,305 @@ - (instancetype)shortCopy;
...
+            });
+        });
 
-testLifecycleConfiguration.appType = SDLAppHMITypeNavigation;
+        context(@"the module supports the GetSystemCapabilities request", ^{
+            __block SDLSystemCapability *testSystemCapability = nil;
+            __block SDLVideoStreamingCapability *testVideoStreamingCapability = nil;
 
-SDLConfiguration *testConfig = [[SDLConfiguration alloc] initWithLifecycle:testLifecycleConfiguration lockScreen:[SDLLockScreenConfiguration enabledConfiguration] logging:[SDLLogConfiguration debugConfiguration] streamingMedia:testConfiguration fileManager:[SDLFileManagerConfiguration defaultConfiguration] encryption:nil];
+            context(@"The module does not support VideoStreamingCapability.additionalVideoStreamingCapabilities", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m:1159]:
```suggestion
            context(@"the module does not support VideoStreamingCapability.additionalVideoStreamingCapabilities", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 3]
```diff
@@ -1113,200 +1115,305 @@ - (instancetype)shortCopy;
...
-        expect(streamingLifecycleManager.currentAppState).to(equal(SDLAppStateActive));
-        expect(streamingLifecycleManager.currentVideoStreamState).to(equal(SDLVideoStreamManagerStateStarting));
-        expect(streamingLifecycleManager.videoFormat).to(beNil());
-        expect(streamingLifecycleManager.dataSource).to(equal(testDataSource));
-        expect(streamingLifecycleManager.supportedFormats).to(haveCount(2));
-        expect(streamingLifecycleManager.preferredFormats).notTo(beNil());
-        expect(streamingLifecycleManager.preferredResolutions).notTo(beNil());
-        expect(streamingLifecycleManager.preferredFormatIndex).to(equal(2));
-        expect(streamingLifecycleManager.preferredResolutionIndex).to(equal(0));
+            context(@"The module supports VideoStreamingCapability.additionalVideoStreamingCapabilities", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m:1193]:
```suggestion
            context(@"the module supports VideoStreamingCapability.additionalVideoStreamingCapabilities", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 4]
```diff
@@ -1113,200 +1115,305 @@ - (instancetype)shortCopy;
...
+        });
     });
 
-    context(@"and receiving an error response", ^{
-        // This happens if the HU doesn't understand GetSystemCapabilities
-        beforeEach(^{
-            SDLGenericResponse *genericResponse = [[SDLGenericResponse alloc] init];
-            genericResponse.success = @NO;
-            genericResponse.resultCode = SDLResultInvalidData;
+    describe(@"Setting the video encoder properties", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m:1240]:
```suggestion
    describe(@"setting the video encoder properties", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 5]
```diff
@@ -1113,200 +1115,305 @@ - (instancetype)shortCopy;
...
         });
 
-        it(@"should have correct format and resolution", ^{
-            expect(streamingLifecycleManager.preferredFormats).notTo(beNil());
-            expect(streamingLifecycleManager.preferredResolutions).notTo(beNil());
-            if (!streamingLifecycleManager.preferredFormats || !streamingLifecycleManager.preferredResolutions) {
-                failWithMessage(@"absent preferredFormats or preferredResolutions");
-            }
+        context(@"setting the bitrate", ^{
+            describe(@"the VideoStreamingCapability returns a maxBitrate", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m:1248]:
```suggestion
            context(@"the VideoStreamingCapability returns a maxBitrate", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 6]
```diff
@@ -1113,200 +1115,305 @@ - (instancetype)shortCopy;
...
+                });
             });
 
-            it(@"should have correct data from the data source", ^{
-                expect(streamingLifecycleManager.preferredFormats).notTo(beNil());
-                expect(streamingLifecycleManager.preferredResolutions).notTo(beNil());
-                if (!streamingLifecycleManager.preferredFormats || !streamingLifecycleManager.preferredResolutions) {
-                    return;
-                }
+            describe(@"The VideoStreamingCapability returns a nil maxBitrate", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m:1293]:
```suggestion
            context(@"the VideoStreamingCapability returns a nil maxBitrate", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 7]
```diff
@@ -1113,200 +1115,305 @@ - (instancetype)shortCopy;
...
+            testVideoStreamingCapability = nil;
         });
 
-        it(@"should have correct format and resolution", ^{
-            expect(streamingLifecycleManager.preferredFormats).notTo(beNil());
-            expect(streamingLifecycleManager.preferredResolutions).notTo(beNil());
-            if (!streamingLifecycleManager.preferredFormats || !streamingLifecycleManager.preferredResolutions) {
-                failWithMessage(@"absent preferredFormats or preferredResolutions");
-            }
+        context(@"setting the bitrate", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m:1247]:
```suggestion
        describe(@"setting the bitrate", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 8]
```diff
@@ -1113,200 +1115,305 @@ - (instancetype)shortCopy;
...
+                    streamingLifecycleManager.customEncoderSettings = nil;
+
+                    [streamingLifecycleManager sdl_applyVideoCapability:testVideoStreamingCapability];
+
+                    expect(streamingLifecycleManager.videoEncoderSettings[(__bridge NSString *)kVTCompressionPropertyKey_AverageBitRate]).to(equal(@(600000)));
+                });
             });
+        });
+
+        context(@"setting the framerate", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m:1333]:
```suggestion
        describe(@"setting the framerate", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 9]
```diff
@@ -1113,200 +1115,305 @@ - (instancetype)shortCopy;
...
+            describe(@"the VideoStreamingCapability returns a preferredFPS", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m:1334]:
```suggestion
            context(@"the VideoStreamingCapability returns a preferredFPS", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 10]
```diff
@@ -1113,200 +1115,305 @@ - (instancetype)shortCopy;
...
+                    [streamingLifecycleManager sdl_applyVideoCapability:testVideoStreamingCapability];
+
+                    expect(streamingLifecycleManager.videoEncoderSettings[(__bridge NSString *)kVTCompressionPropertyKey_ExpectedFrameRate]).to(equal(@(testVideoStreamingCapabilityPreferredFPS)));
+                });
             });
 
-            it(@"should set the correct scale value", ^{
-                expect(streamingLifecycleManager.videoScaleManager).notTo(beNil());
-                expect(streamingLifecycleManager.videoScaleManager.scale).to(equal(testVSCScale));
+            describe(@"The VideoStreamingCapability returns a nil preferredFPS", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m:1377]:
```suggestion
            context(@"the VideoStreamingCapability returns a nil preferredFPS", ^{
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLStreamingVideoLifecycleManager.m [hunk 11]
```diff
@@ -796,6 +796,13 @@ - (void)sdl_applyVideoCapabilityWhileStarting:(nullable SDLVideoStreamingCapabil
     if (!matchedVideoCapability.supportedFormats) {
         matchedVideoCapability.supportedFormats = videoCapabilityUpdated.supportedFormats;
     }
+    if (!matchedVideoCapability.maxBitrate) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLStreamingVideoLifecycleManager.m:799]:
```suggestion
    if (matchedVideoCapability.maxBitrate == nil) {
```

File: SmartDeviceLink/private/SDLStreamingVideoLifecycleManager.m [hunk 12]
```diff
@@ -796,6 +796,13 @@ - (void)sdl_applyVideoCapabilityWhileStarting:(nullable SDLVideoStreamingCapabil
...
+        matchedVideoCapability.maxBitrate = videoCapabilityUpdated.maxBitrate;
+    }
+    if (!matchedVideoCapability.preferredFPS) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLStreamingVideoLifecycleManager.m:802]:
```suggestion
    if (matchedVideoCapability.preferredFPS == nil) {
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]
Last one

**Review by joeljfischer — APPROVED** [review]
