### PR TITLE
Fix for overwriting SDLArtwork

### LINKED ISSUE #1117: Setting a `SDLArtwork`'s `overwrite` property to true does not work with screen manager
### Bug Report
If an artwork with the same name is uploaded using the screen manager with `overwrite` set to `true` and `persistent` set to `false`, the new artwork is not shown. 

##### Reproduction Steps
1. Connect app to Core
1. Send a show request with the `graphic` set to an artwork named "TestArtwork"
1. Send a second show request with the `graphic` set  to a different artwork also named "TestArtwork". Set the artwork's `overwrite` property to `true` and `persistent` property to `false`.

##### Expected Behavior
The new artwork will show up in the `graphic` field of the template.

##### Observed Behavior
The `graphic` field of the template shows the old artwork.

##### OS & Version Information
* iOS Version: 12
* SDL iOS Version: 6.1
* Testing Against: SYNC 3

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1117 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit tests added for their respective Spec files. Checks when the overwrite property is set to true for a new SDLArtwork if it gets uploaded or not.

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Fix for overwriting a previously uploaded SDLArtwork with the same name.

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
Fix for overwriting a previously uploaded SDLArtwork with the same name.

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 1]
```diff
@@ -552,7 +552,34 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
...
 
 - (BOOL)sdl_artworkNeedsUpload:(SDLArtwork *)artwork {
-    return (artwork != nil && ![self.fileManager hasUploadedFile:artwork] && !artwork.isStaticIcon);
+    if (artwork != nil) {
+        if (artwork.isStaticIcon) {
+            return NO;
+        } else {
+            return (artwork.overwrite || (self.fileManager != nil && ![self.fileManager hasUploadedFile:artwork]));
+        }
+    }
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:561]:
```suggestion
    if (artwork != nil && !artwork.isStaticIcon) {
        return (artwork.overwrite || (self.fileManager != nil && ![self.fileManager hasUploadedFile:artwork]));
    }
```

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 2]
```diff
@@ -552,7 +552,34 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
...
+    return NO;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:562]:
```suggestion
    
    return NO;
```

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 3]
```diff
@@ -552,7 +552,34 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
...
+}
+
+- (BOOL) sdl_allArtworksUploaded:(NSArray<SDLMenuCell *> *)cells {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:565]:
```suggestion
- (BOOL)sdl_areAllCellArtworksUploaded:(NSArray<SDLMenuCell *> *)cells {
```

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 4]
```diff
@@ -552,7 +552,34 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
...
+        }
+        if (cell.subCells != nil && (cell.subCells.count) > 0) {
+            return [self sdl_allArtworksUploaded:cell.subCells];
+        }
+    }
+
+    return YES;
+}
+
+- (BOOL) sdl_artworkUploaded:(SDLArtwork *)artwork {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:578]:
```suggestion
- (BOOL)sdl_isArtworkUploaded:(nullable SDLArtwork *)artwork {
```

Remember that everything is assumed to be `nonnull` unless you explicitly specify it as `nullable`.

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 5]
```diff
@@ -552,7 +552,34 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
...
+    }
+    return NO;
+}
+
+- (BOOL) sdl_allArtworksUploaded:(NSArray<SDLMenuCell *> *)cells {
+    for (SDLMenuCell *cell in cells) {
+        if (![self sdl_artworkUploaded:cell.icon]) {
+            return NO;
+        }
+        if (cell.subCells != nil && (cell.subCells.count) > 0) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:570]:
```suggestion
        } else if (cell.subCells != nil && (cell.subCells.count) > 0) {
```

File: SmartDeviceLink/private/SDLPreloadChoicesOperation.m [hunk 6]
```diff
@@ -114,7 +114,14 @@ - (void)sdl_preloadCellArtworksWithCompletionHandler:(void(^)(NSError *_Nullable
 }
 
 - (BOOL)sdl_artworkNeedsUpload:(SDLArtwork *)artwork {
-    return (artwork != nil && ![self.fileManager hasUploadedFile:artwork] && !artwork.isStaticIcon);
+    if (artwork != nil) {
+        if (artwork.isStaticIcon) {
+            return NO;
+        } else {
+            return artwork.overwrite || (self.fileManager != nil && ![self.fileManager hasUploadedFile:artwork]);
+        }
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLPreloadChoicesOperation.m:122]:
```suggestion
        if (artwork != nil && !artwork.isStaticIcon) {
            return (artwork.overwrite || (self.fileManager != nil && ![self.fileManager hasUploadedFile:artwork]));
        }
```

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 7]
```diff
@@ -552,7 +552,34 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
 }
 
 - (BOOL)sdl_artworkNeedsUpload:(SDLArtwork *)artwork {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:554]: I think this method should probably be added to the `SDLFileManager` as a public method and removed from all these classes. Could you discuss that with Bilal?

File: SmartDeviceLink/private/SDLSoftButtonReplaceOperation.m [hunk 8]
```diff
@@ -228,7 +228,14 @@ - (void)sdl_sendCurrentStateTextOnlySoftButtonsWithCompletionHandler:(void (^)(B
...
 
 - (BOOL)sdl_artworkNeedsUpload:(SDLArtwork *)artwork {
-    return (artwork != nil && ![self.fileManager hasUploadedFile:artwork] && self.softButtonCapabilities.imageSupported.boolValue && !artwork.isStaticIcon);
+    if (artwork != nil && self.softButtonCapabilities.imageSupported) {
+        if (artwork.isStaticIcon) {
+            return NO;
+        } else {
+            return artwork.overwrite || (self.fileManager != nil && ![self.fileManager hasUploadedFile:artwork]);
+        }
+    }
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLSoftButtonReplaceOperation.m:237]:
```suggestion
    if (artwork != nil && !artwork.isStaticIcon) {
        return (artwork.overwrite || (self.fileManager != nil && ![self.fileManager hasUploadedFile:artwork]));
    }
```

File: SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m [hunk 9]
```diff
@@ -516,29 +516,45 @@ - (void)sdl_updateCurrentScreenDataFromSetDisplayLayout:(SDLSetDisplayLayout *)s
...
 
 - (BOOL)sdl_artworkNeedsUpload:(SDLArtwork *)artwork {
-    return (artwork != nil && ![self.fileManager hasUploadedFile:artwork] && !artwork.isStaticIcon);
+    if (artwork != nil) {
+        if (artwork.isStaticIcon) {
+            return NO;
+        } else {
+            return (artwork.overwrite || (![self.fileManager hasUploadedFile:artwork]));
+        }
+    }
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m:525]:
```suggestion
    if (artwork != nil && !artwork.isStaticIcon) {
        return (artwork.overwrite || (self.fileManager != nil && ![self.fileManager hasUploadedFile:artwork]));
    }
```

File: SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m [hunk 10]
```diff
@@ -516,29 +516,45 @@ - (void)sdl_updateCurrentScreenDataFromSetDisplayLayout:(SDLSetDisplayLayout *)s
...
+    return NO;
+}
+
+- (BOOL) sdl_artworkUploaded:(SDLArtwork *)artwork {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m:529]:
```suggestion
- (BOOL)sdl_artworkIsUploaded:(nullable SDLArtwork *)artwork {
```

File: SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m [hunk 11]
```diff
@@ -516,29 +516,45 @@ - (void)sdl_updateCurrentScreenDataFromSetDisplayLayout:(SDLSetDisplayLayout *)s
...
+    if (artwork != nil) {
+        return artwork.isStaticIcon || (self.fileManager != nil && [self.fileManager hasUploadedFile:artwork]);
+    }
+    return YES;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m:533]:
```suggestion
    return NO;
```

If the artwork is `nil`, it's not uploaded, right? Note, this may break some things, so it may need a refactor. Returning `YES` just doesn't make sense here.

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 12]
```diff
@@ -552,7 +552,34 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
...
+    }
+
+    return YES;
+}
+
+- (BOOL) sdl_artworkUploaded:(SDLArtwork *)artwork {
+    if (artwork != nil) {
+        return artwork.isStaticIcon || (self.fileManager != nil && [self.fileManager hasUploadedFile:artwork]);
+    }
+    return YES;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:582]:
```suggestion
    return NO;
```

If the artwork is `nil`, it's not uploaded, right? Note, this may break some things, so it may need a refactor. Returning `YES` just doesn't make sense here.

File: SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m [hunk 13]
```diff
@@ -516,29 +516,45 @@ - (void)sdl_updateCurrentScreenDataFromSetDisplayLayout:(SDLSetDisplayLayout *)s
...
 }
 
 - (BOOL)sdl_shouldUpdatePrimaryImage {
     // If the template is updating, we don't yet know it's capabilities. Just assume the template supports the primary image. 
     BOOL templateSupportsPrimaryArtwork = [self.currentCapabilities hasImageFieldOfName:SDLImageFieldNameGraphic] || [self sdl_shouldUpdateTemplateConfig];
-    BOOL graphicMatchesExisting = [self.currentScreenData.primaryGraphic.name isEqualToString:self.updatedState.primaryGraphic.name];
+    BOOL graphicNameMatchesExisting = [self.currentScreenData.primaryGraphic.name isEqualToString:self.updatedState.primaryGraphic.name];
+    BOOL shouldOverwriteGraphic = self.updatedState.primaryGraphic != nil && self.updatedState.primaryGraphic.overwrite;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m:540]:
```suggestion
    BOOL shouldOverwriteGraphic = self.updatedState.primaryGraphic.overwrite;
```

You shouldn't need to check for `nil` here

File: SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m [hunk 14]
```diff
@@ -228,6 +231,13 @@ @interface SDLMenuManager()
                     expect(submenu).to(haveCount(1));
                     expect(sentCommand.cmdIcon.value).to(equal(testArtwork.name));
                     expect(sentSubmenu.menuIcon.value).to(equal(testArtwork2.name));
+                    OCMReject([mockFileManager uploadArtworks:[OCMArg any] completionHandler:[OCMArg any]]);
+                });
+
+                it(@"should properly override an image cell", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m:237]:
```suggestion
                it(@"should properly overwrite an image cell", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m [hunk 15]
```diff
@@ -145,6 +147,25 @@
                         }] completionHandler:[OCMArg any]]);
                         expect(@(testOp.currentState)).to(equal(SDLPreloadChoicesOperationStatePreloadingChoices));
                     });
+
+                    it(@"should properly override artwork", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m:151]:
```suggestion
                    it(@"should properly overwrite artwork", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLTextAndGraphicUpdateOperationSpec.m [hunk 16]
```diff
@@ -820,18 +820,36 @@
...
                     expect(testConnectionManager.receivedRequests).to(haveCount(1));
                     SDLShow *firstSentRequest = testConnectionManager.receivedRequests[0];
                     expect(firstSentRequest.mainField1).to(equal(field1String));
                     expect(firstSentRequest.mainField2).to(beEmpty());
                     expect(firstSentRequest.graphic).toNot(beNil());
                     expect(firstSentRequest.secondaryGraphic).to(beNil());
+                    OCMReject([mockFileManager uploadArtworks:[OCMArg any] progressHandler:[OCMArg any] completionHandler:[OCMArg any]]);
+                });
+
+                it(@"should properly override artwork", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLTextAndGraphicUpdateOperationSpec.m:838]:
```suggestion
                it(@"should properly overwrite artwork", ^{
```

File: SmartDeviceLinkTests/SDLSoftButtonReplaceOperationSpec.m [hunk 17]
```diff
@@ -296,6 +299,19 @@
                         expect(sentRequests.firstObject.softButtons.lastObject.type).to(equal(SDLSoftButtonTypeBoth));
                     });
 
+                    it(@"should properly override artwork", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/SDLSoftButtonReplaceOperationSpec.m:302]:
```suggestion
                    it(@"should properly overwrite artwork", ^{
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLMenuManager.m (hunk 7 above)
Comment (FrankElias77) [reply SmartDeviceLink/private/SDLMenuManager.m:554]: Sure!

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 18]
```diff
@@ -539,7 +539,7 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
 
     NSMutableSet<SDLArtwork *> *mutableArtworks = [NSMutableSet set];
     for (SDLMenuCell *cell in cells) {
-        if ([self sdl_artworkNeedsUpload:cell.icon]) {
+        if (self.fileManager != nil && [self.fileManager fileNeedsUpload:cell.icon]) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:542]:
```suggestion
        if ([self.fileManager fileNeedsUpload:cell.icon]) {
```

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 19]
```diff
@@ -551,8 +551,17 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
     return [mutableArtworks allObjects];
 }
 
-- (BOOL)sdl_artworkNeedsUpload:(SDLArtwork *)artwork {
-    return (artwork != nil && ![self.fileManager hasUploadedFile:artwork] && !artwork.isStaticIcon);
+- (BOOL)sdl_areAllCellArtworksUploaded:(NSArray<SDLMenuCell *> *)cells {
+    for (SDLMenuCell *cell in cells) {
+        SDLArtwork *artwork = cell.icon;
+        if (artwork != nil && !artwork.isStaticIcon && self.fileManager != nil && ![self.fileManager hasUploadedFile:(artwork)]) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:557]:
```suggestion
        if (artwork != nil && !artwork.isStaticIcon && ![self.fileManager hasUploadedFile:artwork]) {
```

In addition, instead of checking `artwork != nil` here, the `fileManager hasUploadedFile:` method should return `NO` if the passed artwork is `nil`. Additionally, the implementation of `hasUploadedFile` uses `true` and `false` instead of `YES` and `NO`. Could you please fix that?

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 20]
```diff
@@ -551,8 +551,17 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
...
+            return NO;
+        } else if (cell.subCells != nil && (cell.subCells.count) > 0) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:559]:
```suggestion
        } else if (cell.subCells.count > 0) {
```

if `subCells` is `nil`, `count` will return `0`.

File: SmartDeviceLink/private/SDLPreloadChoicesOperation.m [hunk 21]
```diff
@@ -87,10 +87,10 @@ - (void)sdl_preloadCellArtworksWithCompletionHandler:(void(^)(NSError *_Nullable
 
     NSMutableArray<SDLArtwork *> *artworksToUpload = [NSMutableArray arrayWithCapacity:self.cellsToUpload.count];
     for (SDLChoiceCell *cell in self.cellsToUpload) {
-        if ([self sdl_shouldSendChoicePrimaryImage] && [self sdl_artworkNeedsUpload:cell.artwork]) {
+        if ([self sdl_shouldSendChoicePrimaryImage] && self.fileManager != nil && ([self.fileManager fileNeedsUpload:cell.artwork])) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLPreloadChoicesOperation.m:90]:
```suggestion
        if ([self sdl_shouldSendChoicePrimaryImage] && [self.fileManager fileNeedsUpload:cell.artwork]) {
```

File: SmartDeviceLink/private/SDLPreloadChoicesOperation.m [hunk 22]
```diff
@@ -87,10 +87,10 @@ - (void)sdl_preloadCellArtworksWithCompletionHandler:(void(^)(NSError *_Nullable
...
             [artworksToUpload addObject:cell.artwork];
         }
-        if ([self sdl_shouldSendChoiceSecondaryImage] && [self sdl_artworkNeedsUpload:cell.secondaryArtwork]) {
+        if ([self sdl_shouldSendChoiceSecondaryImage] && self.fileManager != nil && ([self.fileManager fileNeedsUpload:cell.secondaryArtwork])) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLPreloadChoicesOperation.m:93]:
```suggestion
        if ([self sdl_shouldSendChoiceSecondaryImage] && [self.fileManager fileNeedsUpload:cell.secondaryArtwork]) {
```

File: SmartDeviceLink/private/SDLSoftButtonReplaceOperation.m [hunk 23]
```diff
@@ -103,7 +103,7 @@ - (void)start {
 - (void)sdl_uploadInitialStateImagesWithCompletionHandler:(void (^)(void))handler {
     NSMutableArray<SDLArtwork *> *initialStatesToBeUploaded = [NSMutableArray array];
     for (SDLSoftButtonObject *object in self.softButtonObjects) {
-        if ([self sdl_artworkNeedsUpload:object.currentState.artwork]) {
+        if (self.fileManager != nil && [self.fileManager fileNeedsUpload:object.currentState.artwork] && self.softButtonCapabilities.imageSupported.boolValue) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLSoftButtonReplaceOperation.m:106]:
```suggestion
        if ([self.fileManager fileNeedsUpload:object.currentState.artwork]) {
```

Everything else here is unnecessary, you check if images are supported near the top of `start`

File: SmartDeviceLink/private/SDLSoftButtonReplaceOperation.m [hunk 24]
```diff
@@ -118,7 +118,7 @@ - (void)sdl_uploadOtherStateImagesWithCompletionHandler:(void (^)(void))handler
     for (SDLSoftButtonObject *object in self.softButtonObjects) {
         for (SDLSoftButtonState *state in object.states) {
             if ([state.name isEqualToString:object.currentState.name]) { continue; }
-            if ([self sdl_artworkNeedsUpload:state.artwork]) {
+            if (self.fileManager != nil && [self.fileManager fileNeedsUpload:state.artwork] && self.softButtonCapabilities.imageSupported.boolValue) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLSoftButtonReplaceOperation.m:121]:
```suggestion
            if ([self.fileManager fileNeedsUpload:state.artwork]) {
```

File: SmartDeviceLink/private/SDLSoftButtonReplaceOperation.m [hunk 25]
```diff
@@ -227,17 +227,13 @@ - (void)sdl_sendCurrentStateTextOnlySoftButtonsWithCompletionHandler:(void (^)(B
...
-}
-
 /// Checks all the button states for images that need to be uploaded.
 /// @return True if all images have been uploaded; false at least one image needs to be uploaded
 - (BOOL)sdl_allStateImagesAreUploaded {
     for (SDLSoftButtonObject *button in self.softButtonObjects) {
         for (SDLSoftButtonState *state in button.states) {
             SDLArtwork *artwork = state.artwork;
-            if (![self sdl_artworkNeedsUpload:artwork]) { continue; }
+            if (self.fileManager != nil && ![self.fileManager fileNeedsUpload:artwork] && self.softButtonCapabilities.imageSupported.boolValue) { continue; }
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLSoftButtonReplaceOperation.m:236]:
```suggestion
            if (![self.fileManager fileNeedsUpload:artwork]) { continue; }
```

File: SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m [hunk 26]
```diff
@@ -111,7 +111,7 @@ - (void)sdl_updateGraphicsAndShow:(SDLShow *)show {
             }
             [strongSelf finishOperation];
         }];
-    } else if (![self sdl_artworkNeedsUpload:self.updatedState.primaryGraphic] && ![self sdl_artworkNeedsUpload:self.updatedState.secondaryGraphic]) {
+    } else if (self.fileManager != nil && ![self.fileManager fileNeedsUpload:self.updatedState.primaryGraphic] && ![self.fileManager fileNeedsUpload:self.updatedState.secondaryGraphic]) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m:114]:
```suggestion
    } else if (![self.fileManager fileNeedsUpload:self.updatedState.primaryGraphic] && ![self.fileManager fileNeedsUpload:self.updatedState.secondaryGraphic]) {
```

File: SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m [hunk 27]
```diff
@@ -515,30 +515,36 @@ - (void)sdl_updateCurrentScreenDataFromSetDisplayLayout:(SDLSetDisplayLayout *)s
...
 #pragma mark - Should Update
 
-- (BOOL)sdl_artworkNeedsUpload:(SDLArtwork *)artwork {
-    return (artwork != nil && ![self.fileManager hasUploadedFile:artwork] && !artwork.isStaticIcon);
+- (BOOL)sdl_isArtworkUploaded:(nullable SDLArtwork *)artwork {
+    if (artwork != nil) {
+        return artwork.isStaticIcon || (self.fileManager != nil && [self.fileManager hasUploadedFile:artwork]);
+    }
+
+    return NO;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m:523]:
```suggestion
    if (artwork == nil) { return NO; }
    
    return (artwork.isStaticIcon || [self.fileManager hasUploadedFile:artwork]);
```

File: SmartDeviceLink/public/SDLFileManager.h [hunk 28]
```diff
@@ -136,6 +136,19 @@ typedef void (^SDLFileManagerStartupCompletionHandler)(BOOL success, NSError *__
...
+ * Check if an SdlFile needs to be uploaded to Core or not.
+ * It is different from hasUploadedFile() because it takes isStaticIcon and overwrite properties into consideration.
+ * ie, if the file is static icon, the method always returns false.
+ * If the file is dynamic, it returns true in one of these situations:
+ * 1) the file has the overwrite property set to true
+ * 2) the file hasn't been uploaded to Core before.
+ *
+ * @param file the SdlFile that needs to be checked
+ * @return boolean that tells whether file needs to be uploaded to Core or not
+ */
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLFileManager.h:149]:
```suggestion
/**
 * Check if an SDLFile needs to be uploaded to Core or not. This method differs from hasUploadedFile() because it takes the `isStaticIcon` and `overwrite` properties into consideration.
 *
 * For example, if the file is static icon, the method always returns false.
 *
 * If the file is dynamic, it returns true in one of these situations: 1) the file has the overwrite property set to true, 2) the file hasn't been uploaded to Core before.
 *
 * @param file the SDLFile that needs to be checked
 * @return BOOL that tells whether file needs to be uploaded to Core or not
 */
```

File: SmartDeviceLink/public/SDLFileManager.m [hunk 29]
```diff
@@ -426,6 +426,14 @@ - (void)sdl_uploadFile:(SDLFile *)file completionHandler:(nullable SDLFileManage
 
 #pragma mark Artworks
 
+- (BOOL)fileNeedsUpload:(SDLFile *)file {
+    if (file != nil && !file.isStaticIcon) {
+        return (file.overwrite || ![self hasUploadedFile:file]);
+    }
+
+    return NO;
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLFileManager.m:434]:
```suggestion
    if (file == nil || file.isStaticIcon) { return NO; }
    
    return (file.overwrite || ![self hasUploadedFile:file]);
```

File: SmartDeviceLink/public/SDLFileManager.m [hunk 30]
```diff
@@ -426,6 +426,14 @@ - (void)sdl_uploadFile:(SDLFile *)file completionHandler:(nullable SDLFileManage
 
 #pragma mark Artworks
 
+- (BOOL)fileNeedsUpload:(SDLFile *)file {
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLFileManager.m:429]: This method needs unit tests

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLPreloadChoicesOperation.m [hunk 31]
```diff
@@ -87,10 +87,10 @@ - (void)sdl_preloadCellArtworksWithCompletionHandler:(void(^)(NSError *_Nullable
 
     NSMutableArray<SDLArtwork *> *artworksToUpload = [NSMutableArray arrayWithCapacity:self.cellsToUpload.count];
     for (SDLChoiceCell *cell in self.cellsToUpload) {
-        if ([self sdl_shouldSendChoicePrimaryImage] && self.fileManager != nil && ([self.fileManager fileNeedsUpload:cell.artwork])) {
+        if ([self sdl_shouldSendChoicePrimaryImage] && ([self.fileManager fileNeedsUpload:cell.artwork])) {
             [artworksToUpload addObject:cell.artwork];
         }
-        if ([self sdl_shouldSendChoiceSecondaryImage] && self.fileManager != nil && ([self.fileManager fileNeedsUpload:cell.secondaryArtwork])) {
+        if ([self sdl_shouldSendChoiceSecondaryImage] && ([self.fileManager fileNeedsUpload:cell.secondaryArtwork])) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLPreloadChoicesOperation.m:93]:
```suggestion
        if ([self sdl_shouldSendChoiceSecondaryImage] && [self.fileManager fileNeedsUpload:cell.secondaryArtwork]) {
```

File: SmartDeviceLink/private/SDLPreloadChoicesOperation.m [hunk 32]
```diff
@@ -87,10 +87,10 @@ - (void)sdl_preloadCellArtworksWithCompletionHandler:(void(^)(NSError *_Nullable
 
     NSMutableArray<SDLArtwork *> *artworksToUpload = [NSMutableArray arrayWithCapacity:self.cellsToUpload.count];
     for (SDLChoiceCell *cell in self.cellsToUpload) {
-        if ([self sdl_shouldSendChoicePrimaryImage] && self.fileManager != nil && ([self.fileManager fileNeedsUpload:cell.artwork])) {
+        if ([self sdl_shouldSendChoicePrimaryImage] && ([self.fileManager fileNeedsUpload:cell.artwork])) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLPreloadChoicesOperation.m:90]:
```suggestion
        if ([self sdl_shouldSendChoicePrimaryImage] && [self.fileManager fileNeedsUpload:cell.artwork]) {
```

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 33]
```diff
@@ -554,9 +554,9 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
 - (BOOL)sdl_areAllCellArtworksUploaded:(NSArray<SDLMenuCell *> *)cells {
     for (SDLMenuCell *cell in cells) {
         SDLArtwork *artwork = cell.icon;
-        if (artwork != nil && !artwork.isStaticIcon && self.fileManager != nil && ![self.fileManager hasUploadedFile:(artwork)]) {
+        if (artwork != nil && !artwork.isStaticIcon && ![self.fileManager hasUploadedFile:artwork]) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:557]: I _think_ that this code will cause a failure in the following situation:

`cells` array: `@[cellWithArt, cellWithoutArt]` passed to this method will return `NO`, because the `cellWithoutArt` returns `NO` after the `artwork != nil` check. This should be fixed by some code like:

```objc
if (artwork == nil) { continue; }
```

Because this method should only check if all the artworks are uploaded, not if they all have artwork **and** that artwork is uploaded, if that makes sense.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]
