### PR TITLE
Fixing issue that caused SDLTransportDidDisconnect to get called befo…

### LINKED ISSUE #1097: Manager reconnects after receiving a `OnAppInterfaceUnregistered` notification
### Bug Report
The lifecycle manager attempts to reconnect to Core after receiving a `OnAppInterfaceUnregistered` notification with a reason code of `PROTOCOL_VIOLATION`. 

Currently the `SDLLifecycleManager` only stops the manager if the reason code is `APP_UNAUTHORIZED`. It should also stop the manager if the reason code is a `PROTOCOL_VIOLATION`. 

##### Reproduction Steps
1. Connect a video streaming app with `appType` of `NAVIGATION` to a head unit that does not support video streaming. When the video streaming manager sends a video start service request, Core responds with following error:
```
[Proxy] Unregistration forced by module. {
    notification =     {
        correlationID = 4294967295;
        name = OnAppInterfaceUnregistered;
        parameters =         {
            reason = "PROTOCOL_VIOLATION";
        };
    };
}
```

##### Expected Behavior
The lifecycle manager should stop and not attempt to reconnect to Core.

##### Observed Behavior
The lifecycle manager attempts to reconnect to Core.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.1
* Testing Against: Generic HMI + SDL Core v5.0

### PR DESCRIPTION
**Pull request by justingluck93**
Fixes #1097 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Use Core and open the menu, click `UNAUTHORIZED_TRANSPORT_REGISTRATION`, this will fire a `OnAppInterfaceUnregistered` `APP_UNAUTHORIZED`. You can see that the app now stops then manager instead of reconnecting.

### Summary
Fixing issue that caused the proxy to reconnect before stop was called.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLProxy.m [hunk 1]
```diff
@@ -447,6 +444,10 @@ - (void)handleRPCDictionary:(NSDictionary<NSString *, id> *)dict {
     }
 
     [self sdl_invokeDelegateMethodsWithFunction:functionName message:newMessage];
+    
+    if ([functionName isEqualToString:SDLRPCFunctionNameOnAppInterfaceUnregistered] || [functionName isEqualToString:SDLRPCFunctionNameUnregisterAppInterface]) {
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLProxy.m]: Add a comment that interception of `SDLRPCFunctionNameOnAppInterfaceUnregistered` must be done **after* * it is broadcast as a notification to prevent reconnection attempts in the lifecycle manager when the `AppInterfaceUnregisteredReason` should prevent reconnections.

File: SmartDeviceLink/SDLProxy.m [hunk 2]
```diff
@@ -447,6 +444,11 @@ - (void)handleRPCDictionary:(NSDictionary<NSString *, id> *)dict {
     }
 
     [self sdl_invokeDelegateMethodsWithFunction:functionName message:newMessage];
+    
+    //Intercepting SDLRPCFunctionNameOnAppInterfaceUnregistered must happen after it is broadcasted as a notification above. This will prevent reccoction attempts in the lifecycle manager when the AppInterfaceUnregisteredReason should prevent reconnections.
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLProxy.m]: Spelling mistake `reccoction`

Comment (justingluck93) [reply SmartDeviceLink/SDLProxy.m]: Fixed ty! good catch
