### PR TITLE
Increase the timeout on some tests to fix CI fails

### LINKED ISSUE #1929: Fix Sometimes Failing CI Tests
### Bug Report
Timing issues sometimes cause CI tests to fail.

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1929 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit test fixes, no additions or removals

#### Core Tests
n/a - unit test fixes only

Core version / branch / commit hash / module tested against: n/a
HMI name / version / branch / commit hash / module tested against: n/a

### Summary
Fixed unit test timeouts to increase reliability

##### Bug Fixes
* Unit test fixes to increase reliability on CI

### Tasks Remaining:
n/a

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
One change requested.

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 1]
```diff
@@ -44,7 +44,7 @@ typedef NS_ENUM(NSInteger, SDLSecondaryTransportType) {
 };
 
 // should be in sync with SDLSecondaryTransportManager.m
-static const float RetryConnectionDelay = 5.25;
+//static const float RetryConnectionDelay = 5.25;
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m:47]: I forgot I was going to use it.

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 2]
```diff
@@ -1011,12 +1002,7 @@ __block void (^sendNotificationForHMILevel)(SDLHMILevel hmiLevel) = ^(SDLHMILeve
                     [manager.stateMachine setToState:SDLSecondaryTransportStateReconnecting fromOldState:nil callEnterTransition:YES];
                 });
 
-                // wait for the timer
-                float waitTime = RetryConnectionDelay;
-                NSLog(@"Please wait for reconnection timeout... (for %.02f seconds)", waitTime);
-                [NSThread sleepForTimeInterval:waitTime];
-
-                expect(manager.stateMachine.currentState).toEventually(equal(SDLSecondaryTransportStateConfigured));
+                expect(manager.stateMachine.currentState).withTimeout(RegisterTransportTime + 3.0).toEventually(equal(SDLSecondaryTransportStateConfigured));
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m:1005]: Did you mean to use `RetryConnectionDelay` instead of `RegisterTransportTime`?

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m (hunk 2 above)
Comment (joeljfischer) [reply SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: 🤦

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
It looks like some tests are failing in the `SDLSoftButtonManagerSpec` on the remote: https://github.com/smartdevicelink/sdl_ios/pull/1930/checks?check_run_id=2042800017
I did have it fail once in the same place when running the tests locally but couldn't reproduce after running the tests a few times.

**Review by NicoleYarroch — APPROVED** [review]
