### PR TITLE
Fix initializing soft button object error states

### LINKED ISSUE #2067: Update SoftButtonObject initialization with invalid configurations
### Bug Report
Currently we return `nil` if a `SoftButtonObject` is created with two states that are the same. There are other cases that should be handled, such as the state array having no objects or if there's no state with `initialStateName`.

##### Reproduction Steps
1. Create a soft button object with no states

##### Expected Behavior
An exception in DEBUG and a `nil` object in RELEASE

##### Observed Behavior
Undefined behavior

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 7.3.1
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App
n/a

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #2067 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
* Removed unnecessary stubs from soft button object tests

#### Core Tests
* Tested setting multiple soft buttons, some with one state and some with multiple states

Core version / branch / commit hash / module tested against: Manticore (Core v8.0.0)
HMI name / version / branch / commit hash / module tested against: Manticore (Generic_HMI v0.11.0)

### Summary
This PR updates creating `SoftButtonObject`s to properly crash in DEBUG when states are invalid and return `nil` in RELEASE.

##### Bug Fixes
* Creating `SoftButtonObject`s properly crash in DEBUG when states are invalid and return `nil` in RELEASE.

### Tasks Remaining:
n/a

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/public/SDLSoftButtonObject.m [hunk 1]
```diff
@@ -36,10 +36,16 @@ - (instancetype)initWithName:(NSString *)name states:(NSArray<SDLSoftButtonState
...
+    BOOL hasStateWithInitialName = NO;
+    for (SDLSoftButtonState *state in states) {
+        if ([state.name isEqualToString:initialStateName]) {
+            hasStateWithInitialName = YES;
+        }
     }
+    NSAssert(![self sdl_hasTwoStatesOfSameName:states], @"A SoftButtonObject must have states with different names.");
+    NSAssert(hasStateWithInitialName, @"A SoftButtonObject must have a state with initialStateName.");
+    if ([self sdl_hasTwoStatesOfSameName:states]) { return nil; }
+    if (!hasStateWithInitialName) { return nil; }
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLSoftButtonObject.m:48]: Need to log errors here

File: SmartDeviceLink/public/SDLSoftButtonState.m [hunk 2]
```diff
@@ -33,6 +33,7 @@ @implementation SDLSoftButtonState
 
 - (instancetype)initWithStateName:(NSString *)stateName text:(nullable NSString *)text image:(nullable UIImage *)image {
     NSParameterAssert((text != nil) || (image != nil));
+    if ((text == nil) && (image == nil)) { return nil; }
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLSoftButtonState.m:36]: Log error

File: SmartDeviceLink/public/SDLSoftButtonState.m [hunk 3]
```diff
@@ -43,6 +44,7 @@ - (instancetype)initWithStateName:(NSString *)stateName text:(nullable NSString
     if (!self) { return nil; }
 
     NSParameterAssert((text != nil) || (artwork != nil));
+    if ((text == nil) && (artwork == nil)) { return nil; }
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLSoftButtonState.m:47]: Log error

**Review by FrankElias77 — APPROVED** [review]
