### PR TITLE
Security manager set for secondary protocol

### LINKED ISSUE #1476: SecurityManager not set for SecondaryProtocol
### Bug Report
SecurityManager not set for SecondaryProtocol

##### Reproduction Steps
1. Install a Mobile Navigation App on your iPhone with sdl_ios 6.4.1
2. Connect your iPhone over Bluetooth to the IVI
3. Connect your iPhone over WiFi to the IVI
4. Make sure the Mobile Nav App is connected and permissions up-to-date
5. Start the Mobile Nav App on the IVI

##### Expected Behavior
- The Mobile Nav App should connect Audio and Video over the secondary protocol
- The Mobile Nav App should authenticate on the secondary protocol
- The Mobile Nav App should start streaming the UI to the IVI

##### Observed Behavior
- Error message in the logs: `Could not start streaming service, encryption was requested by the remote system but failed because there is no security manager set for this app` in `SDLProtocol.m:205`
- Investigation showed that PrimaryProtocol has a SecurityManager set in [`SDLProxy.m:534`](https://github.com/smartdevicelink/sdl_ios/blob/6.4.1/SmartDeviceLink/SDLProxy.m#L534) 
- The SecondaryProtocol is created in [`SDLSecondaryTransportManager.m:528`](https://github.com/smartdevicelink/sdl_ios/blob/6.4.1/SmartDeviceLink/SDLSecondaryTransportManager.m#L528) but it's never set to the same SecurityManager.
- After manually setting `secondaryProtocol.securityManager = primaryProtocol.securityManager` the app started streaming.

##### OS & Version Information
* iOS Version: 13.2
* SDL iOS Version: 6.4.1
* Testing Against: Ford SYNC bench with secondary transport

### PR DESCRIPTION
**Pull request by justingluck93**
Fixes #1476 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Tests secondary transport to see if video encryption works

### Summary
Set secondary transports security manager so RPC encryption will work.

### Tasks Remaining:
- [ ] Have Ford test with this branch 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 1]
```diff
@@ -509,6 +509,9 @@ - (BOOL)sdl_startTCPSecondaryTransport {
     [protocol.protocolDelegateTable addObject:self];
 
     self.secondaryProtocol = protocol;
+    if(self.primaryProtocol.securityManager) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m]:
```suggestion
    if (self.primaryProtocol.securityManager) {
```

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 2]
```diff
@@ -531,6 +534,9 @@ - (BOOL)sdl_startIAPSecondaryTransport {
...
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m]:
```suggestion
    if (self.primaryProtocol.securityManager) {
```

**Comment by joeljfischer** [comment]
@kshala-ford Can you please confirm that this PR fixes your issue?

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 3]
```diff
@@ -509,6 +509,9 @@ - (BOOL)sdl_startTCPSecondaryTransport {
...
+        self.secondaryProtocol.securityManager = self.primaryProtocol.securityManager;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m]: I think you can just remove the if statement

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 4]
```diff
@@ -531,6 +534,9 @@ - (BOOL)sdl_startIAPSecondaryTransport {
...
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m]: See above

Comment (justingluck93) [reply SmartDeviceLink/SDLSecondaryTransportManager.m]: done

File: SmartDeviceLink/SDLSecondaryTransportManager.m (hunk 3 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLSecondaryTransportManager.m]: done

**Comment by mrapitis** [comment]
@joeljfischer we will test on the bench and provide feedback. Thanks!

**Comment by mrapitis** [comment]
@justingluck93 we have performed some testing on the bench and unfortunately the problem has not been completely solved.  The primary use case, when the app is placed into a streamable state for the first time still reports an error regarding the security manager not being set.  However for secondary use cases, when the app is placed into a streamable state, followed by a not streamable, followed by a streamable state are working now.  We will continue to investigate on our side, but it does seem like we are still missing a step in the flow.

**Comment by justingluck93** [comment]
@mrapitis @kshala-ford Can you please try to test again with this PR!

**Comment by mrapitis** [comment]
@justingluck93 no resolution with the additional changes.  

Upon further investigation it looks like a race condition is occurring between handleRegisterAppInterfaceResponse linked below and the SecondaryTransportManager.  There is no synchronization between these two events which is causing an issue.  Sometimes the RAI response will be received before the setup of the SecondaryTransportManager, othertimes the SecondaryTransport will be setup first -- however the security manager is not available until after the RegisterAppInterfaceResponse is received.  It seems like the SecondaryTransportManager needs to be able to query SDLProxy if the SecurityManager is available and if so, set its value internally.  Also, if the SecurityManager is updated in the handleRegisterAppInterfaceResponse, it should notify the SecondaryTransportManager to update its value for the SecurityManager.  

https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink/SDLProxy.m#L534

File: SmartDeviceLink/SDLNotificationConstants.h [hunk 5]
```diff
@@ -130,6 +130,9 @@ extern SDLNotificationName const SDLDidBecomeReady;
 /// Name for a notification sent by the user when their CarWindow view has been updated
 extern SDLNotificationName const SDLDidUpdateProjectionView;
 
+// Name for a security manager set notification
+extern SDLNotificationName const SDLSecurityManagerSet;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLNotificationConstants.h]:
```suggestion
extern SDLNotificationName const SDLDidSetSecurityManager;
```

Comment (joeljfischer) [reply SmartDeviceLink/SDLNotificationConstants.h]: This is the wrong place for this. You're adding a public API.

File: SmartDeviceLink/SDLNotificationConstants.m [hunk 6]
```diff
@@ -22,6 +22,8 @@
 SDLNotificationName const SDLDidBecomeReady = @"com.sdl.notification.managerReady";
 SDLNotificationName const SDLDidReceiveVehicleIconNotification = @"com.sdl.notification.vehicleIcon";
 SDLNotificationName const SDLDidUpdateProjectionView = @"com.sdl.notification.projectionViewUpdate";
+SDLNotificationName const SDLSecurityManagerSet = @"com.sdl.notification.securityManagerSet";
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLNotificationConstants.m]: See above

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 7]
```diff
@@ -705,6 +709,10 @@ - (SDLSecondaryTransportType)sdl_getTransportTypeFromProtocol:(SDLProtocol *)pro
     }
 }
 
+- (void)securityManagerWasSet {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m]:
```suggestion
- (void)proxyDidSetSecurityManager {
```

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 8]
```diff
@@ -705,6 +709,10 @@ - (SDLSecondaryTransportType)sdl_getTransportTypeFromProtocol:(SDLProtocol *)pro
...
+    self.secondaryProtocol.securityManager = self.primaryProtocol.securityManager;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m]: Did you test this? It doesn't seem like it'd be enough to restart the secondary transport manager in checking and setting the security manager.

You need to test after updating:

1. Does this work if you don't set a security manager.
2. Does this work if the `TransportEventUpdate` is set before the RAIR is returned.
3. Does this work if the `TransportEventUpdate` is set after the RAIR is returned.

Comment (justingluck93) [reply SmartDeviceLink/SDLSecondaryTransportManager.m]: this should be resolved now

File: SmartDeviceLink/SDLProxy.m [hunk 9]
```diff
@@ -535,7 +535,6 @@ - (void)handleRegisterAppInterfaceResponse:(SDLRPCResponse *)response {
     if (self.protocol.securityManager && [self.protocol.securityManager respondsToSelector:@selector(setAppId:)]) {
         self.protocol.securityManager.appId = self.appId;
     }
-
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProxy.m]: Add this back in

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 10]
```diff
@@ -94,6 +95,8 @@ @interface SDLSecondaryTransportManager ()
 @property (strong, nonatomic, nullable) NSString *ipAddress;
 // TCP port number of SDL Core. If the information isn't available then TCPPortUnspecified is stored.
 @property (assign, nonatomic) int tcpPort;
+// App is ready to set security manager to secondary protocol
+@property (assign, nonatomic) BOOL isAppReady;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m]:
```suggestion
@property (assign, nonatomic, getter=isAppReady) BOOL appReady;
```

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 11]
```diff
@@ -352,6 +357,7 @@ - (void)sdl_configureManager:(nullable NSArray<SDLSecondaryTransportTypeBox *> *
     // this will trigger audio / video streaming if they are allowed on primary transport
     [self sdl_handleTransportUpdateWithPrimaryAvailable:YES secondaryAvailable:NO];
 
+    self.isAppReady = true;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m]: Why is this here instead of in `appDidBecomeReady`? Also remember that in Obj-C, true / false is YES / NO.

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 12]
```diff
@@ -705,6 +713,13 @@ - (SDLSecondaryTransportType)sdl_getTransportTypeFromProtocol:(SDLProtocol *)pro
     }
 }
 
+- (void)appDidBecomeReady {
+    self.secondaryProtocol.securityManager = self.primaryProtocol.securityManager;
+    if ([self.stateMachine.currentState isEqualToString:SDLSecondaryTransportStateConfigured]) {
+         [self.stateMachine transitionToState:SDLSecondaryTransportStateConnecting];
+    }
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m]: Do you not need to set the security manager here?

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 13]
```diff
@@ -52,6 +52,7 @@ @interface SDLSecondaryTransportManager ()
 @property (strong, nonatomic) NSMutableDictionary<SDLServiceTypeBox *, SDLTransportClassBox *> *streamingServiceTransportMap;
 @property (strong, nonatomic, nullable) NSString *ipAddress;
 @property (assign, nonatomic) int tcpPort;
+@property (assign, nonatomic) BOOL isAppReady;
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: You really should add new tests for each of these issues:

1. When the security manager is set before the RAIR
2. When the security manager is set after the RAIR

File: SmartDeviceLink/SDLSecondaryTransportManager.m (hunk 12 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLSecondaryTransportManager.m]: removed

File: SmartDeviceLink/SDLProxy.m (hunk 9 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLProxy.m]: added

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m (hunk 13 above)
Comment (justingluck93) [reply SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: added

File: SmartDeviceLink/SDLProxy.m [hunk 14]
```diff
@@ -535,7 +535,7 @@ - (void)handleRegisterAppInterfaceResponse:(SDLRPCResponse *)response {
...
+
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProxy.m]:
```suggestion

```

File: SmartDeviceLink/SDLSecondaryTransportManager.m (hunk 12 above)
Comment (joeljfischer) [reply SmartDeviceLink/SDLSecondaryTransportManager.m]: I don't think you understood my original comment. I think you _do_ need to set it here, right? Or not? If not, why not?

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 15]
```diff
@@ -491,44 +496,67 @@ + (void)swapConnectionMethods {
...
+
                 dispatch_sync(testStateMachineQueue, ^{
                     [manager startWithPrimaryProtocol:testPrimaryProtocol];
                 });
 
                 manager.secondaryTransportType = SDLTransportSelectionIAP;
             });
 
-            it(@"should transition to Connecting state", ^{
+            it(@"should transition to Connecting state but before RAIR is sent", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: I'm not understanding what this means. What is this testing? It's testing that the security manager is `nil` here?

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 16]
```diff
@@ -491,44 +496,67 @@ + (void)swapConnectionMethods {
...
                     [manager.stateMachine transitionToState:SDLSecondaryTransportStateConfigured];
                 });
 
                 expect(manager.stateMachine.currentState).to(equal(SDLSecondaryTransportStateConnecting));
+                expect(manager.secondaryProtocol.securityManager).to(beNil());
+
                 OCMVerifyAll(testStreamingProtocolDelegate);
             });
+
+            it(@"should transition to Connecting state after RAIR is sent", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: I'm not sure what this is testing? That it transitions to the Connecting state if the security manager is set and the library becomes ready? I don't know that that's worth testing.

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 17]
```diff
@@ -491,44 +496,67 @@ + (void)swapConnectionMethods {
...
-                dispatch_sync(testStateMachineQueue, ^{
-                    [manager.stateMachine transitionToState:SDLSecondaryTransportStateConfigured];
-                });
             });
 
             describe(@"and Transport Event Update is not received", ^{
                 it(@"should stay in Configured state", ^{
+
+                    dispatch_sync(testStateMachineQueue, ^{
+                        [manager.stateMachine transitionToState:SDLSecondaryTransportStateConfigured];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: Why did you add this here?

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 18]
```diff
@@ -552,11 +580,34 @@ + (void)swapConnectionMethods {
                     testTransportEventUpdateMessage = [[SDLV2ProtocolMessage alloc] initWithHeader:testTransportEventUpdateHeader andPayload:testTransportEventUpdatePayload.data];
                 });
 
-                it(@"should transition to Connecting state", ^{
+                it(@"should transition to Connecting state but before RAIR is sent", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: Again, this is poor documentation / naming. Are you trying to say / test "it should transition to the connecting state when a transport event update is received and there's no security manager"?

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 19]
```diff
@@ -552,11 +580,34 @@ + (void)swapConnectionMethods {
...
+
+                    [testPrimaryProtocol handleBytesFromTransport:testTransportEventUpdateMessage.data];
+                    [NSThread sleepForTimeInterval:0.1];
+
+                    expect(manager.stateMachine.currentState).to(equal(SDLSecondaryTransportStateConnecting));
+                    expect(manager.secondaryProtocol.securityManager).to(beNil());
+                    OCMVerifyAll(testStreamingProtocolDelegate);
+                });
+
+                it(@"should transition to Connecting state after RAIR is sent", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: Again poor documentation / naming. Is this "it should transition to the connecting state after the library becomes ready when a security manager is set"?

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 20]
```diff
@@ -700,6 +750,7 @@ + (void)swapConnectionMethods {
                 manager.secondaryTransportType = SDLTransportSelectionTCP;
                 manager.ipAddress = @"192.168.1.1";
                 manager.tcpPort = 12345;
+                manager.appReady = YES;
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: When the transport is closed, `appReady` is going to be `NO`, right? If not, then when you enter the `reconnecting` state in the `SecondaryTransportManager` you need to reset it to `NO`.

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 21]
```diff
@@ -483,36 +488,62 @@ + (void)swapConnectionMethods {
...
 
                 manager.secondaryTransportType = SDLTransportSelectionIAP;
             });
 
-            it(@"should transition to Connecting state", ^{
-                // setToState cannot be used here, as the method will set the state after calling didEnterStateConfigured
-                dispatch_sync(testStateMachineQueue, ^{
-                    [manager.stateMachine transitionToState:SDLSecondaryTransportStateConfigured];
+            context(@"before the security manager is set by register app interface response", ^{
+                it(@"should transition to Connecting", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: It should transition to connecting before the security manager is set or isAppReady is set? That doesn't seem right?

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 22]
```diff
@@ -483,36 +488,62 @@ + (void)swapConnectionMethods {
...
+
+                    OCMVerifyAll(testStreamingProtocolDelegate);
                 });
+            });
 
-                expect(manager.stateMachine.currentState).to(equal(SDLSecondaryTransportStateConnecting));
-                OCMVerifyAll(testStreamingProtocolDelegate);
+            context(@"after the security manager is set by register app interface response", ^{
+                it(@"should transition to Connecting state", ^{
+                    testPrimaryProtocol.securityManager = OCMClassMock([SDLFakeSecurityManager class]);
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: This should be in a beforeEach in the context.

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 23]
```diff
@@ -483,36 +488,62 @@ + (void)swapConnectionMethods {
...
+
+                    dispatch_sync(testStateMachineQueue, ^{
+                         [manager.stateMachine setToState:SDLSecondaryTransportStateConfigured fromOldState:nil callEnterTransition:NO];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: See above, this should be set in the appropriate describe.

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 24]
```diff
@@ -483,36 +488,62 @@ + (void)swapConnectionMethods {
...
+                    });
+
+                    // By the time this notification is recieved the RAIR should have been sent and the security manager should exist if available
+                    [[NSNotificationCenter defaultCenter] postNotificationName:SDLDidBecomeReady object:nil];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: Same as above, this should be in the beforeEach

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 25]
```diff
@@ -528,7 +559,9 @@ + (void)swapConnectionMethods {
 
             describe(@"and Transport Event Update is not received", ^{
                 it(@"should stay in Configured state", ^{
+
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]:
```suggestion
```

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 26]
```diff
@@ -552,12 +585,32 @@ + (void)swapConnectionMethods {
                     testTransportEventUpdateMessage = [[SDLV2ProtocolMessage alloc] initWithHeader:testTransportEventUpdateHeader andPayload:testTransportEventUpdatePayload.data];
                 });
 
-                it(@"should transition to Connecting state", ^{
-                    [testPrimaryProtocol handleBytesFromTransport:testTransportEventUpdateMessage.data];
-                    [NSThread sleepForTimeInterval:0.1];
+                context(@"before the security manager is set by register app interface response", ^{
+                    it(@"should transition to Connecting", ^{
+                        [testPrimaryProtocol handleBytesFromTransport:testTransportEventUpdateMessage.data];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: This should be sent in the above beforeEach.

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 27]
```diff
@@ -552,12 +585,32 @@ + (void)swapConnectionMethods {
...
+                        [NSThread sleepForTimeInterval:0.1];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: Same

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 28]
```diff
@@ -552,12 +585,32 @@ + (void)swapConnectionMethods {
...
-                    OCMVerifyAll(testStreamingProtocolDelegate);
+                        expect(manager.stateMachine.currentState).to(equal(SDLSecondaryTransportStateConnecting));
+                        expect(manager.secondaryProtocol.securityManager).to(beNil());
+                        OCMVerifyAll(testStreamingProtocolDelegate);
+                    });
+                });
+
+                context(@"after the security manager is set by register app interface response", ^{
+                    it(@"should transition to Connecting", ^{
+                        testPrimaryProtocol.securityManager = OCMClassMock([SDLFakeSecurityManager class]);
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: See above

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m (hunk 23 above)
Comment (justingluck93) [reply SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: Done

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m (hunk 22 above)
Comment (justingluck93) [reply SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: Done

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m [hunk 29]
```diff
@@ -483,36 +488,62 @@ + (void)swapConnectionMethods {
...
             });
 
-            it(@"should transition to Connecting state", ^{
-                // setToState cannot be used here, as the method will set the state after calling didEnterStateConfigured
-                dispatch_sync(testStateMachineQueue, ^{
-                    [manager.stateMachine transitionToState:SDLSecondaryTransportStateConfigured];
+            context(@"before the security manager is set by register app interface response", ^{
+                it(@"should transition to Connecting", ^{
+                    // setToState cannot be used here, as the method will set the state after calling didEnterStateConfigured
+                    dispatch_sync(testStateMachineQueue, ^{
```
[the remark this answers is not in the document]
Comment (justingluck93) [reply SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: Done

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m (hunk 21 above)
Comment (justingluck93) [reply SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: i fixed the code to match this catch! the manager would connect on an or case

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m (hunk 24 above)
Comment (justingluck93) [reply SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: moved

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m (hunk 26 above)
Comment (justingluck93) [reply SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: moved

File: SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m (hunk 28 above)
Comment (justingluck93) [reply SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m]: moved

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 30]
```diff
@@ -705,6 +713,13 @@ - (SDLSecondaryTransportType)sdl_getTransportTypeFromProtocol:(SDLProtocol *)pro
     }
 }
 
+- (void)appDidBecomeReady {
+    self.appReady = YES;
+    if (([self.stateMachine.currentState isEqualToString:SDLSecondaryTransportStateConfigured] && self.tcpPort != SDLControlFrameInt32NotFound && self.ipAddress) || self.secondaryTransportType == SDLSecondaryTransportTypeIAP) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m]: Check `self.ipAddress != nil` instead. Move the OR to the next line. Like so:

```objc
    if (([self.stateMachine.currentState isEqualToString:SDLSecondaryTransportStateConfigured] && self.tcpPort != SDLControlFrameInt32NotFound && self.ipAddress != nil) 
       || self.secondaryTransportType == SDLSecondaryTransportTypeIAP) {
```

**Comment by joeljfischer** [comment]
@mrapitis Could you test again with this branch?

**Comment by mrapitis** [comment]
@joeljfischer, @justingluck93 initial test results are looking good with the updated PR.  We will continue to test and provide feedback.

**Comment by theresalech** [comment]
Hi @mrapitis, do you have any update on your additional testing?  If possible, can you please let us know when you anticipate testing being completed?  We are working to determine when we can include this fix in a library release.  Thanks!

**Comment by joeljfischer** [comment]
@mrapitis Hi Markos, could you please provide us an update on this fix?

**Comment by mrapitis** [comment]
@joeljfischer Hi Joel, the changes look to be working well.  Can we plan to include this fix in an upcoming release?

**Comment by joeljfischer** [comment]
@mrapitis Thanks for the update. I will have a discussion with our PMs about including this in an upcoming release.
