### PR TITLE
Fix SoftButtonManager Race Conditions

### LINKED ISSUE #1177: The soft button manager can enter an infinite loop when artwork upload fails
### Bug Report
If the phone is disconnected from Core while soft button images are being uploaded, the soft button manager will enter an infinite loop trying to upload images. It should only attempt to upload the artworks the number of times set by the user in the `SDLFileManagerConfiguration`.  I assume this bug will also occur if any of the soft button artwork uploads fail. 

##### Reproduction Steps
1. Connect the example app to Core
2. Disconnect the example app from Core while the soft button images are being uploaded. Do not close the app.

##### Expected Behavior
The soft button manager stops attempting to upload images after the max number of uploads attempts has been reached (as set by the user in the `SDLFileManagerConfiguration`).

##### Observed Behavior
The soft button manager enters an infinite loop of trying to upload the image. 

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.1
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App

[Soft Button Manager Infinite Loop.log.zip](https://github.com/smartdevicelink/sdl_ios/files/2941549/Soft.Button.Manager.Infinite.Loop.log.zip)

### LINKED ISSUE #1234: Transitioning multiple soft buttons to the next state in the Soft Button manager fails
### Bug Report
1. If two soft buttons transition to the new state at the same time, the second button state will not be sent in the `updateWithCompletionHandler:` method because the `isDirty` param is set to `NO` by the first button transition. 

##### Reproduction Steps
1. Use the `ScreenManager` to set two buttons, buttonA and buttonB, with multiple states. When buttonA is tapped, transition buttonA to the next state and buttonB to the next state.
2. Connect the app to Core
3. Tap on buttonA on the SDL app

##### Expected Behavior
Both button states transition successfully to the next state.

##### Observed Behavior
Only buttonA transitions to the next state. ButtonB stays in its current state.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.1
* Testing Against: Manticore

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1177, #1234 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Smoke tests + unit tests

### Summary
This PR fixes several longstanding state issues in the `SoftButtonManager` by simplifying the logic using `NSOperation`. One such issue is when transitioning states really close together, only one state would transition due to race conditions.

##### Bug Fixes
* Fixed race conditions in the Soft Button Manager

### Tasks Remaining:
- [x] Unit tests

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLSoftButtonReplaceOperation.h [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+@protocol SDLConnectionManagerType;
+
+NS_ASSUME_NONNULL_BEGIN
+
+@interface SDLSoftButtonReplaceOperation : SDLAsynchronousOperation
+
+@property (strong, nonatomic) NSString *mainField1;
+
+- (instancetype)initWithConnectionManager:(id<SDLConnectionManagerType>)connectionManager fileManager:(SDLFileManager *)fileManager capabilities:(SDLSoftButtonCapabilities *)capabilities softButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects mainField1:(NSString *)mainField1;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSoftButtonReplaceOperation.h]: Add documentation for the `mainField1` property and init.

File: SmartDeviceLink/SDLSoftButtonTransitionOperation.h [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+@protocol SDLConnectionManagerType;
+
+NS_ASSUME_NONNULL_BEGIN
+
+@interface SDLSoftButtonTransitionOperation : SDLAsynchronousOperation
+
+@property (strong, nonatomic) NSString *mainField1;
+
+- (instancetype)initWithConnectionManager:(id<SDLConnectionManagerType>)connectionManager capabilities:(SDLSoftButtonCapabilities *)capabilities softButtons:(NSArray<SDLSoftButtonObject *> *)softButtons mainField1:(NSString *)mainField1;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSoftButtonTransitionOperation.h]: Add documentation for the `mainField1` property and init.

File: SmartDeviceLink/SDLSoftButtonManager.m [hunk 3]
```diff
@@ -129,231 +117,52 @@ - (void)setSoftButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects
...
+    SDLSoftButtonReplaceOperation *op = [[SDLSoftButtonReplaceOperation alloc] initWithConnectionManager:self.connectionManager fileManager:self.fileManager capabilities:self.softButtonCapabilities softButtonObjects:_softButtonObjects mainField1:self.currentMainField1];
+    [self.transactionQueue cancelAllOperations];
+    [self.transactionQueue addOperation:op];
 }
 
 - (void)sdl_transitionSoftButton:(SDLSoftButtonObject *)softButton {
-    self.isDirty = YES;
-    [self updateWithCompletionHandler:nil];
+    SDLSoftButtonTransitionOperation *op = [[SDLSoftButtonTransitionOperation alloc] initWithConnectionManager:self.connectionManager capabilities:self.softButtonCapabilities softButtons:self.softButtonObjects mainField1:self.currentMainField1];
+    [self.transactionQueue addOperation:op];
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/SDLSoftButtonManager.m]: I don't think so. A batched update may not change the soft buttons, since batching affects both "soft button" and "text and graphic" managers. In addition, imagine you have the following transaction queue:

1. replace [s1, s2, s3]
2. transition [s1]

Then you start a batch with:
3. transition [s2]

If you cancel 1 and 2, then 3 will no longer make any sense.

[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLSoftButtonManager.m]: Makes sense.

File: SmartDeviceLink/SDLSoftButtonManager.h [hunk 4]
```diff
@@ -35,6 +35,9 @@ typedef void(^SDLSoftButtonUpdateCompletionHandler)(NSError *__nullable error);
  */
 @property (copy, nonatomic) NSArray<SDLSoftButtonObject *> *softButtonObjects;
 
+/**
+ All transitions made in-between beginUpdates and this method will occur as one RPC update.
+ */
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSoftButtonManager.h]: Shouldn't this be amended to say that this does not include button transitions since each transition will send a separate `Show` request?

File: SmartDeviceLink/SDLSoftButtonTransitionOperation.h [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+ The primary text field on the system template. This is necessary to HAX a workaround for Sync 3.
+ */
+@property (strong, nonatomic) NSString *mainField1;
+
+/**
+ Initialize the transition operation
+
+ @param connectionManager The manager that will send the resultant RPCs
+ @param capabilities The capabilites of the soft buttons on the current template
+ @param softButtonObjects The soft buttons that should be sent
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSoftButtonTransitionOperation.h]: `softButtonObjects` should be `softButtons` in the documentation
