### PR TITLE
SDL 0180 - Fix to support broaden choice cell uniqueness

### LINKED ISSUE #1024: [SDL 0180] Broaden Choice Uniqueness
Proposal: [Broaden Choice Uniqueness](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0180-broaden-choice-uniqueness.md)

>This proposal broadens choice and sub-menu uniqueness to allow `PerformInteraction` and sub-menu `AddCommand` primary text to be identical.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/530

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with the following revisions: numbers should be added after duplicate(s) for older versions of core, and documentation should call out that while the primary text doesn't have to be unique, it has to be clear.
> The proposal was revised to incorporate these revisions on July 12, 2018.

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1024 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit test update to support cells with same title

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
broadens choice and sub-menu uniqueness to allow PerformInteraction and sub-menu AddCommand primary text to be identical.

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* broadens choice and sub-menu uniqueness to allow PerformInteraction and sub-menu AddCommand primary text to be identical.

### Tasks Remaining:
N/a

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLChoiceSetManager.m [hunk 1]
```diff
@@ -53,6 +54,7 @@
 @interface SDLChoiceCell()
 
 @property (assign, nonatomic) UInt16 choiceId;
+@property (nonatomic, readwrite) NSString *uniqueText;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLChoiceSetManager.m:57]:
```suggestion
@property (strong, nonatomic, readwrite) NSString *uniqueText;
```

File: SmartDeviceLink/private/SDLChoiceSetManager.m [hunk 2]
```diff
@@ -445,7 +447,27 @@ - (void)dismissKeyboardWithCancelID:(NSNumber<SDLInt> *)cancelID {
 /// @param choices The choices to be uploaded
 /// @return The choices that have not yet been uploaded to the module
 - (NSSet<SDLChoiceCell *> *)sdl_choicesToBeUploadedWithArray:(NSArray<SDLChoiceCell *> *)choices {
-    NSMutableSet<SDLChoiceCell *> *choicesSet = [NSMutableSet setWithArray:choices];
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLChoiceSetManager.m:448]: It's important to keep this as a mutable set to weed out duplicates first. I think you can use fast enumeration to loop a set and I don't think the index is important here:

```objc
for (SDLChoiceCell *cell in choicesSet) {

}
```

File: SmartDeviceLink/private/SDLChoiceSetManager.m [hunk 3]
```diff
@@ -445,7 +447,27 @@ - (void)dismissKeyboardWithCancelID:(NSNumber<SDLInt> *)cancelID {
...
+    NSMutableArray<SDLChoiceCell *> *choicess = [choices mutableCopy];
+    NSMutableDictionary<NSString *, NSNumber *> *dictCounter = [[NSMutableDictionary alloc] init];
+    SDLVersion *version = [[SDLVersion alloc] initWithMajor:7 minor:1 patch:0];
+    if ([[SDLGlobals sharedGlobals].rpcVersion isLessThanVersion:version]) {
+        for (NSUInteger i = 0; i < choicess.count; i++) {
+            NSString *cellName = choicess[i].text;
+            NSNumber *counter = dictCounter[cellName];
+            if (counter) {
+                [dictCounter setObject:[NSNumber numberWithInt:counter.intValue + 1] forKey:cellName];
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLChoiceSetManager.m:458]:
```suggestion
                dictCounter[cellName] = counter + 1;
```

I think that this syntax is generally better.

File: SmartDeviceLink/private/SDLChoiceSetManager.m [hunk 4]
```diff
@@ -445,7 +447,27 @@ - (void)dismissKeyboardWithCancelID:(NSNumber<SDLInt> *)cancelID {
...
+            } else {
+                [dictCounter setObject:[NSNumber numberWithInt:1] forKey:cellName];
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLChoiceSetManager.m:460]:
```suggestion
                dictCounter[cellName] = @1;
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]
This also needs to affect MenuCell and the MenuManager

File: SmartDeviceLink/public/SDLMenuCell.m [hunk 5]
```diff
@@ -16,6 +16,8 @@ @interface SDLMenuCell()
 
 @property (assign, nonatomic) UInt32 parentCellId;
 @property (assign, nonatomic) UInt32 cellId;
+@property (strong, nonatomic, readwrite) NSString *uniqueTitle;
+@property (copy, nonatomic, readwrite, nullable) NSArray<SDLMenuCell *> *subCells;
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLMenuCell.m:20]: This doesn't seem to be necessary for these changes. Can it be removed?

File: SmartDeviceLink/public/SDLMenuCell.m [hunk 6]
```diff
@@ -52,7 +56,7 @@ - (instancetype)initWithTitle:(NSString *)title icon:(nullable SDLArtwork *)icon
 }
 
 - (NSString *)description {
-    return [NSString stringWithFormat:@"SDLMenuCell: %u-\"%@\", artworkName: %@, voice commands: %lu, isSubcell: %@, hasSubcells: %@, submenuLayout: %@", (unsigned int)_cellId, _title, _icon.name, (unsigned long)_voiceCommands.count, (_parentCellId != UINT32_MAX ? @"YES" : @"NO"), (_subCells.count > 0 ? @"YES" : @"NO"), _submenuLayout];
+    return [NSString stringWithFormat:@"SDLMenuCell: %u-\"%@\"-\"%@\", artworkName: %@, voice commands: %lu, isSubcell: %@, hasSubcells: %@, submenuLayout: %@", (unsigned int)_cellId, _title, _uniqueTitle, _icon.name, (unsigned long)_voiceCommands.count, (_parentCellId != UINT32_MAX ? @"YES" : @"NO"), (_subCells.count > 0 ? @"YES" : @"NO"), _submenuLayout];
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLMenuCell.m:59]:
```suggestion
    return [NSString stringWithFormat:@"SDLMenuCell: %u-\"%@\"", unique title: %@, artworkName: %@, voice commands: %lu, isSubcell: %@, hasSubcells: %@, submenuLayout: %@", (unsigned int)_cellId, _title, ([_title isEqualToString:_uniqueTitle] ? @"NO" : _uniqueTitle),  _icon.name, (unsigned long)_voiceCommands.count, (_parentCellId != UINT32_MAX ? @"YES" : @"NO"), (_subCells.count > 0 ? @"YES" : @"NO"), _submenuLayout];
```

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 7]
```diff
@@ -530,6 +526,33 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
     }
 }
 
+- (NSArray<SDLMenuCell *> *)sdl_addUniqueNamesToCells:(nullable NSArray<SDLMenuCell *> *)choices {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:529]:
```suggestion
- (void)sdl_addUniqueNamesToCells:(nullable NSArray<SDLMenuCell *> *)choices {
```

1. See choice set manager comment on improving this method
2. I don't think there needs to be a return value and the `subcells` doesn't need to be made public. The array is immutable, but what's within it can change. You don't have to set a new array, you can just modify the cells within the array.

**Review by joeljfischer — CHANGES_REQUESTED** [review]
Additional missing pieces:

1. `SDLMenuCellSpec`, `SDLChoiceCellSpec`, `SDLPreloadChoicesOperationSpec` updates

File: SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m [hunk 8]
```diff
@@ -169,9 +176,28 @@ - (BOOL)sdl_shouldRPCsIncludeImages:(NSArray<SDLMenuCell *> *)cells;
...
-            it(@"should fail with a duplicate title", ^{
-                testManager.menuCells = @[textOnlyCell, textOnlyCell];
-                expect(testManager.menuCells).to(beEmpty());
+            it(@"should not fail with a duplicate title", ^{
+                testManager.menuCells = @[textAndImageCell, textAndImageCell2];
+                expect(testManager.menuCells).toNot(beEmpty());
+                if ([[SDLGlobals sharedGlobals].rpcVersion isLessThanVersion:version]) {
+                    expect(testManager.menuCells.firstObject.uniqueTitle).to(equal("Test 2"));
+                    expect(testManager.menuCells.lastObject.uniqueTitle).to(equal("Test 2 (2)"));
+                } else {
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m:185]: I don't see any place where the version is changed and this is re-tested. I think you need to make two separate tests, one with the contents of each part of the if, and then modify the pre-conditions to test each properly.

File: SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m [hunk 9]
```diff
@@ -169,9 +176,28 @@ - (BOOL)sdl_shouldRPCsIncludeImages:(NSArray<SDLMenuCell *> *)cells;
...
+                }
+            });
+
+            it(@"should not fail with a duplicate title for subCells", ^{
+                testManager.menuCells = @[submenuCell2];
+                expect(testManager.menuCells).toNot(beEmpty());
+                if ([[SDLGlobals sharedGlobals].rpcVersion isLessThanVersion:version]) {
+                    expect(testManager.menuCells.firstObject.subCells.firstObject.uniqueTitle).to(equal("Test 2"));
+                    expect(testManager.menuCells.firstObject.subCells.lastObject.uniqueTitle).to(equal("Test 2 (2)"));
+                } else {
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m:197]: See above.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 10]
```diff
@@ -530,6 +529,33 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
     }
 }
 
+/// Checks if 2 or more cells have the same text/title. In case this condition is true, this function will handle the presented issue by adding "(count)".
+/// E.g. Choices param contains 2 cells with text/title "Address" will be handled by updating the uniqueText/uniqueTitle of the second cell to "Address (2)".
+/// @param choices The choices to be uploaded.
+- (void)sdl_addUniqueNamesToCells:(nullable NSArray<SDLMenuCell *> *)choices {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:535]: The cells are displaying on the head unit as:

```
Item (3)
Item (2)
Item
```

It should be:

```
Item
Item (1)
Item (2)
```

---

When testing with a subcell item (4th item) it came out as:

```
Item (3)
Item (2)
Item
Item (4) - Had subcells, but they would not appear

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/public/SDLChoiceSet.m [hunk 11]
```diff
@@ -69,16 +69,23 @@ - (instancetype)initWithTitle:(NSString *)title delegate:(id<SDLChoiceSetDelegat
...
         if (cell.voiceCommands == nil) { continue; }
         [uniqueVoiceCommands addObjectsFromArray:cell.voiceCommands];
         choiceCellWithVoiceCommandCount += 1;
         allVoiceCommandsCount += cell.voiceCommands.count;
     }
 
+    if (choicesSet.count < choices.count) {
+        SDLLogE(@"Attempted to create a choice set with duplicate cell text. Cell text must be unique. The choice set will not be set.");
+        return nil;
+    }
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLChoiceSet.m]: Move this into a new method

File: SmartDeviceLink/public/SDLChoiceSet.m [hunk 12]
```diff
@@ -69,16 +69,23 @@ - (instancetype)initWithTitle:(NSString *)title delegate:(id<SDLChoiceSetDelegat
         return nil;
     }
 
+    NSMutableSet<SDLChoiceCell *> *choicesSet = [NSMutableSet setWithCapacity:choices.count];
     NSMutableSet<NSString *> *uniqueVoiceCommands = [NSMutableSet set];
     NSUInteger allVoiceCommandsCount = 0;
     NSUInteger choiceCellWithVoiceCommandCount = 0;
     for (SDLChoiceCell *cell in choices) {
+        [choicesSet addObject:cell];
         if (cell.voiceCommands == nil) { continue; }
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLChoiceSet.m:78]:
```suggestion

        if (cell.voiceCommands == nil) { continue; }
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetSpec.m [hunk 13]
```diff
@@ -156,12 +156,12 @@ @interface SDLChoiceSet()
                 expect(testChoiceSet).to(beNil());
             });
 
-            it(@"should not return nil with equivalent cell text", ^{
+            it(@"should return nil when 2 or more cells are identical", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetSpec.m:159]: Also need to test voice commands here

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 14]
```diff
@@ -179,13 +179,34 @@ - (void)setMenuCells:(NSArray<SDLMenuCell *> *)menuCells {
     self.waitingOnHMIUpdate = NO;
 
     NSMutableSet<NSString *> *allMenuVoiceCommands = [NSMutableSet set];
+    NSMutableSet *cellCheckSet = [NSMutableSet set];
     NSUInteger voiceCommandCount = 0;
     for (SDLMenuCell *cell in cells) {
+        [cellCheckSet addObject:cell];
+        if (cell.subCells.count > 0) {
+            NSMutableSet *subCellsCheckSet = [NSMutableSet set];
+            for (SDLMenuCell *subCell in cell.subCells) {
```
[the remark this answers is not in the document]
Comment (FrankElias77) [reply SmartDeviceLink/private/SDLMenuManager.m:189]: I know that it could be done with recursion but only one layer of subCells is supported

[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/private/SDLMenuManager.m]: That's not true https://github.com/smartdevicelink/sdl_ios/pull/1732

File: SmartDeviceLink/public/SDLChoiceSet.m [hunk 15]
```diff
@@ -144,6 +123,47 @@ - (void)setHelpList:(nullable NSArray<SDLVRHelpItem *> *)helpList {
...
+    if (identicalCellsCheckSet.count < choices.count) {
+        SDLLogE(@"Attempted to create a choice set with duplicate cell text. Cell text must be unique. The choice set will not be set.");
+        return NO;
+    }
+
+    // All or none of the choices must have VR commands
+    if ((choiceCellWithVoiceCommandCount > 0 && choiceCellWithVoiceCommandCount < choices.count)) {
+        SDLLogE(@"If using voice recognition commands, all of the choice set cells must have unique VR commands. There are %lu cells with unique voice commands and %lu total cells. The choice set will not be set.", (unsigned long)choiceCellWithVoiceCommandCount, (unsigned long)choices.count);
+        return NO;
+    }
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLChoiceSet.m:157]:
```suggestion
```

This is unnecessary because `SDLPreloadChoicesOperation` L156 will add VR to cells if they need it.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m [hunk 16]
```diff
@@ -168,9 +175,63 @@ - (BOOL)sdl_shouldRPCsIncludeImages:(NSArray<SDLMenuCell *> *)cells;
...
+        context(@"duplicate titles version <= 7.1.0", ^{
+            beforeEach(^{
+                [SDLGlobals sharedGlobals].rpcVersion = [[SDLVersion alloc] initWithMajor:7 minor:0 patch:0];
+            });
+
+            it(@"should not fail with a duplicate title. version < 7.1.0", ^{
+                testManager.menuCells = @[textAndImageCell, textAndImageCell2];
+                expect(testManager.menuCells).toNot(beEmpty());
+                expect(testManager.menuCells.firstObject.uniqueTitle).to(equal("Test 2"));
+                expect(testManager.menuCells.lastObject.uniqueTitle).to(equal("Test 2 (2)"));
```
[the remark this answers is not in the document]
Comment (FrankElias77) [reply SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m:207]: It was agreed the first duplicate title should start with (2)

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 17]
```diff
@@ -160,41 +161,29 @@ - (void)setMenuConfiguration:(SDLMenuConfiguration *)menuConfiguration {
...
-    // Check for duplicate titles
-    if (titleCheckSet.count != menuCells.count) {
-        SDLLogE(@"Not all cell titles are unique. The menu will not be set.");
-        return;
-    }
-
-    // Check for duplicate voice recognition commands
-    if (allMenuVoiceCommands.count != voiceCommandCount) {
-        SDLLogE(@"Attempted to create a menu with duplicate voice commands. Voice commands must be unique. The menu will not be set.");
+    if (![self sdl_menuCellsAreUnique:cells]) {
```
[the remark this answers is not in the document]
Comment (FrankElias77) [reply SmartDeviceLink/private/SDLMenuManager.m:181]: Based on what i understood from this comment https://github.com/smartdevicelink/sdl_ios/pull/1886#discussion_r573828305, the unique names to cells and the checks where added in one function sdl_menuCellsAreUnique..

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 18]
```diff
@@ -530,6 +529,62 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
...
+    NSMutableSet *identicalCellsCheckSet = [NSMutableSet set];
+    for (SDLMenuCell *cell in cells) {
+        [identicalCellsCheckSet addObject:cell];
+        if (cell.subCells.count > 0 && ![self sdl_menuCellsAreUnique:cell.subCells]) {
+            return NO;
+        }
+
+        if (cell.voiceCommands == nil) { continue; }
+        [identicalVoiceCommandsCheckSet addObjectsFromArray:cell.voiceCommands];
+        voiceCommandCount += cell.voiceCommands.count;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:576]: This probably should be broken out. It's not a part of the check that the method name describes: `menuCellsAreUnique`, they can be unique and still have duplicate voice commands.

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 19]
```diff
@@ -530,6 +529,62 @@ - (BOOL)sdl_isDynamicMenuUpdateActive:(SDLDynamicMenuUpdatesMode)dynamicMenuUpda
...
+    }
+
+    // Check for duplicate cells
+    if (identicalCellsCheckSet.count != cells.count) {
+        SDLLogE(@"Not all cells are unique. The menu will not be set.");
+        return NO;
+    }
+
+    return YES;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:585]:
```suggestion
    return (identicalCellsCheckSet.count != cells.count)
```

The log already occurs in the calling method.

File: SmartDeviceLink/public/SDLChoiceSet.m [hunk 20]
```diff
@@ -67,30 +69,7 @@ - (instancetype)initWithTitle:(NSString *)title delegate:(id<SDLChoiceSetDelegat
...
-    if ((choiceCellWithVoiceCommandCount > 0 && choiceCellWithVoiceCommandCount < choices.count)) {
-        SDLLogE(@"If using voice recognition commands, all of the choice set cells must have unique VR commands. There are %lu cells with unique voice commands and %lu total cells. The choice set will not be set.", (unsigned long)choiceCellWithVoiceCommandCount, (unsigned long)choices.count);
-        return nil;
-    }
-    // All the VR commands must be unique
-    if (uniqueVoiceCommands.count < allVoiceCommandsCount) {
-        SDLLogE(@"If using voice recognition commands, all VR commands must be unique. There are %lu unique VR commands and %lu VR commands. The choice set will not be set.", (unsigned long)uniqueVoiceCommands.count, (unsigned long)allVoiceCommandsCount);
+    if (![self sdl_choiceCellsAreUnique:choices]) {
         return nil;
     }
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLChoiceSet.m:74]:
```suggestion
    if (![self sdl_choiceCellsAreUnique:choices]) { return nil; }
```

If statements that return in one line are placed into one line as general style for this project.

File: SmartDeviceLink/public/SDLChoiceSet.m [hunk 21]
```diff
@@ -144,6 +123,42 @@ - (void)setHelpList:(nullable NSArray<SDLVRHelpItem *> *)helpList {
...
 }
 
+#pragma mark - Helpers
+
+/**
+ Check for duplicate choices and voiceCommands
+
+ @param choices The choices you will be adding
+ @return Boolean that indicates whether choices are unique or not
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLChoiceSet.m:132]:
```suggestion
 @return Boolean that indicates whether choices and voice commands are unique or not
```

File: SmartDeviceLink/public/SDLMenuCell.h [hunk 22]
```diff
@@ -55,6 +55,11 @@ typedef void(^SDLMenuCellSelectionHandler)(SDLTriggerSource triggerSource);
  */
 @property (strong, nonatomic, readonly, nullable) SDLMenuLayout submenuLayout;
 
+/**
+ Primary text of the cell to be displayed on the module. Used to distinguish cells with the same `title` but other fields are different. This is autogenerated by the screen manager. This will not be used when connected to modules supporting RPC 7.1+.
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLMenuCell.h:59]:
```suggestion
 Primary text of the cell to be displayed on the module. Used to distinguish cells with the same `title` but other fields are different. This is autogenerated by the screen manager. This will not be used when connected to modules supporting RPC 7.1+ because duplicate titles are supported.
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]
I did not check unit tests or core tests due to the changes needed here.

File: SmartDeviceLink/public/SDLChoiceSet.m [hunk 23]
```diff
@@ -144,6 +121,40 @@ - (void)setHelpList:(nullable NSArray<SDLVRHelpItem *> *)helpList {
...
 
+#pragma mark - Helpers
+
+/**
+ Check for duplicate choices and voiceCommands
+
+ @param choices The choices you will be adding
+ @return Boolean that indicates whether choices and voice commands are unique or not
+ */
+-(BOOL)sdl_choiceCellsAreUnique:(NSArray<SDLChoiceCell *> *)choices {
```
Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLChoiceSet.m:132]: If the developer creates a set of `SDLChoiceCell` with duplicate `text` set and different `secondaryArtwork`s but the module does not support `secondaryArtwork`, then you end up with a bunch of rows with the exact same name:
Duplicate cell names

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
I found a couple of edge case issues.

File: SmartDeviceLink/public/SDLChoiceSet.m (hunk 23 above)
Comment (joeljfischer) [reply SmartDeviceLink/public/SDLChoiceSet.m:132]: After investigating this, this is also possible just by creating the same cell except for different VR commands. I think that we should just add a documentation warning that if uniquing features are not displayed on screen then the same information will be displayed across multiple cells. I added this to the initializers for `SDLChoiceSet`:

```
WARNING: If you display multiple cells with the same `text` with the only uniquing property between cells being different `vrCommands` or a feature that is not displayed on the head unit (e.g. if the head unit doesn't display `secondaryArtwork` and that's the only uniquing property between two cells) then the cells may appear to be the same to the user in `Manual` mode. This only applies to RPC connections >= 7.1.0.

WARNING: On < 7.1.0 connections, the `text` cell will be automatically modified among cells that have the same `text` when they are preloaded, so they will always appear differently on-screen when they are displayed. `cell.uniqueText` will be created by appending ` (2)`, ` (3)`, etc.
```

**Review by NicoleYarroch — APPROVED** [review]
