### PR TITLE
Fix for RPC spec generator to stop producing #pragmas that suppress deprecated warnings to property and enum definitions

### LINKED ISSUE #1757: RPC spec generator should not add #pragmas to suppress deprecation warnings to property and enum definitions
### Bug Report
The RPC spec generator should not wrap deprecated properties or enum with `#pragma`s to suppress `"-Wdeprecated-declarations` as it is not necessary. 

```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
// some property or enum definition
#pragma clang diagnostic pop
```

##### Reproduction Steps
1. Run the generator script in the "generator" folder of the library.

##### Expected Behavior
The generated file for `SDLCharacterSet` should should generate for `SDLCharacterSetType2`:
```
/**
 * @deprecated
 * @since SDL 7.0.0
 */
extern SDLCharacterSet const SDLCharacterSetType2 __deprecated_msg("");
```

##### Observed Behavior
It currently generates:
```
/**
 * @deprecated
 * @since SDL 7.0.0
 */
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
extern SDLCharacterSet const SDLCharacterSetType2 __deprecated_msg("");
#pragma clang diagnostic pop
```

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: 6.7
* Testing Against: N/A

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1757 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
removed #pragmas from RPC spec generator that suppress deprecation warnings to property and enum definitions

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* removed #pragmas from RPC spec generator that suppress deprecation warnings to property and enum definitions

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: generator/templates/base_struct_function.m.jinja2 [hunk 1]
```diff
@@ -34,31 +23,14 @@ NS_ASSUME_NONNULL_BEGIN
...
-{%- if deprecated or param.deprecated %}
-#pragma clang diagnostic pop
-{%- endif %}
     [self.{{parameters_store}} sdl_setObject:{{param.origin}} forName:SDLRPCParameterName{{param.method_suffix}}];
 }
-{% if deprecated or param.deprecated %}
-#pragma clang diagnostic push
-#pragma clang diagnostic ignored "-Wdeprecated-declarations"
-{%- endif %}
 - ({{'nullable ' if not param.mandatory}}{{param.type_generic}}{{param.type_sdl|trim}}){{param.origin}} {
```
Comment (NicoleYarroch) [inline generator/templates/base_struct_function.m.jinja2:33]:
```suggestion

- ({{'nullable ' if not param.mandatory}}{{param.type_generic}}{{param.type_sdl|trim}}){{param.origin}} {
```

Comment (NicoleYarroch) [reply generator/templates/base_struct_function.m.jinja2:33]: I added a newline between the setter and getter to keep line spacing consistent between each function consistent in the implementation file.

File: generator/templates/functions/template.m.jinja2 [hunk 2]
```diff
@@ -6,16 +6,13 @@
 #import "SDLRPCParameterNames.h"
 {%- endblock %}
 {% block constructors %}
-#pragma clang diagnostic push
-#pragma clang diagnostic ignored "-Wdeprecated-declarations"
```
Comment (NicoleYarroch) [inline generator/templates/functions/template.m.jinja2:10]: This #pragma push/pop needs to be here because `initWithName` was deprecated in this class's superclass, `SDLRPCMessage`.

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
Left some comments

**Review by NicoleYarroch — APPROVED** [review]
