### PR TITLE
Fix presenting a keyboard shows the test cell

### LINKED ISSUE #1050: Presenting the keyboard should not show a cell (6.1-develop)
### Bug Report
Currently, presenting a keyboard only interaction via the choice set manager shows the "Test Cell" cell. This is unnecessary.

##### Reproduction Steps
1. Use the choice set manager to present the keyboard

##### Expected Behavior
"Test Cell" isn't present

##### Observed Behavior
"Test Cell" is present

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: 6.1-develop (https://github.com/smartdevicelink/sdl_ios/commit/43efffc3e883d1beee890b9dc70cf948f448a767)
* Testing Against: Sync Gen 3 v.3.0

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1050 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Smoke tests

### Summary
Removes the test cell from being presented in a keyboard only interaction

### Changelog
This is an intra-release change, so no changelog is needed

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLPresentKeyboardOperation.m [hunk 1]
```diff
@@ -114,7 +114,7 @@ - (SDLPerformInteraction *)performInteraction {
     SDLPerformInteraction *performInteraction = [[SDLPerformInteraction alloc] init];
     performInteraction.initialText = self.initialText;
     performInteraction.interactionMode = SDLInteractionModeManualOnly;
-    performInteraction.interactionChoiceSetIDList = @[@0];
+    performInteraction.interactionChoiceSetIDList = @[];
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLPresentKeyboardOperation.m]: The test case is failing

Comment (joeljfischer) [reply SmartDeviceLink/SDLPresentKeyboardOperation.m]: Fixed
