### PR TITLE
Fix #382 Timers are not appropriately stopped when deallocated.

### LINKED ISSUE #382: Timers are not appropriately stopped when deallocated.
This is a more generic issue stemming from #341 
### Bug Report

Our custom timer class, `SDLTimer`, is currently not handling itself correctly when set to nil, without being cancelled beforehand. i.e. the `elapsedBlock` will continue to fire.
##### Reproduction Steps
1. Use a version of SDL that supports sending heartbeats (v4.0.2).
2. Connect application to Core
3. Disconnect app.
4. Look at logs. Will see printout for inability to send heartbeat.
##### Expected Behavior

Timers are correctly stopped.
##### Observed Behavior

Timers still fire.
##### OS & Version Information
- iOS Version: 9.1.2
- SDL iOS Version: v4.0.2
- Testing Against: iOS Simulator connected to Core via Relay.

### PR DESCRIPTION
**Pull request by cromotron**
Fixes #382

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
NSTimer has a strong reference to its target, therefore the SDLTimer never gets released and dealloc isn’t called.
I eliminated the deadlock by adding a separate target.

##### Enhancements
Timer is stopped when the reference to the SDLTimer is set to nil

##### Bug Fixes
Timers are not appropriately stopped when deallocated.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLTimer.m [hunk 1]
```diff
@@ -4,6 +4,36 @@
...
+    self = [super init];
+    if (self) {
+        _delegate = delegate;
+    }
+    return self;
+}
+
+- (void)timerElapsed {
+    if ([self.delegate conformsToProtocol:@protocol(SDLTimerTargetDelegate)]) {
+        [_delegate timerElapsed];
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLTimer.m]: The delegate never gets called because `SDLTimer` does not conformToProtocol `SDLTimerTargetDelegate`

File: SmartDeviceLink/SDLTimer.m [hunk 2]
```diff
@@ -4,6 +4,36 @@
...
+    }
+}
+
+@end
+
 
 @interface SDLTimer ()
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLTimer.m]: The `SDLTimer` needs to conform to the `SDLTimerTargetDelegate`
`@interface SDLTimer () <SDLTimerTargetDelegate>`

**Comment by NicoleYarroch** [comment]
The `elapsedBlock` never gets called with the changes made in this branch. I believe it is because the `SDLTimer` class does not conform to protocol `SDLTimerTargetDelegate`.
