### PR TITLE
Fix issues shown by OCMock 3.5

### LINKED ISSUE #1517: Latest version of OCMock causes tests to fail
### Bug Report
When updating to OCMock >= 3.5.0 using `carthage update` causes several tests to fail due to not using a mocked object. See [this line](https://github.com/erikdoe/ocmock/blob/master/Source/Changes.txt#L18) in the release notes.

##### Reproduction Steps
1. Update to the latest version of test frameworks by using `carthage update`.
2. Run the unit tests.

##### Expected Behavior
No unit test failures

##### Observed Behavior
Multiple unit test failures

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: n/a
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1517 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit tests were fixed in places that a mocked object was never used.

#### Core Tests
n/a, only relates to unit test code

Core version / branch / commit hash / module tested against: n/a
HMI name / version / branch / commit hash / module tested against: n/a

### Summary
This PR fixes issues related to OCMock 3.5 and updates testing dependencies.

##### Bug Fixes
* Updated testing dependencies and fixing test issues related to OCMock 3.5 which causes test failures if a mocked object isn't used.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLinkTests/ProxySpecs/SDLHapticManagerSpec.m [hunk 1]
```diff
@@ -44,14 +44,14 @@ @interface SDLFocusableItemLocator ()
 
 QuickSpecBegin(SDLHapticManagerSpec)
 
-describe(@"the haptic manager", ^{
+fdescribe(@"the haptic manager", ^{
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/ProxySpecs/SDLHapticManagerSpec.m]: Remove the focus here

Comment (joeljfischer) [reply SmartDeviceLinkTests/ProxySpecs/SDLHapticManagerSpec.m]: Fixed
