### PR TITLE
Fix PreloadChoicesOperation uploading images when WindowCapability properties are nil

### LINKED ISSUE #1618: ChoiceSetManager PreloadOperation uploads images with windowCapability `nil`
### Bug Report
We should always upload choice images if `windowCapabilities.imageFields` is `nil` to account for the case where `DisplayCapabilities` comes back `nil`. This will allow the head unit to do what it wants with the info in that case.

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1618

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit tests were run but not updated

#### Core Tests
This was tested against Core for basic choice set functionality.

Core version / branch / commit hash / module tested against: Ford Sync 3.4 19353_DEVTEST
HMI name / version / branch / commit hash / module tested against: Ford Sync 3.4 19353_DEVTEST

### Summary
This updates the check for uploading choice images during a choice set operation to check for the window capability like it does elsewhere in the operation.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLPreloadChoicesOperation.m [hunk 1]
```diff
@@ -87,12 +87,10 @@ - (void)sdl_preloadCellArtworksWithCompletionHandler:(void(^)(NSError *_Nullable
 
     NSMutableArray<SDLArtwork *> *artworksToUpload = [NSMutableArray arrayWithCapacity:self.cellsToUpload.count];
     for (SDLChoiceCell *cell in self.cellsToUpload) {
-        if ([self.windowCapability hasImageFieldOfName:SDLImageFieldNameChoiceImage]
-            && [self sdl_artworkNeedsUpload:cell.artwork]) {
+        if ([self sdl_shouldSendChoicePrimaryImage] && [self sdl_artworkNeedsUpload:cell.artwork]) {
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLPreloadChoicesOperation.m:90]: `sdl_shouldSendChoicePrimaryImage` and `sdl_shouldSendChoiceSecondaryImage` default to `YES` if `windowCapability` is `nil` so the images still get uploaded/displayed.

Comment (joeljfischer) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m:90]: `windowCapability` cannot be `nil`

Comment (NicoleYarroch) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m:90]: I guess I am confused because the title for this PR is "Fix PreloadChoicesOperation uploading images when WindowCapability is nil"

Comment (joeljfischer) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m:90]: Fixed the title

Comment (NicoleYarroch) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m:90]: Just so we are on the same page, if `windowCapability.imageFields` is `nil`, you do not want to upload the choice set images, right? Because right now they are still uploaded if `windowCapability.imageFields` is `nil`.

Comment (joeljfischer) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m:90]: The intention is that if it’s nil, it is uploaded. The main PR for this conversation was a few weeks ago on #1575

Comment (NicoleYarroch) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m:90]: Ok. Can you add documentation to the methods because the description on the issue and on this PR make it sound that you don't want to upload images when the properties are `nil`.
