### PR TITLE
Align with Java Suite Permission Manager Parameter Permissions

### LINKED ISSUE #1682: Update Permission Manager to allow tracking parameter permissions
### Bug Report
To align with the java_suite, we should add a new method to the `SDLPermissionManager` class that tracks the permissions of parameters from a passed in RPC. 

##### Test Case, Sample Code, and / or Example App
[java_suite implementation of method](https://github.com/smartdevicelink/sdl_java_suite/blob/9946777469c0f58a9732cab42669c56850edb761/base/src/main/java/com/smartdevicelink/managers/permission/BasePermissionManager.java#L284)

### PR DESCRIPTION
**Pull request by lapinskijw**
Fixes #1682 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Updated unit tests for the `SDLPermissionFilterSpec` and `SDLPermissionElementSpec.m`. Added new spec files for the new `SDLPermissionElement` and `SDLRPCPermissionStatus` objects.

#### Core Tests
Ran example apps with TDK. Verified that correct parameter was allowed testing on Core and updating the policy table to allow/disallow RPC permission parameter. Verified correct values were coming back using Manticore for the updated methods.

Core version / branch / commit hash / module tested against: Core 6.1.0 Release
HMI name / version / branch / commit hash / module tested against: SYNC 3.0 Build 17276_DEVTEST, Manticore v2.6.0

### Summary
This PR aligns the behavior seen in the Java suite permission manager with iOS. Two new classes were made to align behavior: `SDLPermissionElement` and `SDLRPCPermissionStatus`. iOS users can now track parameter permissions using the new `isPermissionParameterAllowed:parameter` method.

##### Enhancements
Added new objects and methods that allow iOS to track parameter permissions.

### Tasks Remaining:
- [x] Implement `isPermissionParameterAllowed:parameter` internally.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLPermissionManager.m [hunk 1]
```diff
@@ -287,6 +313,39 @@ - (void)sdl_hmiLevelDidChange:(SDLRPCNotificationNotification *)notification {
...
+ *  @return An array of permission elements.
+ */
+- (NSArray<SDLPermissionElement *> *)sdl_createPermissionElementFromRPCNames:(NSArray<NSString *> *)rpcNames {
+    NSMutableArray *permissionElements = [[NSMutableArray alloc] init];
+    for (NSString *rpcName in rpcNames) {
+        SDLPermissionElement *permissionElement = [[SDLPermissionElement alloc] initWithRPCName:rpcName parameterPermissions:nil];
+        [permissionElements addObject:permissionElement];
+    }
+
+    return permissionElements;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPermissionManager.m:346]:
```suggestion
    return [permissionElements copy];
```

If you don't copy this you sneakily have a mutable array and bad stuff could occur.

File: SmartDeviceLink/SDLPermissionManager.m [hunk 2]
```diff
@@ -405,6 +464,22 @@ - (BOOL)rpcNameRequiresEncryption:(SDLRPCFunctionName)rpcName {
     return NO;
 }
 
+- (BOOL)isPermissionParameterAllowed:(SDLRPCFunctionName)rpcName parameter:(NSString *)parameter {
+    return [self isPermissionParameterAllowed:rpcName parameter:parameter permissionItems:self.permissions hmiLevel:self.currentHMILevel];
+}
+
+- (BOOL)isPermissionParameterAllowed:(SDLRPCFunctionName)rpcName parameter:(NSString *)parameter permissionItems:(NSMutableDictionary<SDLPermissionRPCName, SDLPermissionItem *> *)permissionItems hmiLevel:(SDLHMILevel)hmiLevel {
+
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPermissionManager.m:472]:
```suggestion
```

File: SmartDeviceLink/SDLPermissionManager.m [hunk 3]
```diff
@@ -405,6 +464,22 @@ - (BOOL)rpcNameRequiresEncryption:(SDLRPCFunctionName)rpcName {
     return NO;
 }
 
+- (BOOL)isPermissionParameterAllowed:(SDLRPCFunctionName)rpcName parameter:(NSString *)parameter {
+    return [self isPermissionParameterAllowed:rpcName parameter:parameter permissionItems:self.permissions hmiLevel:self.currentHMILevel];
+}
+
+- (BOOL)isPermissionParameterAllowed:(SDLRPCFunctionName)rpcName parameter:(NSString *)parameter permissionItems:(NSMutableDictionary<SDLPermissionRPCName, SDLPermissionItem *> *)permissionItems hmiLevel:(SDLHMILevel)hmiLevel {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPermissionManager.m:471]: This isn't called anywhere except the above method, so is it necessary?

File: SmartDeviceLink/SDLRPCPermissionStatus.m [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+//
+//  Created by James Lapinski on 6/29/20.
+//  Copyright © 2020 smartdevicelink. All rights reserved.
+//
+
+#import "SDLRPCPermissionStatus.h"
+
+@implementation SDLRPCPermissionStatus
+
+- (instancetype)initWithRPCName:(SDLRPCFunctionName)rpcName isRPCAllowed:(BOOL)isRPCAllowed rpcParameters:(nullable NSMutableDictionary<NSString *,NSNumber *> *)rpcParameters {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLRPCPermissionStatus.m:13]: Missing creation of self

File: SmartDeviceLinkTests/DevAPISpecs/SDLPermissionFilterSpec.m [hunk 5]
```diff
@@ -2,148 +2,228 @@
...
-        
+
         it(@"should copy the identifier correctly", ^{
             expect(testCopiedFilter.identifier).to(equal(testFilter.identifier));
         });
-        
+
         it(@"should copy the filter array correctly", ^{
-            expect(testCopiedFilter.rpcNames).to(equal(testFilter.rpcNames));
+            expect(testCopiedFilter.permissionElements).to(equal(testFilter.permissionElements));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPermissionFilterSpec.m:203]: I think this should fail if done correctly if you copy because it's checking references, which should be different. That means that this test is written incorrectly and succeeds incorrectly? The previous version would succeed because the strings were the same? I'm not sure.

File: SmartDeviceLinkTests/SDLPermissionElementSpec.m [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+            testPermissionElement = [[SDLPermissionElement alloc] initWithRPCName:testRPCName1 parameterPermissions:parameterPermissions];
+        });
+
+        it(@"should set the rpcName correctly", ^{
+            expect(testPermissionElement.rpcName).to(equal(testRPCName1));
+        });
+
+        it(@"should set the parameterPermissions correctly", ^{
+            expect(testPermissionElement.parameterPermissions).to(equal(parameterPermissions));
+        });
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/SDLPermissionElementSpec.m:41]: Combine into one `it`

File: SmartDeviceLinkTests/SDLPermissionElementSpec.m [hunk 7]
```diff
@@ -0,0 +1,68 @@
...
+            expect(testPermissionElementCopy).toNot(beIdenticalTo(testPermissionElement));
+        });
+
+        it(@"should copy the rpc name correctly", ^{
+            expect(testPermissionElementCopy.rpcName).to(equal(testPermissionElement.rpcName));
+        });
+
+        it(@"should copy the parameter permissions correctly", ^{
+            expect(testPermissionElementCopy.parameterPermissions).to(equal(testPermissionElement.parameterPermissions));
+        });
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/SDLPermissionElementSpec.m:63]: Combine into one test

File: SmartDeviceLinkTests/SDLRPCPermissionStatusSpec.m [hunk 8]
```diff
@@ -0,0 +1,49 @@
...
+describe(@"A rpc permission status", ^{
+    __block NSString *testRPCName = nil;
+    __block NSString *testParameterName = nil;
+    __block BOOL isRPCAllowed = NO;
+    __block NSMutableDictionary<NSString *,NSNumber *> *allowedParameters = nil;
+
+    beforeEach(^{
+        testRPCName = @"testRPCName";
+        testParameterName = @"testParameterRPCName";
+        allowedParameters = [@{testParameterName:@0} mutableCopy];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/SDLRPCPermissionStatusSpec.m:25]:
```suggestion
        allowedParameters = [@{ testParameterName: @0 } mutableCopy];
```

File: SmartDeviceLinkTests/SDLRPCPermissionStatusSpec.m [hunk 9]
```diff
@@ -0,0 +1,49 @@
...
+            expect(testSDLRPCPermissionStatusSpec.rpcName).to(equal(testRPCName));
+        });
+
+        it(@"should set isRPCAllowed correctly", ^{
+            expect(testSDLRPCPermissionStatusSpec.isRPCAllowed).to(equal(isRPCAllowed));
+        });
+
+        it(@"should set the parameter permissions correctly", ^{
+            expect(testSDLRPCPermissionStatusSpec.rpcParameters[testParameterName]).to(equal(@NO));
+        });
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/SDLRPCPermissionStatusSpec.m:45]: Combine into one test

File: SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m [hunk 10]
```diff
@@ -42,85 +50,110 @@ @interface SDLPermissionManager ()
...
         limitedHMINotification = [[SDLRPCNotificationNotification alloc] initWithName:SDLDidChangeHMIStatusNotification object:nil rpcNotification:testLimitedHMIStatus];
         backgroundHMINotification = [[SDLRPCNotificationNotification alloc] initWithName:SDLDidChangeHMIStatusNotification object:nil rpcNotification:testBackgroundHMIStatus];
         noneHMINotification = [[SDLRPCNotificationNotification alloc] initWithName:SDLDidChangeHMIStatusNotification object:nil rpcNotification:testNoneHMIStatus];
+
+        // Permission Elements
+        testPermissionElementAllAllowed = [[SDLPermissionElement alloc] initWithRPCName:testRPCNameAllAllowed parameterPermissions:@[testRPCParameterNameAllAllowed]];
+        testPermissionElementFullLimitedAllowed = [[SDLPermissionElement alloc] initWithRPCName:testRPCNameFullLimitedAllowed parameterPermissions:@[testRPCParameterNameFullLimitedAllowed]];
+        testPermissionElementDisallowed = [[SDLPermissionElement alloc] initWithRPCName:testRPCNameAllDisallowed    parameterPermissions:@[testRPCParameterNameAllDisallowed]];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m:156]:
```suggestion
        testPermissionElementDisallowed = [[SDLPermissionElement alloc] initWithRPCName:testRPCNameAllDisallowed parameterPermissions:@[testRPCParameterNameAllDisallowed]];
```

File: Example Apps/Example ObjC/RPCPermissionsManager.m [hunk 11]
```diff
@@ -24,11 +24,16 @@ + (void)setupPermissionsCallbacksWithManager:(SDLManager *)manager {
     [self sdlex_checkCurrentPermissionWithManager:manager rpcName:showRPCName];
 
     // Checks if all the RPCs need to create menus are allowed right at this moment
-    NSArray<SDLRPCFunctionName> *menuRPCNames = @[SDLRPCFunctionNameAddCommand, SDLRPCFunctionNameCreateInteractionChoiceSet, SDLRPCFunctionNamePerformInteraction];
+    SDLPermissionElement *addCommandPermissionElement = [[SDLPermissionElement alloc] initWithRPCName:SDLRPCFunctionNameAddCommand parameterPermissions:nil];
+    SDLPermissionElement *createInteractionPermissionElement = [[SDLPermissionElement alloc] initWithRPCName:SDLRPCFunctionNameCreateInteractionChoiceSet parameterPermissions:nil];
+    SDLPermissionElement *performInteractionPermissionElement = [[SDLPermissionElement alloc] initWithRPCName:SDLRPCFunctionNamePerformInteraction parameterPermissions:nil];
+    NSArray<SDLPermissionElement *> *menuRPCNames = @[addCommandPermissionElement, createInteractionPermissionElement, performInteractionPermissionElement];
```
Comment (joeljfischer) [inline Example Apps/Example ObjC/RPCPermissionsManager.m:30]:
```suggestion
    NSArray<SDLPermissionElement *> *menuRPCPermissions = @[addCommandPermissionElement, createInteractionPermissionElement, performInteractionPermissionElement];
```

File: Example Apps/Example ObjC/RPCPermissionsManager.m [hunk 12]
```diff
@@ -24,11 +24,16 @@ + (void)setupPermissionsCallbacksWithManager:(SDLManager *)manager {
...
     [self sdlex_checkCurrentGroupPermissionsWithManager:manager rpcNames:menuRPCNames];
 
     // Set up an observer for permissions changes to media template releated RPCs. Since the `groupType` is set to all allowed, this block is called when the group permissions changes from all allowed. This block is called immediately when created.
-    NSArray<SDLRPCFunctionName> *mediaTemplateRPCs = @[SDLRPCFunctionNameSetMediaClockTimer, SDLRPCFunctionNameSubscribeButton];
+    SDLPermissionElement *setMediaClockPermissionElement = [[SDLPermissionElement alloc] initWithRPCName:SDLRPCFunctionNameSetMediaClockTimer parameterPermissions:nil];
+    SDLPermissionElement *subscribeButtonPermissionElement = [[SDLPermissionElement alloc] initWithRPCName:SDLRPCFunctionNameSubscribeButton parameterPermissions:nil];
+    NSArray<SDLPermissionElement *> *mediaTemplateRPCs = @[setMediaClockPermissionElement, subscribeButtonPermissionElement];
```
Comment (joeljfischer) [inline Example Apps/Example ObjC/RPCPermissionsManager.m:36]:
```suggestion
    NSArray<SDLPermissionElement *> *mediaTemplateRPCPermissions = @[setMediaClockPermissionElement, subscribeButtonPermissionElement];
```

File: Example Apps/Example Swift/RPCPermissionsManager.swift [hunk 13]
```diff
@@ -20,11 +20,16 @@ class RPCPermissionsManager {
         _ = checkCurrentPermission(with: manager, rpcName: showRPCName)
 
         // Checks if all the RPCs need to create menus are allowed right at this moment
-        let menuRPCNames = [SDLRPCFunctionName.addCommand, SDLRPCFunctionName.createInteractionChoiceSet, SDLRPCFunctionName.performInteraction]
+        let addCommandPermissionElement = SDLPermissionElement(rpcName: SDLRPCFunctionName.addCommand, parameterPermissions: nil)
+        let createInteractionPermissionElement = SDLPermissionElement(rpcName: SDLRPCFunctionName.createInteractionChoiceSet, parameterPermissions: nil)
+        let performInteractionPermissionElement = SDLPermissionElement(rpcName: SDLRPCFunctionName.performInteraction, parameterPermissions: nil)
+        let menuRPCNames = [addCommandPermissionElement, createInteractionPermissionElement, performInteractionPermissionElement]
```
Comment (joeljfischer) [inline Example Apps/Example Swift/RPCPermissionsManager.swift:26]:
```suggestion
        let menuRPCPermissions = [addCommandPermissionElement, createInteractionPermissionElement, performInteractionPermissionElement]
```

File: Example Apps/Example Swift/RPCPermissionsManager.swift [hunk 14]
```diff
@@ -20,11 +20,16 @@ class RPCPermissionsManager {
...
         _ = checkCurrentGroupPermissions(with: manager, rpcNames: menuRPCNames)
 
         // Set up an observer for permissions changes to media template releated RPCs. Since the `groupType` is set to all allowed, this block is called when the group permissions changes from all allowed. This block is called immediately when created.
-        let mediaTemplateRPCs = [SDLRPCFunctionName.setMediaClockTimer, SDLRPCFunctionName.subscribeButton]
+        let setMediaClockPermissionElement = SDLPermissionElement(rpcName: SDLRPCFunctionName.setMediaClockTimer, parameterPermissions: nil)
+        let subscribeButtonPermissionElement = SDLPermissionElement(rpcName: SDLRPCFunctionName.subscribeButton, parameterPermissions: nil)
+        let mediaTemplateRPCs = [setMediaClockPermissionElement, subscribeButtonPermissionElement]
```
Comment (joeljfischer) [inline Example Apps/Example Swift/RPCPermissionsManager.swift:32]:
```suggestion
        let mediaTemplatePermissions = [setMediaClockPermissionElement, subscribeButtonPermissionElement]
```

File: SmartDeviceLink/SDLRPCPermissionStatus.m [hunk 15]
```diff
@@ -11,6 +11,9 @@
 @implementation SDLRPCPermissionStatus
 
 - (instancetype)initWithRPCName:(SDLRPCFunctionName)rpcName isRPCAllowed:(BOOL)isRPCAllowed rpcParameters:(nullable NSMutableDictionary<NSString *,NSNumber *> *)rpcParameters {
+    self = [super init];
+    if (!self) { return nil; }
+    
     _rpcName = rpcName;
     _rpcAllowed = isRPCAllowed;
     _rpcParameters = rpcParameters;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLRPCPermissionStatus.m:19]: This class should have a `description` method

File: SmartDeviceLink/SDLPermissionManager.m [hunk 16]
```diff
@@ -88,10 +92,10 @@ - (SDLPermissionGroupStatus)groupStatusOfRPCPermissions:(NSArray<SDLPermissionEl
         return SDLPermissionGroupStatusUnknown;
     }
 
-    return [self sdl_groupStatusOfRPCPermissions:rpcNames withPermissions:[self.permissions copy] hmiLevel:self.currentHMILevel];
+    return [self.class sdl_groupStatusOfRPCPermissions:rpcNames withPermissions:[self.permissions copy] hmiLevel:self.currentHMILevel];
 }
 
-- (SDLPermissionGroupStatus)sdl_groupStatusOfRPCPermissions:(NSArray<SDLPermissionElement *> *)rpcNames withPermissions:(NSDictionary<SDLPermissionRPCName, SDLPermissionItem *> *)permissions hmiLevel:(SDLHMILevel)hmiLevel {
++ (SDLPermissionGroupStatus)sdl_groupStatusOfRPCPermissions:(NSArray<SDLPermissionElement *> *)rpcNames withPermissions:(NSMutableDictionary<SDLPermissionRPCName, SDLPermissionItem *> *)permissions hmiLevel:(SDLHMILevel)hmiLevel {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPermissionManager.m:98]:
```suggestion
+ (SDLPermissionGroupStatus)sdl_groupStatusOfRPCPermissions:(NSArray<SDLPermissionElement *> *)rpcNames withPermissions:(NSDictionary<SDLPermissionRPCName, SDLPermissionItem *> *)permissions hmiLevel:(SDLHMILevel)hmiLevel {
```

File: SmartDeviceLink/SDLPermissionManager.m [hunk 17]
```diff
@@ -471,9 +473,13 @@ - (BOOL)rpcNameRequiresEncryption:(SDLRPCFunctionName)rpcName {
     return NO;
 }
 
-- (BOOL)isPermissionParameterAllowed:(SDLRPCFunctionName)rpcName parameter:(NSString *)parameter permissionItems:(NSMutableDictionary<SDLPermissionRPCName, SDLPermissionItem *> *)permissionItems hmiLevel:(SDLHMILevel)hmiLevel {
+- (BOOL)isPermissionParameterAllowed:(SDLRPCFunctionName)rpcName parameter:(NSString *)parameter {
+    return [self.class sdl_isPermissionParameterAllowed:rpcName parameter:parameter permissionItems:self.permissions hmiLevel:self.currentHMILevel];
+}
+
++ (BOOL)sdl_isPermissionParameterAllowed:(SDLRPCFunctionName)rpcName parameter:(NSString *)parameter permissionItems:(NSMutableDictionary<SDLPermissionRPCName, SDLPermissionItem *> *)permissionItems hmiLevel:(SDLHMILevel)hmiLevel {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPermissionManager.m:480]:
```suggestion
+ (BOOL)sdl_isPermissionParameterAllowed:(SDLRPCFunctionName)rpcName parameter:(NSString *)parameter permissionItems:(NSDictionary<SDLPermissionRPCName, SDLPermissionItem *> *)permissionItems hmiLevel:(SDLHMILevel)hmiLevel {
```

File: SmartDeviceLink/SDLRPCPermissionStatus.m [hunk 18]
```diff
@@ -21,4 +21,10 @@ - (instancetype)initWithRPCName:(SDLRPCFunctionName)rpcName isRPCAllowed:(BOOL)i
     return self;
 }
 
+#pragma mark - Description
+
+- (NSString *)description {
+    return [NSString stringWithFormat:@"RPC name: %@, allowed: %@, RPC parameters %@", self.rpcName, (self.isRPCAllowed ? @"YES" : @"NO"), self.rpcParameters];
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLRPCPermissionStatus.m:27]:
```suggestion
    return [NSString stringWithFormat:@"RPC Permission Status, RPC name: %@, allowed: %@, RPC parameters %@", self.rpcName, (self.isRPCAllowed ? @"YES" : @"NO"), self.rpcParameters];
```

File: SmartDeviceLink-iOS.xcodeproj/project.pbxproj [hunk 19]
```diff
@@ -38,11 +38,18 @@
 		00E22CED22C2F1B300BC6B08 /* SDLEncryptionConfiguration.h in Headers */ = {isa = PBXBuildFile; fileRef = 00E22CEB22C2F1B300BC6B08 /* SDLEncryptionConfiguration.h */; settings = {ATTRIBUTES = (Public, ); }; };
 		00EADD3322DFE54B0088B608 /* SDLEncryptionLifecycleManagerSpec.m in Sources */ = {isa = PBXBuildFile; fileRef = 00EADD3222DFE54B0088B608 /* SDLEncryptionLifecycleManagerSpec.m */; };
 		00EADD3522DFE5670088B608 /* SDLEncryptionConfigurationSpec.m in Sources */ = {isa = PBXBuildFile; fileRef = 00EADD3422DFE5670088B608 /* SDLEncryptionConfigurationSpec.m */; };
+		106187B924AA75540045C4EC /* SDLRPCPermissionStatusSpec.m in Sources */ = {isa = PBXBuildFile; fileRef = 106187B824AA75540045C4EC /* SDLRPCPermissionStatusSpec.m */; };
+		106187BA24AA76550045C4EC /* SDLRPCPermissionStatus.h in Headers */ = {isa = PBXBuildFile; fileRef = 106982A824AA3B4700B1F649 /* SDLRPCPermissionStatus.h */; settings = {ATTRIBUTES = (Public, ); }; };
+		106412C6249FB80B0069A97A /* SDLPermissionElement.h in Headers */ = {isa = PBXBuildFile; fileRef = 106412C4249FB80B0069A97A /* SDLPermissionElement.h */; settings = {ATTRIBUTES = (Public, ); }; };
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink-iOS.xcodeproj/project.pbxproj:43]: `SDLRPCParameterNames` is not going to be public
