### PR TITLE
Fixed incorrect VR capability in the system capability manager

### LINKED ISSUE #950: SDLSystemCapabilityManager does not set the vrCapability correctly
### Bug Report
The `SystemCapabilityManager` does not set the `vrCapability` correctly because an enum comparison using `==` always fails.

The code should be:
```
self.vrCapability = (response.vrCapabilities.count > 0 && [response.vrCapabilities.firstObject isEqualToEnum:SDLVRCapabilitiesText]) ? YES : NO;
```
##### Reproduction Steps
1. Connect app to a head unit
1. Check the `vrCapability` via the `SystemCapabilityManager` once connected.

##### Expected Behavior
If the head unit supports VR, `vrCapability` should be `YES`.

##### Observed Behavior
If the head unit supports VR, `vrCapability` is `NO`.

##### OS & Version Information
* iOS Version: [What version of iOS are you using when the bug occurred]
* SDL iOS Version: [What version of the library has this bug been seen on]
* Testing Against: [What you tested with to observe this behavior]

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #950 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Test already written

### Summary
* The `vrCapability` is now set correctly in the `SystemCapabilityManager`.

##### Enhancements
* The `SystemCapabilityManager` did not set the `vrCapability` correctly because the enum comparison using `==` always failed.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLSystemCapabilityManager.m [hunk 1]
```diff
@@ -101,7 +101,7 @@ - (void)sdl_registerResponse:(SDLRPCResponseNotification *)notification {
     self.hmiZoneCapabilities = response.hmiZoneCapabilities;
     self.speechCapabilities = response.speechCapabilities;
     self.prerecordedSpeechCapabilities = response.prerecordedSpeech;
-    self.vrCapability = (response.vrCapabilities.count > 0 && response.vrCapabilities.firstObject == SDLVRCapabilitiesText) ? YES : NO;
+    self.vrCapability = (response.vrCapabilities.count > 0 && [response.vrCapabilities.firstObject isEqualToEnum: SDLVRCapabilitiesText]) ? YES : NO;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSystemCapabilityManager.m]: Is there an extra space here?
