### PR TITLE
Fix SDLPredefinedLayoutNonMedia not found in templatesAvailable

### LINKED ISSUE #1996: Race condition occur in NSMutableDictionary (store)
### Bug Report
Race condition found in `NSMutableDictionary+Store` when one thread sets a value to the dictionary and the other thread is reading. This race only occurred with TCP connection not on SYNC.

The first thread started in func `- (void)stream:(NSStream *)aStream handleEvent:(NSStreamEvent)eventCode` of `SDLTCPTransport` and another Read-only thread started when `handler` gets called in `- (void)sdl_runHandlersForResponse:(SDLRPCResponseNotification *)notification` func of `SDLResponseDispatcher` and the request is `SDLRegisterAppInterface *regRequest = [[SDLRegisterAppInterface alloc] initWithLifecycleConfiguration:self.configuration.lifecycleConfig];` sent in `didEnterStateConnected` func of `SDLLifeCycleManager`

##### Reproduction Steps
1. Connect app
2. Launch app on the hmi

##### OS & Version Information
* iOS Version: Xcode 12.5 simulator
* SDL iOS Version: Branch develop
* Testing Against: Manticore

### LINKED ISSUE #1999: SDLPredefinedLayoutNonMedia not found in templatesAvailable
### Bug Report
Connecting to Sync and checking the `templatesAvailable` property won't match what we have for NON_MEDIA because SDL returns NON-MEDIA (the internal name). We need to change to use the internal name so that equality checks work (see MobileWeather).

##### Reproduction Steps
1. Launch app
2. ChangeLayout to nonMedia with SDLPredefinedLayoutNonMedia

##### Expected Behavior
`SDLPredefinedLayoutNonMedia` is found in `templatesAvailable`

##### Observed Behavior
`SDLPredefinedLayoutNonMedia` is not found in `templatesAvailable`

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1999

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit test added in SDLSystemCapabilityManagerSpec to check if "NON-MEDIA" is added

#### Core Tests
On Manticore the returned templatesAvailable includes "NON-MEDIA" which does not present the bug

Core version / branch / commit hash / module tested against: 7.1.1 develop
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Added "NON-MEDIA" to `templatesAvailable` In a case where sync's response for templatesAvailable had "NON_MEDIA" instead

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Added "NON-MEDIA" to `templatesAvailable` In a case where sync's response for templatesAvailable had "NON_MEDIA" instead

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by joeljfischer** [comment]
@FrankElias77 This PR has merge conflicts, please fix them before review

File: SmartDeviceLink/public/SDLSystemCapabilityManager.m [hunk 1]
```diff
@@ -201,7 +201,13 @@ - (nullable SDLWindowCapability *)defaultMainWindowCapability {
     }
 
     // Copy all available display capability properties
-    defaultWindowCapability.templatesAvailable = [self.displayCapabilities.templatesAvailable copy];
+    NSArray *templatesArray = [self.displayCapabilities.templatesAvailable copy];
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLSystemCapabilityManager.m:204]:
```suggestion
    NSArray<NSString *> *templatesArray = [self.displayCapabilities.templatesAvailable copy];
```

File: SmartDeviceLink/public/SDLSystemCapabilityManager.m [hunk 2]
```diff
@@ -201,7 +201,13 @@ - (nullable SDLWindowCapability *)defaultMainWindowCapability {
...
+    if ([templatesArray containsObject:@"NON_MEDIA"]) {
+        NSMutableArray *templatesMutableArray = [templatesArray mutableCopy];
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLSystemCapabilityManager.m:206]:
```suggestion
        NSMutableArray<NSString *> *templatesMutableArray = [templatesArray mutableCopy];
```

File: SmartDeviceLink/public/SDLSystemCapabilityManager.m [hunk 3]
```diff
@@ -201,7 +201,13 @@ - (nullable SDLWindowCapability *)defaultMainWindowCapability {
...
+        [templatesMutableArray addObject:@"NON-MEDIA"];
+        templatesArray = [NSArray arrayWithArray:templatesMutableArray];
+    }
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLSystemCapabilityManager.m:209]: Use `indexOfObject:` instead to get an index that `NON_MEDIA` is at (if it's in there), then use `replaceObjectAtIndex:withObject:` to replace `NON-MEDIA` instead of merely adding it.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/public/SDLSystemCapabilityManager.m [hunk 4]
```diff
@@ -200,8 +200,17 @@ - (nullable SDLWindowCapability *)defaultMainWindowCapability {
         return @[displayCapability];
     }
 
+    // HAX: Issue #1999, Ford Sync bug returning incorrect template name for "NON-MEDIA" (https://github.com/smartdevicelink/sdl_ios/issues/1999).
+    NSArray<NSString *> *templatesArray = [self.displayCapabilities.templatesAvailable copy];
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLSystemCapabilityManager.m:204]:
```suggestion
    NSMutableArray<NSString *> *mutableTemplatesAvailable = [self.displayCapabilities.templatesAvailable copy];
```

File: SmartDeviceLink/public/SDLSystemCapabilityManager.m [hunk 5]
```diff
@@ -200,8 +200,17 @@ - (nullable SDLWindowCapability *)defaultMainWindowCapability {
...
+    for (NSUInteger i = 0; i < templatesArray.count; i++) {
+        if ([templatesArray[i] isEqual:@"NON_MEDIA"]) {
+            NSMutableArray<NSString *> *templatesMutableArray = [templatesArray mutableCopy];
+            templatesMutableArray[i] = @"NON-MEDIA";
+            templatesArray = [NSArray arrayWithArray:templatesMutableArray];
+        }
+    }
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLSystemCapabilityManager.m:211]:
```suggestion
    for (NSUInteger i = 0; i < mutableTemplatesAvailable.count; i++) {
        if ([mutableTemplatesAvailable[i] isEqualToString:@"NON_MEDIA"]) {
            mutableTemplatesAvailable[i] = @"NON-MEDIA";
            break;
        }
    }
```

File: SmartDeviceLink/public/SDLSystemCapabilityManager.m [hunk 6]
```diff
@@ -200,8 +200,17 @@ - (nullable SDLWindowCapability *)defaultMainWindowCapability {
...
     // Copy all available display capability properties
-    defaultWindowCapability.templatesAvailable = [self.displayCapabilities.templatesAvailable copy];
+    defaultWindowCapability.templatesAvailable = templatesArray;
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLSystemCapabilityManager.m:213]:
```suggestion
    defaultWindowCapability.templatesAvailable = [mutableTemplatesAvailable copy];
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — CHANGES_REQUESTED** [review]
