### PR TITLE
Bugfix/issue 1667 permission manager method alignment

### LINKED ISSUE #1667: Add new method to Permission Manager in order to align with java_suite
### Bug Report
The `SDLPermissionManager` currently triggers the observer callback in the `addObserverForRPCs:groupType:withHandler:` method immediately after adding the observer. This functionality is not aligned with the java_suite observer method, which does not call the observer immediately after adding it.

In order to potentially avoid any breaking changes, we should add a new method to the `SDLPermissionManager` to align with the java_suite. This new method will only notify the observer when all of the RPCs are allowed if the `groupType` parameter is set to `allAllowed` (i.e. it will not notify the observer immediately upon subscription unless the all the RPCs are allowed).

### PR DESCRIPTION
**Pull request by lapinskijw**
Fixes #1667 and #1661 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Added unit tests for new methods that take a `SDLRPCFunctionName`. Added tests to test the new functionality introduced with `subscribeToRPCs:groupType:withHandler:`.

#### Core Tests
Ran tests against Core and verified that the callback in `subscribeToRPCs:groupType:withHandler:` was not called immediately. Verified appropriate permission responses were passed back from old/new methods by printing out the results of the method call.

Core version / branch / commit hash / module tested against: SYNC 3.0 Build 17276_DEVTEST
HMI name / version / branch / commit hash / module tested against: Manticore v0.7.2

### Summary
Deprecated functions whose parameter took a `SDLPermissionRPCName` and created new methods that take a `SDLRPCFunctionName` instead. New permissions observer method was created to align with Java Suite, now the observer will not be called when it is first set.

##### Enhancements
Deprecated methods -> new method
- `isRPCAllowed:` -> `isRPCPermitted:`
- `groupStatusOfRPCs:` -> `groupStatusOfRPCNames:`
- `statusOfRPCs:` -> `statusOfRPCNames:`
- `addObserverForRPCs:groupType:withHandler:` -> `subscribeToRPCs:groupType:withHandler:`
- `statusOfRPCs:` -> `statusOfRPCNames:`
- `rpcRequiresEncryption:` -> `rpcNameRequiresEncryption:`

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLPermissionManager.m [hunk 1]
```diff
@@ -74,6 +74,15 @@ - (BOOL)isRPCAllowed:(NSString *)rpcName {
...
 }
 
+- (BOOL)isRPCPermitted:(SDLRPCFunctionName)rpcName {
+    if (self.permissions[rpcName] == nil || self.currentHMILevel == nil) {
+        return NO;
+    }
+
+    SDLPermissionItem *item = self.permissions[rpcName];
+    return [item.hmiPermissions.allowed containsObject:self.currentHMILevel];
+}
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPermissionManager.m:84]: Since this is the same implementation as `isRPCAllowed`, the deprecated one can change to just call the new one. That way if we ever have to fix a bug we don't have to fix it twice.

File: SmartDeviceLink/SDLPermissionManager.m [hunk 2]
```diff
@@ -82,6 +91,14 @@ - (SDLPermissionGroupStatus)groupStatusOfRPCs:(NSArray<SDLPermissionRPCName> *)r
     return [self.class sdl_groupStatusOfRPCs:rpcNames withPermissions:[self.permissions copy] hmiLevel:self.currentHMILevel];
 }
 
+- (SDLPermissionGroupStatus)groupStatusOfRPCNames:(NSArray<SDLRPCFunctionName> *)rpcNames {
+    if (self.currentHMILevel == nil) {
+        return SDLPermissionGroupStatusUnknown;
+    }
+
+    return [self.class sdl_groupStatusOfRPCs:rpcNames withPermissions:[self.permissions copy] hmiLevel:self.currentHMILevel];
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPermissionManager.m:99]: Same as above

File: SmartDeviceLink/SDLPermissionManager.m [hunk 3]
```diff
@@ -132,6 +149,17 @@ + (SDLPermissionGroupStatus)sdl_groupStatusOfRPCs:(NSArray<SDLPermissionRPCName>
...
 
+- (NSDictionary<SDLRPCFunctionName,NSNumber *> *)statusOfRPCNames:(NSArray<SDLRPCFunctionName> *)rpcNames {
+    NSMutableDictionary<SDLRPCFunctionName, NSNumber *> *permissionAllowedDict = [NSMutableDictionary dictionary];
+    
+    for (SDLRPCFunctionName rpcName in rpcNames) {
+        BOOL allowed = [self isRPCPermitted:rpcName];
+        permissionAllowedDict[rpcName] = @(allowed);
+    }
+
+    return [permissionAllowedDict copy];
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPermissionManager.m:160]: Same as above

File: SmartDeviceLink/SDLPermissionManager.m [hunk 4]
```diff
@@ -149,9 +177,18 @@ - (SDLPermissionObserverIdentifier)addObserverForRPCs:(NSArray<SDLPermissionRPCN
     return filter.identifier;
 }
 
+- (SDLPermissionObserverIdentifier)subscribeToRPCs:(NSArray<SDLRPCFunctionName> *)rpcNames groupType:(SDLPermissionGroupType)groupType withHandler:(SDLPermissionsChangedHandler)handler {
+    SDLPermissionFilter *filter = [SDLPermissionFilter filterWithRPCNames:rpcNames groupType:groupType observer:handler];
+
+    // Store the filter for later use
+    [self.filters addObject:filter];
+
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPermissionManager.m:185]: This doesn't look right. I think you're now _never_ calling the initial observer, which is not correct. See above in the documentation on this topic.

File: SmartDeviceLink/SDLPermissionManager.m [hunk 5]
```diff
@@ -374,6 +411,13 @@ - (BOOL)rpcRequiresEncryption:(SDLPermissionRPCName)rpcName {
     return NO;
 }
 
+- (BOOL)rpcNameRequiresEncryption:(SDLRPCFunctionName)rpcName {
+    if (self.permissions[rpcName].requireEncryption != nil) {
+        return self.permissions[rpcName].requireEncryption.boolValue;
+    }
+    return NO;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPermissionManager.m:418]: See above one should call the other.

File: SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m [hunk 6]
```diff
@@ -133,193 +134,363 @@ @interface SDLPermissionManager ()
...
+                    someRPCName = @"some rpc name";
+
+                    #pragma clang diagnostic push
+                    #pragma clang diagnostic ignored "-Wdeprecated-declarations"
+                    testResultBOOL = [testPermissionsManager isRPCAllowed:someRPCName];
+                    #pragma clang diagnostic pop
+                });
+
+                it(@"should not be allowed", ^{
+                    expect(@(testResultBOOL)).to(equal(@NO));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m:152]:
```suggestion
                    expect(testResultBOOL).to(beFalse());
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m [hunk 7]
```diff
@@ -133,193 +134,363 @@ @interface SDLPermissionManager ()
...
-                expect(@(testResultBOOL)).to(equal(@NO));
+
+            context(@"isRPCPermitted: method", ^{
+                beforeEach(^{
+                    someRPCFunctionName = @"SomeRPCFunctionName";
+                    testResultBOOL = [testPermissionsManager isRPCPermitted:someRPCName];
+                });
+
+                it(@"should not be allowed", ^{
+                    expect(@(testResultBOOL)).to(equal(@NO));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m:163]:
```suggestion
                    expect(testResultBOOL).to(beFalse());
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m [hunk 8]
```diff
@@ -133,193 +134,363 @@ @interface SDLPermissionManager ()
...
+                    #pragma clang diagnostic ignored "-Wdeprecated-declarations"
                     testResultBOOL = [testPermissionsManager isRPCAllowed:testRPCNameAllAllowed];
+                    #pragma clang diagnostic pop
                 });
-                
-                it(@"should be allowed", ^{
-                    expect(@(testResultBOOL)).to(equal(@YES));
+
+                it(@"should not be allowed", ^{
+                    expect(@(testResultBOOL)).to(equal(@NO));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m:179]:
```suggestion
                    expect(testResultBOOL).to(beFalse());
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m [hunk 9]
```diff
@@ -133,193 +134,363 @@ @interface SDLPermissionManager ()
...
                     [[NSNotificationCenter defaultCenter] postNotification:testPermissionsNotification];
-                    
-                    testResultBOOL = [testPermissionsManager isRPCAllowed:testRPCNameAllDisallowed];
+                    testResultBOOL = [testPermissionsManager isRPCPermitted:someRPCName];
                 });
-                
-                it(@"should be denied", ^{
+
+                it(@"should not be allowed", ^{
                     expect(@(testResultBOOL)).to(equal(@NO));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m:190]:
```suggestion
                    expect(testResultBOOL).to(beFalse());
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m [hunk 10]
```diff
@@ -133,193 +134,363 @@ @interface SDLPermissionManager ()
...
+                        [[NSNotificationCenter defaultCenter] postNotification:limitedHMINotification];
+                        [[NSNotificationCenter defaultCenter] postNotification:testPermissionsNotification];
+                        #pragma clang diagnostic push
+                        #pragma clang diagnostic ignored "-Wdeprecated-declarations"
+                        testResultBOOL = [testPermissionsManager isRPCAllowed:testRPCNameAllAllowed];
+                        #pragma clang diagnostic pop
+                    });
+
+                    it(@"should be allowed", ^{
+                        expect(@(testResultBOOL)).to(equal(@YES));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m:208]:
```suggestion
                        expect(testResultBOOL).to(beTrue());
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m [hunk 11]
```diff
@@ -133,193 +134,363 @@ @interface SDLPermissionManager ()
...
+                        [[NSNotificationCenter defaultCenter] postNotification:limitedHMINotification];
+                        [[NSNotificationCenter defaultCenter] postNotification:testPermissionsNotification];
+                        #pragma clang diagnostic push
+                        #pragma clang diagnostic ignored "-Wdeprecated-declarations"
+                        testResultBOOL = [testPermissionsManager isRPCAllowed:testRPCNameAllDisallowed];
+                        #pragma clang diagnostic pop
+                    });
+
+                    it(@"should be denied", ^{
+                        expect(@(testResultBOOL)).to(equal(@NO));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m:223]:
```suggestion
                        expect(testResultBOOL).to(beFalse());
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m [hunk 12]
```diff
@@ -133,193 +134,363 @@ @interface SDLPermissionManager ()
...
+                context(@"and the permission is allowed", ^{
+                    beforeEach(^{
+                        [[NSNotificationCenter defaultCenter] postNotification:limitedHMINotification];
+                        [[NSNotificationCenter defaultCenter] postNotification:testPermissionsNotification];
+
+                        testResultBOOL = [testPermissionsManager isRPCPermitted:testRPCNameAllAllowed];
+                    });
+
+                    it(@"should be allowed", ^{
+                        expect(@(testResultBOOL)).to(equal(@YES));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m:238]:
```suggestion
                        expect(testResultBOOL).to(beTrue());
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m [hunk 13]
```diff
@@ -133,193 +134,363 @@ @interface SDLPermissionManager ()
...
+                context(@"and the permission is denied", ^{
+                    beforeEach(^{
+                        [[NSNotificationCenter defaultCenter] postNotification:limitedHMINotification];
+                        [[NSNotificationCenter defaultCenter] postNotification:testPermissionsNotification];
+
+                        testResultBOOL = [testPermissionsManager isRPCPermitted:testRPCNameAllDisallowed];
+                    });
+
+                    it(@"should be denied", ^{
+                        expect(@(testResultBOOL)).to(equal(@NO));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m:251]:
```suggestion
                        expect(testResultBOOL).to(beFalse());
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m [hunk 14]
```diff
@@ -355,99 +529,144 @@ @interface SDLPermissionManager ()
...
+
+                    // This should not be called even with data currently present, the handler will only be called when an permissions update occurs after the RPC is subscribed to
+                    [testPermissionsManager subscribeToRPCs:@[testRPCNameAllAllowed, testRPCNameAllDisallowed] groupType:SDLPermissionGroupTypeAny withHandler:^(NSDictionary<SDLPermissionRPCName,NSNumber *> * _Nonnull change, SDLPermissionGroupStatus status) {
+                        testObserverCalled = YES;
+                    }];
+                });
+
+                it(@"should not be called", ^{
+                    expect(@(testObserverCalled)).to(equal(@NO));
+                });
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m:596]: This is incorrect; it should be called

File: SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m [hunk 15]
```diff
@@ -355,99 +529,144 @@ @interface SDLPermissionManager ()
...
+
+                beforeEach(^{
+                    testObserverCalled = NO;
+                    [testPermissionsManager subscribeToRPCs:@[testRPCNameAllAllowed, testRPCNameAllDisallowed] groupType:SDLPermissionGroupTypeAny withHandler:^(NSDictionary<SDLPermissionRPCName,NSNumber *> * _Nonnull change, SDLPermissionGroupStatus status) {
+                        testObserverCalled = YES;
+                    }];
+                });
+
+                it(@"should not be called", ^{
+                    expect(@(testObserverCalled)).to(equal(@NO));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m:573]:
```suggestion
                    expect(testObserverCalled).to(beFalse());
```
