### PR TITLE
Streamingvideolifecyclemanagers is streaming supported

### LINKED ISSUE #1411: Version needed Streamingvideolifecyclemanagers isStreamingSupported
##### Expected Behavior
Version for isStreamingSupported

##### Observed Behavior
no. Version for isStreamingSupported

### PR DESCRIPTION
**Pull request by justingluck93**
Fixes #1411 

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLStreamingVideoLifecycleManager.m [hunk 1]
```diff
@@ -563,9 +564,12 @@ - (void)sdl_didReceiveRegisterAppInterfaceResponse:(SDLRPCResponseNotification *
     SDLLogV(@"Determining whether streaming is supported");
 #pragma clang diagnostic push
 #pragma clang diagnostic ignored "-Wdeprecated"
-    _streamingSupported = registerResponse.hmiCapabilities.videoStreaming ? registerResponse.hmiCapabilities.videoStreaming.boolValue : registerResponse.displayCapabilities.graphicSupported.boolValue;
+    if ([SDLGlobals.sharedGlobals.rpcVersion isGreaterThanOrEqualToVersion:[[SDLVersion alloc] initWithMajor:4 minor:5 patch:0]]) {
+        _streamingSupported = registerResponse.hmiCapabilities.videoStreaming ? registerResponse.hmiCapabilities.videoStreaming.boolValue : registerResponse.displayCapabilities.graphicSupported.boolValue;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLStreamingVideoLifecycleManager.m]:
```suggestion
        _streamingSupported = registerResponse.hmiCapabilities.videoStreaming.boolValue;
```

If we're >= 4.5 and `videoStreaming` is `nil`, then we can assume it doesn't support video streaming.

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 2]
```diff
@@ -172,6 +177,10 @@ __block void (^sendNotificationForHMILevel)(SDLHMILevel hmiLevel, SDLVideoStream
 
                     someDisplayCapabilities.screenParams = someScreenParams;
 
+                    SDLVersion *oldVersion = [SDLVersion versionWithMajor:6 minor:0 patch:0];
+                    id globalMock = OCMPartialMock([SDLGlobals sharedGlobals]);
+                    OCMStub([globalMock rpcVersion]).andReturn(oldVersion);
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m]: What is this for?

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 3]
```diff
@@ -149,6 +150,10 @@ __block void (^sendNotificationForHMILevel)(SDLHMILevel hmiLevel, SDLVideoStream
...
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m]: What is this for?

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m [hunk 4]
```diff
@@ -188,6 +197,31 @@ __block void (^sendNotificationForHMILevel)(SDLHMILevel hmiLevel, SDLVideoStream
...
+#pragma clang diagnostic ignored "-Wdeprecated"
+                    someRegisterAppInterfaceResponse.displayCapabilities = someDisplayCapabilities;
+#pragma clang diagnostic pop
+                    SDLRPCResponseNotification *notification = [[SDLRPCResponseNotification alloc] initWithName:SDLDidReceiveRegisterAppInterfaceResponse object:self rpcResponse:someRegisterAppInterfaceResponse];
+
+                    [[NSNotificationCenter defaultCenter] postNotification:notification];
+                    [NSThread sleepForTimeInterval:0.1];
+                });
+
+                it(@"should support streaming", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m]:
```suggestion
                it(@"should support streaming even though hmiCapabilities.videoStreaming is nil", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m (hunk 2 above)
Comment (justingluck93) [reply SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m]: so i can test that if the SDLVersion is 4.5+ it will run the code in the 'if' in `SDLStreamingVideoLifecycleManager.m`
