### PR TITLE
Fixed the file manager erroring if the ListFiles RPC must be encrypted

### LINKED ISSUE #1975: The File Manager will not send images if the ListFiles request is rejected by the module due to encryption
### Bug Report
If the `SDLFileManager` sends a `ListFiles`  request and the module rejects it because it needs to be encrypted, the file manager transitions to the error state and no artworks can be sent.

Technically, the `SDLFileManager` should either 1) not send the `ListFiles` request until the encryption manager has been setup or 2) it should send the `ListFiles` request again when the encryption manager has been setup. 

A quick workaround would be to check in `didEnterStateFetchingInitialList` if `[error.userInfo[@"resultCode"] isEqualToEnum:SDLResultEncryptionNeeded]` and just transition to the `SDLFileManagerStateReady` if so. This means that the library will waste time re-uploading artworks that already exist on the module but it works as a temporary fix until the `SDLFileManager` can be reworked to add a dependency on the encryption manager. 

##### Reproduction Steps
1. Configure the module to require encryption for the `ListFiles` RPC.
2. Connect the SDL app to the module and launch the SDL app.

##### Expected Behavior
The artworks in the `Show` request should show up.

##### Observed Behavior
The artworks for the `Show` request are never sent to the module due to the `SDLFileManager` being in the error state.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 7.1
* Testing Against: sdl_core (commit d7c804de1e5bc90f9359ea21b9d9c54de70bb947 (HEAD -> develop, origin/develop))

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #1975

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
* Unit tests added to _SDLFileManagerSpec_ to test new state transition. 

#### Core Tests
* Configure the module to require encryption for the `ListFiles` RPC. Then, connect the SDL app to the module and launch the SDL app. The `SDLFileManager` should be able to send artworks even if the module rejects the `ListFiles` request due to `ENCRYPTION_NEEDED`.

##### Core version / branch / commit hash / module tested against: 
* sdl_core: commit d7c804de1e5bc90f9359ea21b9d9c54de70bb947 (HEAD -> develop, origin/develop)

##### HMI name / version / branch / commit hash / module tested against: 
* sdl_hmi: commit 71cbfe9a094a860df42577adb0f7579b18fc44c7 (HEAD -> develop, tag: 5.5.0, origin/master, origin/develop, origin/HEAD)

### Summary
If the module requires that `ListFiles` RPC be encrypted, the `SDLFileManager` is now still able to send artworks/files. 

##### Bug Fixes
* Fixed the `SDLFileManager` transitioning to the error sate if the module rejects the `ListFiles` RPC because it must be encrypted. 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/public/SDLFileManager.m [hunk 1]
```diff
@@ -178,11 +178,16 @@ - (void)didEnterStateFetchingInitialList {
...
-            if([error.userInfo[@"resultCode"] isEqualToEnum:SDLResultDisallowed]) {
+            if ([error.userInfo[@"resultCode"] isEqualToEnum:SDLResultDisallowed]) {
+                // HAX: In the case we are DISALLOWED we still want to transition to a ready state. Some head units return DISALLOWED for this RPC but otherwise work.
                 SDLLogW(@"ListFiles is disallowed. Certain file manager APIs may not work properly.");
                 [weakSelf.stateMachine transitionToState:SDLFileManagerStateReady];
                 BLOCK_RETURN;
+            } else if ([error.userInfo[@"resultCode"] isEqualToEnum:SDLResultEncryptionNeeded]) {
+                // HAX: If the module rejects the ListFiles request because it requires that the request be encrypted, we still want to transition to a ready state. Unfortunately, since we do not know what files are on the module already, we may end up doing unnecessary duplicate file uploads.
+                SDLLogW(@"ListFiles must be encrypted. We do not know which files have already been uploaded to the module. Certain file manager APIs may not work properly.");
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLFileManager.m:188]:
```suggestion
                SDLLogE(@"ListFiles must be encrypted but was not when the file manager started. We do not know which files have already been uploaded to the module. All files will need to be re-uploaded. Certain file manager APIs may not work properly.");
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m [hunk 2]
```diff
@@ -172,6 +172,22 @@ @implementation FileManagerSpecHelper
             });
         });
 
+        describe(@"after receiving a ListFiles error with a resultCode ENCRYPTION_NEEDED", ^{
+            beforeEach(^{
+                SDLListFilesOperation *operation = testFileManager.pendingTransactions.firstObject;
+                NSMutableDictionary *userInfo = [[NSError sdl_fileManager_unableToStartError].userInfo mutableCopy];
+                userInfo[@"resultCode"] = SDLResultEncryptionNeeded;
+                NSError *errorWithResultCode = [NSError errorWithDomain:[NSError sdl_fileManager_unableToStartError].domain code:[NSError sdl_fileManager_unableToStartError].code userInfo:userInfo];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m:180]: Replace these lines with just creating the error on one line. Don't copy a bunch of stuff and modify the error.

File: SmartDeviceLink/public/SDLFileManager.m [hunk 3]
```diff
@@ -178,11 +178,16 @@ - (void)didEnterStateFetchingInitialList {
...
         if (error != nil) {
-            // HAX: In the case we are DISALLOWED we still want to transition to a ready state. Some head units return DISALLOWED for this RPC but otherwise work.
-            if([error.userInfo[@"resultCode"] isEqualToEnum:SDLResultDisallowed]) {
+            if ([error.userInfo[@"resultCode"] isEqualToEnum:SDLResultDisallowed]) {
+                // HAX: In the case we are DISALLOWED we still want to transition to a ready state. Some head units return DISALLOWED for this RPC but otherwise work.
                 SDLLogW(@"ListFiles is disallowed. Certain file manager APIs may not work properly.");
                 [weakSelf.stateMachine transitionToState:SDLFileManagerStateReady];
                 BLOCK_RETURN;
+            } else if ([error.userInfo[@"resultCode"] isEqualToEnum:SDLResultEncryptionNeeded]) {
+                // HAX: If the module rejects the ListFiles request because it requires that the request be encrypted, we still want to transition to a ready state. Unfortunately, since we do not know what files are on the module already, we may end up doing unnecessary duplicate file uploads.
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLFileManager.m:187]:
```suggestion
                // If the module rejects the ListFiles request because it requires that the request be encrypted, we still want to transition to a ready state. Unfortunately, since we do not know what files are on the module already, we may end up doing unnecessary duplicate file uploads.
```

This isn't a HAX because it's not working around a module bug.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m (hunk 2 above)
Comment (NicoleYarroch) [reply SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m]: I refactored the tests that check for an error response from the `ListFiles` request so it is easier to read.

**Review by joeljfischer — APPROVED** [review]
