### PR TITLE
Fix lock screen dismiss animation not working on certain older systems

### LINKED ISSUE #1504: Lock screen dismiss animation breaks
### Bug Report
The lock screen dismiss animation breaks the first time the lock screen is shown. 

##### Reproduction Steps
1. App is open on phone
1. TDK is set to "parked"
1. Connect app to TDK (SYNC 3 v3.0)

##### Expected Behavior
The lock screen should show and be dismissed since the vehicle is not moving. The dismissal of the lock screen should be animated. 

##### Observed Behavior
The lock screen should show and be dismissed since the vehicle is not moving. The lock screen dismissal is not animated. 

I believe this is because `dismiss` is called twice in quick succession
due to two driver distraction notifications coming in one right after another. We should probably check if the lock screen is already in the process of being dismissed before doing the dismissal.

##### OS & Version Information
* iOS Version: 13
* SDL iOS Version: 6.4.1
* Testing Against: TDK, SYNC 3, v3.0

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1504, #1565 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit tests currently do not exist for the `SDLLockScreenPresenter` class, so no new unit tests were added in this bugfix PR. They were run and pass.

#### Core Tests
- [x] Connected while DD_OFF.
- [x] Repeatedly enable / disable DD as fast as possible.
- [x] Connected, backgrounded app, disconnected, reconnected, foregrounded app

Core version / branch / commit hash / module tested against: Sync Gen 3.0 (19205_DEVTEST), Sync Gen 3.0 (17276_DEVTEST)
HMI name / version / branch / commit hash / module tested against: Same as above

### Summary
* This PR tracks dismissals to prevent "double" dismissals causing the dismiss animation to break.
* Changes the synchronization of the lock manager to not run a bunch of code async. 
* Changes the startup sequence to account for cases where the app is backgrounded when starting.

##### Bug Fixes
* The lock screen dismiss animation will no longer break on older SDL systems.
* Disconnecting and reconnecting an app in the background will no longer prevent the lock screen from being dismissed in certain cases.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 1]
```diff
@@ -168,9 +167,12 @@ - (void)sdl_dismissLockscreenWithCompletionHandler:(void (^ _Nullable)(void))com
     [[NSNotificationCenter defaultCenter] postNotificationName:SDLLockScreenManagerWillDismissLockScreenViewController object:nil];
 
     SDLLogD(@"Dismissing the lockscreen window");
+    _isDismissing = YES;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLLockScreenPresenter.m]: When I test the Obj-C app on a iOS 12 device, the lockscreen can not be dismissed when:
1. Set the TDK driving status to "moving".
1. Connect the device to a SYNC 3.0 head unit using a USB cord. The lockscreen should show up.
1. Trigger a `DD_OFF` notification by setting the TDK driving status to "parked"

### Expected
The lock screen dismisses.

### Actual
The lock screen can not be dismissed.

Comment (joeljfischer) [reply SmartDeviceLink/SDLLockScreenPresenter.m]: Fixed

**Comment by NicoleYarroch** [comment]
I got a crash when testing LMP with this branch installed to SYNC 3.0:
1. Open LMP on the device and keep in the foreground.
1. Set the SYNC 3.0 module to "parked".
1. Connect the device to SYNC 3.0 using a USB cord. Launch the SDL app. The lock screen shows and dismisses.
1. Trigger a DD_ON notification by setting the module to "moving". 
1. Put app on device in background.
1. Pull USB cord. Device app should still be in background.
1. Bring app on device to foreground

### Expected Result
Lock screen dismisses

### Actual Result
Lock screen dismisses and app crashes. 

```
2020-02-25 11:23:52.832912-0500 Livio Music[500:63894] [Lockscreen] Dismissing the lockscreen window
2020-02-25 11:23:52.835041-0500 Livio Music[500:63894] [Lockscreen] Presenting the lockscreen window
2020-02-25 11:23:53.394217-0500 Livio Music[500:63894] [Lockscreen] Lockscreen window dismissed
2020-02-25 11:23:53.396489-0500 Livio Music[500:63894] [Lockscreen] Presenting the lockscreen window
2020-02-25 11:23:53.402151-0500 Livio Music[500:63333] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <SDLLockScreenRootViewController: 0x103c15340>.'
*** First throw call stack:
(0x1884ed54c 0x1882080c8 0x18bf39e08 0x18bf3c148 0x18bf3c6f4 0x18bf556bc 0x18bf51c98 0x18bf519b0 0x18c9b4108 0x18c9b3dac 0x18c9eae0c 0x18c9be088 0x18c9be5b0 0x18c9be708 0x18efb2038 0x1037ff32c 0x10380d3e0 0x188468700 0x18846345c 0x188462978 0x192592534 0x18c554f0c 0x10053d184 0x1882e2f04)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by NicoleYarroch** [comment]
I got a crash when testing LMP with this branch installed to SYNC 3.0:
1. Open LMP on the device and keep in the foreground.
1. Set the SYNC 3.0 module to "parked".
1. Connect the device to SYNC 3.0 using a USB cord. Launch the SDL app. The lock screen shows and dismisses.
1. Trigger a DD_ON notification by setting the module to "moving". 
1. Put app on device in background.
1. Pull USB cord. Device app should still be in background.
1. Bring app on device to foreground

### Expected Result
Lock screen dismisses

### Actual Result
Lock screen dismisses and app crashes. 

```
2020-02-25 11:23:52.832912-0500 Livio Music[500:63894] [Lockscreen] Dismissing the lockscreen window
2020-02-25 11:23:52.835041-0500 Livio Music[500:63894] [Lockscreen] Presenting the lockscreen window
2020-02-25 11:23:53.394217-0500 Livio Music[500:63894] [Lockscreen] Lockscreen window dismissed
2020-02-25 11:23:53.396489-0500 Livio Music[500:63894] [Lockscreen] Presenting the lockscreen window
2020-02-25 11:23:53.402151-0500 Livio Music[500:63333] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <SDLLockScreenRootViewController: 0x103c15340>.'
*** First throw call stack:
(0x1884ed54c 0x1882080c8 0x18bf39e08 0x18bf3c148 0x18bf3c6f4 0x18bf556bc 0x18bf51c98 0x18bf519b0 0x18c9b4108 0x18c9b3dac 0x18c9eae0c 0x18c9be088 0x18c9be5b0 0x18c9be708 0x18efb2038 0x1037ff32c 0x10380d3e0 0x188468700 0x18846345c 0x188462978 0x192592534 0x18c554f0c 0x10053d184 0x1882e2f04)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by NicoleYarroch** [comment]
I got a crash when testing LMP with this branch installed to SYNC 3.0:
1. Open LMP on the device and keep in the foreground.
1. Set the SYNC 3.0 module to "parked".
1. Connect the device to SYNC 3.0 using a USB cord. Launch the SDL app. The lock screen shows and dismisses.
1. Trigger a DD_ON notification by setting the module to "moving". 
1. Put app on device in background.
1. Pull USB cord. Device app should still be in background.
1. Bring app on device to foreground

### Expected Result
Lock screen dismisses

### Actual Result
Lock screen dismisses and app crashes. 

```
2020-02-25 11:23:52.832912-0500 Livio Music[500:63894] [Lockscreen] Dismissing the lockscreen window
2020-02-25 11:23:52.835041-0500 Livio Music[500:63894] [Lockscreen] Presenting the lockscreen window
2020-02-25 11:23:53.394217-0500 Livio Music[500:63894] [Lockscreen] Lockscreen window dismissed
2020-02-25 11:23:53.396489-0500 Livio Music[500:63894] [Lockscreen] Presenting the lockscreen window
2020-02-25 11:23:53.402151-0500 Livio Music[500:63333] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <SDLLockScreenRootViewController: 0x103c15340>.'
*** First throw call stack:
(0x1884ed54c 0x1882080c8 0x18bf39e08 0x18bf3c148 0x18bf3c6f4 0x18bf556bc 0x18bf51c98 0x18bf519b0 0x18c9b4108 0x18c9b3dac 0x18c9eae0c 0x18c9be088 0x18c9be5b0 0x18c9be708 0x18efb2038 0x1037ff32c 0x10380d3e0 0x188468700 0x18846345c 0x188462978 0x192592534 0x18c554f0c 0x10053d184 0x1882e2f04)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by joeljfischer** [comment]
@NicoleYarroch I believe I have fixed the issue.

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 2]
```diff
@@ -47,30 +45,41 @@ - (void)stop {
...
-            if (self.shouldShowLockScreen) { return; }
+            if (self.shouldShowLockScreen) {
+                if (completionHandler != nil) { completionHandler(); }
+                return;
+            }
 
             SDLLogV(@"The lockscreen has been presented but needs to be dismissed");
-            [self sdl_dismissWithCompletionHandler:nil];
+            [self sdl_dismissWithCompletionHandler:^(BOOL success) {
+                completionHandler();
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLLockScreenPresenter.m]: The app is crashing with a threading error here:

Branch installed on LMP and connected to SYNC 3.0 head unit.
1. Set the SYNC v3.0 head unit to "parked"
1. Open LMP and connect the device to the head unit using a USB cord.
1. Launch the SDL app by selecting the icon on the HMI.

### Expected result
Lock screen shows  and dismisses

### Actual result
Lock screen shows and then the app crashes.

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 3]
```diff
@@ -47,30 +45,41 @@ - (void)stop {
...
+            self.lockWindow = nil;
+            self.lockViewController = nil;
+        }
     }];
 }
 
 /// Shows or hides the lockscreen with an animation. If the lockscreen is shown/dismissed in rapid succession the final state of the lockscreen may not match the expected state as the order in which the animations finish can be random. To guard against this scenario, store the expected state of the lockscreen. When the animation finishes, check the expected state to make sure that the final state of the lockscreen matches the expected state. If not, perform a final animation to the expected state.
 /// @param show True if the lockscreen should be shown; false if it should be dismissed
-- (void)updateLockScreenToShow:(BOOL)show {
+- (void)updateLockScreenToShow:(BOOL)show withCompletionHandler:(nullable SDLLockScreenDidFinishHandler)completionHandler {
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/SDLLockScreenPresenter.m]: Fixed

File: SmartDeviceLink/SDLLockScreenPresenter.m (hunk 2 above)
Comment (joeljfischer) [reply SmartDeviceLink/SDLLockScreenPresenter.m]: I'm not seeing this crash either on the example app or LMP.

Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLockScreenPresenter.m]: I just had it crash twice here. I think the issue is that `completionHandler` is `nil`. Should probably check if it is `nil` before trying to call it.

Comment (joeljfischer) [reply SmartDeviceLink/SDLLockScreenPresenter.m]: I think I fixed it.

**Comment by joeljfischer** [comment]
@NicoleYarroch Bug 1 is fixed, Bug 2 I only saw once out of 8 tries and have not been able to replicate it since.

File: SmartDeviceLink/SDLLockScreenManager.m [hunk 4]
```diff
@@ -209,20 +231,30 @@ - (void)sdl_updateLockscreenViewControllerWithDismissableState:(BOOL)enabled {
     }
     
     __weak typeof(self) weakself = self;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLLockScreenManager.m]:
```suggestion
    __weak typeof(self) weakSelf = self;
```

File: SmartDeviceLink/SDLLockScreenManager.m [hunk 5]
```diff
@@ -65,6 +65,24 @@ - (instancetype)initWithConfiguration:(SDLLockScreenConfiguration *)config notif
 - (void)start {
     self.canPresent = NO;
 
+    [self sdl_runOnMainQueue:^{
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLLockScreenManager.m]: Use `weakSelf`/`strongSelf` in this block

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 6]
```diff
@@ -39,38 +37,53 @@ - (instancetype)init {
 }
 
 /// Resets the manager by dismissing and destroying the lockscreen.
-- (void)stop {
+- (void)stopWithCompletionHandler:(nullable SDLLockScreenDidFinishHandler)completionHandler {
     self.shouldShowLockScreen = NO;
 
     if (self.lockWindow == nil) {
         return;
     }
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLLockScreenPresenter.m]:
```suggestion
    if (self.lockWindow == nil) {
        if (completionHandler != nil) {
            completionHandler();
        }
        return;
    }
```

Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLockScreenPresenter.m]: When `stopWithCompletionHandler:` is called from `SDLLockScreenPresenter`'s `start` method and it returns here before calling the `completionHandler`, then `sdl_start` is never called in `SDLLockScreenPresenter`. This means that `canPresent` is forever stuck at `NO`. 

## Reproduction steps
I can reproduce this issue with the LMP on iOS 13.3.

1. Open LMP on the device. 
1. Set the TDK moving status to "Speed"
1. Connect LMP to the TDK with a USB cord.
1. Launch the app on the TDK by selecting the app icon. 

### Expected result
Lockscreen shows because the TDK's moving status is set to "Speed".

### Actual result
Lockscreen never shows, even when I toggle the moving status button.

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 7]
```diff
@@ -39,38 +37,53 @@ - (instancetype)init {
...
 /// @param show True if the lockscreen should be shown; false if it should be dismissed
-- (void)updateLockScreenToShow:(BOOL)show {
+- (void)updateLockScreenToShow:(BOOL)show withCompletionHandler:(nullable SDLLockScreenDidFinishHandler)completionHandler {
     // Store the expected state of the lockscreen
     self.shouldShowLockScreen = show;
 
     if (show) {
         [self sdl_presentWithCompletionHandler:^{
-            if (self.shouldShowLockScreen) { return; }
+            if (self.shouldShowLockScreen) {
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLLockScreenPresenter.m]: Use `weakSelf`/`strongSelf` in this block

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 8]
```diff
@@ -39,38 +37,53 @@ - (instancetype)init {
...
     if (self.lockWindow == nil) {
         return;
     }
 
     // Dismiss and destroy the lockscreen window
-    [self sdl_dismissWithCompletionHandler:^{
-        self.lockWindow = nil;
+    [self sdl_dismissWithCompletionHandler:^(BOOL success) {
+        if (success) {
+            self.lockWindow = nil;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLLockScreenPresenter.m]: Use `weakSelf`

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 9]
```diff
@@ -39,38 +37,53 @@ - (instancetype)init {
...
-            [self sdl_dismissWithCompletionHandler:nil];
+            [self sdl_dismissWithCompletionHandler:^(BOOL success) {
+                if (completionHandler != nil) { completionHandler(); }
+            }];
         }];
     } else {
-        [self sdl_dismissWithCompletionHandler:^{
-            if (!self.shouldShowLockScreen) { return; }
+        [self sdl_dismissWithCompletionHandler:^(BOOL success) {
+            if (!self.shouldShowLockScreen) {
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLLockScreenPresenter.m]: Use `weakSelf`/`strongSelf` in this block
