### PR TITLE
Xcode 8.3 beta 2 fixes

### LINKED ISSUE #532: Xcode 8.3b2 throws new warnings
### Bug Report
Reported in slack, new warnings in Xcode 8.3 beta 2 are causing build errors. Specifically, there are warnings / errors around the casing of import statements not matching the casing of the actual files on disk.

Additionally we are seeing new analyzer warnings around copying mutable containers when they should be held as references.

##### Reproduction Steps
1. Open SmartDeviceLink-iOS.xcodeproj in Xcode 8.3 beta 2
1. Build the project
1. See the warnings and analyzer errors

##### Expected Behavior
No warnings

##### Observed Behavior
Warnings

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 4.5.3
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #532

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
n/a

### Summary
Fixes new warnings as seen in Xcode 8.3b2.

##### Bug Fixes
* Fixes import file cases not matching actual file cases.
* Fix copying some mutable properties that should be referenced.

### CODE REVIEW

File: SmartDeviceLink/SDLFileManager.m [hunk 1]
```diff
@@ -40,7 +40,7 @@ @interface SDLFileManager ()
 @property (weak, nonatomic) id<SDLConnectionManagerType> connectionManager;
 
 // Remote state
-@property (copy, nonatomic, readwrite) NSMutableSet<SDLFileName *> *mutableRemoteFileNames;
+@property (strong, nonatomic, readwrite) NSMutableSet<SDLFileName *> *mutableRemoteFileNames;
```
Comment (asm09fsu) [inline SmartDeviceLink/SDLFileManager.m]: Should we be doing this in this PR?

File: SmartDeviceLink/SDLPermissionManager.m [hunk 2]
```diff
@@ -23,8 +23,8 @@
 
 @interface SDLPermissionManager ()
 
-@property (copy, nonatomic) NSMutableDictionary<SDLPermissionRPCName, SDLPermissionItem *> *permissions;
-@property (copy, nonatomic) NSMutableArray<SDLPermissionFilter *> *filters;
+@property (strong, nonatomic) NSMutableDictionary<SDLPermissionRPCName, SDLPermissionItem *> *permissions;
```
Comment (asm09fsu) [inline SmartDeviceLink/SDLPermissionManager.m]: Should we be doing this in this PR?

File: SmartDeviceLink/SDLFileManager.m (hunk 1 above)
Comment (joeljfischer) [inline SmartDeviceLink/SDLFileManager.m]: Yes, these are private properties, so we can modify them if desired. Warnings appear in Xcode 8.3b2 if they are left as is.

Comment (asm09fsu) [inline SmartDeviceLink/SDLFileManager.m]: Okay to me
