### PR TITLE
Fix issue around premature stream close resulting in hangs in iAP transmit queue

### LINKED ISSUE #522: IAPTransport Writes Output Stream from Different Thread than Scheduled Run Loop
The input and output streams for the EASessions used by the SDL mobile proxy are scheduled and opened on the main thread in SDLIAPSession's startStream method. However, the output stream is written to from the dispatch queue com.sdl.transport.iap.transmit in SDLIAPTransport's sendData method. This cross-thread usage of the output stream appears to violate the Apple usage guidelines for NSOutputStream, as stated in https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Streams/Articles/WritingOutputStreams.html. I have bold formatted the specific guideline from the relevant paragraph.

Before you open the stream to begin the streaming of data, send a scheduleInRunLoop:forMode: message to the stream object to schedule it to receive stream events on a run loop. By doing this, you are helping the delegate to avoid blocking when the stream is unable to accept more bytes. If streaming is taking place on another thread, be sure to schedule the stream object on that thread’s run loop. **You should never attempt to access a scheduled stream from a thread different than the one owning the stream’s run loop**. Finally, send the NSOutputStream instance an open message to start the streaming of data to the output container.

The IAPSession startStream method should be extended to include a dispatch_queue argument that should be set to nil if the main run loop is to be used and to the custom dispatch queue to be used otherwise. Then as discussed in this StackOverflow article, the run loop for the thread backing the dispatch queue should be used and the run loop's run method must be called:

http://stackoverflow.com/questions/14022044/how-to-schedule-event-in-runloop-in-gcd

Alternatively, an NSThread can be detached to process the output stream.

### PR DESCRIPTION
**Pull request by davidswi**
Fixes #522

This PR is **ready** for review.

### Risk

This PR makes **no** API changes. However, it affects every send over the IAP transport, so risk is moderate.

### Testing Plan

Testing has been performed using test apps against several pre-production head units running SDLCore.

### Summary
Fixes a hang due to stream close on main thread while loop runs on IAP transmit queue

##### Bug Fixes
* Fixes hangs in the IAP transmit queue when the output stream closes on the main thread before all data in the current send block has been transmitted.

### CODE REVIEW

**Comment by davidswi** [comment]
I should point out that this change will not be necessary if/once the background thread stream processing changes are accepted into the SDL iOS proxy.

File: SmartDeviceLink/SDLIAPTransport.m [hunk 1]
```diff
@@ -272,8 +272,9 @@ - (void)sendData:(NSData *)data {
         NSOutputStream *ostream = self.session.easession.outputStream;
         NSMutableData *remainder = data.mutableCopy;
 
-        while (remainder.length != 0) {
-            if (ostream.streamStatus == NSStreamStatusOpen && ostream.hasSpaceAvailable) {
+        while (ostream.streamStatus == NSStreamStatusOpen &&
+               remainder.length != 0) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLIAPTransport.m]: Style-wise, unless there's many checks, we generally prefer to leave two checks on the same line and let wrapping occur naturally if necessary.
