### PR TITLE
Consolidate logic for saving the dynamic mtu size

### LINKED ISSUE #1615: Consolidate logic for saving the dynamic mtu size
### Bug Report
The dynamic `mtu` size for `SDLServiceTypeRPC` is saved in the `SDLProtocol` class, while the streaming audio and video managers save it in their own respective classes. It would make sense to consolidate saving the dynamic `mtu` size in the `handleProtocolStartServiceACKMessage:` method of the `SDLProtocol` class.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.5
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1615

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Added unit tests to the mtu size in SDLProtocolSpec for audio and video service types.

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Save mtu size for audio and video stream in didReceiveStartServiceACK's method of SDLProtocol class instead of their own managers.

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Save mtu size for audio and video stream in didReceiveStartServiceACK's method of SDLProtocol class instead of their own managers.

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLProtocol.m [hunk 1]
```diff
@@ -513,7 +513,7 @@ - (void)protocol:(SDLProtocol *)protocol didReceiveStartServiceACK:(SDLProtocolM
         switch (startServiceACK.header.serviceType) {
             case SDLServiceTypeRPC: {
                 SDLControlFramePayloadRPCStartServiceAck *startServiceACKPayload = [[SDLControlFramePayloadRPCStartServiceAck alloc] initWithData:startServiceACK.payload];
-
+
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLProtocol.m:516]:
```suggestion

```

In Xcode, please go to preferences -> Text Editing -> Editing and turn on "Automatically trim trailing whitespace" and "Including whitespace-only lines". Thanks! If you just removed whitespace last time and didn't remove the entire line and I didn't notice, sorry!

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]
