### PR TITLE
Fixed menu manager sending secondary image with menuCells when menuCommandSecondaryImage is not supported

### LINKED ISSUE #2006: MenuManager sending secondary image with menuCells when menuCommandSecondaryImage is not supported.
### Bug Report
For menu cells, if `cmdIcon` is supported but `menuCommandSecondaryImage` is not, we will send a secondary image for `menuCells` if the file had been previously uploaded or is a static icon.

##### Reproduction Steps
1. Remove ImageField "menuCommandSecondaryImage" as a supported field from generic_hmi
2. Upload a menu with a normal cell that uses the same image for primary and secondary.

##### Expected Behavior
The Image only shows up in the primary Image field.

##### Observed Behavior
The image shows up in the primary and secondary image fields.

##### OS & Version Information
* iOS Version: [What version of iOS are you using when the bug occurred]
* SDL iOS Version: [What version of the library has this bug been seen on]
* Testing Against: [What you tested with to observe this behavior]

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #2006 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
Tested if the secondaryImage is still being sent in a menu command or a menu submenu cell after the `menuCommandSecondaryImage` and `menuSubMenuSecondaryImage` are removed from displayCapabilities in generic hmi.

Core version / branch / commit hash / module tested against: 7.1.0
HMI name / version / branch / commit hash / module tested against: Generic / 0.10.0

### Summary
Check if the if the image is supported in our windowCapability before sending the Command/SubMenu cell

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Check if the if the image is supported in our windowCapability before sending the Command/SubMenu cell

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by joeljfischer — CHANGES_REQUESTED** [review]
Can we add updated tests to the spec files for this change?

File: SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m [hunk 1]
```diff
@@ -204,6 +209,46 @@ - (void)sdl_displayCapabilityDidUpdate;
             testManager.currentSystemContext = SDLSystemContextMain;
         });
 
+        // hmi does not support menuCommandSecondaryImage
+        context(@"hmi does not support menuCommandSecondaryImage", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m:213]:
```suggestion
        // HMI does not support a command secondary image
        context(@"HMI does not support a command secondary image", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m [hunk 2]
```diff
@@ -204,6 +209,46 @@ - (void)sdl_displayCapabilityDidUpdate;
...
+                SDLAddCommand *cellCommand = (SDLAddCommand *)testManager.inProgressUpdate.firstObject;
+                SDLAddSubMenu *cellSubMenu = (SDLAddSubMenu *)testManager.inProgressUpdate[1];
+                expect(cellCommand.menuParams.menuName).to(equal(@"Test 2"));
+                expect(cellCommand.secondaryImage).to(beNil());
+                expect(cellSubMenu.secondaryImage).toNot(beNil());
+            });
+        });
+
+        // hmi does not support menuSubMenuSecondaryImage
+        context(@"hmi does not support menuSubMenuSecondaryImage", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m:233]:
```suggestion
        // HMI does not support a submenu secondary image
        context(@"HMI does not support a submenu secondary image", ^{
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]
