### PR TITLE
Refactor IAP Transport / Fix EASessions left open

### LINKED ISSUE #1799: High CPU usage in Energy Organizer, iOS 14+
### Bug Report
We're seeing a lot of reports in the Energy organizer for high sustained CPU usage, and this also appears to be affecting our background battery usage metrics. 99% of these reports seem to be from iOS 14.

Sample of some of the stack traces have some slim details:

image
image
image

There's a good number of others but most follow that same pattern. All of these are logged due to high CPU usage, with messages along the lines of "90 seconds cpu time over 94 seconds (96% cpu average), exceeding limit of 50% cpu over 180 seconds."

We haven't been able to locally reproduce at the moment.

##### Reproduction Steps
TBD

##### OS & Version Information
* iOS Version: 14.0+ (1-2% or less reports on iOS 13.7, none on anything less)
* SDL iOS Version: Both 6.6 and 6.7

### LINKED ISSUE #1809: Possible infinity loop with iAP run loop
### Bug Report
There is a possible infinity loop in the [SDLIAPDataSession sdl_accessoryEventLoop](https://github.com/smartdevicelink/sdl_ios/blob/7.0.0-rc.2/SmartDeviceLink/private/SDLIAPDataSession.m#L322). There is no confirmed bug to this issue. However other reports show apps freaking out causing high CPU load possible due to this or another infinity loop.

A planned fix should add more checks to prevent a possible infinity loop. Should be no harm to regular use case but cancel the loop if the iAP session is cancelled.

##### OS & Version Information
* iOS Version: iOS 14.0
* SDL iOS Version: 7.0.0 RC2

### LINKED ISSUE #1892: [SDLIAPDataSession destroySessionWithCompletionHandler:]_block_invoke () crash issue.
### Bug Report
[Summary] 
When integrate with our app, it shows 93 devices crash from apple Organizer Crash Report.

##### Reproduction Steps
Not sure about how to reproduce it.

##### Expected Behavior
No crash.

##### Observed Behavior
Show crash report.

##### OS & Version Information
* iOS Version: 13.7-14.2
* SDL iOS Version: v7.0.0

##### Test Case, Sample Code, and / or Example App
#5	(null) in __57-[SDLIAPDataSession destroySessionWithCompletionHandler:]_block_invoke ()
Screen Shot 2021-01-18 at 3 27 59 PM

### LINKED ISSUE #1893: ExternalAccessory:-[EASession _endStreams] crash on our app.
### Bug Report
[Summary]
We recieved crash report from apple organizer.

##### Reproduction Steps
I'm not sure when cause this crash, but received from apple report.
Screen Shot 2021-01-19 at 4 50 18 PM

##### Expected Behavior
No crash.

##### Observed Behavior
Have crash.

##### OS & Version Information
* iOS Version: 13.5-14.2
* SDL iOS Version: 7.0.0

### PR DESCRIPTION
**Pull request by kmicha19-ford**
Fixes #1799  (when used in conjunction with https://github.com/kmicha19-ford/sdl_ios/pull/2)
Fixes #1809
Fixes #1892
Fixes #1893

This PR is ready for review.

### Risk

This PR makes no  API changes.

### Testing Plan

- I have verified that I have not introduced new warnings in this PR (or explain why below)
- I have tested this PR against Core and verified behavior.

#### Unit Tests

Unit tests were updated for the refactored classes.

#### Core Tests

- Built the Obj-C example app and verified that all interactions work
   - iAP disconnect / reconnect
   - LockScreen on/off rapidly
- Built the Swift example app and verified that all interactions work
   - iAP disconnect / reconnect
   - LockScreen on/off rapidly

### Summary

* Refactors iAPSession code that uses the Apple External Accessory Frameworks to create, open, use, and close EASessions. 

##### Breaking Changes
* None

##### Enhancements

* Moves all managment of EASession creation, open, and closing into a single class, SDLIAPSession
* Eliminates the use of NSThread from SDLIAPDataSession
* SDLIAPSession now uses a DispatchQueue to provide the required thread for EASession
* Uses composition instead of inheritance, SDLIAPControlSession and SDLIAPDataSession now use SDLIAPSession instead of being subclasses of it
* Provides a short simple code path for closing EASessions
* Eliminates over two hundred lines of code

### Tasks Remaining:
- More unit tests

### CLA
- I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLIAPSession.m [hunk 1]
```diff
@@ -11,101 +11,285 @@
...
+            SDLLogD(@"EASession inputstream already closed for EASession %@", self.eaSession);
+        }
+        if ([self isOutputStream:stream]) {
+            SDLLogD(@"EASession outputstream already closed for EASession %@", self.eaSession);
+        }
+        return;
     }
-
+    
+    [stream close];
```
Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLIAPSession.m:101]: While testing, I have experienced random crashes at `[stream close]`. I suspect the issue is that `[stream close]` is being called on the main thread due to the accessory disconnected notification being sent on the main thread (in the `SDLIAPTransport` transport class). We have experienced crash in the [past](https://github.com/smartdevicelink/sdl_ios/pull/1592) and have found that we must open and close the I/O streams on the same thread. 

Since you switched from using a thread to dispatching to the `iapSessionQueue`, this means we have no guarantee that the I/O streams will be opened and closed on the same thread even if we change the code to dispatch closing the I/O threads to the `iapSessionQueue` (due to the fact that behind the scenes the blocks can be dispatched to different threads).

I was curious what the motivation was behind the switching from using a thread to to using the `iapSessionQueue`? Obviously, your changes are simpler and easier to read so I hope there is a solution that lets us keep the  `iapSessionQueue`.

Comment (kmicha19-ford) [reply SmartDeviceLink/private/SDLIAPSession.m:101]: iOS recommends that new designs not use NSThread and instead to use newer techologies such as GCD.  Using a DispatchQueue moves the responsility of creating and managing the thread to iOS. As you correctly mention, dispatch queue blocks can be dispatched to different threads. However self.eaSession always runs on the same thread, the thread that GCD used when we create self.eaSession here in SDLIAPSession

 (void) startSession {
dispatch_async(self.iapSessionQueue, ^{
        self.eaSession = [[EASession alloc] initWithAccessory:self.accessory forProtocol:self.protocolString];

Notice there are no other calls to dispatch_async(self.iapSessionQueue) anywhere in SDLIAPSession.  All further access is via self.eaSession, thus [stream close] is always on the same thread as was used for example in [stream open]

Comment (joeljfischer) [reply SmartDeviceLink/private/SDLIAPSession.m:101]: @kmicha19-ford I'm not quite following. Are you saying that `self.eaSession` is internally thread-safe and any calls to it will internally dispatch to the correct thread, and therefore it doesn't matter from where the `NSStream close` call comes from? Since those seem to be separate objects and classes, could you clarify the relation? I know an `EASession` uses the stream, but you seem to be closing the stream without accessing `self.eaSession` at this code line. As @NicoleYarroch noted, there seem to be crashes with this PR related to closing the stream, so it can't be entirely safe here.

Comment (makinney) [reply SmartDeviceLink/private/SDLIAPSession.m:101]: Sorry for delay with answer.  Work Mac went down yesterday. IT scheduled an appointment for Monday to take it in to run diagnostics. Meanwhile I am on a backup computer. 

EASession is not thread safe. As to other questions I need to get things setup on this backup Mac and so I can run this code and look at some things before answering these questions. Hopefully by Monday if not end of day today.

Comment (makinney) [reply SmartDeviceLink/private/SDLIAPSession.m:101]: @NicoleYarroch - Are you seeing random crashes at [stream close] with this PR? (Or something with existing code base)?

Comment (makinney) [reply SmartDeviceLink/private/SDLIAPSession.m:101]: @joeljfischer Which separate objects and classes are you referring to in your comment?

Comment (NicoleYarroch) [reply SmartDeviceLink/private/SDLIAPSession.m:101]: I was testing with the Swift example app using your branch. The crash occurred when I pulled the USB cord. I was testing with an iPhone 11 (iOS v.132.1). The crash only happened twice during ~30 disconnect tests. 

It was crashing at `[stream close]` both times. When I looked at the stack trace, I could see that the main thread was executing `[stream close]`. I traced it back to getting the accessory disconnect notification. 

I did notice while testing that sometimes `[stream close]` was triggered by the stream getting an `NSStreamEventEndEncountered` event and other times by the accessory disconnect notification. Sometimes both threads were trying to close the stream. It could be that the crash was related to both threads trying to close the stream at the same time? However I suspect that it is more likely that the the stream was being closed by a thread that does not own the stream (i.e. the main thread).

Comment (makinney) [reply SmartDeviceLink/private/SDLIAPSession.m:101]: I have a fix that ensures sessions are always closed on the sessions thread.  However there is an issue pushing the commit from my backup Mac. I am working on resolving this now.

Comment (kmicha19-ford) [reply SmartDeviceLink/private/SDLIAPSession.m:103]: @NicoleYarroch - I pushed a fix for close session.   Review appreciated.

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
I mostly made some style formatting suggestions. Namely, private methods in the implementation files are prefixed by "sdl_". I tried to find most of them but I may have missed a few. 

I did experience a crash on disconnect that should be a pretty easy fix.

I haven't had the chance yet to thoroughly test secondary transports and switching between BT and USB transports but testing the multisession and control protocols worked well.

**Comment by kmicha19-ford** [comment]
Thanks Nicole,

I have been without a work computer all week. Going into Dearborn today to get it fixed or replaced.  I will look at what you have here in detail by Monday if not by EOD today.

Mike
________________________________

**Comment by kmicha19-ford** [comment]
Just commited changes based on PR comments.  These include the following.  
prefixing all private methods with 'sdl_'
removed blank space from beginning of method names
removed extraneous semicolons
moved one public method up that was in the marked as private section
Note, not sure about when to you want to use SDLLogD, SDLLogV or even SDLLogE

File: SmartDeviceLink/private/SDLIAPDataSession.m [hunk 2]
```diff
@@ -6,370 +6,144 @@
...
+    if (remainder != nil) {
+        NSUInteger bytesRemaining = remainder.length;
+  //      SDLLogD(@"SDLIAPDataSession sending data for IAPSession %@.", self.iapSession);
+        [self.iapSession write:remainder length:bytesRemaining withCompletionHandler:^(NSInteger bytesWritten) {
+            if (bytesWritten == bytesRemaining) {
+                [self.sendDataQueue popBuffer];
+            } else {
+                // Cleave the sent bytes from the data, the remainder will sit at the head of the queue
+                // SDLLogD(@"SDLIAPDataSession writeDataToSessionStream bytes written %ld", (long)bytesWritten);
+                [remainder replaceBytesInRange:NSMakeRange(0, (NSUInteger)bytesWritten) withBytes:NULL length:0];
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/private/SDLIAPDataSession.m:65]: @kmicha19-ford, were you able to fix this crash that I found? That was the major issue I wanted to get fix before I continued testing.

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
I think a few things were missed from my last review. Can you tag me when you have a fix for the crash I noted in the last review? Thanks!

File: SmartDeviceLink/private/SDLIAPDataSession.h [hunk 3]
```diff
@@ -7,18 +7,32 @@
...
+
+/**
+ *  The unique ID assigned to the session between the app and accessory. If no session exists the value will be 0.
+ */
+@property (assign, nonatomic, readonly) NSUInteger connectionID;
+
+/**
+ *  The accessory with which to open a session.
+ */
+@property (nullable, strong, nonatomic, readonly) EAAccessory *accessory;
```
[the remark this answers is not in the document]
Comment (kmicha19-ford) [reply SmartDeviceLink/private/SDLIAPDataSession.h:35]: The suggest change looks the same as the original?

File: SmartDeviceLink/private/SDLIAPTransport.m [hunk 4]
```diff
@@ -224,9 +232,18 @@ - (void)disconnectWithCompletionHandler:(void (^)(void))disconnectCompletionHand
...
 
+- (EAAccessory * _Nullable)accessory {
+    if (self.controlSession.accessory != nil) {
+        return self.controlSession.accessory;
+    }
+    if (self.dataSession.accessory != nil) {
+        return self.dataSession.accessory;
+    }
+    return nil;
+}
```
[the remark this answers is not in the document]
Comment (kmicha19-ford) [reply SmartDeviceLink/private/SDLIAPTransport.m:246]: Removed.  We use this in our SDL with OEM extensions to support so called marketplace apps.

**Comment by kmicha19-ford** [comment]
I reviewed comments and made multiple updates for style requirements and also removed an used function.  Hopefully I have everything this time.

File: SmartDeviceLink/private/SDLIAPDataSession.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/private/SDLIAPDataSession.h:34]: Sorry. Must have been a copy and paste error

File: SmartDeviceLink/private/SDLIAPDataSession.m [hunk 5]
```diff
@@ -7,369 +7,146 @@
...
 }
 
-// Must be called on accessoryEventLoop.
-- (void)sdl_closeSession {
-    if (self.eaSession == nil) {
-        return;
-    }
-
-    SDLLogD(@"Closing EASession for accessory connection id: %tu, name: %@", self.connectionID, self.eaSession.accessory.name);
+#pragma mark Otherd
```
Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLIAPDataSession.m:134]:
```suggestion
#pragma mark Getters
```

File: SmartDeviceLink/private/SDLIAPTransport.m [hunk 6]
```diff
@@ -370,7 +376,7 @@ - (void)dataSessionDidReceiveData:(nonnull NSData *)data {
 /**
  *  Called when the data session should be retried.
  */
-- (void)dataSessionShouldRetry {
+- (void)dataSessionDidEnd{
```
Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLIAPTransport.m:379]:
```suggestion
- (void)dataSessionDidEnd {
```

File: SmartDeviceLink/private/SDLIAPControlSession.m [hunk 7]
```diff
@@ -22,206 +22,94 @@
...
-    self = [super initWithAccessory:accessory forProtocol:ControlProtocolString];
-    if (!self) { return nil; }
-
+- (instancetype)initWithAccessory:(nullable EAAccessory *)accessory delegate:(id<SDLIAPControlSessionDelegate>)delegate forProtocol:(NSString *)protocol {
+    SDLLogD(@"SDLIAPControlSession init with protocol %@ and accessory %@", protocol, accessory);
+    self = [super init];
+    _iapSession = [[SDLIAPSession alloc] initWithAccessory:accessory forProtocol:protocol iAPSessionDelegate:self];
     _protocolIndexTimer = nil;
     _delegate = delegate;
+    SDLLogD(@"SDLIAPControlSession Wait for the protocol string from Core, setting timeout timer for %d seconds", ProtocolIndexTimeoutSeconds);
```
Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLIAPControlSession.m:40]:
```suggestion
    SDLLogD(@"SDLIAPControlSession Waiting for the protocol string from Core, setting timeout timer for %d seconds", ProtocolIndexTimeoutSeconds);
```

**Review by NicoleYarroch — COMMENTED** [review]
I found a few minor things to fix. A couple of comments from my previous reveiw were missed on the SDLIAPDataSession.m file.

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
I found a few minor spacing issues - otherwise testing went well

**Review by NicoleYarroch — APPROVED** [review]
