### PR TITLE
Fix to deprecate SDLDisplayCapabilities

### LINKED ISSUE #1857: Deprecate 'DisplayCapabilities'
### Bug Report
We should deprecate `DisplayCapabilities` and point users to using the `SystemCapabilityManager` in its place and also then suppress warnings in the `SystemCapabilityManager`.

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: 7.1.0
* Testing Against: N/A

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1857 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Deprecate DisplayCapabilities and point users to using the SystemCapabilityManager and suppress warnings.

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Deprecate DisplayCapabilities and point users to using the SystemCapabilityManager and suppress warnings.

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/public/SDLDisplayCapabilities.h [hunk 1]
```diff
@@ -17,7 +17,7 @@
  */
 
 NS_ASSUME_NONNULL_BEGIN
-
+__deprecated_msg("Use the displayCapabilities property in SDLSystemCapabilityManager instead.")
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLDisplayCapabilities.h:20]:
```suggestion
__deprecated_msg("Use SDLSystemCapabilityManager.defaultMainWindowCapability instead")
```

**Review by joeljfischer — APPROVED** [review]

**Review by joeljfischer — CHANGES_REQUESTED** [review]
See above comment

**Review by joeljfischer — APPROVED** [review]
