### PR TITLE
deprecate autoCompleteText property in SDLKeyboardProperties

### LINKED ISSUE #1784: The autoCompleteText property in SDLKeyboardProperties should be deprecated
### Bug Report
Since the `autoCompleteText` property in `SDLKeyboardProperties` was deprecated in [RPC spec v.6.0](https://github.com/smartdevicelink/rpc_spec/blob/53e3dfb3cd7ff75a3425312ae4aeb758a1e0fc51/MOBILE_API.xml#L2572), it should be deprecated in the library. There should also be an init that sets all non-deprecated properties. 

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.7
* Testing Against:  n/a

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1784 

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Changed tests to support newer init function that doesn't support autoCompleteText property.

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Deprecated autoCompleteText property in SDLKeyboardProperties

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Deprecated autoCompleteText property in SDLKeyboardProperties

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/public/SDLKeyboardProperties.h [hunk 1]
```diff
@@ -58,11 +68,16 @@ NS_ASSUME_NONNULL_BEGIN
...
- Optional
+ * Deprecated, use autoCompleteList instead.
+ * {"string_min_length": 1, "string_max_length": 1000}
+ *
+ * @deprecated in SmartDeviceLink 6.0.0
+ * @added in SmartDeviceLink 3.0.0
  */
-@property (nullable, strong, nonatomic) NSString *autoCompleteText;
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
```
Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLKeyboardProperties.h:78]: We can remove the ` #pragma clang diagnostic push/pop` as it is unneeded

File: SmartDeviceLink/public/SDLKeyboardProperties.h [hunk 2]
```diff
@@ -25,7 +25,17 @@ NS_ASSUME_NONNULL_BEGIN
...
+- (instancetype)initWithLanguage:(nullable SDLLanguage)language layout:(nullable SDLKeyboardLayout)layout keypressMode:(nullable SDLKeypressMode)keypressMode limitedCharacterList:(nullable NSArray<NSString *> *)limitedCharacterList autoCompleteText:(nullable NSString *)autoCompleteText autoCompleteList:(nullable NSArray<NSString *> *)autoCompleteList __deprecated_msg("Use initWithLanguage:keyboardLayout:keypressMode:limitedCharacterList:autoCompleteList: instead");
+
+/**
+ * @param language - language
+ * @param keyboardLayout - keyboardLayout
+ * @param keypressMode - keypressMode
+ * @param limitedCharacterList - limitedCharacterList
+ * @param autoCompleteList - autoCompleteList
+ * @return A SDLKeyboardProperties object
+ */
```
Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLKeyboardProperties.h:37]:
```suggestion
/**
 * Convenience init with all parameters.
 *
 * @param language - language
 * @param keyboardLayout - keyboardLayout
 * @param keypressMode - keypressMode
 * @param limitedCharacterList - limitedCharacterList
 * @param autoCompleteList - autoCompleteList
 * @return A SDLKeyboardProperties object
 */
```

File: SmartDeviceLink/public/SDLKeyboardProperties.m [hunk 3]
```diff
@@ -11,16 +11,19 @@
 @implementation SDLKeyboardProperties
 
 - (instancetype)initWithLanguage:(nullable SDLLanguage)language layout:(nullable SDLKeyboardLayout)layout keypressMode:(nullable SDLKeypressMode)keypressMode limitedCharacterList:(nullable NSArray<NSString *> *)limitedCharacterList autoCompleteText:(nullable NSString *)autoCompleteText autoCompleteList:(nullable NSArray<NSString *> *)autoCompleteList {
+    return [self initWithLanguage:language keyboardLayout:layout keypressMode:keypressMode limitedCharacterList:limitedCharacterList autoCompleteList:autoCompleteList];
```
Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLKeyboardProperties.m:14]: `autoCompleteList` did not get set in this init.

File: SmartDeviceLink/public/SDLKeyboardProperties.m [hunk 4]
```diff
@@ -58,11 +61,17 @@ - (void)setLimitedCharacterList:(nullable NSArray<NSString *> *)limitedCharacter
     return [self.store sdl_objectsForName:SDLRPCParameterNameLimitedCharacterList ofClass:NSString.class error:nil];
 }
 
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
```
Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLKeyboardProperties.m:65]: We can remove the ` #pragma clang diagnostic push/pop` as it is unneeded

File: SmartDeviceLink/public/SDLKeyboardProperties.m [hunk 5]
```diff
@@ -58,11 +61,17 @@ - (void)setLimitedCharacterList:(nullable NSArray<NSString *> *)limitedCharacter
...
 - (void)setAutoCompleteText:(nullable NSString *)autoCompleteText {
+#pragma clang diagnostic pop
     [self.store sdl_setObject:autoCompleteText forName:SDLRPCParameterNameAutoCompleteText];
 }
 
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
```
Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLKeyboardProperties.m:72]: We can remove the ` #pragma clang diagnostic push/pop` as it is unneeded.

File: SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLKeyboardPropertiesSpec.m [hunk 6]
```diff
@@ -57,18 +54,31 @@
...
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
         SDLKeyboardProperties *testStruct = [[SDLKeyboardProperties alloc] initWithLanguage:testLanguage layout:testLayout keypressMode:testMode limitedCharacterList:testLimitedCharacterList autoCompleteText:testAutoCompleteText autoCompleteList:testAutoCompleteList];
+#pragma clang diagnostic pop
+        expect(testStruct.language).to(equal(testLanguage));
+        expect(testStruct.keyboardLayout).to(equal(testLayout));
+        expect(testStruct.keypressMode).to(equal(testMode));
+        expect(testStruct.limitedCharacterList).to(equal(testLimitedCharacterList));
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
+        expect(testStruct.autoCompleteText).to(beNil());
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLKeyboardPropertiesSpec.m:71]: You should still be able to set `autoCompleteText` using this init.

File: SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLKeyboardPropertiesSpec.m [hunk 7]
```diff
@@ -32,14 +32,12 @@
         testStruct.keyboardLayout = testLayout;
         testStruct.keypressMode = testMode;
         testStruct.limitedCharacterList = testLimitedCharacterList;
-        testStruct.autoCompleteText = testAutoCompleteText;
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLKeyboardPropertiesSpec.m:35]: All the tests for `autoCompleteText` should be added back. We are marking `autoCompleteText` as deprecated but developers should still be able to use it (i.e. developers will still need to use `autoCompleteText` when connecting to older modules).

File: SmartDeviceLink/public/SDLKeyboardProperties.h [hunk 8]
```diff
@@ -58,11 +68,16 @@ NS_ASSUME_NONNULL_BEGIN
...
+ * Deprecated, use autoCompleteList instead.
+ * {"string_min_length": 1, "string_max_length": 1000}
+ *
+ * @deprecated in SmartDeviceLink 6.0.0
+ * @added in SmartDeviceLink 3.0.0
  */
-@property (nullable, strong, nonatomic) NSString *autoCompleteText;
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
+@property (nullable, strong, nonatomic) NSString *autoCompleteText __deprecated;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLKeyboardProperties.h:79]:
```suggestion
@property (nullable, strong, nonatomic) NSString *autoCompleteText __deprecated_msg("Use autoCompleteList instead");
```

Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLKeyboardProperties.h:79]: There are several places in the library where the deprecated `autoCompleteText` or deprecated `init` are used. If the new `init` can be used, the code should be updated to use the new init. Otherwise the old init needs to be wrapped with `#pragma clang diagnostic push/pop`. Anywhere that `autoCompleteText` is set should get wrapped with `#pragma clang diagnostic push/pop`. Using `#pragma clang diagnostic push/pop` will suppress the warning messages.

You should be able to see the warnings in the sidebar after building the library (To show the Issue Navigator open **View > Navigators > Issues**)

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
I left some comments.

File: SmartDeviceLink/public/SDLKeyboardProperties.m (hunk 3 above)
Comment (FrankElias77) [reply SmartDeviceLink/public/SDLKeyboardProperties.m:14]: autoCompleteText instead

File: SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLKeyboardPropertiesSpec.m (hunk 7 above)
Comment (NicoleYarroch) [reply SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLKeyboardPropertiesSpec.m:35]: All the tests for `autoCompleteText` still need to be added back

File: SmartDeviceLink/public/SDLKeyboardProperties.m [hunk 9]
```diff
@@ -11,16 +11,21 @@
 @implementation SDLKeyboardProperties
 
 - (instancetype)initWithLanguage:(nullable SDLLanguage)language layout:(nullable SDLKeyboardLayout)layout keypressMode:(nullable SDLKeypressMode)keypressMode limitedCharacterList:(nullable NSArray<NSString *> *)limitedCharacterList autoCompleteText:(nullable NSString *)autoCompleteText autoCompleteList:(nullable NSArray<NSString *> *)autoCompleteList {
+    SDLKeyboardProperties *keyboardProperties = [[SDLKeyboardProperties alloc] initWithLanguage:language keyboardLayout:layout keypressMode:keypressMode limitedCharacterList:limitedCharacterList autoCompleteList:autoCompleteList];
+    keyboardProperties.autoCompleteText = autoCompleteText;
+    return keyboardProperties;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLKeyboardProperties.m:16]:
```suggestion
    self = [[self init] initWithLanguage:language keyboardLayout:layout keypressMode:keypressMode limitedCharacterList:limitedCharacterList autoCompleteList:autoCompleteList];
    if (!self) { return nil; }

    self.autoCompleteText = autoCompleteText;
    
    return self;
```

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
I left a couple comments

File: SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLKeyboardPropertiesSpec.m [hunk 10]
```diff
@@ -33,28 +33,41 @@
         testStruct.keypressMode = testMode;
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLKeyboardPropertiesSpec.m:33]: One last thing, the last two tests should check if `autoCompleteText` has been set to `nil`.

```
it(@"Should get correctly when initialized with initWithLanguage:keyboardLayout:keypressMode:limitedCharacterList:autoCompleteList:", ^ {
    SDLKeyboardProperties *testStruct = [[SDLKeyboardProperties alloc] initWithLanguage:testLanguage keyboardLayout:testLayout keypressMode:testMode limitedCharacterList:testLimitedCharacterList autoCompleteList:testAutoCompleteList];
    expect(testStruct.language).to(equal(testLanguage));
    expect(testStruct.keyboardLayout).to(equal(testLayout));
    expect(testStruct.keypressMode).to(equal(testMode));
    expect(testStruct.limitedCharacterList).to(equal(testLimitedCharacterList));
    expect(testStruct.autoCompleteList).to(equal(testAutoCompleteList));
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
    expect(testStruct.autoCompleteText).to(beNil());
#pragma clang diagnostic pop
});

it(@"Should return nil if not set", ^ {
    SDLKeyboardProperties* testStruct = [[SDLKeyboardProperties alloc] init];
    
    expect(testStruct.language).to(beNil());
    expect(testStruct.keyboardLayout).to(beNil());
    expect(testStruct.keypressMode).to(beNil());
    expect(testStruct.limitedCharacterList).to(beNil());
    expect(testStruct.autoCompleteList).to(beNil());
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
    expect(testStruct.autoCompleteText).to(beNil());
#pragma clang diagnostic pop
});
```

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
A couple of tests are missing in `SDLKeyboardPropertiesSpec`

**Review by NicoleYarroch — APPROVED** [review]
