### PR TITLE
Fix SDLStreamingMediaManager private classes should not be public properties / methods

### LINKED ISSUE #1627: SDLStreamingMediaManager secondaryTransport property should be hidden
### Bug Report
`SDLSecondaryTransportManager` is a private class, but there's a public property on the public class `SDLStreamingMediaManager`. We should hide it. We also have a public method `startSecondaryTransportWithProtocol:` that takes an `SDLProtocol`, which is a private class. That should be hidden as well.

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1627 

This PR is **ready** for review.

### Risk
This PR makes **major** API changes. These changes are internal to this release

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit tests were run and fixed

#### Core Tests
No core tests were done because no logic was changed.

Core version / branch / commit hash / module tested against: n/a
HMI name / version / branch / commit hash / module tested against: n/a

### Summary
This PR fixes private classes being exposed through public properties on `SDLStreamingMediaManager`.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLImageField.h [hunk 1]
```diff
@@ -40,7 +40,7 @@ NS_ASSUME_NONNULL_BEGIN
 /// @param name The name identifying this image field
 /// @param imageTypeSupported The image data types this field supports
 /// @param imageResolution The native resolution of this image field
-- (instancetype)initWithName:(SDLImageFieldName)name imageTypeSupported:(NSArray<SDLFileType> *)imageTypeSupported imageResolution:(SDLImageResolution *)imageResolution;
+- (instancetype)initWithName:(SDLImageFieldName)name imageTypeSupported:(NSArray<SDLFileType> *)imageTypeSupported imageResolution:(nullable SDLImageResolution *)imageResolution;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLImageField.h:43]: This change was done in another PR

File: SmartDeviceLink/SDLImageField.m [hunk 2]
```diff
@@ -38,7 +38,7 @@ - (nullable SDLImageResolution *)imageResolution {
     return [self.store sdl_objectForName:SDLRPCParameterNameImageResolution ofClass:SDLImageResolution.class error:nil];
 }
 
-- (instancetype)initWithName:(SDLImageFieldName)name imageTypeSupported:(NSArray<SDLFileType> *)imageTypeSupported imageResolution:(SDLImageResolution *)imageResolution {
+- (instancetype)initWithName:(SDLImageFieldName)name imageTypeSupported:(NSArray<SDLFileType> *)imageTypeSupported imageResolution:(nullable SDLImageResolution *)imageResolution {
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLImageField.m:41]: This change was done in another PR
