### PR TITLE
Fixed SDL App Crash - index out of range in replaceBytesInRange

### LINKED ISSUE #2112: SDL App Crash
### Bug Summary

Hundreds of crashes have been reported by devices. It is unclear what steps are producing the crash beyond connecting to a vehicle.

Device Details: 
62% iOS 15 and 36% iOS 16
100% background

The stack trace from crashlytics has been attached.

 There was a previous crash also with this version of SDL but it is unclear of the two crashes are related. 
Previously a crash was seen due to SDL Assertions where it returned the following message. This was fixed by disabling assertions int he log build.
`SDL ASSERTION: Retrieving object from store error: Requested NSArray but returned NSTaggedPointerString, for object key: "speechCapabilities"`

### Reproduction Steps

1. Connect device with LiveOne on a Ford vehicle. 

Expected Behavior: App should not crash

Observed Behavior: App crashes

### iOS Version(s)

15.6.1

### sdl_ios Version

7.5.0

### Testing Environment(s)

```markdown
FORD ESCAPE SYNC 3.0.20204_PRODUCT
```

### Relevant log output

```shell
Fatal Exception: NSRangeException
*** -[NSConcreteMutableData replaceBytesInRange:withBytes:length:]: range {0, 8180} exceeds data length 43

Fatal Exception: NSRangeException
0  CoreFoundation                 0x99288 __exceptionPreprocess
1  libobjc.A.dylib                0x16744 objc_exception_throw
2  Foundation                     0x8825c allocateStorageWithSentinel
3  Slacker                        0x5dfd50 -[SDLIAPSession write:length:withCompletionHandler:] + 64 (SDLIAPSession.m:64)
4  Slacker                        0x5df148 -[SDLIAPDataSession writeDataToSessionStream] + 57 (SDLIAPDataSession.m:57)
5  Slacker                        0x5e0868 -[SDLIAPSession sdl_streamHasSpaceToWrite] + 222 (SDLIAPSession.m:222)
6  Slacker                        0x5e0660 -[SDLIAPSession stream:handleEvent:] + 170 (SDLIAPSession.m:170)
7  ExternalAccessory              0xa3a8 -[EAOutputStream _streamEventTrigger]
8  CoreFoundation                 0x11ff14 __CFSocketPerformV0
9  CoreFoundation                 0xbb414 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
10 CoreFoundation                 0xcc1a0 __CFRunLoopDoSource0
11 CoreFoundation                 0x5694 __CFRunLoopDoSources0
12 CoreFoundation                 0xb05c __CFRunLoopRun
13 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific
14 Foundation                     0x19444 -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
15 Slacker                        0x5e0588 -[SDLIAPSession sdl_startStreamRunLoop] + 142 (SDLIAPSession.m:142)
16 libdispatch.dylib              0x1e6c _dispatch_call_block_and_release
17 libdispatch.dylib              0x3a30 _dispatch_client_callout
18 libdispatch.dylib              0xb124 _dispatch_lane_serial_drain
19 libdispatch.dylib              0xbc80 _dispatch_lane_invoke
20 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread
21 libsystem_pthread.dylib        0x10bc _pthread_wqthread
22 libsystem_pthread.dylib        0xe5c start_wqthread
```

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #2112 

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
Run these changes with the example navigation app test app and forced this crash into occurinng.

Core version / branch / commit hash / module tested against: 8.2.0 | WorkBench
HMI name / version / branch / commit hash / module tested against: generic_hmi 0.13 | Workbench

### Summary
Add safety blocks on the unsent bytes process to avoid crashes

##### Breaking Changes
- Implemented an alternative for `replaceBytesInRange:` func.
- Added try/catch to wrap the exception

##### Enhancements
* N/A

##### Bug Fixes
* N/A

### Tasks Remaining:
- [x] Retest on workbench

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by jshivabeharry** [comment]
Approved for Sync 3. Will need to test on Monday for Sync 4.

File: SmartDeviceLink/private/SDLIAPDataSession.m [hunk 1]
```diff
@@ -58,10 +58,24 @@ - (void)writeDataToSessionStream {
...
                 if (bytesWritten == bytesRemaining) {
                     [self.sendDataQueue popBuffer];
-                } else if (bytesRemaining > bytesWritten) {
+                } else if (bytesRemaining > bytesWritten && remainder.length > bytesWritten) {
                     // Cleave the sent bytes from the data, the remainder will sit at the head of the queue
-                    SDLLogV(@"SDLIAPDataSession writeDataToSessionStream bytes written %ld", (long)bytesWritten);
-                    [remainder replaceBytesInRange:NSMakeRange(0, (NSUInteger)bytesWritten) withBytes:NULL length:0];
+                    @try {
+                        SDLLogV(@"SDLIAPDataSession writeDataToSessionStream bytes written %ld", (long)bytesWritten);
+                        NSData *rem = [remainder subdataWithRange:NSMakeRange((NSUInteger)bytesWritten, remainder.length - 1)];
```
Comment (jshivabeharry) [inline SmartDeviceLink/private/SDLIAPDataSession.m:65]:
```suggestion
                        NSData *rem = [remainder subdataWithRange:NSMakeRange((NSUInteger)bytesWritten, remainder.length - (NSUInteger)bytesWritten)];
```
The second parameter for `NSMakeRange` is the length of the range, not its position. Right now it will fail the initial block because it tries creates a range that exceeds the length of the data and thus will force it into the `replaceBytesInRange` block.

**Review by jshivabeharry — CHANGES_REQUESTED** [review]

**Review by jshivabeharry — APPROVED** [review]
