### PR TITLE
Fixed the lock screen configuration's show in optional state

### LINKED ISSUE #1070: The lock screen configuration's `showInOptionalState` does not work as expected
The lock screen configuration's `showInOptionalState` does not keep the lock screen visible when set to `true`.

### Bug Report
If the lock screen configuration was init'd with the `enabled` configuration and then the `showInOptionalState` is set to `true`, the lock screen should be present, even when the car is stationary. Instead the lock screen behaves the same as the `enabled` configuration.

Line 140 in the `sdl_checkLockScreen` function of the SDLLockScreenManager might need to be changed to 
```
} else if (self.presenter.presented && !self.config.showInOptionalState) {
```

##### Reproduction Steps
1. Set app's lock screen configuration to `enabled` and then set `showInOptionalState` to `true`.
1. Connect the app to a head unit while the head unit is "stationary"

##### Expected Behavior
The lock screen should show and not be dismissed.

##### Observed Behavior
The lock screen is shown, but immediately dismissed. 

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.0.2
* Testing Against: SDL_iOS example app and TDK

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #1070

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Test cases added to _SDLLockScreenManagerSpec_ to test the `SDLLockScreenStatusOptional` state.

### Summary
If the lock screen configuration's `showInOptionalState` is set to true, the lock screen is now not dismissed when the app is in the "lock screen optional" state.

##### Enhancements
* The lock screen configuration's `showInOptionalState` now works as expected.

### Tasks Remaining:
- [x] Test enabled state with `showInOptionalState` set to true with Manticore and SYNC3
- [x] Test enabled state with `showInOptionalState` set to false with Manticore and SYNC3

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLLockScreenManager.m [hunk 1]
```diff
@@ -147,6 +150,53 @@ - (void)sdl_checkLockScreen {
...
+ *  1. The app should have received at least 1 driver distraction notification (i.e. a `OnDriverDistraction` notification) from SDL Core. Older versions of Core did not send a notification immediately on connection.
+ *  2. The driver is not distracted (i.e. the last `OnDriverDistraction` notification received was for a driver distraction state off).
+ *  3. The `hmiLevel` can not be `NONE`.
+ *  4. If the `hmiLevel` is currently `BACKGROUND` then the previous `hmiLevel` should have been `FULL` or `LIMITED` (i.e. the user should have interacted with app before it was backgrounded).
+ *
+ *  @param lockScreenStatus The most recent lock screen status received from SDL Core
+ *  @param previousHMILevel The previous `hmiLevel`
+ *  @return                 True if currently if the "lock screen optional" state; false if not
+ */
++ (BOOL)sdl_inLockScreenOptionalStateForLockScreenStatus:(nullable SDLOnLockScreenStatus *)lockScreenStatus previousHMILevel:(nullable SDLHMILevel)previousHMILevel {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLockScreenManager.m]: Much of this logic already exists in `SDLLockScreenStatusManager`.

Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLockScreenManager.m]: Should be fixed.
