### PR TITLE
Fix for button event notification

### LINKED ISSUE #1793: SYNC 3.0 bug with button event notifications
### Bug Report
The screen manager assigns a unique `softButtonID` to each soft button in the `Show` request starting with zero. However, it appears that on SYNC 3.0 the module will not send `OnButtonEvent` notifications when the soft button is selected if the `softButtonID` is zero. It will send the `OnButtonPress` notification. 

When I configured the screen manager to set the first `softButtonID` to 100, I received the `OnButtonEvent` notifications. A workaround for this bug might be to start setting the `softButtonID`s at 1 instead of 0. 

##### Reproduction Steps
1. Use the screen manager to set two soft buttons.
2. Connect to the SYNC 3.0 module using an iAP (USB) connection. 
3. Select the left-most soft button on the HMI (i.e. the button with `softButtonID` set to zero)

##### Expected Behavior
When the button is selected the module should send two `OnButtonEvent` notifications and one `OnButtonPress` notification. 

```
OnButtonEvent (notification)
{
    buttonEventMode = BUTTONDOWN;
    buttonName = "CUSTOM_BUTTON";
    customButtonID = 0;
}

OnButtonEvent (notification)
{
    buttonEventMode = BUTTONUP;
    buttonName = "CUSTOM_BUTTON";
    customButtonID = 0;
}

OnButtonPress (notification)
{
    buttonName = "CUSTOM_BUTTON";
    buttonPressMode = SHORT;
    customButtonID = 0;
}
```

##### Observed Behavior
When the button is selected the module only sends the `OnButtonPress` notification. 
```
OnButtonPress (notification)
{
    buttonName = "CUSTOM_BUTTON";
    buttonPressMode = SHORT;
    customButtonID = 0;
}
```

##### OS & Version Information
* iOS Version: 14.0
* SDL iOS Version: 7.0
* Testing Against: SYNC 3.0 (BUILD 17276_DEVTEST)

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1793 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: SYNC 3.0

### Summary
Increment the initial ID in order to receive OnButtonEvent notification

##### Breaking Changes
* N/a

##### Enhancements
* N/A

##### Bug Fixes
* Increment the initial ID in order to receive OnButtonEvent notification

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLSoftButtonManager.m [hunk 1]
```diff
@@ -125,7 +125,7 @@ - (void)setSoftButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects
     // Set the soft button ids. Check to make sure no two soft buttons have the same name, there aren't many soft buttons, so n^2 isn't going to be bad
     for (NSUInteger i = 0; i < softButtonObjects.count; i++) {
         NSString *buttonName = softButtonObjects[i].name;
-        softButtonObjects[i].buttonId = i * 100;
+        softButtonObjects[i].buttonId = (i * 100) ? (i * 100) : (i + 1);
```
Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLSoftButtonManager.m:128]:
```suggestion
       // HAX: Due to a SYNC 3.0 bug (https://github.com/smartdevicelink/sdl_ios/issues/1793#issue-708356008), a `buttonId` can not be zero. As a workaround we will start the `buttonId`s from 1.
        softButtonObjects[i].buttonId = (i * 100) ? (i * 100) : (i + 1);
```

Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLSoftButtonManager.m:128]: I have no idea why the code increments the `buttonId`s by 100. There is no reason for doing so as far as I can tell. We could probably get away with just doing
`softButtonObjects[i].buttonId = i + 1`;

Comment (NicoleYarroch) [reply SmartDeviceLink/private/SDLSoftButtonManager.m:128]: Also, If we start the `buttonId`s from `1` we will have to update the "ok" `buttonId` in the Swift and Obj-C example apps alert. If you click on the right most button in both example apps you will see that the alert keeps reappearing. This is due to the "ok" `buttonId` being set to `1`.

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
Left some comments

File: SmartDeviceLink/private/SDLSoftButtonManager.m (hunk 1 above)
Comment (FrankElias77) [reply SmartDeviceLink/private/SDLSoftButtonManager.m:128]: I thought of replacing the first index with 1, in case the *100 in other indexes affects other things. But sure i can increment the index as suggested.

**Review by joeljfischer — APPROVED** [review]

File: SmartDeviceLink/private/SDLSoftButtonManager.m (hunk 1 above)
Comment (joeljfischer) [reply SmartDeviceLink/private/SDLSoftButtonManager.m]: @FrankElias77 This still needs to be fixed

**Review by joeljfischer — CHANGES_REQUESTED** [review]
See Nicole's comment above

File: Example Apps/Example ObjC/AlertManager.m [hunk 2]
```diff
@@ -15,7 +15,7 @@
 @implementation AlertManager
 
 + (void)sendAlertWithManager:(SDLManager *)sdlManager image:(nullable NSString *)imageName textField1:(NSString *)textField1 textField2:(nullable NSString *)textField2 {
-    SDLSoftButton *okSoftButton = [[SDLSoftButton alloc] initWithType:SDLSoftButtonTypeText text:AlertOKButtonText image:nil highlighted:YES buttonId:1 systemAction:nil handler:nil];
+    SDLSoftButton *okSoftButton = [[SDLSoftButton alloc] initWithType:SDLSoftButtonTypeText text:AlertOKButtonText image:nil highlighted:YES buttonId:2 systemAction:nil handler:nil];
```
Comment (joeljfischer) [inline Example Apps/Example ObjC/AlertManager.m:18]:
```suggestion
    SDLSoftButton *okSoftButton = [[SDLSoftButton alloc] initWithType:SDLSoftButtonTypeText text:AlertOKButtonText image:nil highlighted:YES buttonId:10000 systemAction:nil handler:nil];
```

This will still fail if there are two other soft buttons on the screen (like the example apps have)

File: Example Apps/Example Swift/AlertManager.swift [hunk 3]
```diff
@@ -17,7 +17,7 @@ class AlertManager {
     ///   - textField2: The second line of text in the alert
     ///   - sdlManager: The SDLManager
     class func sendAlert(imageName: String? = nil, textField1: String, textField2: String? = nil, sdlManager: SDLManager) {
-        let okSoftButton = SDLSoftButton(type: .text, text: AlertOKButtonText, image: nil, highlighted: true, buttonId: 1, systemAction: nil, handler: nil)
+        let okSoftButton = SDLSoftButton(type: .text, text: AlertOKButtonText, image: nil, highlighted: true, buttonId: 2, systemAction: nil, handler: nil)
```
Comment (joeljfischer) [inline Example Apps/Example Swift/AlertManager.swift:20]:
```suggestion
        let okSoftButton = SDLSoftButton(type: .text, text: AlertOKButtonText, image: nil, highlighted: true, buttonId: 10000, systemAction: nil, handler: nil)
```

File: SmartDeviceLink/private/SDLSoftButtonManager.m [hunk 4]
```diff
@@ -125,7 +125,8 @@ - (void)setSoftButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects
     // Set the soft button ids. Check to make sure no two soft buttons have the same name, there aren't many soft buttons, so n^2 isn't going to be bad
     for (NSUInteger i = 0; i < softButtonObjects.count; i++) {
         NSString *buttonName = softButtonObjects[i].name;
-        softButtonObjects[i].buttonId = i * 100;
+        // HAX: Due to a SYNC 3.0 bug (https://github.com/smartdevicelink/sdl_ios/issues/1793#issue-708356008), a `buttonId` can not be zero. As a workaround we will start the `buttonId`s from 1.
+        softButtonObjects[i].buttonId = (i + 1);
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLSoftButtonManager.m:129]: We should institute a rollover max button id cap here of 1000

File: SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonManagerSpec.m [hunk 5]
```diff
@@ -172,8 +172,8 @@ - (void)sdl_displayCapabilityDidUpdate:(SDLSystemCapability *)systemCapability;
 
         it(@"should set soft buttons correctly", ^{
             expect(testManager.softButtonObjects).toNot(beNil());
-            expect(testObject1.buttonId).to(equal(0));
-            expect(testObject2.buttonId).to(equal(100));
+            expect(testObject1.buttonId).to(equal(1));
+            expect(testObject2.buttonId).to(equal(2));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonManagerSpec.m:176]: This will need to be fixed

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLSoftButtonManager.m [hunk 6]
```diff
@@ -123,16 +123,22 @@ - (void)setSoftButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects
...
     // Set the soft button ids. Check to make sure no two soft buttons have the same name, there aren't many soft buttons, so n^2 isn't going to be bad
+    NSUInteger buttonId = 1;
     for (NSUInteger i = 0; i < softButtonObjects.count; i++) {
         NSString *buttonName = softButtonObjects[i].name;
-        softButtonObjects[i].buttonId = i * 100;
+        // HAX: Due to a SYNC 3.0 bug (https://github.com/smartdevicelink/sdl_ios/issues/1793#issue-708356008), a `buttonId` can not be zero. As a workaround we will start the `buttonId`s from 1.
+        if (buttonId == 1001) {
+            buttonId = 1;
+        }
+        softButtonObjects[i].buttonId = buttonId;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLSoftButtonManager.m:133]:
```suggestion
        // HAX: Due to a SYNC 3.0 bug (https://github.com/smartdevicelink/sdl_ios/issues/1793#issue-708356008), a `buttonId` can not be zero. As a workaround we will start the `buttonId`s from 1.
        softButtonObjects[i].buttonId = i + 1;
```

I'm sorry, I misunderstood this code when I told you the other stuff last time. This should be fine.

File: SmartDeviceLink/private/SDLSoftButtonManager.m [hunk 7]
```diff
@@ -123,16 +123,22 @@ - (void)setSoftButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects
...
         for (NSUInteger j = (i + 1); j < softButtonObjects.count; j++) {
             if ([softButtonObjects[j].name isEqualToString:buttonName]) {
                 _softButtonObjects = @[];
                 SDLLogE(@"Attempted to set soft button objects, but two buttons had the same name: %@", softButtonObjects);
                 return;
             }
         }
+        buttonId += 1;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLSoftButtonManager.m:141]:
```suggestion
```

File: SmartDeviceLink/private/SDLSoftButtonManager.m [hunk 8]
```diff
@@ -123,16 +123,22 @@ - (void)setSoftButtonObjects:(NSArray<SDLSoftButtonObject *> *)softButtonObjects
     }
 
     // Set the soft button ids. Check to make sure no two soft buttons have the same name, there aren't many soft buttons, so n^2 isn't going to be bad
+    NSUInteger buttonId = 1;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLSoftButtonManager.m:126]:
```suggestion
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]
