### PR TITLE
Fix out of range exception and failure to cancel Asynchronous RPC Operation

### LINKED ISSUE #1076: Crash NSRangeException
### Bug Report
sdl_abortOperationWithRequest called when an operation is isCancelled but not is isFinished, and try to call progressHandler in a for-each cycle then try to get a request for the array by index is equal requests.count (out of the range).
https://github.com/smartdevicelink/sdl_ios/blob/3bb5e39e98ea18a176f1c60cfdd8284902f2c262/SmartDeviceLink/SDLAsynchronousRPCRequestOperation.m#L127

##### Reproduction Steps
1. Create SDLAsynchronousRPCRequestOperation with few requests
2. Run operation
3. Call cancel for operation before it is finished

##### Expected Behavior
No crash and progressHandler for all requests

##### Observed Behavior
Crash

##### OS & Version Information
* iOS Version: Any
* SDL iOS Version: 5.2.0 to the 6.0.2
* Testing Against: Crash

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1076

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Unit tests have been added

### Summary
Fix possible crashes in SDLAsynchronousRPCOperation on cancellation of operations.

##### Bug Fixes
* Fix possible crashes in SDLAsynchronousRPCOperation on cancellation of operations.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by mvyrko** [comment]
@joeljfischer Good to have it in 6.1.0. Thank you in advance

File: SmartDeviceLinkTests/DevAPISpecs/SDLAsynchronousRPCRequestOperationSpec.m [hunk 1]
```diff
@@ -62,6 +63,32 @@
...
+            for (int i = 0; i < 3; i++) {
+                SDLAddCommand *addCommand = [[SDLAddCommand alloc] init];
+                addCommand.correlationID = @(i);
+                [sendRequests addObject:addCommand];
+
+                testProgressResponses[addCommand.correlationID] = [[TestRequestProgressResponse alloc] initWithCorrelationId:addCommand.correlationID percentComplete:((float)(i+1)/3.0) error:nil];
+            }
+        });
+
+        fit(@"should fail correctly", ^{
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/DevAPISpecs/SDLAsynchronousRPCRequestOperationSpec.m]: Remove the focus from this test case.

Comment (joeljfischer) [reply SmartDeviceLinkTests/DevAPISpecs/SDLAsynchronousRPCRequestOperationSpec.m]: Fixed
