### PR TITLE
Throw an exception if SDL is setup before the app's root view controller

### LINKED ISSUE #1255: v6.2.1 Causes Infinite Recursion if the App's Window is Setup after SDL
### Bug Report
After the v6.2.1 lock screen fix, if an app sets up its app window _after_ it sets up SDL, it will cause infinite recursion due to the lock screen window being the only window that exists.

##### Reproduction Steps
1. Setup SDL in app delegate
2. Setup window in app delegate _after_ SDL
3. Run the app

##### Expected Behavior
App does not crash or gives explicit instruction to the developer on when to setup SDL.

##### Observed Behavior
App crashes without any way for the developer to know what's happening.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: v6.2.1
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1255 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Smoke tests performed

### Summary
Throw an exception with detailed information if the lock screen is setup before the app’s window.

##### Bug Fixes
* If SDL is setup before the app's window and root view controller, fix an infinite recursion crash by throwing our own exception with detailed information on how to fix it.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLScreenshotViewController.m [hunk 1]
```diff
@@ -30,18 +32,20 @@ - (instancetype)init {
...
 }
 
-// HAX: https://github.com/smartdevicelink/sdl_ios/issues/1250
+    // HAX: https://github.com/smartdevicelink/sdl_ios/issues/1250
 - (UIInterfaceOrientationMask)supportedInterfaceOrientations {
     UIViewController *viewController = [self sdl_topMostControllerForWindow:[UIApplication sharedApplication].windows[0]];
 
-    if (viewController != nil) {
+    if (viewController == self) {
+        @throw [NSException sdl_invalidLockscreenSetupException];
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLScreenshotViewController.m]: Why not just assert and return a default value? Isn't the orientation only an issue for navigation apps using `CarWindow`. Seems kind of pointless to crash a developer's non-navigation app for api that doesn't affect their app.
