### PR TITLE
Removed check for class type

### LINKED ISSUE #1218: Remove class check for `actualLanguage` in the `SDLLifecycleManager`
### Bug Report
Remove class check for `actualLanguage` in the `SDLLifecycleManager`. The check was added in PR #1128, but is no longer an issue with the merge of PR #1199, which verifies the type of a returned object. 

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.2
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by justingluck93**
Fixes #1218 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
Removed class check

##### Bug Fixes
No need to class check anymore 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLLifecycleManager.m [hunk 1]
```diff
@@ -333,7 +333,7 @@ - (void)didEnterStateRegistered {
     BOOL delegateCanUpdateLifecycle = [self.delegate respondsToSelector:@selector(managerShouldUpdateLifecycleToLanguage:)];
     
     // language mismatch? but actual language is a supported language? and delegate has implemented method?
-    if ([actualLanguage isKindOfClass:[NSString class]] && ![actualLanguage isEqualToEnum:desiredLanguage] && [supportedLanguages containsObject:actualLanguage] && delegateCanUpdateLifecycle) {
+    if (![actualLanguage isEqualToEnum:desiredLanguage] && [supportedLanguages containsObject:actualLanguage] && delegateCanUpdateLifecycle) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLifecycleManager.m]: Instead of checking if it's a kind of class, you'll have to check if it's `nil` instead.

File: SmartDeviceLink/SDLLifecycleManager.m [hunk 2]
```diff
@@ -344,7 +344,6 @@ - (void)didEnterStateUpdatingConfiguration {
     // we can expect that the delegate has implemented the update method and the actual language is a supported language
     SDLLanguage actualLanguage = self.registerResponse.language;
 
-    if ([actualLanguage isKindOfClass:[NSString class]]) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLifecycleManager.m]: Here also
