### PR TITLE
Fix the APT handler was removed after the response handler was called

### LINKED ISSUE #1559: Audio pass-through failed due to a timing issue.
### Bug Report
Audio pass-through failed due to a timing issue.

### Preconditions
1. Connect the head unit to the phone via BT+USB
2. The app is a VR app.

##### Reproduction Steps
1. Activate App 
2. Click PTT to start APT
3. Click PTT again immediately to stop the first APT and start the second APT

##### Expected Behavior
The second APT recording successful.

##### Observed Behavior
The second APT recording failed.

Proxy will clear `audioPassThruHandler` after sending `handler(request, response, error)` to App.
When the user clicks PTT again immediately to stop the first APT and start the second APT,
the `audioPassThruHandler` of the second APT will be cleared due to a timing issue.

Sequence:
1. Proxy sends `handler(request, response, error)` of the first APT to App.
2. App starts the second APT and creates the `APTHandler` of the second APT.
3. Proxy clears the `APTHandler`.
(Proxy should clear the `APTHandler` of the first APT, but it clears the `APTHandler` of the second APT just updated)
4. App can't use the `APTHandler` of the second APT, so the issue occurs.

I think the right sequence should be as follows：
3→1→2

SDLResponseDispatcher.m
```objc
// Called by notifications
- (void)sdl_runHandlersForResponse:(SDLRPCResponseNotification *)notification {
    if (![notification isResponseKindOfClass:[SDLRPCResponse class]]) {
        return;
    }

    __kindof SDLRPCResponse *response = notification.response;

    NSError *error = nil;
    if (![response.success boolValue]) {
        error = [NSError sdl_lifecycle_rpcErrorWithDescription:response.resultCode andReason:response.info];
    }

    // Find the appropriate request completion handler, remove the request and response handler
    SDLResponseHandler handler = self.rpcResponseHandlerMap[response.correlationID];
    SDLRPCRequest *request = self.rpcRequestDictionary[response.correlationID];
    [self.rpcRequestDictionary safeRemoveObjectForKey:response.correlationID];
    [self.rpcResponseHandlerMap safeRemoveObjectForKey:response.correlationID];

    // Run the response handler
    if (handler) {
        if (!response.success.boolValue) {
            SDLLogW(@"Request failed: %@, response: %@, error: %@", request, response, error);
        }
	handler(request, response, error); // step 1
    }

    // If we errored on the response, the delete / unsubscribe was unsuccessful
    if (error) {
        return;
    }

    // If it's a DeleteCommand, UnsubscribeButton, or PerformAudioPassThru we need to remove handlers for the corresponding RPCs
    if ([response isKindOfClass:[SDLDeleteCommandResponse class]]) {
        SDLDeleteCommand *deleteCommandRequest = (SDLDeleteCommand *)request;
        NSNumber *deleteCommandId = deleteCommandRequest.cmdID;
        [self.commandHandlerMap safeRemoveObjectForKey:deleteCommandId];
    } else if ([response isKindOfClass:[SDLUnsubscribeButtonResponse class]]) {
        SDLUnsubscribeButton *unsubscribeButtonRequest = (SDLUnsubscribeButton *)request;
        SDLButtonName unsubscribeButtonName = unsubscribeButtonRequest.buttonName;
        [self.buttonHandlerMap safeRemoveObjectForKey:unsubscribeButtonName];
    } else if ([response isKindOfClass:[SDLPerformAudioPassThruResponse class]]) {
        _audioPassThruHandler = nil; // step 2
    }
}

#pragma mark Audio Pass Thru
    
- (void)sdl_runHandlerForAudioPassThru:(SDLRPCNotificationNotification *)notification {
    SDLOnAudioPassThru *onAudioPassThruNotification = notification.notification;
    
	if (self.audioPassThruHandler) { // step 3
        self.audioPassThruHandler(onAudioPassThruNotification.bulkData);
    }
}
```
##### OS & Version Information
* iOS Version: 10.2
* SDL iOS Version: 6.4.1
* Testing Against: SDL Core 6.0.1 + HMI running on our development environment.

##### Test Case, Sample Code, and / or Example App
logs:[log_36.txt](https://github.com/smartdevicelink/sdl_ios/files/4222635/log_36.txt)

##### Occurrence:
100%

##### Recovery Method:
None

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1559

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit tests were run. New unit tests were investigated and added.

- [x] Test if the `AddCommand` handler is removed by the time the handler is called.

#### Core Tests
Tests were performed against the HU based on the reported bug.

- [x] Have a `PAPT` run from the handler of the `PAPT` to ensure that a new audio pass thru modal appears.

Core version / branch / commit hash / module tested against: Sync 3.0 (17
HMI name / version / branch / commit hash / module tested against: Sync 3.0

### Summary
This PR changes the order of operations in the `SDLResponseDispatcher` to remove command / button / audio pass thru handlers before calling the response handler of the delete / unsubscribe.

##### Bug Fixes
* Fix audio pass thru handlers being deleted after the `PAPT` response handler is called, leading to situations where the APT handler would never be called if a new `PAPT` were started from the old `PAPT` response handler.

### Tasks Remaining:
- [x] Fix unit tests

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLinkTests/Notifications/SDLResponseDispatcherSpec.m [hunk 1]
```diff
@@ -109,7 +109,7 @@
             });
             
             it(@"should run the handler", ^{
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/Notifications/SDLResponseDispatcherSpec.m]: I'm still getting random test cases failing locally. Travis is reporting failed test cases in this class as well.
