### PR TITLE
Fixed checking if streaming is supported returning wrong value

### LINKED ISSUE #1569: The Streaming Media Manager returns an incorrect value for `isStreamingSupported`
### Bug Report
The `SDLStreamingMediaManager` returns `false` for `isStreamingSupported` if video or audio has not yet started streaming. Since `isStreamingSupported` is set based on the value returned in the`RegisterAppInterface` response there is no need to wait for video or audio to start streaming in order to return an accurate value. 

##### Reproduction Steps
1. Connect a video streaming app to a head unit. Launch the SDL app by selecting the icon on the HMI (if necessary).
1. When the `start` handler has been called on the `sdlManager`, check if video is supported by querying `sdlManager.streamManager?.isStreamingSupported`.

##### Expected Behavior
It should return true as `videoLifecycleManager.isStreamingSupported` returns `true`.

##### Observed Behavior
It returns false as video has not yet started streaming.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.5
* Testing Against: SYNC 4

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #1569 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
* Fixed test cases in the `SDLStreamingAudioLifecycleManagerSpec` and `SDLStreamingVideoLifecycleManagerSpec`.

#### Core Tests
Core version / branch / commit hash / module tested against: SYNC 3.0 and Manticore (SDL Core v6.0.1 and Generic HMI v0.7.2)
HMI name / version / branch / commit hash / module tested against: SYNC 3.0 and Manticore (SDL Core v6.0.1 and Generic HMI v0.7.2)

### Summary
Fixed the `SDLStreamingMediaManager` returning `false` for `isStreamingSupported` if video/audio has not yet started streaming.

##### Bug Fixes
* Fixed the `SDLStreamingMediaManager` returning `false` for `isStreamingSupported` if video/audio has not yet started streaming. Since `isStreamingSupported` is set based on the value returned in the `RegisterAppInterface` response there is no need to wait for video or audio to start streaming in order to return an accurate value.
* Fixed the `SDLStreamingAudioLifecycleManager` possibly setting the wrong value for `isStreamingSupported` on pre-4.5.0 head units. 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLStreamingAudioLifecycleManager.m [hunk 1]
```diff
@@ -232,18 +233,25 @@ - (void)sdl_didReceiveRegisterAppInterfaceResponse:(SDLRPCResponseNotification *
...
 #pragma clang diagnostic push
 #pragma clang diagnostic ignored "-Wdeprecated"
-    SDLLogV(@"Determining whether streaming is supported");
-    _streamingSupported = registerResponse.hmiCapabilities.videoStreaming ? registerResponse.hmiCapabilities.videoStreaming.boolValue : registerResponse.displayCapabilities.graphicSupported.boolValue;
-#pragma clang diagnostic pop
-
-    if (!self.isStreamingSupported) {
-        SDLLogE(@"Graphics are not supported on this head unit. We are are assuming screen size is also unavailable and exiting.");
-        return;
+    if ([SDLGlobals.sharedGlobals.rpcVersion isGreaterThanOrEqualToVersion:[[SDLVersion alloc] initWithMajor:4 minor:5 patch:0]]) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLStreamingAudioLifecycleManager.m]: This should use the `SystemCapabilityManager` once `isCapabilitySupported` is merged instead of re-doing the same code here.

File: SmartDeviceLink/SDLStreamingMediaManager.m [hunk 2]
```diff
@@ -34,18 +35,22 @@ @implementation SDLStreamingMediaManager
...
 
-    _audioLifecycleManager = [[SDLStreamingAudioLifecycleManager alloc] initWithConnectionManager:connectionManager streamingConfiguration: configuration.streamingMediaConfig encryptionConfiguration:configuration.encryptionConfig];
-    _videoLifecycleManager = [[SDLStreamingVideoLifecycleManager alloc] initWithConnectionManager:connectionManager configuration:configuration];
+    _audioLifecycleManager = [[SDLStreamingAudioLifecycleManager alloc] initWithConnectionManager:connectionManager configuration:configuration systemCapabilityManager:systemCapabilityManager];
+    _videoLifecycleManager = [[SDLStreamingVideoLifecycleManager alloc] initWithConnectionManager:connectionManager configuration:configuration systemCapabilityManager:systemCapabilityManager];
 
     return self;
 }
 
+- (instancetype)initWithConnectionManager:(id<SDLConnectionManagerType>)connectionManager configuration:(SDLConfiguration *)configuration {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLStreamingMediaManager.m]: It appears that this initializer is being used in the lifecycle manager instead of the new one, which makes the `systemCapabilityManager` always nil.

Comment (NicoleYarroch) [reply SmartDeviceLink/SDLStreamingMediaManager.m]: Fixed.

File: SmartDeviceLink/SDLStreamingMediaManager.h [hunk 3]
```diff
@@ -118,14 +119,16 @@ NS_ASSUME_NONNULL_BEGIN
 /// Initializer unavailable
 - (instancetype)init NS_UNAVAILABLE;
 
-/**
- Create a new streaming media manager for navigation and VPM apps with a specified configuration
+/// Create a new streaming media manager for navigation and projection apps with a specified configuration.
+/// @param connectionManager The pass-through for RPCs
+/// @param configuration This session's configuration
+- (instancetype)initWithConnectionManager:(id<SDLConnectionManagerType>)connectionManager configuration:(SDLConfiguration *)configuration;
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLStreamingMediaManager.h]: Yep. Fixed.
