### PR TITLE
Align System Capability Manager Behavior with Java Suite

### LINKED ISSUE #1535: Update SystemCapabilityManager to align with Java_Suite
### Bug Report
The `SystemCapabilityManager`s in the two app libraries are currently out of alignment with widely varying methods and behavior. We need to align the two behavior even if we cannot currently align them entirely in nomenclature.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: v6.5.0
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1535 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
- [x] New `subscribe` method
- [x] `isCapabilitySupported` method

#### Core Tests
- [x] Test Obj-C subscribe with 0, 1, 2, and 3 parameters
  - Test cached capability
  - Test updated capability
  - Test unsubscribe
- [x] Test Obj-C subscribe with update handler
  - Test cached capability
  - Test updated capability
  - Test unsubscribe
- [x] Test Obj-C subscribe with block (deprecated)
  - Test cached capability
  - Test updated capability
  - Test unsubscribe
- [x] Test isCapabilitySupported

- [x] Check method signatures for Swift

Core version / branch / commit hash / module tested against: Sync Gen 3.2 (18124_DEVTEST), Manticore v.2.4.2 (SDL Core v6.0.1)
HMI name / version / branch / commit hash / module tested against: Sync Gen 3.2 (18124_DEVTEST), Manticore v.2.4.2 (Generic HMI v0.7.2)

### Summary
This PR makes additions and some minor behavioral changes to existing system capability manager methods in order to bring behavior into alignment with the Java Suite SCM as much as is reasonable.

##### Enhancements
* Added a `SystemCapabilityManager.subscribeToCapabilityType:withUpdateHandler:` method with more verbose error reporting than the now deprecated `SystemCapabilityManager.subscribeToCapabilityType:withBlock:` method.
* The `SystemCapabilityManager.subscribeToCapabilityType:withObserver:selector:` selector now supports up to three parameters, adding an `error` parameter and boolean `subscribed` parameter.
* All `subscribe` methods now immediately return the cached value.
* Added `isCapabilitySupported:` method that can be used to quickly determine if the feature is supported by the head unit or not.

##### Bug Fixes
* All capability data is no longer downloaded on first HMI_FULL. Instead the data will be downloaded when the first `updateCapabilityType:completionHandler:` call or the first `subscribe` to that capability type is made.
* Calling `unsubscribeFromCapabilityType:withObserver:` such that no observers remain for that type will now unsubscribe the `SystemCapabilityManager` from receiving any more data about that type until `updateCapabilityType:completionHandler:` or another `subscribe` call is made for that type.
* Removed caching data from GSC responses sent outside of the SCM. This simplifies the manager, tests, and aligns with the Java Suite SCM.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 1]
```diff
@@ -239,53 +248,88 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
...
  *
  * 1. No parameters e.g. `- (void)phoneCapabilityUpdated;`
- * 2. One `SDLSystemCapability *` parameter e.g. `- (void)phoneCapabilityUpdated:(SDLSystemCapability *)capability`
  *
- * This method will be called immediately with the current value and called every time the value is updated on RPC v5.1.0+ systems (`supportsSubscriptions == YES`). If this method is called on a sub-v5.1.0 system (`supportsSubscriptions == NO`), the method will return `NO` and the selector will never be called.
+ * 2. One `SDLSystemCapability *` parameter, e.g. `- (void)phoneCapabilityUpdated:(SDLSystemCapability *)capability`
+ *
+ * 3. Two parameters, one `SDLSystemCapability *` parameter, and one `NSError` parameter, e.g. `- (void)phoneCapabilityUpdated:(SDLSystemCapability *)capability error:(NSError *)error`
+ *
+ * 4. Three parameters, one `SDLSystemCapability *` parameter, one `NSError` parameter, and one `BOOL` parameter e.g. `- (void)phoneCapabilityUpdated:(SDLSystemCapability *)capability error:(NSError *)error subscribed:(BOOL)subscribed`
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSystemCapabilityManager.h]: I confused as to why `subscribed:(BOOL)subscribed` is returning false when I subscribe to `SDLSystemCapabilityType.displays` even though the selector gets called every time the display capability updates (connected to a `sub-v5.1.0` system).

```
self.sdlManager.systemCapabilityManager.subscribe(toCapabilityType: SDLSystemCapabilityType.displays, withObserver: self, selector: #selector(displayCapabilityUpdated(systemCapability:error:subscribed:)))

@objc func displayCapabilityUpdated(systemCapability: SDLSystemCapability, error: NSError?, subscribed: Bool) { }
```

File: SmartDeviceLink/SDLSystemCapabilityManager.m [hunk 2]
```diff
@@ -352,94 +232,140 @@ For backward compatibility (AppLink 2.0) static image type is always presented
...
- *  @param getSystemCapability The `GetSystemCapability` request to send
- */
-- (void)sdl_sendGetSystemCapability:(SDLGetSystemCapability *)getSystemCapability completionHandler:(nullable SDLUpdateCapabilityHandler)handler {
-    __weak typeof(self) weakSelf = self;
+    __weak typeof(self) weakself = self;
     [self.connectionManager sendConnectionRequest:getSystemCapability withResponseHandler:^(__kindof SDLRPCRequest * _Nullable request, __kindof SDLRPCResponse * _Nullable response, NSError * _Nullable error) {
+        if (![response isKindOfClass:[SDLGetSystemCapabilityResponse class]]) {
+            SDLLogE(@"GetSystemCapability failed, type: %@, did not return a GetSystemCapability response", type);
+            if (handler == nil) { return; }
+            handler(nil, NO, [NSError sdl_systemCapabilityManager_moduleDoesNotSupportCapabilityType]);
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.m]: 😭 Fixed

File: SmartDeviceLink/SDLSystemCapabilityManager.h (hunk 1 above)
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: It shouldn't be, I checked the logic a few times and tested it and it's working fine for me.

```objc
if (!self.supportsSubscriptions && ![type isEqualToEnum:SDLSystemCapabilityTypeDisplays]) {
        return NO;
    } else {
        return YES;
    }
```

File: SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m [hunk 3]
```diff
@@ -142,6 +160,153 @@ @interface SDLSystemCapabilityManager ()
...
+                        [SDLGlobals sharedGlobals].rpcVersion = [SDLVersion versionWithString:@"3.0.0"];
+                    });
+
+                    context(@"when displayCapabilities.graphicSupported is true", ^{
+                        beforeEach(^{
+                            testSystemCapabilityManager.displayCapabilities = [[SDLDisplayCapabilities alloc] init];
+                            testSystemCapabilityManager.displayCapabilities.graphicSupported = @YES;
+                        });
+
+                        fit(@"should return true", ^{
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m]: After I removed the focus the `SDLSystemCapabilityManagerSpec` test cases pass fine if I just run the test cases in that one file but if I run all the test cases, 2 tests fail in `SDLSystemCapabilityManagerSpec`.

File: SmartDeviceLinkTests/DevAPISpecs/TestSystemCapabilityObserver.h [hunk 4]
```diff
@@ -17,7 +17,9 @@ NS_ASSUME_NONNULL_BEGIN
 @property (assign, nonatomic) NSUInteger selectorCalledCount;
 
 - (void)capabilityUpdated;
-- (void)capabilityUpdatedWithNotification:(SDLSystemCapabilityManager *)capabilityManager;
+- (void)capabilityUpdatedWithCapability:(SDLSystemCapability *)capability;
+- (void)capabilityUpdatedWithCapability:(SDLSystemCapability *)capability error:(NSError *)error;
+- (void)capabilityUpdatedWithCapability:(SDLSystemCapability *)capability error:(NSError *)error subscribed:(BOOL)subscribed;
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/DevAPISpecs/TestSystemCapabilityObserver.h]: Should add a test case for checking the `subscribed` value for `SDLSystemCapabilityTypeDisplays` since that seems to be a unique case.

File: SmartDeviceLink/SDLSystemCapabilityManager.m [hunk 5]
```diff
@@ -352,94 +232,140 @@ For backward compatibility (AppLink 2.0) static image type is always presented
...
     [self.connectionManager sendConnectionRequest:getSystemCapability withResponseHandler:^(__kindof SDLRPCRequest * _Nullable request, __kindof SDLRPCResponse * _Nullable response, NSError * _Nullable error) {
+        if (![response isKindOfClass:[SDLGetSystemCapabilityResponse class]]) {
+            SDLLogE(@"GetSystemCapability failed, type: %@, did not return a GetSystemCapability response", type);
+            if (handler == nil) { return; }
+            handler(nil, NO, [NSError sdl_systemCapabilityManager_moduleDoesNotSupportSystemCapabilities]);
+            return;
+        }
+
         if (error != nil) {
+            SDLLogE(@"GetSystemCapability failed, type: %@, error: %@", type, error);
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSystemCapabilityManager.m]: The `response.resultCode` should be checked here instead of the `error` since the request can succeed but also have an error message.

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 6]
```diff
@@ -239,53 +248,88 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
...
  *
  * @param type The type of the system capability to subscribe to
  * @param observer The object that will have `selector` called whenever the capability is updated
  * @param selector The selector on `observer` that will be called whenever the capability is updated
- * @return Whether or not the subscription succeeded. `NO` if the connected system doesn't support capability subscriptions, or if the `selector` doesn't support the correct parameters (see above)
+ * @return Whether or not the subscription succeeded. `NO` if the connected system doesn't support capability subscriptions, or if the `selector` doesn't support the correct parameters (see above).
  */
 - (BOOL)subscribeToCapabilityType:(SDLSystemCapabilityType)type withObserver:(id)observer selector:(SEL)selector;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSystemCapabilityManager.h]: If I attempt to subscribe to `SDLSystemCapabilityTypeVideoStreaming` after I have got the notification that the SDL app started successfully but before the `hmiLevel` is `FULL` then I get an error saying `SDLResultDisallowed` but if I wait until the `hmiLevel` is `FULL` then I get the video capabilities from the module (`appType` is `default`). Maybe add some documentation that subscriptions should only happened if the `hmiLevel` is non-`NONE`.

File: SmartDeviceLink/SDLSystemCapabilityManager.h (hunk 1 above)
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: Fixed

File: SmartDeviceLink-iOS.xcodeproj/xcshareddata/xcschemes/SmartDeviceLink-Example-ObjC.xcscheme [hunk 7]
```diff
@@ -0,0 +1,78 @@
+<?xml version="1.0" encoding="UTF-8"?>
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink-iOS.xcodeproj/xcshareddata/xcschemes/SmartDeviceLink-Example-ObjC.xcscheme]: I don't know why mine disappeared, but I only have one on this branch and can't use the Obj-C app if it's not here...

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 8]
```diff
@@ -212,6 +216,11 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
  */
 @property (nullable, strong, nonatomic, readonly) SDLWindowCapability *defaultMainWindowCapability;
 
+/**
+ YES if subscriptions are available on the connected module and you will automatically be notified if the value changes on the module. If NO, calls to `subscribe` methods will subscribe to updates, but the module will not automatically notify you. You will need to call `updateWithCapabilityType:completionHandler:` to force an update if you need one (though this should be rare).
+ */
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: Done

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 9]
```diff
@@ -239,53 +248,88 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
 - (void)stop;
 
 /**
- *  Retrieves a capability type from the remote system. This function must be called in order to retrieve the values for `navigationCapability`, `phoneCapability`, `videoStreamingCapability`, `remoteControlCapability`, and `appServicesCapabilities`. If you do not call this method first, those values will be nil. After calling this method, assuming there is no error in the handler, you may retrieve the capability you requested from the manager within the handler.
+ * Returns the window capability object of the primary display with the specified window ID. This is a convenient method to easily access capabilities of windows for instance widget windows of the main display.
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: Rewrote

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 10]
```diff
@@ -239,53 +248,88 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
...
  *
- *  @param type The type of capability to retrieve
- *  @param handler The handler to be called when the retrieval is complete
+ * @param windowID The ID of the window to get capabilities
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: Rewrote

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 11]
```diff
@@ -239,53 +248,88 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
...
+/// @param type The SystemCapabilityType that will be checked.
+/// @return Whether or not `type` is supported by the connected head unit.
+- (BOOL)isCapabilitySupported:(SDLSystemCapabilityType)type NS_SWIFT_NAME(isCapabilitySupported(type:));
 
- @param type The type of capability to subscribe to
- @param block The block to be called when the capability is updated
- @return An object that can be used to unsubscribe the block using unsubscribeFromCapabilityType:withObserver: by passing it in the observer callback, or nil if subscriptions aren't available on this head unit
+/**
+ *  This method has been superceded by `subscribeToCapabilityType:` methods. You should use one of those instead, unless you only want a value once, and it must be updated. If you subscribe to a capability and are connected to a head unit that does not support subscriptions, when this method returns, it will also call all subscriptions. Therefore, you can use this method to force an update to all subscriptions of that particular type.
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: Rewritten

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 12]
```diff
@@ -239,53 +248,88 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
...
+ *
+ *  Retrieves and updates a capability type from the remote system. This function must be called in order to retrieve the values for `navigationCapability`, `phoneCapability`, `videoStreamingCapability`, `remoteControlCapability`, and `appServicesCapabilities`. If you do not call this method first, those values will be nil. After calling this method, assuming there is no error in the handler, you may retrieve the capability you requested from the manager within the handler.
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: Rewritten

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 13]
```diff
@@ -239,53 +248,88 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
...
  */
-- (nullable id<NSObject>)subscribeToCapabilityType:(SDLSystemCapabilityType)type withBlock:(SDLCapabilityUpdateHandler)block;
+- (void)updateCapabilityType:(SDLSystemCapabilityType)type completionHandler:(SDLUpdateCapabilityHandler)handler;
 
-/**
- * Subscribe to a particular capability type with a selector callback. The selector supports the following parameters:
+/// Subscribe to a particular capability type using a block callback.
+///
+/// On v5.1.0+ systems (where `supportsSubscriptions == YES`):
+/// This method will be called immediately with the current value and will be called every time the value is updated. If this is the first subscription of this `SDLSystemCapabilityType`, then the value will be retrieved and a subscription will be attempted. The current cached value (`nil`) will nevertheless be returned immediately.
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: Rewrote

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 14]
```diff
@@ -239,53 +248,88 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
...
+///
+/// On sub-v5.1.0 systems (where `supportsSubscriptions == NO`):
+/// The method will be called immediately with the current value and will _not_ be automatically called every time the value is updated, unless the `type` is `DISPLAYS` which is supported on every version. If `updateCapabilityType:completionHandler` is called and a new value is retrieved, this value will be updated then. If this is the first subscription of this `SDLSystemCapabilityType`, then the value will be retrieved and returned. The current cached value (`nil`) will nevertheless be returned immediately.
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: Rewrote

File: SmartDeviceLink/SDLSystemCapabilityObserver.h [hunk 15]
```diff
@@ -14,6 +14,8 @@ NS_ASSUME_NONNULL_BEGIN
 
 typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
 
+typedef void (^SDLCapabilityUpdateWithErrorHandler)(SDLSystemCapability *_Nullable capability, BOOL subscribed, NSError *_Nullable error);
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityObserver.h]: Fixed

File: SmartDeviceLink/SDLSystemCapabilityManager.m (hunk 5 above)
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.m]: Fixed

File: SmartDeviceLink/SDLSystemCapabilityManager.h (hunk 6 above)
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: Fixed, now it will return `nil` or `NO` if it fails to attempt a subscription and tracks the HMI level and cancels out if the HMI level is NONE.

File: SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m (hunk 3 above)
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m]: Fixed

File: SmartDeviceLinkTests/DevAPISpecs/TestSystemCapabilityObserver.h (hunk 4 above)
Comment (joeljfischer) [reply SmartDeviceLinkTests/DevAPISpecs/TestSystemCapabilityObserver.h]: Fixed

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 16]
```diff
@@ -239,53 +248,88 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
...
+ * @param handler The handler to be called when the retrieval is complete
  */
-- (nullable id<NSObject>)subscribeToCapabilityType:(SDLSystemCapabilityType)type withBlock:(SDLCapabilityUpdateHandler)block;
+- (void)updateCapabilityType:(SDLSystemCapabilityType)type completionHandler:(SDLUpdateCapabilityHandler)handler;
 
-/**
- * Subscribe to a particular capability type with a selector callback. The selector supports the following parameters:
+/// Subscribe to a particular capability type using a block callback.
+///
+/// On v5.1.0+ systems (where `supportsSubscriptions == YES`):
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSystemCapabilityManager.h]: In addition to `the current cached value of `nil` will be returned immediately`, you should add that `subscribed` will be `false`.

Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: Done (though on the other method because the method you've commented on does not have a subscribed flag).

File: SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m [hunk 17]
```diff
@@ -41,14 +43,30 @@
...
+@property (nullable, strong, nonatomic, readwrite) SDLRemoteControlCapabilities *remoteControlCapability;
+@property (nullable, strong, nonatomic, readwrite) SDLSeatLocationCapability *seatLocationCapability;
 
 @end
 
 
 QuickSpecBegin(SDLSystemCapabilityManagerSpec)
 
-describe(@"System capability manager", ^{
+fdescribe(@"System capability manager", ^{
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m]: done

File: SmartDeviceLink/SDLSystemCapabilityManager.h (hunk 6 above)
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: Fixed, the HMI level now starts assuming NONE and will change when it gets an explicit HMI status.

File: SmartDeviceLink/SDLSystemCapabilityManager.m [hunk 18]
```diff
@@ -568,32 +506,100 @@ - (void)sdl_saveDisplayCapabilityListUpdate:(NSArray<SDLDisplayCapability *> *)n
...
 }
 
-- (BOOL)subscribeToCapabilityType:(SDLSystemCapabilityType)type withObserver:(id<NSObject>)observer selector:(SEL)selector {
-    // DISPLAYS always works due to old-style SetDisplayLayoutRepsonse updates, but otherwise, subscriptions won't work
-    if (!self.supportsSubscriptions && ![type isEqualToEnum:SDLSystemCapabilityTypeDisplays]) { return NO; }
+- (nullable id<NSObject>)subscribeToCapabilityType:(SDLSystemCapabilityType)type withUpdateHandler:(SDLCapabilityUpdateWithErrorHandler)handler {
+    SDLLogD(@"Subscribing to capability type: %@ with a handler", type);
+
+    if ([self.currentHMILevel isEqualToEnum:SDLHMILevelNone] && ![type isEqualToEnum:SDLSystemCapabilityTypeDisplays]) {
+        SDLLogE(@"Attempted to subscribe to type: %@ in HMI level NONE, which is not allowed. Please wait until you are in HMI BACKGROUND, LIMITED, or FULL before attempting to subscribe to any SystemCapabilityType other than DISPLAYS.", type);
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSystemCapabilityManager.m]: Instead of printing the error, why not call the handler or invoke the selector with the error?

File: SmartDeviceLink/SDLSystemCapabilityManager.m [hunk 19]
```diff
@@ -136,136 +128,26 @@ - (void)stop {
...
-
-/**
- *  Registers for notifications and responses from Core
- */
-- (void)sdl_registerForNotifications {
-    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(sdl_registerResponse:) name:SDLDidReceiveRegisterAppInterfaceResponse object:nil];
-    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(sdl_displayLayoutResponse:) name:SDLDidReceiveSetDisplayLayoutResponse object:nil];
-    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(sdl_systemCapabilityUpdatedNotification:) name:SDLDidReceiveSystemCapabilityUpdatedNotification object:nil];
-    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(sdl_systemCapabilityResponseNotification:) name:SDLDidReceiveGetSystemCapabilitiesResponse object:nil];
-    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(sdl_hmiStatusNotification:) name:SDLDidChangeHMIStatusNotification object:nil];
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSystemCapabilityManager.m]: I think you still want to be registered for `SDLDidChangeHMIStatusNotification`, otherwise the `currentHMILevel` is always `NONE`.

Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.m]: Strange, did I forget to add the notification register? I added it now.

File: SmartDeviceLink/SDLSystemCapabilityManager.m (hunk 18 above)
Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.m]: Done

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 20]
```diff
@@ -239,53 +248,90 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
...
+/// This method will be called immediately with the current value and will be called every time the value is updated. If this is the first subscription of this `SDLSystemCapabilityType`, then the current cached value of `nil` will be returned immediately, an updated value will be retrieved, and a subscription will be attempted.
+///
+/// On sub-v5.1.0 systems (where `supportsSubscriptions == NO`):
+/// The method will be called immediately with the current value and will _not_ be automatically called every time the value is updated, unless the `type` is `DISPLAYS` which is supported on every version. If `updateCapabilityType:completionHandler` is called and a new value is retrieved, this value will be updated then. If this is the first subscription of this `SDLSystemCapabilityType`, then the current cached value of `nil` will be returned immediately, an updated value will be retrieved, and a subscription will be attempted.
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSystemCapabilityManager.h]: > If this is the first subscription of this `SDLSystemCapabilityType`, then the current cached value of `nil` will be returned immediately, an updated value will be retrieved, and a subscription will be attempted.

Sounds like this is no longer true with the most recent fixes.

Comment (joeljfischer) [reply SmartDeviceLink/SDLSystemCapabilityManager.h]: Fixed

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 21]
```diff
@@ -239,53 +248,90 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
...
  */
-- (nullable id<NSObject>)subscribeToCapabilityType:(SDLSystemCapabilityType)type withBlock:(SDLCapabilityUpdateHandler)block;
+- (void)updateCapabilityType:(SDLSystemCapabilityType)type completionHandler:(SDLUpdateCapabilityHandler)handler;
 
-/**
- * Subscribe to a particular capability type with a selector callback. The selector supports the following parameters:
+/// Subscribe to a particular capability type using a block callback.
+///
+/// On v5.1.0+ systems (where `supportsSubscriptions == YES`):
+/// This method will be called immediately with the current value and will be called every time the value is updated. If this is the first subscription of this `SDLSystemCapabilityType`, then the current cached value of `nil` will be returned immediately, an updated value will be retrieved, and a subscription will be attempted.
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSystemCapabilityManager.h]: Isn't this also false on On v5.1.0+ systems?

> If this is the first subscription of this `SDLSystemCapabilityType`, then the current cached value of `nil` will be returned immediately, an updated value will be retrieved, and a subscription will be attempted

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 22]
```diff
@@ -239,53 +248,90 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
...
+///
+/// @param type The type of capability to subscribe to
+/// @param block The block to be called when the capability is updated
+/// @return An object that can be used to unsubscribe the block using unsubscribeFromCapabilityType:withObserver: by passing it in the observer callback, or nil if the manager can't attempt the subscription for some reason (such as the app being in HMI_NONE and the type is not DISPLAYS).
+- (nullable id<NSObject>)subscribeToCapabilityType:(SDLSystemCapabilityType)type withBlock:(SDLCapabilityUpdateHandler)block __deprecated_msg("use subscribeToCapabilityType:withUpdateHandler: instead");
+
+/// Subscribe to a particular capability type using a handler callback.
+///
+/// On v5.1.0+ systems (where `supportsSubscriptions == YES`):
+/// This method will be called immediately with the current value and will be called every time the value is updated. If this is the first subscription of this `SDLSystemCapabilityType`, then the current cached value of `nil` will be returned immediately, an updated value will be retrieved, and a subscription will be attempted.
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSystemCapabilityManager.h]: Isn't this also false on On v5.1.0+ systems?

> If this is the first subscription of this `SDLSystemCapabilityType`, then the current cached value of `nil` will be returned immediately, an updated value will be retrieved, and a subscription will be attempted

File: SmartDeviceLink/SDLSystemCapabilityManager.h [hunk 23]
```diff
@@ -239,53 +248,90 @@ typedef void (^SDLCapabilityUpdateHandler)(SDLSystemCapability *capability);
...
- * 2. One `SDLSystemCapability *` parameter e.g. `- (void)phoneCapabilityUpdated:(SDLSystemCapability *)capability`
  *
- * This method will be called immediately with the current value and called every time the value is updated on RPC v5.1.0+ systems (`supportsSubscriptions == YES`). If this method is called on a sub-v5.1.0 system (`supportsSubscriptions == NO`), the method will return `NO` and the selector will never be called.
+ * 2. One `SDLSystemCapability *` parameter, e.g. `- (void)phoneCapabilityUpdated:(SDLSystemCapability *)capability`
+ *
+ * 3. Two parameters, one `SDLSystemCapability *` parameter, and one `NSError` parameter, e.g. `- (void)phoneCapabilityUpdated:(SDLSystemCapability *)capability error:(NSError *)error`
+ *
+ * 4. Three parameters, one `SDLSystemCapability *` parameter, one `NSError` parameter, and one `BOOL` parameter e.g. `- (void)phoneCapabilityUpdated:(SDLSystemCapability *)capability error:(NSError *)error subscribed:(BOOL)subscribed`
+ *
+ * On v5.1.0+ systems (where `supportsSubscriptions == YES`):
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLSystemCapabilityManager.h]: Isn't this also false on On v5.1.0+ systems?

> If this is the first subscription of this `SDLSystemCapabilityType`, then the current cached value of `nil` will be returned immediately, an updated value will be retrieved, and a subscription will be attempted
