### PR TITLE
Fix main menu UI updates do not take text field name image field name into consideration

### LINKED ISSUE #1928: Main Menu UI Updates Don't Take TextFieldName / ImageFieldName into account
### Bug Report
When uploading an `SDLMenuCell`, we need to check `SDLTextFieldNameMenuCommandSecondaryText`, `SDLTextFieldNameMenuCommandTertiaryText`, `SDLTextFieldNameMenuSubMenuSecondaryText`, `SDLTextFieldNameMenuSubMenuTertiaryText`, `SDLImageFieldNameMenuCommandSecondaryImage`, and `SDLImageFieldNameMenuSubMenuSecondaryImage`.

##### Reproduction Steps
1. Connect to a head unit that doesn't support secondary text, tertiary text, or secondary image.
2. Attempt to send a menu cell with secondary text, tertiary text, or secondary image.

##### Expected Behavior
The unsupported text and image are not sent / uploaded.

##### Observed Behavior
The unsupported text and image are sent / uploaded.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 7.1.0-develop
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App
n/a

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1928 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: SYNC3/generic_hmi

### Summary
Implement new checks to handle SDLTextFieldNameMenuCommandSecondaryText, SDLTextFieldNameMenuCommandTertiaryText, SDLTextFieldNameMenuSubMenuSecondaryText and SDLTextFieldNameMenuSubMenuTertiaryText

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Implement new checks to handle SDLTextFieldNameMenuCommandSecondaryText, SDLTextFieldNameMenuCommandTertiaryText, SDLTextFieldNameMenuSubMenuSecondaryText and SDLTextFieldNameMenuSubMenuTertiaryText

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 1]
```diff
@@ -724,8 +724,8 @@ - (SDLAddCommand *)sdl_commandForMenuCell:(SDLMenuCell *)cell withArtwork:(BOOL)
     params.menuName = cell.uniqueTitle;
     params.parentID = cell.parentCellId != UINT32_MAX ? @(cell.parentCellId) : nil;
     params.position = @(position);
-    params.secondaryText = (cell.secondaryText.length == 0) ? nil : cell.secondaryText;
-    params.tertiaryText = (cell.tertiaryText.length == 0) ? nil : cell.tertiaryText;
+    params.secondaryText = (cell.secondaryText.length == 0 || ![self.windowCapability hasTextFieldOfName:SDLTextFieldNameMenuCommandSecondaryText]) ? nil : cell.secondaryText;
+    params.tertiaryText = (cell.tertiaryText.length == 0 || ![self.windowCapability hasTextFieldOfName:SDLTextFieldNameMenuCommandTertiaryText]) ? nil : cell.tertiaryText;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:728]:
```suggestion
    params.secondaryText = (cell.secondaryText.length > 0 && [self.windowCapability hasTextFieldOfName:SDLTextFieldNameMenuCommandSecondaryText]) ? cell.secondaryText : nil;
    params.tertiaryText = (cell.tertiaryText.length > 0 && [self.windowCapability hasTextFieldOfName:SDLTextFieldNameMenuCommandTertiaryText]) ? cell.tertiaryText : nil;
```

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 2]
```diff
@@ -747,8 +747,8 @@ - (SDLAddSubMenu *)sdl_subMenuCommandForMenuCell:(SDLMenuCell *)cell withArtwork
         submenuLayout = self.menuConfiguration.defaultSubmenuLayout;
     }
     
-    NSString *secondaryText = (cell.secondaryText.length == 0) ? nil : cell.secondaryText;
-    NSString *tertiaryText = (cell.tertiaryText.length == 0) ? nil : cell.tertiaryText;
+    NSString *secondaryText = (cell.secondaryText.length == 0 || ![self.windowCapability hasTextFieldOfName:SDLTextFieldNameMenuSubMenuSecondaryText]) ? nil : cell.secondaryText;
+    NSString *tertiaryText = (cell.tertiaryText.length == 0 || ![self.windowCapability hasTextFieldOfName:SDLTextFieldNameMenuSubMenuTertiaryText]) ? nil : cell.tertiaryText;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:751]:
```suggestion
    NSString *secondaryText = (cell.secondaryText.length > 0 && [self.windowCapability hasTextFieldOfName:SDLTextFieldNameMenuSubMenuSecondaryText]) ? cell.secondaryText : nil;
    NSString *tertiaryText = (cell.tertiaryText.length > 0 && [self.windowCapability hasTextFieldOfName:SDLTextFieldNameMenuSubMenuTertiaryText]) ? cell.tertiaryText : nil;
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]
1. Also need to fix `SDLImage *secondaryImage =`... to check the appropriate ImageFieldName and don't set the `SDLImage` if that is not available. 
2. Also need to fix `SDLImage *icon =`... to check the ImageFieldName and `fileNeedsUpload`, I think.
