### PR TITLE
Remove Deprecations

### LINKED ISSUE #679: Remove all deprecated and unneeded code for v5.0
### Bug Report
For v5.0, we should remove all deprecated methods and classes (other than the `SDLProxy` and `SDLProtocol` layers).

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #679 

This PR is **ready** for review.

### Risk
This PR makes **major** API changes.

### Testing Plan
Tests have been updated

### Summary
This PR removes deprecated code (and also fixes a bug in SDLConfiguration)

##### Breaking Changes
* Numerous deprecated methods have been removed

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLConfiguration.m [hunk 1]
```diff
@@ -59,6 +59,7 @@ - (instancetype)initWithLifecycle:(SDLLifecycleConfiguration *)lifecycleConfig l
     _lifecycleConfig = lifecycleConfig;
     _lockScreenConfig = lockScreenConfig ?: [SDLLockScreenConfiguration enabledConfiguration];
     _loggingConfig = logConfig ?: [SDLLogConfiguration defaultConfiguration];
+    _streamingMediaConfig = streamingMediaConfig;
 
     if (_streamingMediaConfig != nil) {
         NSAssert(!([_lifecycleConfig.appType isEqualToEnum:SDLAppHMITypeNavigation] || [_lifecycleConfig.appType isEqualToEnum:SDLAppHMITypeProjection]), @"You should only set a streaming media configuration if your app is a NAVIGATION or PROJECTION HMI type");
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLConfiguration.m]: This assert statement is getting called when app type *is* set to Navigation. Since assert statements only get called if they are false, the **!** should be removed from the conditional statement.

File: SmartDeviceLink/SDLProtocolListener.h [hunk 2]
```diff
@@ -17,11 +17,6 @@ NS_ASSUME_NONNULL_BEGIN
 - (void)handleProtocolEndServiceNAKMessage:(SDLProtocolMessage *)endServiceNAK;
 
 // Older protocol handlers
-- (void)handleProtocolStartSessionACK:(SDLServiceType)serviceType sessionID:(Byte)sessionID version:(Byte)version __deprecated_msg("use handleProtocolStartSessionACKMessage: instead");
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLProtocolListener.h]: The `handleProtocolStartSessionACK` protocol handler is still being used in the `SDLProxy` class. The `SDLProxy` class needs to implement the `handleProtocolStartServiceACKMessage`protocol handler, otherwise setup will not complete.  This is why setup is not finishing when the protocol string is **com.smartdevicelink.prot2**.

Comment (NicoleYarroch) [reply SmartDeviceLink/SDLProtocolListener.h]: This needs to get fixed on **develop** as well.

File: SmartDeviceLink/SDLProtocolListener.h [hunk 3]
```diff
@@ -17,11 +17,6 @@ NS_ASSUME_NONNULL_BEGIN
...
-- (void)handleProtocolStartSessionACK:(SDLProtocolHeader *)header __deprecated_msg("use handleProtocolStartSessionACKMessage: instead");
-- (void)handleProtocolStartSessionNACK:(SDLServiceType)serviceType __deprecated_msg("use handleProtocolStartSessionNAKMessage: instead");
-- (void)handleProtocolEndSessionACK:(SDLServiceType)serviceType __deprecated_msg("use handleProtocolEndSessionACKMessage: instead");
-- (void)handleProtocolEndSessionNACK:(SDLServiceType)serviceType __deprecated_msg("use handleProtocolEndSessionNAKMessage: instead");
 - (void)handleHeartbeatForSession:(Byte)session;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLProtocolListener.h]: `handleProtocolStartSessionACK`, `handleProtocolStartSessionNACK`, `handleProtocolEndSessionACK`, and `handleProtocolEndSessionNACK` are all being used in the `SDLStreamingMediaLifecycleManager`. This means that video is not streaming because setup does not complete.

**Comment by joeljfischer** [comment]
@NicoleYarroch Fixed and merged base back in
