### PR TITLE
Fix Failing Travis Tests

### LINKED ISSUE #1640: Sometimes Travis is failing tests
### Bug Report
Sometimes Travis is failing tests (maybe due to timing issues):

```
Failing tests:

SmartDeviceLinkTests:

-[SDLCacheFileManagerSpec a_cache_file_manager__request_with_existing_icon__request_with_expired_icon__image_download_fails__it_should_return_error_and_no_image]

-[SDLSequentialRPCRequestOperationSpec Sending_sequential_requests__where_all_requests_succeed__where_the_requests_are_continued__should_correctly_send_all_requests]

-[SDLSequentialRPCRequestOperationSpec Sending_sequential_requests__where_all_requests_succeed__where_the_requests_are_continued__should_correctly_send_all_requests]
```

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1640, #1642 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit tests were updated to pass Travis

#### Core Tests
No library behavior was modified

Core version / branch / commit hash / module tested against: n/a
HMI name / version / branch / commit hash / module tested against: n/a

### Summary
This PR updates some unit tests in an attempt to pass Travis

### Changelog
n/a - no library changes

### Tasks Remaining:
- [ ] Ensure tests actually pass travis

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLinkTests/Notifications/SDLResponseDispatcherSpec.m [hunk 1]
```diff
@@ -714,11 +714,6 @@
                 [testDispatcher storeRequest:testPerformAudioPassThru handler:nil];
             });
             
-            it(@"should store the handler" ,^{
-//                expect(testDispatcher.audioPassThruHandler).toNot(beNil());
-//                expect(testDispatcher.audioPassThruHandler).to(equal(testPerformAudioPassThru.audioDataHandler));
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/Notifications/SDLResponseDispatcherSpec.m:719]: You can get these to compile by casting `audioPassThruHandler` to `id`
```
expect((id)testDispatcher.audioPassThruHandler).to(equal((id)testPerformAudioPassThru.audioDataHandler));
```

Comment (joeljfischer) [reply SmartDeviceLinkTests/Notifications/SDLResponseDispatcherSpec.m:719]: Blocks aren’t an `id` though so I suspect that casting them to that isn’t doing a proper comparison.
