### PR TITLE
Fixed File Manager not returning that files are uploaded when they are

### LINKED ISSUE #1978: File manager returns that files are not uploaded if the connection is > v4.4.0
### Bug Report
Currently we send the initial text & images when the `hmiLevel` goes to `FULL` the first time. However, sometimes the image is not sent due to the file manager not yet being in the ready state. We should try to send the image again if the image upload failed due to this reason.

##### Reproduction Steps
1. Run iOS example app
2. Launch it on desired hmi

##### Expected Behavior
Images displayed correctly

##### Observed Behavior
Images not displayed

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: 7.1
* Testing Against: Manticore

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1978 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
1. Register and launch app on hmi
2. Check if the screenManager's `primaryGraphic` is presented.

7.1 Test plan: Screen Manager - Text & Graphic

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: Manticore

### Summary
`hasUploadedFile` func of SDLFIleManager returns `NO` sometimes when it should be returning `YES` which caused the primaryGraphic not being displayed. This bug could be seen usually on second app launch.

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Updates in `hasUploadedFile` func of SDLFIleManager.

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m [hunk 1]
```diff
@@ -256,6 +257,51 @@ @implementation FileManagerSpecHelper
         });
     });
 
+    describe(@"check hasUploadedFile response", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m:260]: This needs to be split up better. Sub-categories should be:

```
context(@"on RPC version >= 4.4.0")

context(@"on RPC version < 4.4.0")
```

below that there should be:

```
context(@"when the file is persistent")

context(@"when the file is not persistent")
```

below that:

```
context(@"when the file is in remoteFileNames")

context(@"when the file is not in remoteFileNames")
```

and below that:

```
context(@"when the file is in uploadedEphemeralFiles")

context(@"when the file is not in uploadedEphemeralFiles") // Only for non-persistent
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m [hunk 2]
```diff
@@ -256,6 +258,142 @@ @implementation FileManagerSpecHelper
...
+        __block SDLFile *testFile = nil;
+
+        context(@"on RPC version >= 4.4.0", ^{
+            beforeEach(^{
+                [SDLGlobals sharedGlobals].rpcVersion = [SDLVersion versionWithMajor:7 minor:1 patch:0];
+                [testFileManager.stateMachine setToState:SDLFileManagerStateReady fromOldState:SDLFileManagerStateShutdown callEnterTransition:NO];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m:267]: This seems like it could be called on the enclosing `describe`

File: SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m [hunk 3]
```diff
@@ -256,6 +258,142 @@ @implementation FileManagerSpecHelper
...
+
+            context(@"when the file is persistent", ^{
+                beforeEach(^{
+                    NSData *testFileData = [@"someData" dataUsingEncoding:NSUTF8StringEncoding];
+                    testFile = [SDLFile persistentFileWithData:testFileData name:@"testFile4" fileExtension:@"png"];
+                });
+
+                it(@"should return NO", ^{
+                    expect([testFileManager hasUploadedFile:testFile]).to(equal(NO));
+                });
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m:308]: Isn't this identical to the below `context(@"when the file is not in remoteFileNames", ^{`

File: SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m [hunk 4]
```diff
@@ -256,6 +258,142 @@ @implementation FileManagerSpecHelper
...
+                NSData *testFileData = [@"someData" dataUsingEncoding:NSUTF8StringEncoding];
+                testFile = [SDLFile persistentFileWithData:testFileData name:@"testFile4" fileExtension:@"png"];
+            });
+
+            context(@"when the file is in remoteFileNames", ^{
+                beforeEach(^{
+                    testFileManager.mutableRemoteFileNames = [NSMutableSet setWithArray:testInitialFileNames2];
+                });
+
+                it(@"should return NO", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m:278]:
```suggestion
                it(@"should return YES", ^{
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]
