### PR TITLE
The secondary transport manager now only starts a timer when the secondary transport has opened

### LINKED ISSUE #1716: The secondary transport manager should not start a timer when the primary transport opens
### Bug Report
When the primary transport opens, the `SDLSecondaryTransportManager` is notified via the `onProtocolOpened` delegate method. The `SDLSecondaryTransportManager` starts a timer to watch for a response to the request to register the secondary transport even though no such request can be sent due to the secondary transport not being established. 

##### Reproduction Steps
1. Connect a navigation app that supports secondary transports to the module.
1. The `registerTransportTimer` on the  `SDLSecondaryTransportManager` will be started as soon as the primary transport is established. If the secondary transport is not established by the time timer elapses, then irrelevant logs are printed. 

##### Expected Behavior
The `registerTransportTimer` should only be created if the secondary transport has been established. 

##### Observed Behavior
The `registerTransportTimer` is created even if the secondary transport has not been established.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.6 
* Testing Against: SdlTcpApp

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #1716, #1718 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit tests were added to the `SDLSecondaryTransportManagerSpec` and the `SDLProtocolReceivedMessageRouterSpec`

#### Core Tests
Tested against the SdlTcpApp_0_4_0 Fake TCP server and SYNC 3.0.

Core version / branch / commit hash / module tested against: SYNC 3.0.
HMI name / version / branch / commit hash / module tested against: SYNC 3.0.

### Summary
When the primary transport opens, the `SDLSecondaryTransportManager` is notified via the onProtocolOpened delegate method. Since the secondary transport has not yet been established, the `SDLSecondaryTransportManager` no longer starts a timer to watch for a response to the request to register the secondary transport.

##### Bug Fixes
* The `SDLSecondaryTransportManager` now only starts a timer to watch for a response to the request to register the secondary transport when the secondary transport has opened. 
* Fixed the protocol message router not routing the `EndServiceNAK` frame correctly.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 1]
```diff
@@ -536,10 +536,15 @@ - (BOOL)sdl_isTCPReady {
...
 
-#pragma mark - SDLProtocolListener Implementation
+#pragma mark - SDLProtocolDelegate Implementation
 
 // called on transport's thread, notifying that the transport is established
 - (void)onProtocolOpened {
+    if (self.secondaryProtocol == nil) {
+        // The primary transport opened
+        return;
+    }
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m:546]:
```suggestion
    // The primary transport opened
    if (self.secondaryProtocol == nil) { return; }
```

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 2]
```diff
@@ -536,10 +536,15 @@ - (BOOL)sdl_isTCPReady {
     return YES;
 }
 
-#pragma mark - SDLProtocolListener Implementation
+#pragma mark - SDLProtocolDelegate Implementation
 
 // called on transport's thread, notifying that the transport is established
 - (void)onProtocolOpened {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m:542]: Would it be better to pass the protocol in all of these messages to do an identity check?

File: SmartDeviceLink/SDLProtocolDelegate.h [hunk 3]
```diff
@@ -11,78 +12,85 @@ NS_ASSUME_NONNULL_BEGIN
...
- *
- *  @param session Session number
- */
+
+#pragma mark - Protocol Messages
+
+/// Called when a protocol frame is received.
+/// @param msg A SDLProtocolMessage object
+/// @param protocol The transport's protocol
+- (void)onProtocolMessageReceived:(SDLProtocolMessage *)msg protocol:(SDLProtocol *)protocol;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProtocolDelegate.h:21]:
```suggestion
- (void)protocol:(SDLProtocol *)protocol didReceiveMessage:(SDLProtocolMessage *)msg;
```

File: SmartDeviceLink/SDLProtocolDelegate.h [hunk 4]
```diff
@@ -11,78 +12,85 @@ NS_ASSUME_NONNULL_BEGIN
...
+
+/// Called when the start service frame succeeds.
+/// @discussion This frame can be sent on both the primary and secondary transports
+/// @param startServiceACK A SDLProtocolMessage object
+/// @param protocol The transport's protocol
+- (void)handleProtocolStartServiceACKMessage:(SDLProtocolMessage *)startServiceACK protocol:(SDLProtocol *)protocol;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProtocolDelegate.h:27]:
```suggestion
- (void)protocol:(SDLProtocol *)protocol didReceiveStartServiceACK:(SDLProtocolMessage *)startServiceACK {
```

File: SmartDeviceLink/SDLProtocolDelegate.h [hunk 5]
```diff
@@ -11,78 +12,85 @@ NS_ASSUME_NONNULL_BEGIN
...
+
+/// Called when the start service frame fails.
+/// @discussion This frame can be sent on both the primary and secondary transports
+/// @param startServiceNAK A SDLProtocolMessage object
+/// @param protocol The transport's protocol
+- (void)handleProtocolStartServiceNAKMessage:(SDLProtocolMessage *)startServiceNAK protocol:(SDLProtocol *)protocol;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProtocolDelegate.h:33]:
```suggestion
- (void)protocol:(SDLProtocol *)protocol didReceiveStartServiceNAK:(SDLProtocolMessage *)startServiceNAK {
```

File: SmartDeviceLink/SDLProtocolDelegate.h [hunk 6]
```diff
@@ -11,78 +12,85 @@ NS_ASSUME_NONNULL_BEGIN
...
+
+/// Called when the end service frame succeeds.
+/// @discussion This frame can be sent on both the primary and secondary transports
+/// @param endServiceACK A SDLProtocolMessage object
+/// @param protocol The transport's protocol
+- (void)handleProtocolEndServiceACKMessage:(SDLProtocolMessage *)endServiceACK protocol:(SDLProtocol *)protocol;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProtocolDelegate.h:39]:
```suggestion
- (void)protocol:(SDLProtocol *)protocol didReceiveEndServiceACK:(SDLProtocolMessage *)endServiceACK {
```

File: SmartDeviceLink/SDLProtocolDelegate.h [hunk 7]
```diff
@@ -11,78 +12,85 @@ NS_ASSUME_NONNULL_BEGIN
...
+
+/// Called when the end service frame fails.
+/// @discussion This frame can be sent on both the primary and secondary transports
+/// @param endServiceNAK A SDLProtocolMessage object
+/// @param protocol The transport's protocol
+- (void)handleProtocolEndServiceNAKMessage:(SDLProtocolMessage *)endServiceNAK protocol:(SDLProtocol *)protocol;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProtocolDelegate.h:45]:
```suggestion
- (void)protocol:(SDLProtocol *)protocol didReceiveEndServiceNAK:(SDLProtocolMessage *)endServiceNAK {
```

File: SmartDeviceLink/SDLProtocolDelegate.h [hunk 8]
```diff
@@ -11,78 +12,85 @@ NS_ASSUME_NONNULL_BEGIN
...
+
+#pragma mark Secondary Transport Messages
+
+/// Called when the secondary transport registration frame succeeds.
+/// @discussion This frame is only sent on the secondary transport
+/// @param registerSecondaryTransportACK A SDLProtocolMessage object
+/// @param protocol The transport's protocol
+- (void)handleProtocolRegisterSecondaryTransportACKMessage:(SDLProtocolMessage *)registerSecondaryTransportACK protocol:(SDLProtocol *)protocol;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProtocolDelegate.h:53]:
```suggestion
- (void)protocol:(SDLProtocol *)protocol didReceiveRegisterSecondaryTransportACK:(SDLProtocolMessage *)registerSecondaryTransportACK {
```

File: SmartDeviceLink/SDLProtocolDelegate.h [hunk 9]
```diff
@@ -11,78 +12,85 @@ NS_ASSUME_NONNULL_BEGIN
...
+
+/// Called when the secondary transport registration frame fails.
+/// @discussion This frame is only sent on the secondary transport
+/// @param registerSecondaryTransportNAK A SDLProtocolMessage object
+/// @param protocol The transport's protocol
+- (void)handleProtocolRegisterSecondaryTransportNAKMessage:(SDLProtocolMessage *)registerSecondaryTransportNAK protocol:(SDLProtocol *)protocol;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProtocolDelegate.h:59]:
```suggestion
- (void)protocol:(SDLProtocol *)protocol didReceiveRegisterSecondaryTransportNAK:(SDLProtocolMessage *)registerSecondaryTransportNAK {
```

File: SmartDeviceLink/SDLProtocolDelegate.h [hunk 10]
```diff
@@ -11,78 +12,85 @@ NS_ASSUME_NONNULL_BEGIN
...
+
+/// Called when the status or configuration of one or more transports has updated.
+/// @discussion This frame is only sent on the primary transport
+/// @param transportEventUpdate A SDLProtocolMessage object
+/// @param protocol The transport's protocol
+- (void)handleTransportEventUpdateMessage:(SDLProtocolMessage *)transportEventUpdate protocol:(SDLProtocol *)protocol;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProtocolDelegate.h:65]:
```suggestion
- (void)protocol:(SDLProtocol *)protocol didReceiveTransportEventUpdate:(SDLProtocolMessage *)transportEventUpdate {
```

File: SmartDeviceLink/SDLProtocolDelegate.h [hunk 11]
```diff
@@ -11,78 +12,85 @@ NS_ASSUME_NONNULL_BEGIN
...
-
-/**
- *  Called when an error is notified from transport.
- *
- *  Note: currently, this is used only by TCP transport.
- *
- *  @param error The type of the error
- */
-- (void)onTransportError:(NSError *)error;
+#pragma mark - Transport Lifecycle
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProtocolDelegate.h:78]: Move above the deprecated methods

File: SmartDeviceLink/SDLProtocolDelegate.h [hunk 12]
```diff
@@ -11,78 +12,85 @@ NS_ASSUME_NONNULL_BEGIN
...
+
+/// Called when the transport opens.
+/// @param protocol The transport's protocol
+- (void)onProtocolOpened:(SDLProtocol *)protocol;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProtocolDelegate.h:82]:
```suggestion
- (void)protocolDidOpen:(SDLProtocol *)protocol;
```

File: SmartDeviceLink/SDLProtocolDelegate.h [hunk 13]
```diff
@@ -11,78 +12,85 @@ NS_ASSUME_NONNULL_BEGIN
...
+
+/// Called when the transport closes.
+/// @param protocol The transport's protocol
+- (void)onProtocolClosed:(SDLProtocol *)protocol;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProtocolDelegate.h:86]:
```suggestion
- (void)protocolDidClose:(SDLProtocol *)protocol;
```

File: SmartDeviceLink/SDLProtocolDelegate.h [hunk 14]
```diff
@@ -11,78 +12,85 @@ NS_ASSUME_NONNULL_BEGIN
...
+
+/// Called when the transport errors.
+/// @discussion Currently only used by TCP transport.
+/// @param error The error
+/// @param protocol The transport's protocol
+- (void)onTransportError:(NSError *)error protocol:(SDLProtocol *)protocol;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLProtocolDelegate.h:92]:
```suggestion
- (void)protocol:(SDLProtocol *)protocol transportDidError:(NSError *)error;
```

File: SmartDeviceLink/SDLProtocolDelegate.h (hunk 3 above)
Comment (joeljfischer) [reply SmartDeviceLink/SDLProtocolDelegate.h:21]: I'm sorry 😬

File: SmartDeviceLink/SDLStreamingAudioLifecycleManager.m [hunk 15]
```diff
@@ -208,27 +208,27 @@ - (void)handleProtocolStartServiceACKMessage:(SDLProtocolMessage *)startServiceA
...
     [self.audioStreamStateMachine transitionToState:SDLAudioStreamManagerStateStopped];
 }
 
-- (void)handleProtocolEndServiceNAKMessage:(SDLProtocolMessage *)endServiceNAK {
+- (void)handleProtocolEndServiceNAKMessage:(SDLProtocolMessage *)endServiceNAK protocol:(SDLProtocol *)protocol {
     if (endServiceNAK.header.serviceType != SDLServiceTypeAudio) { return; }
 
     SDLControlFramePayloadNak *nakPayload = [[SDLControlFramePayloadNak alloc] initWithData:endServiceNAK.payload];
-    SDLLogE(@"Request to end audio service NAKed with playlod: %@", nakPayload);
+    SDLLogE(@"Request to end audio service NAKed on transport %@, with playlod: %@", protocol.transport, nakPayload);
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLStreamingAudioLifecycleManager.m:231]:
```suggestion
    SDLLogE(@"Request to end audio service NAKed on transport %@, with payload: %@", protocol.transport, nakPayload);
```

File: SmartDeviceLink/SDLProtocolDelegate.h (hunk 11 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLProtocolDelegate.h:78]: Fixed

File: SmartDeviceLink/SDLLifecycleProtocolHandler.m [hunk 16]
```diff
@@ -81,25 +83,38 @@ - (void)onProtocolOpened {
...
     [self.rpcStartServiceTimeoutTimer start];
 }
 
+/// Helper method for closing the current session
+- (void)sdl_closeSessionWithDelay:(float)delay {
+    __weak typeof(self) weakSelf = self;
+    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delay * NSEC_PER_SEC)), dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
+        [weakSelf protocolDidClose:self.protocol];
+    });
+}
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLifecycleProtocolHandler.m:98]:
```suggestion
```

File: SmartDeviceLink/SDLLifecycleProtocolHandler.m [hunk 17]
```diff
@@ -81,25 +83,38 @@ - (void)onProtocolOpened {
         __weak typeof(self) weakSelf = self;
         self.rpcStartServiceTimeoutTimer.elapsedBlock = ^{
             SDLLogE(@"Start session timed out after %f seconds, closing the connection.", StartSessionTime);
-            [weakSelf performSelector:@selector(onProtocolClosed) withObject:nil afterDelay:0.1];
+            [weakSelf sdl_closeSessionWithDelay:(float)0.1];
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLifecycleProtocolHandler.m:86]:
```suggestion
            [weakSelf.protocol stopWithCompletionHandler:^{}];
```

Comment (joeljfischer) [reply SmartDeviceLink/SDLLifecycleProtocolHandler.m:86]: In my testing, this does the same thing and is a bit cleaner.

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 18]
```diff
@@ -536,10 +540,13 @@ - (BOOL)sdl_isTCPReady {
     return YES;
 }
 
-#pragma mark - SDLProtocolListener Implementation
+#pragma mark - SDLProtocolDelegate Implementation
 
 // called on transport's thread, notifying that the transport is established
-- (void)onProtocolOpened {
+- (void)protocolDidOpen:(SDLProtocol *)protocol {
+    // The primary transport opened
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m:547]:
```suggestion
```

This is actually checking for the secondary transport, right? As noted by the log below.

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 19]
```diff
@@ -594,19 +607,21 @@ - (void)sdl_transportClosed {
 }
 
 // called from SDLProtocol's _receiveQueue of secondary transport
-- (void)handleProtocolRegisterSecondaryTransportACKMessage:(SDLProtocolMessage *)registerSecondaryTransportACK {
-    SDLLogD(@"Received Register Secondary Transport ACK frame");
+- (void)protocol:(SDLProtocol *)protocol didReceiveRegisterSecondaryTransportACK:(SDLProtocolMessage *)registerSecondaryTransportACK {
+    if (self.secondaryProtocol != protocol) { return; }
 
+    SDLLogD(@"Received Register Secondary Transport ACK frame");
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m:613]:
```suggestion
    SDLLogD(@"Received Register Secondary Transport ACK on the secondary (%@) transport", protocol.transport);
```

File: SmartDeviceLink/SDLSecondaryTransportManager.m [hunk 20]
```diff
@@ -594,19 +607,21 @@ - (void)sdl_transportClosed {
...
     });
 }
 
 // called from SDLProtocol's _receiveQueue of secondary transport
-- (void)handleProtocolRegisterSecondaryTransportNAKMessage:(SDLProtocolMessage *)registerSecondaryTransportNAK {
-    SDLLogW(@"Received Register Secondary Transport NAK frame");
+- (void)protocol:(SDLProtocol *)protocol didReceiveRegisterSecondaryTransportNAK:(SDLProtocolMessage *)registerSecondaryTransportNAK {
+    if (self.secondaryProtocol != protocol) { return; }
 
+    SDLLogW(@"Received Register Secondary Transport NAK frame");
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLSecondaryTransportManager.m:624]:
```suggestion
    SDLLogW(@"Received Register Secondary Transport NAK on the secondary (%@) transport", protocol.transport);
```

File: SmartDeviceLink/SDLStreamingAudioLifecycleManager.m [hunk 21]
```diff
@@ -190,10 +190,10 @@ - (void)didEnterStateAudioStreamShuttingDown {
     [self.protocol endServiceWithType:SDLServiceTypeAudio];
 }
 
-#pragma mark - SDLProtocolListener
+#pragma mark - SDLProtocolDelegate
 #pragma mark Start Service ACK/NAK
 
-- (void)handleProtocolStartServiceACKMessage:(SDLProtocolMessage *)startServiceACK {
+- (void)protocol:(SDLProtocol *)protocol didReceiveStartServiceACK:(SDLProtocolMessage *)startServiceACK {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLStreamingAudioLifecycleManager.m:196]: Update the debug log in here with the transport info?

File: SmartDeviceLink/SDLStreamingAudioLifecycleManager.m [hunk 22]
```diff
@@ -208,27 +208,27 @@ - (void)handleProtocolStartServiceACKMessage:(SDLProtocolMessage *)startServiceA
     [self.audioStreamStateMachine transitionToState:SDLAudioStreamManagerStateReady];
 }
 
-- (void)handleProtocolStartServiceNAKMessage:(SDLProtocolMessage *)startServiceNAK {
+- (void)protocol:(SDLProtocol *)protocol didReceiveStartServiceNAK:(SDLProtocolMessage *)startServiceNAK {
     if (startServiceNAK.header.serviceType != SDLServiceTypeAudio) { return; }
-    SDLLogE(@"Request to start audio service NAKed");
+    SDLLogE(@"Request to start audio service NAKed on transport %@", protocol.transport);
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLStreamingAudioLifecycleManager.m:213]: Add payload like end NAK below

File: SmartDeviceLink/SDLStreamingVideoLifecycleManager.m [hunk 23]
```diff
@@ -546,11 +545,11 @@ - (void)handleProtocolStartServiceACKMessage:(SDLProtocolMessage *)startServiceA
     [self.videoStreamStateMachine transitionToState:SDLVideoStreamManagerStateReady];
 }
 
-- (void)handleProtocolStartServiceNAKMessage:(SDLProtocolMessage *)startServiceNAK {
+- (void)protocol:(SDLProtocol *)protocol didReceiveStartServiceNAK:(SDLProtocolMessage *)startServiceNAK {
     if (startServiceNAK.header.serviceType != SDLServiceTypeVideo) { return; }
 
     SDLControlFramePayloadNak *nakPayload = [[SDLControlFramePayloadNak alloc] initWithData:startServiceNAK.payload];
-    SDLLogE(@"Request to start video service NAKed with reason: %@", nakPayload.description);
+    SDLLogE(@"Request to start video service NAKed on transport %@, with reason: %@", protocol.transport, nakPayload.description);
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLStreamingVideoLifecycleManager.m:552]:
```suggestion
    SDLLogE(@"Request to start video service NAKed on transport %@, with payload: %@", protocol.transport, nakPayload);
```

File: SmartDeviceLink/SDLStreamingVideoLifecycleManager.m [hunk 24]
```diff
@@ -574,18 +573,18 @@ - (void)handleProtocolStartServiceNAKMessage:(SDLProtocolMessage *)startServiceN
...
     [self.videoStreamStateMachine transitionToState:SDLVideoStreamManagerStateStopped];
 }
 
-- (void)handleProtocolEndServiceNAKMessage:(SDLProtocolMessage *)endServiceNAK {
+- (void)protocol:(SDLProtocol *)protocol didReceiveEndServiceNAK:(SDLProtocolMessage *)endServiceNAK {
     if (endServiceNAK.header.serviceType != SDLServiceTypeVideo) { return; }
 
     SDLControlFramePayloadNak *nakPayload = [[SDLControlFramePayloadNak alloc] initWithData:endServiceNAK.payload];
-    SDLLogE(@"Request to end video service NAKed with payload: %@", nakPayload);
+    SDLLogE(@"Request to end video service NAKed on transport %@, with reason: %@", protocol.transport, nakPayload);
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLStreamingVideoLifecycleManager.m:587]:
```suggestion
    SDLLogE(@"Request to end video service NAKed on transport %@, with payload: %@", protocol.transport, nakPayload);
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleProtocolHandlerSpec.m [hunk 25]
```diff
@@ -150,6 +150,20 @@ @interface SDLLifecycleProtocolHandler ()
...
+                testHandler.rpcStartServiceTimeoutTimer = nil;
+            });
+
+            it(@"should send a transport disconnected notification when the timer elapses", ^{
+                OCMExpect([mockNotificationDispatcher postNotificationName:[OCMArg isEqual:SDLTransportDidDisconnect] infoObject:[OCMArg isNil]]);
+
+                [testHandler protocolDidOpen:mockProtocol];
+
+                OCMVerifyAllWithDelay(mockNotificationDispatcher, 11.0);
+            });
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleProtocolHandlerSpec.m:164]: This would need to update if you change to `[protocol stop]`

File: SmartDeviceLink/SDLStreamingAudioLifecycleManager.m (hunk 21 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLStreamingAudioLifecycleManager.m:196]: Added.

File: SmartDeviceLink/SDLStreamingAudioLifecycleManager.m (hunk 22 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLStreamingAudioLifecycleManager.m:213]: Added

File: SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleProtocolHandlerSpec.m (hunk 25 above)
Comment (NicoleYarroch) [reply SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleProtocolHandlerSpec.m:164]: Fixed
