### PR TITLE
Fixed empty string bug in Menu Cell texts

### LINKED ISSUE #1923: Empty string bug with Menu Cell
### Bug Report
If we set an empty string (i.e. `""`) for `secondaryText` or `tertiaryText`, when creating a `SDLMenuCell` object we should send a `nil` instead. Otherwise core will reject the request.

##### Reproduction Steps
1. Define an `SDLMenuCell`
2. Set the secondary `secondaryText` or `tertiaryText` property of `SDLMenuCell` to an empty string (i.e. `""`)
3. Launch app

##### Expected Behavior
The response from core should not present any error

##### Observed Behavior
The response from core is the following
```
{
    info = "RPC.msg_params.menuParams.secondaryText: Got string of size: 0, minimum allowed: 1";
    resultCode = "INVALID_DATA";
    success = 0;
}
```

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: branch develop
* Testing Against: generic_hmi

##### Test Case, Sample Code, and / or Example App
N/A

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1923 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: Branch develop
HMI name / version / branch / commit hash / module tested against: Generic/ branch develop

### Summary
In case the secondaryText or tertiaryText are being set with an empty string, replace it with nil instead.

##### Breaking Changes
* In case the secondaryText or tertiaryText are being set with an empty string, replace it with nil instead.

##### Enhancements
* N/A

##### Bug Fixes
* N/A

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 1]
```diff
@@ -673,8 +673,8 @@ - (SDLAddCommand *)sdl_commandForMenuCell:(SDLMenuCell *)cell withArtwork:(BOOL)
     params.menuName = cell.title;
     params.parentID = cell.parentCellId != UINT32_MAX ? @(cell.parentCellId) : nil;
     params.position = @(position);
-    params.tertiaryText = cell.tertiaryText;
-    params.secondaryText = cell.secondaryText;
+    params.secondaryText = ([cell.secondaryText isEqualToString:@""]) ? nil : cell.secondaryText;
+    params.tertiaryText = ([cell.tertiaryText isEqualToString:@""]) ? nil : cell.tertiaryText;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:677]:
```suggestion
    params.secondaryText = (cell.secondaryText.length == 0) ? nil : cell.secondaryText;
    params.tertiaryText = (cell.tertiaryText.length == 0) ? nil : cell.tertiaryText;
```

File: SmartDeviceLink/private/SDLMenuManager.m [hunk 2]
```diff
@@ -695,7 +695,11 @@ - (SDLAddSubMenu *)sdl_subMenuCommandForMenuCell:(SDLMenuCell *)cell withArtwork
     } else {
         submenuLayout = self.menuConfiguration.defaultSubmenuLayout;
     }
-    return [[SDLAddSubMenu alloc] initWithMenuID:cell.cellId menuName:cell.title position:@(position) menuIcon:icon menuLayout:submenuLayout parentID:nil secondaryText:cell.secondaryText tertiaryText:cell.tertiaryText secondaryImage:secondaryImage];
+    
+    NSString *secondaryText = ([cell.secondaryText isEqualToString:@""]) ? nil : cell.secondaryText;
+    NSString *tertiaryText = ([cell.tertiaryText isEqualToString:@""]) ? nil : cell.tertiaryText;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLMenuManager.m:700]:
```suggestion
    NSString *secondaryText = (cell.secondaryText.length == 0) ? nil : cell.secondaryText;
    NSString *tertiaryText = (cell.tertiaryText.length == 0) ? nil : cell.tertiaryText;
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]
