### PR TITLE
Cell Icons do not show up on first menu set

### LINKED ISSUE #1312: Cell Icons are a no show the first time a menu is set
### Bug Report
It only happens the first time I send a menu if I send 1 menu item with artwork or 100 menu items with the same artwork, the DeleteCommands are never sent. If I send 100 menu items with different artworks, the DeleteCommands are sent.

##### Reproduction Steps
1. Set a menu with artwork 
2. Open menu and notice cells have no icon

##### Expected Behavior
Cells should have icons

##### Observed Behavior
Cells have no icons

### PR DESCRIPTION
**Pull request by justingluck93**
Fixes #1312

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
Added an array to only delete the cells that have artwork so we don't over deleted or over add

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLMenuManager.m [hunk 1]
```diff
@@ -315,10 +316,10 @@ - (void)sdl_updateMenuWithCellsToDelete:(NSArray<SDLMenuCell *> *)deleteCells ce
         self.hasQueuedUpdate = YES;
         return;
     }
-
     __weak typeof(self) weakself = self;
     [self sdl_sendDeleteCurrentMenu:deleteCells withCompletionHandler:^(NSError * _Nullable error) {
         [weakself sdl_sendUpdatedMenu:addCells usingMenu:weakself.menuCells withCompletionHandler:^(NSError * _Nullable error) {
+
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLMenuManager.m]: Remove this extra line
