### PR TITLE
Fix for  Two voiceCommands contains the same string

### LINKED ISSUE #1959: Two voiceCommands contains the same string
### Bug Report
When two voice commands contain the same string, the update should be aborted

##### Reproduction Steps
1. Upload a voiceCommandA and voiceCommandB that contains the same string in voiceCommandA

##### Expected Behavior
The upload should be aborted

##### Observed Behavior
The upload continues

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1959 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit test added in `SDLVoiceCommandManagerSpec`

#### Core Tests
Test applied below was done on the example app.
1. Modified ProxyManager to send voiceCommands [] in the initial state(When app is launched on hmi)
`voiceCommandA = ["Test 1", "Test 2"];
voiceCommandB = ["Test 2", "Test 3"];
screenManager.voiceCommands = [voiceCommandA, voiceCommandB]`;

`SDLVoiceCommandManager` should not send an updateOperation

Core version / branch / commit hash / module tested against: 7.1.0
HMI name / version / branch / commit hash / module tested against: generic_hmi -> release/0.10.0, sdl_hmi -> release/5.5.0, SYNC 3

### Summary
The upload request of new voiceCommands should fail in case 2 voiceCommands contains the same string

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* The upload request of new voiceCommands should fail in case 2 voiceCommands contains the same string

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m [hunk 1]
```diff
@@ -57,6 +57,21 @@ - (void)start {
     }
 
     __weak typeof(self) weakSelf = self;
+
+    // Evaluate the pendingVoiceCommands to check if there is two or more voiceCommands with the same string
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m:61]: This should be done in `SDLVoiceCommandManager` so that the operation isn't even created if it's not needed. Encapsulate it into a class method there.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Comment by joeljfischer** [comment]
According to your PR description, you did not test this against any Core version. Please do so before review.

**Comment by joeljfischer** [comment]
My last comment was not addressed. In addition, `n/a` is not correct for the unit tests section.

**Comment by joeljfischer** [comment]
You still have not listed the tests you performed for this PR on Core, additionally, please test on v7.1.0 final of Core and list the version of Generic HMI you tested with (and make sure it's a final version).

File: SmartDeviceLink/private/SDLVoiceCommandManager.m [hunk 2]
```diff
@@ -146,6 +150,22 @@ - (void)sdl_updateIdsOnVoiceCommands:(NSArray<SDLVoiceCommand *> *)voiceCommands
...
+        for (NSString *voiceCommandString in voiceCommand.voiceCommands) {
+            if ([voiceCommandSets containsObject:voiceCommandString]) {
+                SDLLogE(@"Failed to upload voice commands for having duplicate strings in different voiceCommands %@", nil);
+                return NO;
+            } else {
+                [voiceCommandSets addObject:voiceCommandString];
+            }
+        }
+    }
+    return YES;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLVoiceCommandManager.m:166]:
```suggestion
    NSUInteger voiceCommandCount = 0;
    NSMutableSet<NSString *> *voiceCommandsSet = [[NSMutableSet alloc] init];
    for (SDLVoiceCommand *voiceCommand in voiceCommands) {
        [voiceCommandsSet addObjectsFromArray:voiceCommand.voiceCommands];
    }

    return (voiceCommandsSet.count == voiceCommandCount)
```

I think this is simpler and probably faster.

File: SmartDeviceLink/public/SDLVoiceCommand.m [hunk 3]
```diff
@@ -32,6 +33,25 @@ - (NSString *)description {
...
+    if (![object isMemberOfClass:[self class]]) { return NO; }
+
+    return [self isEqualToVoiceCommand:(SDLVoiceCommand *)object];
+}
+
+- (BOOL)isEqualToVoiceCommand:(SDLVoiceCommand *)voiceCommand {
+    if (voiceCommand == nil) { return NO; }
+
+    return (self.hash == voiceCommand.hash);
+}
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLVoiceCommand.m:53]: None of this seems necessary for this PR.

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 4]
```diff
@@ -155,6 +157,19 @@ @interface SDLVoiceCommandManager()
...
             });
         });
+
+        // updating voice commands with duplicate string in different voice commands
+        describe(@"when new voice commands are set and have duplicate strings in different voice commands", ^{
+            beforeEach(^{
+                testManager.voiceCommands = @[testVoiceCommand2, testVoiceCommand3];
+            });
+
+            // should queue another operation
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:167]:
```suggestion
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLVoiceCommandManager.m [hunk 5]
```diff
@@ -115,8 +115,14 @@ - (void)setVoiceCommands:(NSArray<SDLVoiceCommand *> *)voiceCommands {
     // Set the new voice commands internally
     _voiceCommands = voiceCommands;
 
+    if (![self sdl_arePendingVoiceCommandsUnique:voiceCommands]) {
+        SDLLogE(@"Not all voice command strings are unique across all voice commands. Voice commands will not be set.");
+        return;
+    }
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLVoiceCommandManager.m:121]: This needs to be done before setting the voice commands in L116 or else it doesn't work properly.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]
