### PR TITLE
include userLocation in SetGlobalProperties init

### LINKED ISSUE #1771: `SetGlobalProperties` init is missing `userLocation`
### Bug Report
`userLocation` variable is not included when initializing `SetGlobalProperties`.

##### Reproduction Steps
1. Look for SDLSetGlobalProperties.
2. Check init function.

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: [What version of the library has this bug been seen on]
* Testing Against: N/A

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1771

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
included 'userLocation' variable in SetGlobalProperties init.

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* included 'userLocation' variable in SetGlobalProperties init and deprecated the previous one.

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/public/SDLSetGlobalProperties.h [hunk 1]
```diff
@@ -69,7 +69,24 @@ NS_ASSUME_NONNULL_BEGIN
...
+ @param vrHelp The items of the help interface prompt
+ @param menuTitle The title of the menu button
+ @param menuIcon The icon on the menu button
+ @param keyboardProperties The properties of a keyboard prompt
+ @param userLocation userLocation
+ @param menuLayout The layout of the top-level main menu
+ @return The SetGlobalProperties RPC
+ */
+
+- (instancetype)initWithHelpText:(nullable NSString *)helpText timeoutText:(nullable NSString *)timeoutText vrHelpTitle:(nullable NSString *)vrHelpTitle vrHelp:(nullable NSArray<SDLVRHelpItem *> *)vrHelp menuTitle:(nullable NSString *)menuTitle menuIcon:(nullable SDLImage *)menuIcon keyboardProperties:(nullable SDLKeyboardProperties *)keyboardProperties userLocation:(nullable SDLSeatLocation *)userLocation menuLayout:(nullable SDLMenuLayout)menuLayout;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLSetGlobalProperties.h:89]: Instead of tweaking an existing init, just use the generated (i.e. use the RPC spec generator) init for `SDLSetGlobalProperties`.

File: SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSetGlobalPropertiesSpec.m [hunk 2]
```diff
@@ -20,6 +20,10 @@
 
 QuickSpecBegin(SDLSetGlobalPropertiesSpec)
 
+NSString *menuTitle = @"TheNewMenu";
+NSString *vrHelpTitle = @"vr";
+NSString *helpTest =@"TheHelpText";
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSetGlobalPropertiesSpec.m:25]:
```suggestion
NSString *helpTest = @"TheHelpText";
```

File: SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSetGlobalPropertiesSpec.m [hunk 3]
```diff
@@ -20,6 +20,10 @@
...
+NSString *timeoutTest =@"timeout Test";
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSetGlobalPropertiesSpec.m:26]:
```suggestion
NSString *timeoutTest = @"timeout Test";
```

File: SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSetGlobalPropertiesSpec.m [hunk 4]
```diff
@@ -89,6 +93,28 @@
...
+
+    it(@"Should return new init", ^ {
+        SDLSetGlobalProperties* testRequest = [[SDLSetGlobalProperties alloc] initWithHelpText:helpTest timeoutText:timeoutTest vrHelpTitle:vrHelpTitle vrHelp:[@[help] mutableCopy] menuTitle:menuTitle menuIcon:image keyboardProperties:keyboard menuLayout:nil];
+        
+        SDLSetGlobalProperties* testRequest2 = [[SDLSetGlobalProperties alloc] initWithHelpText:helpTest timeoutText:timeoutTest vrHelpTitle:vrHelpTitle vrHelp:[@[help] mutableCopy] menuTitle:menuTitle menuIcon:image keyboardProperties:keyboard userLocation:nil menuLayout:nil];
+
+        expect(testRequest).to(equal(testRequest2));
+    });
+    
+    it(@"Should set initWithHelpText", ^ {
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSetGlobalPropertiesSpec.m:105]: If there are a lot of inits, use the full method name so it is easier to see which method is being tested. Something like:

"Should initialize correctly with initWithHelpText:timeoutText:vrHelpTitle:vrHelp:menuTitle:menuIcon:keyboardProperties:userLocation:menuLayout:"

File: SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSetGlobalPropertiesSpec.m [hunk 5]
```diff
@@ -89,6 +93,28 @@
         expect(testRequest.keyboardProperties).to(beNil());
         expect(testRequest.userLocation).to(beNil());
     });
+
+    it(@"Should return new init", ^ {
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSetGlobalPropertiesSpec.m:97]: It looks like there were never tests written for the other inits. Can you add a test for each `init` that is missing a test. The **SDLAppServiceManifestSpec** is a good example of how we add tests for each `init` and how to suppress warnings for deprecated inits.

File: SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSetGlobalPropertiesSpec.m [hunk 6]
```diff
@@ -89,6 +93,28 @@
...
+        expect(testRequest).to(equal(testRequest2));
+    });
+    
+    it(@"Should set initWithHelpText", ^ {
+        SDLSetGlobalProperties* testRequest = [[SDLSetGlobalProperties alloc] initWithHelpText:helpTest timeoutText:timeoutTest vrHelpTitle:vrHelpTitle vrHelp:[@[help] mutableCopy] menuTitle:menuTitle menuIcon:image keyboardProperties:keyboard userLocation:seatLocation menuLayout:nil];
+        
+        expect(testRequest.helpPrompt).to(equal([SDLTTSChunk textChunksFromString:helpTest]));
+        expect(testRequest.timeoutPrompt).to(equal([SDLTTSChunk textChunksFromString:timeoutTest]));
+        expect(testRequest.vrHelpTitle).to(equal(vrHelpTitle));
+        expect(testRequest.vrHelp).to(equal([@[help] mutableCopy]));
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSetGlobalPropertiesSpec.m:111]: We can get rid of all `mutableCopy`s in this file as they are not necessary.

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
Left some comments

File: SmartDeviceLink/public/SDLSetGlobalProperties.h [hunk 7]
```diff
@@ -69,7 +69,24 @@ NS_ASSUME_NONNULL_BEGIN
...
+ @param vrHelpTitle The title of the help interface prompt
+ @param vrHelp The items of the help interface prompt
+ @param menuTitle The title of the menu button
+ @param menuIcon The icon on the menu button
+ @param keyboardProperties The properties of a keyboard prompt
+ @param userLocation userLocation
+ @param menuLayout The layout of the top-level main menu
+ @return The SetGlobalProperties RPC
+ */
+
```
Comment (NicoleYarroch) [inline SmartDeviceLink/public/SDLSetGlobalProperties.h:88]:
```suggestion
/**
 * Convenience init for setting all possible global properties
 * 
 * @param userLocation - userLocation
 * @param helpPrompt - helpPrompt
 * @param timeoutPrompt - timeoutPrompt
 * @param vrHelpTitle - vrHelpTitle
 * @param vrHelp - vrHelp
 * @param menuTitle - menuTitle
 * @param menuIcon - menuIcon
 * @param keyboardProperties - keyboardProperties
 * @param menuLayout - menuLayout
 * @return A SDLSetGlobalProperties object
 */
```

Comment (NicoleYarroch) [reply SmartDeviceLink/public/SDLSetGlobalProperties.h:88]: I just copied the generated docs for the init since the order of the parameters in old doc do not match the order for the new init. I added a custom description since it is not created by the RPC spec generator.

**Review by NicoleYarroch — APPROVED** [review]
