### PR TITLE
RPC Spec Alignment for 7.1 Issues

### LINKED ISSUE #1899: RPC Spec 7.1 alignment
### Bug Report
Alignment with rpc spec 7.1 changes on the following issues: 206, 237, 276, 307

##### Reproduction Steps
N/A

##### Expected Behavior
N/A

##### Observed Behavior
N/A

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: 7.1
* Testing Against: N/A

##### Test Case, Sample Code, and / or Example App
N/A

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1899 

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit test added for new constructor method in SDLShow

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Alignment with rpc spec PRs

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* N/A

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/public/SDLShow.h [hunk 1]
```diff
@@ -231,7 +251,7 @@ NS_ASSUME_NONNULL_BEGIN
  *            will not display anything)</li>
  *            </ul>
  */
-@property (strong, nonatomic, nullable) NSString *mediaClock;
+@property (strong, nonatomic, nullable) NSString *mediaClock __deprecated;
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLShow.h:254]: The generated comment for this should say something about when it was deprecated. Please include that.

File: SmartDeviceLink/public/SDLTextFieldName.h [hunk 2]
```diff
@@ -82,7 +82,7 @@ extern SDLTextFieldName const SDLTextFieldNameStatusBar;
  *
  * @discussion This field is commonly used to show elapsed or remaining time in an audio track or audio capture.
  */
-extern SDLTextFieldName const SDLTextFieldNameMediaClock;
+extern SDLTextFieldName const SDLTextFieldNameMediaClock __deprecated;
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLTextFieldName.h:85]: The generated comment for this should include information about when it was deprecated. Please include that information in this comment.

File: SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m [hunk 3]
```diff
@@ -74,8 +74,11 @@ + (void)configure:(Configuration *)configuration {
     sharedExamples(@"unable to send an RPC", ^(QCKDSLSharedExampleContext exampleContext) {
         it(@"cannot publicly send RPCs", ^{
             SDLLifecycleManager *testManager = exampleContext()[@"manager"];
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
             SDLShow *testShow = [[SDLShow alloc] initWithMainField1:@"test" mainField2:nil alignment:nil];
-            
+#pragma clang diagnostic pop
+
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m:81]: Change this instead to use the new initializer

File: SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m [hunk 4]
```diff
@@ -530,7 +533,10 @@ + (void)configure:(Configuration *)configuration {
             });
 
             it(@"can send an RPC of type Request", ^{
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
                 SDLShow *testShow = [[SDLShow alloc] initWithMainField1:@"test" mainField2:nil alignment:nil];
+#pragma clang diagnostic pop
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m:539]: Change this instead to use the new initializer.

File: SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleProtocolHandlerSpec.m [hunk 5]
```diff
@@ -202,7 +202,10 @@ @interface SDLLifecycleProtocolHandler ()
 
         context(@"of a protocol message", ^{
             beforeEach(^{
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
                 SDLShow *showRPC = [[SDLShow alloc] initWithMainField1:@"Test1" mainField2:@"Test2" alignment:SDLTextAlignmentLeft];
+#pragma clang diagnostic pop
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleProtocolHandlerSpec.m:208]: Use the new initializer instead.

File: SmartDeviceLinkTests/Notifications/SDLResponseDispatcherSpec.m [hunk 6]
```diff
@@ -125,7 +125,10 @@
         __block NSUInteger numTimesHandlerCalled = 0;
         
         beforeEach(^{
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
             testShow = [[SDLShow alloc] initWithMainField1:@"Test Show" mainField2:nil alignment:SDLTextAlignmentCenter];
+#pragma clang diagnostic pop
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/Notifications/SDLResponseDispatcherSpec.m:131]: Use the new initializer instead

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]

**Review by joeljfischer — APPROVED** [review]
@FrankElias77 Please merge develop and fix merge conflicts, then this is okay to merge.
