### PR TITLE
Reset screen manager after disconnects

### LINKED ISSUE #952: Menu Manager is not reset on disconnection
The *SDLMenuManager*s `lastMenuId`, `menuCells` and `oldMenuCells`  vars are not reset on disconnection from the head unit. This means that menu items are deleted that we know do not exist (this seems to cause `Media component does not respond` errors on SYNC 3).  

### Bug Report
The *SDLMenuManager* should be reset when the phone disconnects from a head unit.

##### Reproduction Steps
1. Connect the app to the head unit and open the SDL app
1. Disconnect the app from the head unit
1. Reconnect the app to the head unit and open the SDL app

##### Expected Behavior
The menu manager should not attempt to delete `oldMenuCells` as they no longer exist on the SDL app.

##### Observed Behavior
The menu manager attempts to delete `oldMenuCells`.

##### OS & Version Information
* iOS Version: 11.3
* SDL iOS Version: 5.3
* Testing Against: TDK (SYNC 3)

##### Test Case, Sample Code, and / or Example App
The SDL_iOS example app

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #952, #953

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
Smoke tests

### Summary
Fixes the `SDLScreenManager` not being reset when the app is reconnected to a head unit during a session. Menus, images, and buttons were not being set correctly on reconnects due the saved settings in the `SDLScreenManager`'s sub managers. 

##### Enhancements
* The `SDLTextAndGraphicManager`, `SDLSoftButtonManager`, `SDLMenuManager`, and `SDLVoiceCommandManager` are now reset when the app disconnects from the head unit. 

##### Bug Fixes
* Added a `nil` check for a menu cell's handler before it is called.

##### Tasks Remaining
- [x] Fix broken test cases

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLTextAndGraphicManager.m [hunk 1]
```diff
@@ -52,7 +52,7 @@ A show describing the current text and images on the screen (not soft buttons, e
 @property (strong, nonatomic, nullable) SDLDisplayCapabilities *displayCapabilities;
 @property (strong, nonatomic, nullable) SDLHMILevel currentLevel;
 
-@property (strong, nonatomic) SDLArtwork *blankArtwork;
+@property (strong, nonatomic, nullable) SDLArtwork *blankArtwork;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLTextAndGraphicManager.m]: This shouldn't be reset to nil

File: SmartDeviceLink/SDLTextAndGraphicManager.m [hunk 2]
```diff
@@ -589,7 +614,7 @@ - (BOOL)hasQueuedUpdate {
     return (_hasQueuedUpdate || _queuedUpdateHandler != nil);
 }
 
-- (SDLArtwork *)blankArtwork {
+- (nullable SDLArtwork *)blankArtwork {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLTextAndGraphicManager.m]: Shouldn't reset to nil

**Comment by joeljfischer** [comment]
That was meant to be a "request changes"

File: SmartDeviceLink/SDLTextAndGraphicManager.m (hunk 1 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLTextAndGraphicManager.m]: As mentioned in issue #953, I am getting a `sdl_fileManager_fileDoesNotExistError` for the blank artwork when I try to use it on reconnects. Setting the blank artwork to `nil` on disconnect was the only way I could fix problem.

Comment (joeljfischer) [reply SmartDeviceLink/SDLTextAndGraphicManager.m]: In that case, put a comment explaining that where it's reset.
