### PR TITLE
Fix SDLManagerDelegate missing videoStreamingState callback

### LINKED ISSUE #1546: SDLManagerDelegate is missing videoStreamingState callback
### Bug Report
All of the `OnHMIStatus` parameters have their own individual callback in `SDLManagerDelegate`, but `videoStreamingState` is missing.

##### Reproduction Steps
n/a

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.5.1
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1546 

This PR is **not ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Added unit tests to ensure that `videoStreamingState` callback was called when it changed.

#### Core Tests
No head unit was available that supports `VideoStreamingState.STREAMABLE`, so this was tested to ensure that the initial callback was received.

Core version / branch / commit hash / module tested against: Manticore v2.4.2 (SDL Core v6.0.1)
HMI name / version / branch / commit hash / module tested against: Manticore v2.4.2 (Generic HMI v0.7.2).

### Summary
This PR adds an `SDLManagerDelegate` callback for `videoStreamingState` from `OnHMIStatus` to match other `OnHMIStatus` callbacks. This will only be possibly useful in situations when the developer is not "autostreaming" via `CarWindow`.

##### Enhancements
* Added `SDLManagerDelegate.videoStreamingState:didChangeToState:` to match other `OnHMIStatus` based callbacks in `SDLManagerDelegate`.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLLifecycleManager.m [hunk 1]
```diff
@@ -795,18 +800,25 @@ - (void)sdl_hmiStatusDidChange:(SDLRPCNotificationNotification *)notification {
...
         SDLLogD(@"HMI level changed from %@ to %@", oldHMILevel, self.hmiLevel);
     }
 
-    if (![oldStreamingState isEqualToEnum:self.audioStreamingState]) {
-        SDLLogD(@"Audio streaming state changed from %@ to %@", oldStreamingState, self.audioStreamingState);
+    if (![oldAudioStreamingState isEqualToEnum:self.audioStreamingState]) {
+        SDLLogD(@"Audio streaming state changed from %@ to %@", oldAudioStreamingState, self.audioStreamingState);
+    }
+
+    if (![oldAudioStreamingState isEqualToEnum:self.videoStreamingState]) {
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLLifecycleManager.m]: Should be comparing `oldVideoStreamingState` to `self.videoStreamingState` instead of `oldAudioStreamingState`. Also, the log prints out `oldAudioStreamingState` instead of `oldVideoStreamingState`

File: SmartDeviceLink/SDLManagerDelegate.h [hunk 2]
```diff
@@ -41,6 +42,11 @@ NS_ASSUME_NONNULL_BEGIN
  */
 - (void)audioStreamingState:(nullable SDLAudioStreamingState)oldState didChangeToState:(SDLAudioStreamingState)newState;
 
+/// Called when the video streaming state of this application changes. This refers to streaming video for navigation purposes. If you are "autostreaming" via CarWindow, you should not do anything with this method. Everything should be handled for you automatically.
+/// @param oldState The previous state
```
[the remark this answers is not in the document]
Comment (joeljfischer) [reply SmartDeviceLink/SDLManagerDelegate.h]: Fixed

File: SmartDeviceLink/SDLLifecycleManager.m (hunk 1 above)
Comment (joeljfischer) [reply SmartDeviceLink/SDLLifecycleManager.m]: Fixed

Comment (joeljfischer) [reply SmartDeviceLink/SDLLifecycleManager.m]: Fixed
