### PR TITLE
Choice set manager should return nil if there's no menu name

### LINKED ISSUE #1220: Choice set manager should return a `nil` `SDLCreateInteractionChoiceSet` object if mandatory parameters are missing
### Bug Report
The `menuName` parameter is required for a `SDLChoice` request RPC. However, in the *SDLPreloadChoicesOperation* class, the `menuName` is only set if the `displayCapabilities` has a textfield of name `SDLTextFieldNameMenuName`. If the `menuName` is not set, there is no point in sending a `SDLCreateInteractionChoiceSet` request as Core will reject the request. Instead the `sdl_choiceFromCell:` method should return a `nil` object.   

##### Reproduction Steps
1. Connect LMP to sdl_core + generic_hmi
2. Open the menu and select "artists"

##### Expected Behavior
The popup menu should show.

##### Observed Behavior
All the `SDLCreateInteractionChoiceSet` RPCS fail because the `menuName` is not set by the choice set manager. This is due to generic_hmi not returning a valid display capability when the template is changed.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.2
* Testing Against: sdl_core (v.5.1) + generic_hmi (develop)

### PR DESCRIPTION
**Pull request by justingluck93**
Fixes #1220

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
Return nil object if menuName is empty since the RPC will be rejected and fail. 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLError.h [hunk 1]
```diff
@@ -67,6 +67,8 @@ extern SDLErrorDomain *const SDLErrorDomainRPCStore;
 + (NSError *)sdl_choiceSetManager_choicesDeletedBeforePresentation:(NSDictionary *)userInfo;
 + (NSError *)sdl_choiceSetManager_choiceDeletionFailed:(NSDictionary *)userInfo;
 + (NSError *)sdl_choiceSetManager_choiceUploadFailed:(NSDictionary *)userInfo;
++ (NSError *)sdl_choiceSetManager_failedToCreateMenuItems;
+
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLError.h]: Remove the extra line

File: SmartDeviceLink/SDLError.m [hunk 2]
```diff
@@ -228,6 +228,14 @@ + (NSError *)sdl_choiceSetManager_choiceUploadFailed:(NSDictionary *)userInfo {
     return [NSError errorWithDomain:SDLErrorDomainChoiceSetManager code:SDLChoiceSetManagerErrorUploadFailed userInfo:userInfo];
 }
 
++ (NSError *)sdl_choiceSetManager_failedToCreateMenuItems {
+    NSDictionary<NSString *, NSString *> *userInfo = @{
+                                                       NSLocalizedDescriptionKey: NSLocalizedString(@"Choice Set Manager error", nil),
+                                                       NSLocalizedFailureReasonErrorKey: NSLocalizedString(@"Choice set manager failed to create menu items do to menuName being empty.", nil),
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLError.m]: `do` -> `due`

File: SmartDeviceLink/SDLError.m [hunk 3]
```diff
@@ -228,6 +228,14 @@ + (NSError *)sdl_choiceSetManager_choiceUploadFailed:(NSDictionary *)userInfo {
...
+                                                       };
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLError.m]: Add `NSLocalizedRecoverySuggestionErrorKey: NSLocalizedString(@"If you are setting the `menuName`, it is possible that the head unit is sending incorrect `displayCapabilities`.")`

File: SmartDeviceLink/SDLPreloadChoicesOperation.m [hunk 4]
```diff
@@ -118,9 +118,18 @@ - (void)sdl_preloadCells {
 
     NSMutableArray<SDLCreateInteractionChoiceSet *> *choiceRPCs = [NSMutableArray arrayWithCapacity:self.cellsToUpload.count];
     for (SDLChoiceCell *cell in self.cellsToUpload) {
-        [choiceRPCs addObject:[self sdl_choiceFromCell:cell]];
+        SDLCreateInteractionChoiceSet *csCell =  [self sdl_choiceFromCell:cell];
+        if(csCell != nil) {
+            [choiceRPCs addObject:csCell];
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPreloadChoicesOperation.m]: This should log an error as well

File: SmartDeviceLink/SDLPreloadChoicesOperation.m [hunk 5]
```diff
@@ -118,9 +118,18 @@ - (void)sdl_preloadCells {
...
+        }
     }
-
+    
+    if (choiceRPCs.count == 0) {
+         SDLLogE(@"Error choiceRPCs is an empty array");
+        self.internalError = [NSError sdl_choiceSetManager_failedToCreateMenuItems];
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPreloadChoicesOperation.m]: Whitespacing

File: SmartDeviceLink/SDLPreloadChoicesOperation.m [hunk 6]
```diff
@@ -118,9 +118,18 @@ - (void)sdl_preloadCells {
...
-        [choiceRPCs addObject:[self sdl_choiceFromCell:cell]];
+        SDLCreateInteractionChoiceSet *csCell =  [self sdl_choiceFromCell:cell];
+        if(csCell != nil) {
+            [choiceRPCs addObject:csCell];
+        }
     }
-
+    
+    if (choiceRPCs.count == 0) {
+         SDLLogE(@"Error choiceRPCs is an empty array");
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPreloadChoicesOperation.m]: This error needs to be useful to developers, and they won't know what `choiceRPCs` is. This should be something like "All choice cells to send are `nil`, so the choice set will not be shown."

File: SmartDeviceLink/SDLPreloadChoicesOperation.m [hunk 7]
```diff
@@ -118,9 +118,18 @@ - (void)sdl_preloadCells {
...
+        self.internalError = [NSError sdl_choiceSetManager_failedToCreateMenuItems];
+         [self finishOperation];
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPreloadChoicesOperation.m]: There needs to be a return here, right?

File: SmartDeviceLink/SDLPreloadChoicesOperation.m [hunk 8]
```diff
@@ -141,15 +150,20 @@ - (void)sdl_preloadCells {
 
 #pragma mark - Assembling Choice Data
 
-- (SDLCreateInteractionChoiceSet *)sdl_choiceFromCell:(SDLChoiceCell *)cell {
+- (SDLCreateInteractionChoiceSet * _Nullable )sdl_choiceFromCell:(SDLChoiceCell *)cell {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPreloadChoicesOperation.m]: `(nullable SDLCreateInteractionChoice)`

File: SmartDeviceLink/SDLPreloadChoicesOperation.m [hunk 9]
```diff
@@ -141,15 +150,20 @@ - (void)sdl_preloadCells {
...
     NSArray<NSString *> *vrCommands = nil;
     if (cell.voiceCommands == nil) {
         vrCommands = self.isVROptional ? nil : @[[NSString stringWithFormat:@"%hu", cell.choiceId]];
     } else {
         vrCommands = cell.voiceCommands;
     }
 
-    NSString *menuName = [self.displayCapabilities hasTextFieldOfName:SDLTextFieldNameMenuName] ? cell.text : nil;
+   NSString *menuName = [self.displayCapabilities hasTextFieldOfName:SDLTextFieldNameMenuName] ? cell.text : nil;
+
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPreloadChoicesOperation.m]: Unneeded extra line

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m [hunk 10]
```diff
@@ -244,13 +262,14 @@
                 });
 
                 it(@"should be correct with VR optional", ^{
+
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m]: Remove extra line

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m [hunk 11]
```diff
@@ -174,13 +192,13 @@
 
             describe(@"assembling choices", ^{
                 it(@"should be correct with no text and VR required", ^{
+
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m]: Remove extra line

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m [hunk 12]
```diff
@@ -163,8 +181,8 @@
             beforeEach(^{
                 SDLChoiceCell *cellBasic = [[SDLChoiceCell alloc] initWithText:@"Cell1" artwork:nil voiceCommands:nil];
                 SDLChoiceCell *cellWithVR = [[SDLChoiceCell alloc] initWithText:@"Cell2" secondaryText:nil tertiaryText:nil voiceCommands:@[@"Cell2"] artwork:nil secondaryArtwork:nil];
-                 SDLChoiceCell *cellWithAllText = [[SDLChoiceCell alloc] initWithText:@"Cell2" secondaryText:@"Cell2" tertiaryText:@"Cell2" voiceCommands:nil artwork:nil secondaryArtwork:nil];
-
+                SDLChoiceCell *cellWithAllText = [[SDLChoiceCell alloc] initWithText:@"Cell2" secondaryText:@"Cell2" tertiaryText:@"Cell2" voiceCommands:nil artwork:nil secondaryArtwork:nil];
+
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m]: Remove extra line / whitespace

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m [hunk 13]
```diff
@@ -69,6 +72,21 @@
                 cellsWithArtwork = [NSSet setWithArray:@[cell1WithArt, cell2WithArtAndSecondary]];
                 cellsWithStaticIcon = [NSSet setWithArray:@[cellWithStaticIcon]];
             });
+            
+            context(@"menueName is not set", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m]: "if the menuName is not set"

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m [hunk 14]
```diff
@@ -69,6 +72,21 @@
...
+                it(@"should return a nil object", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m]: `@"should not send any requests"`

File: SmartDeviceLink/SDLPreloadChoicesOperation.m (hunk 4 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m]: what is the error?

Comment (joeljfischer) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m]: The developer is saying "show these cells," and this cell we're deciding not to show. We don't want to leave them to figure it out on their own.

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m (hunk 14 above)
Comment (justingluck93) [reply SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m]: fixed

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m (hunk 12 above)
Comment (justingluck93) [reply SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m]: fixed!

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m (hunk 11 above)
Comment (justingluck93) [reply SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m]: fixed!

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m (hunk 10 above)
Comment (justingluck93) [reply SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m]: fixed!

File: SmartDeviceLink/SDLPreloadChoicesOperation.m (hunk 5 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m]: fixed!

File: SmartDeviceLink/SDLError.m (hunk 3 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLError.m]: fixed!

File: SmartDeviceLink/SDLPreloadChoicesOperation.m (hunk 6 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m]: Okay will fix

File: SmartDeviceLink/SDLPreloadChoicesOperation.m (hunk 7 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m]: yes good catch will add

File: SmartDeviceLink/SDLPreloadChoicesOperation.m (hunk 9 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m]: fixed

File: SmartDeviceLink/SDLPreloadChoicesOperation.m (hunk 4 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m]: That error is being logged on line 127, line 121-123 add the item if the item is not nil

Comment (joeljfischer) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m]: Right, but that error is only logged if _none_ of the items are added. If the developer says, "show these 10 items," and one of them is missing a menu name, then a menu will only show up with 9 items. That's a problem if we don't log what went wrong and why only 9 items showed up instead of the 10 they asked for.

Comment (justingluck93) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m]: added the error

File: SmartDeviceLink/SDLPreloadChoicesOperation.m (hunk 5 above)
Comment (joeljfischer) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m]: This does not appear to be fixed

Comment (justingluck93) [reply SmartDeviceLink/SDLPreloadChoicesOperation.m]: now  it should be!

File: SmartDeviceLink/SDLPreloadChoicesOperation.m [hunk 15]
```diff
@@ -141,15 +150,20 @@ - (void)sdl_preloadCells {
...
 
-- (SDLCreateInteractionChoiceSet *)sdl_choiceFromCell:(SDLChoiceCell *)cell {
+- (nullable SDLCreateInteractionChoiceSet *)sdl_choiceFromCell:(SDLChoiceCell *)cell {
     NSArray<NSString *> *vrCommands = nil;
     if (cell.voiceCommands == nil) {
         vrCommands = self.isVROptional ? nil : @[[NSString stringWithFormat:@"%hu", cell.choiceId]];
     } else {
         vrCommands = cell.voiceCommands;
     }
+   NSString *menuName = [self.displayCapabilities hasTextFieldOfName:SDLTextFieldNameMenuName] ? cell.text : nil;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLPreloadChoicesOperation.m]: Whitespacing
