### PR TITLE
Make constants styled correctly

### LINKED ISSUE #711: Alter constants to use common style
### Bug Report
Currently our constants appear to be defined in a variety of styles.

```objc
// SDLRPCPayload
const NSUInteger RPC_HEADER_SIZE = 12;
```

```objc
// SDLIAPSession
NSString *const IOStreamThreadName = @"com.smartdevicelink.iostream";
NSTimeInterval const streamThreadWaitSecs = 1.0;
```

```objc
// SDLIAPTransport
NSString *const LegacyProtocolString = @"com.ford.sync.prot0";
NSString *const ControlProtocolString = @"com.smartdevicelink.prot0";
NSString *const IndexedProtocolStringPrefix = @"com.smartdevicelink.prot";
NSString *const MultiSessionProtocolString = @"com.smartdevicelink.multisession";
NSString *const BackgroundTaskName = @"com.sdl.transport.iap.backgroundTask";
```

##### Expected Behavior
The `SDLIAPTransport` style.

##### Observed Behavior
A variety of styles

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #711

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Unneeded

### Summary
This alters local constant styles to be consistent across the project

### Changelog
None

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLProxy.m [hunk 1]
```diff
@@ -42,9 +42,9 @@
 typedef void (^URLSessionDownloadTaskCompletionHandler)(NSURL *location, NSURLResponse *response, NSError *error);
 
 NSString *const SDLProxyVersion = @"4.6.1";
-const float startSessionTime = 10.0;
-const float notifyProxyClosedDelay = 0.1;
-const int POLICIES_CORRELATION_ID = 65535;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLProxy.m]: POLICIES_CORRELATION_ID on line no. 702 has not been updated

Comment (joeljfischer) [reply SmartDeviceLink/SDLProxy.m]: Fixed
