### PR TITLE
Fix for voice command that contains no string should be removed

### LINKED ISSUE #1964: voiceCommand that contains no string should be removed
### Bug Report
When a voice command contains no strings, it should not be sent in an update

##### Reproduction Steps
1. voiceCommandA = ["Test 1"];
2. voiceCommandB = [];
3. Upload voiceCommands

##### Expected Behavior
currentVoiceCommands = [voiceCommandA];

##### Observed Behavior
currentVoiceCommands = [voiceCommandA, voiceCommandB];

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1964 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit Test added in SDLVoiceCommandUpdateOperationSpec file to check if pendingVoiceCommands handles voice commands with no string

#### Core Tests
Test applied on the example app:

Modified ProxyManager to set the voiceCommandA initial state.

Case 1: The following voiceCommands defined: voiceCommandA = ["", "Test 1", " ", "Test 2", "    "], voiceCommandB = ["Test 3", "Test 4"]
Case 2: The following voiceCommands defined: voiceCommandA = ["", "Test 1", " ", "Test 2", "    "]
Case 3: voiceCommandA = nil
Case 4: The following voiceCommands defined: voiceCommandA = ["", "    ", "\t"]

Core version / branch / commit hash / module tested against: 7.1.0
HMI name / version / branch / commit hash / module tested against: Manticore

### Summary
Update pendingVoiceCommands to prevent from sending a voice command with no string

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Update pendingVoiceCommands to prevent from sending a voice command with no string

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m [hunk 1]
```diff
@@ -155,6 +157,17 @@ - (void)sdl_sendCurrentVoiceCommands:(void(^)(void))completionHandler {
     return [mutableDeletes copy];
 }
 
+/// Remove a voice command from the array of voice commands if it has no strings
```
Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m:160]:
```suggestion
/// Remove a voice command from the array of voice commands if it has no strings
/// @return A list of voice commands with the empty voice commands removed
```

File: SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m [hunk 2]
```diff
@@ -155,6 +157,17 @@ - (void)sdl_sendCurrentVoiceCommands:(void(^)(void))completionHandler {
...
+- (NSArray<SDLVoiceCommand *> *)sdl_removeEmptyVoiceCommands {
+    NSMutableArray<SDLVoiceCommand *> *pendingVoiceCommands = [[NSMutableArray alloc] init];
+    for (SDLVoiceCommand *voiceCommand in self.pendingVoiceCommands) {
+        if (voiceCommand.voiceCommands.count > 0) {
```
Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m:164]: We should also add a check if any if the `voiceCommands` are empty strings (i.e. `@""`) since the module will reject empty strings for `voiceCommands` (https://github.com/smartdevicelink/rpc_spec/blob/8b8c996c738711c4235c8574c179354cbf8982e2/MOBILE_API.xml#L1196)

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
Left some comments.

File: SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m [hunk 3]
```diff
@@ -20,6 +20,7 @@
 @interface SDLVoiceCommand()
 
 @property (assign, nonatomic) UInt32 commandId;
+@property (copy, nonatomic, readwrite) NSArray<NSString *> *voiceCommands;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m:23]: Instead of doing the validation of the empty strings in `SDLVoiceCommandUpdateOperation` and assigning it back, why don't we just do the empty string validation in the `SDLVoiceCommandManager`'s `setVoiceCommands:` method?

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
Left some comments

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 4]
```diff
@@ -155,6 +158,50 @@ @interface SDLVoiceCommandManager()
...
+                        [firstOp finishOperation];
+
+                        [NSThread sleepForTimeInterval:0.5];
+
+                        testManager.voiceCommands = @[testVoiceCommand5];
+                    });
+
+                    // should queue another operation
+                    it(@"should queue another operation", ^{
+                        expect(testManager.transactionQueue.operations).to(haveCount(2));
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:189]: Can we add tests here to make sure that `@[@"Test 3", @" ", @"Test 4"]` becomes `@[@"Test 3", @"Test 4"]`

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 5]
```diff
@@ -49,6 +49,9 @@ @interface SDLVoiceCommandManager()
 
     __block SDLVoiceCommand *testVoiceCommand = [[SDLVoiceCommand alloc] initWithVoiceCommands:@[@"Test 1"] handler:^{}];
     __block SDLVoiceCommand *testVoiceCommand2 = [[SDLVoiceCommand alloc] initWithVoiceCommands:@[@"Test 2"] handler:^{}];
+    __block SDLVoiceCommand *testVoiceCommand3 = [[SDLVoiceCommand alloc] initWithVoiceCommands:@[@"Test 3", @" ", @"Test 4"] handler:^{}];
+    __block SDLVoiceCommand *testVoiceCommand4 = [[SDLVoiceCommand alloc] initWithVoiceCommands:@[@""] handler:^{}];
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:53]: Can we add another `testVoiceCommand` that has a string with multiple white space characters like so: `@"\t   "` and make sure that it doesn't get sent?

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 6]
```diff
@@ -155,6 +158,50 @@ @interface SDLVoiceCommandManager()
...
+        context(@"if it has voice commands to upload with one voice command strings contains an empty string", ^{
+            beforeEach(^{
+                testManager.voiceCommands = @[testVoiceCommand3, testVoiceCommand4, testVoiceCommand5];
+            });
+
+            // should queue another operation
+            it(@"should queue another operation", ^{
+                expect(testManager.transactionQueue.operations).to(haveCount(2));
+                expect(testManager.voiceCommands).to(haveCount(1));
+                expect(testManager.voiceCommands.firstObject.voiceCommands).to(haveCount(2));
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:171]: Can we add tests here to make sure that `@[@"Test 3", @" ", @"Test 4"]` becomes `@[@"Test 3", @"Test 4"]`

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
Left some comments

File: SmartDeviceLink/private/SDLVoiceCommandManager.m [hunk 7]
```diff
@@ -146,6 +155,33 @@ - (void)sdl_updateIdsOnVoiceCommands:(NSArray<SDLVoiceCommand *> *)voiceCommands
...
+    NSMutableArray<NSString *> *voiceCommandStrings = [[NSMutableArray alloc] init];
+    self.areVoiceCommandsEmptyStrings = YES;
+    for (SDLVoiceCommand *voiceCommand in voiceCommands) {
+        if (voiceCommand.voiceCommands.count == 0) {
+            self.areVoiceCommandsEmptyStrings = NO;
+        }
+        for (NSString *voiceCommandString in voiceCommand.voiceCommands) {
+            NSString *probablyEmpty = [voiceCommandString stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
+            if (probablyEmpty.length > 0) {
+                [voiceCommandStrings addObject:voiceCommandString];
```
[the remark this answers is not in the document]
Comment (FrankElias77) [reply SmartDeviceLink/private/SDLVoiceCommandManager.m:172]: No, the `stringByTrimmingCharactersInSet` returns a new string after removing characters from both ends of the set.

File: SmartDeviceLink/public/SDLVoiceCommand.m [hunk 8]
```diff
@@ -13,6 +13,7 @@
 @interface SDLVoiceCommand()
 
 @property (assign, nonatomic) UInt32 commandId;
+@property (copy, nonatomic, readwrite) NSArray<NSString *> *voiceCommands;
```
[the remark this answers is not in the document]
Comment (FrankElias77) [reply SmartDeviceLink/public/SDLVoiceCommand.m:16]: When this line is removed, app crashes with code `BAD_ACCESS` since I am setting this property in `sdl_removeEmptyVoiceCommands` function of `SDLVoiceCommandManager`

File: SmartDeviceLink/private/SDLVoiceCommandManager.m [hunk 9]
```diff
@@ -109,15 +110,21 @@ - (void)setVoiceCommands:(NSArray<SDLVoiceCommand *> *)voiceCommands {
         return;
     }
 
+    // Set the new voice commands internally
+    _voiceCommands = [self sdl_removeEmptyVoiceCommands:voiceCommands];
```
Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLVoiceCommandManager.m:114]: I'm seeing a couple of failing test cases. Due to the fact the `voiceCommands` instance var is set with a new object returned by `sdl_removeEmptyVoiceCommands`, the check to compare `if (voiceCommands == self.voiceCommands) { ... }` always fails.

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
Left some comments.

File: SmartDeviceLink/private/SDLVoiceCommandManager.m [hunk 10]
```diff
@@ -104,20 +106,29 @@ - (void)sdl_updateTransactionQueueSuspended {
...
+
+    // Check if the voiceCommand's strings that are set are all empty strings. If the user only sends voice commands with empty voice command string arrays, the existing voice commands will be deleted, and if the user only sends invalid voice command strings in array(e.g. strings consisting just of whitespace characters) then the voiceCommands update operation will be aborted.
+    if (self.voiceCommands.count == 0 && voiceCommands.count > 0) {
+        SDLLogE(@"New voice commands are set to empty strings");
+        return;
+    }
+
+    // Set the ids
+    [self sdl_updateIdsOnVoiceCommands:self.voiceCommands];
```
Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLVoiceCommandManager.m:127]:
```suggestion
    // Validate the voiceCommand's strings. In the rare case that the user has set only empty whitespace strings, abort the update operation.
    NSArray<SDLVoiceCommand *> *validatedVoiceCommands = [self sdl_removeEmptyVoiceCommands:voiceCommands];
    if (validatedVoiceCommands.count == 0 && voiceCommands.count > 0) {
        SDLLogE(@"New voice commands are invalid, skipping...");
        return;
    }

    _originalVoiceCommands = voiceCommands;
    _voiceCommands = validatedVoiceCommands;

    // Set the ids
    [self sdl_updateIdsOnVoiceCommands:self.voiceCommands];
```

File: SmartDeviceLink/private/SDLVoiceCommandManager.m [hunk 11]
```diff
@@ -104,20 +106,29 @@ - (void)sdl_updateTransactionQueueSuspended {
...
-    if (voiceCommands == self.voiceCommands) {
+    if (voiceCommands == self.comparedVoiceCommands) {
         SDLLogD(@"New voice commands are equal to the existing voice commands, skipping...");
         return;
     }
 
-    // Set the ids
-    [self sdl_updateIdsOnVoiceCommands:voiceCommands];
+    // Set a copy of voiceCommands to reduce duplicate voiceCommands sent
+    self.comparedVoiceCommands = voiceCommands;
```
Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLVoiceCommandManager.m:115]:
```suggestion
```

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
Suggested renaming variables for clarity.

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
I made one suggestion to relocated a comment.

Can you also add the smoke tests you performed under **Core Tests** in the PR description?

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 12]
```diff
@@ -155,6 +159,51 @@ @interface SDLVoiceCommandManager()
...
+
+                        [NSThread sleepForTimeInterval:0.5];
+
+                        testManager.voiceCommands = @[testVoiceCommand5];
+                    });
+
+                    // should queue another operation
+                    it(@"should queue another operation", ^{
+                        expect(testManager.transactionQueue.operations).to(haveCount(1));
+                    });
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:192]: I don't this this is the correct behavior. Shouldn't it **not** queue an operation since the string is empty?

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m [hunk 13]
```diff
@@ -155,6 +159,51 @@ @interface SDLVoiceCommandManager()
...
+                        testManager.voiceCommands = @[testVoiceCommand5];
+                    });
+
+                    // should not queue another operation
+                    it(@"should not queue another operation", ^{
+                        expect(testManager.transactionQueue.operations).to(haveCount(1));
+                    });
+                });
+            });
+        });
```
Comment (NicoleYarroch) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:206]:
```suggestion
        context(@"if any of the voice commands contains an empty string", ^{
            // should remove the empty strings and queue another operation
            it(@"should remove the empty strings and queue another operation", ^{
                testManager.voiceCommands = @[testVoiceCommand2, testVoiceCommand3, testVoiceCommand4, testVoiceCommand5, testVoiceCommand6];

                expect(testManager.transactionQueue.operations).to(haveCount(2));
                expect(testManager.voiceCommands).to(haveCount(2));
                expect(testManager.voiceCommands[0].voiceCommands).to(haveCount(1));
                expect(testManager.voiceCommands[0].voiceCommands).to(equal(@[@"Test 2"]));
                expect(testManager.voiceCommands[1].voiceCommands).to(haveCount(2));
                expect(testManager.voiceCommands[1].voiceCommands).to(equal(@[@"Test 3", @"Test 4"]));
            });

            // should not queue another operation if all the voice command strings are empty strings
            it(@"should not queue another operation if all the voice command strings are empty strings", ^{
                testManager.voiceCommands = @[testVoiceCommand4, testVoiceCommand5];

                expect(testManager.transactionQueue.operations).to(haveCount(1));
                expect(testManager.voiceCommands).to(haveCount(1));
                expect(testManager.voiceCommands.firstObject.voiceCommands).to(haveCount(1));
                expect(testManager.voiceCommands.firstObject.voiceCommands).to(equal(@[@"Test 1"]));
            });
        });
```

Comment (NicoleYarroch) [reply SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m:206]: I made a suggestion to help clarify the tests. Let me know if it makes sense.

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
I made some suggestions to make the tests a little more readable.

**Review by NicoleYarroch — APPROVED** [review]

**Review by NicoleYarroch — APPROVED** [review]
