### PR TITLE
changing inits to class methods to fix swift formatting issues

### LINKED ISSUE #1414: Cancel Interaction inits formatting for swift
### Bug Report
inits formatting for swift is broken

##### Expected Behavior
should be formatted correctly 

##### Observed Behavior
is not formatted correctly

### PR DESCRIPTION
**Pull request by justingluck93**
Fixes #1414 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Summary
Updated methods to be class methods and changed name

- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLCancelInteraction.h [hunk 1]
```diff
@@ -71,28 +71,28 @@ NS_ASSUME_NONNULL_BEGIN
...
-- (instancetype)initWithScrollableMessage;
++ (instancetype)scrollableMessage;
 
 /**
  Convenience init for dismissing the currently presented perform interaction.
 
  @return A SDLCancelInteraction object
  */
-- (instancetype)initWithPerformInteraction;
++ (instancetype)performInteraction;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLCancelInteraction.h]: This needs an `NS_SWIFT_NAME` because for some reason swift is interpreting it as `.perform()` and it should be `.performInteraction()`

Comment (justingluck93) [reply SmartDeviceLink/SDLCancelInteraction.h]: added
