### PR TITLE
Removed the suppress deprecation warning

### LINKED ISSUE #1819: Remove the suppress deprecation wrappers from tests.
### Bug Report
Since the SDLRPCStruct's initWithDictionary was undeprecated we can remove the suppress deprecation warnings from the tests.

The tests in **SDLWindowStatusSpec**:
```
it(@"Should get correctly when initialized", ^ {
    SDLWindowState *state = [[SDLWindowState alloc] initWithApproximatePosition:approximatePosition deviation:deviation];
    SDLGrid *location = [[SDLGrid alloc] init];
    NSDictionary *dict = @{SDLRPCParameterNameLocation:location,
                            SDLRPCParameterNameState:state
                            };
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
    SDLWindowStatus *testStruct = [[SDLWindowStatus alloc] initWithDictionary:dict];
#pragma clang diagnostic pop

    expect(testStruct.location).to(equal(location));
    expect(testStruct.state).to(equal(state));
});
```

can have the push/pop wrappers removed like so:

```
it(@"Should get correctly when initialized", ^ {
    SDLWindowState *state = [[SDLWindowState alloc] initWithApproximatePosition:approximatePosition deviation:deviation];
    SDLGrid *location = [[SDLGrid alloc] init];
    NSDictionary *dict = @{SDLRPCParameterNameLocation:location,
                            SDLRPCParameterNameState:state
                            };
    SDLWindowStatus *testStruct = [[SDLWindowStatus alloc] initWithDictionary:dict];

    expect(testStruct.location).to(equal(location));
    expect(testStruct.state).to(equal(state));
});
```

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: 7.0
* Testing Against: N/A

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1819 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
Remove the suppress deprecation warnings from the tests.

##### Breaking Changes
* Remove the suppress deprecation warnings from the tests.

##### Enhancements
* N/A

##### Bug Fixes
* N/A

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLinkTests/RPCSpecs/NotificationSpecs/SDLOnSyncPDataSpec.m [hunk 1]
```diff
@@ -38,10 +38,7 @@
                                                      SDLRPCParameterNameOperationName:SDLRPCFunctionNameOnSyncPData}};
 #pragma clang diagnostic pop
 
-#pragma clang diagnostic push
-#pragma clang diagnostic ignored "-Wdeprecated-declarations"
         SDLOnSyncPData* testNotification = [[SDLOnSyncPData alloc] initWithDictionary:dict];
-#pragma clang diagnostic pop
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/RPCSpecs/NotificationSpecs/SDLOnSyncPDataSpec.m:44]: `SDLOnSyncPData` itself is deprecated, so this creates a warning when running the tests. Please put these back and ensure that you run tests locally to check for any new warnings before checking off that box in the PR description. Since you're changing a bunch of unit tests, you need to run the unit tests, so this PR really requires that box to be checked off too.

**Review by joeljfischer — CHANGES_REQUESTED** [review]
