### PR TITLE
Fixed SDLButtonPress initializer missing mandatory parameter

### LINKED ISSUE #1635: SDLButtonPress initializer missing a mandatory parameter
### Bug Report
Our available initializers for `SDLButtonPress` are missing the mandatory param `buttonPressMode`.

### PR DESCRIPTION
**Pull request by lapinskijw**
Fixes #1635 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Updated `SDLButtonPressSpec` tests to include new parameter in initializer to set the `SDLButtonPressMode`.

#### Core Tests
n/a unit tests confirm that `SDLButtonPressMode` is being properly set.

### Summary
Created a new initializer for `SDLButtonPress` to include the mandatory `SDLButtonPressMode` parameter. Deprecated the old initializer.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLButtonPressSpec.m [hunk 1]
```diff
@@ -54,11 +54,12 @@
     });
 
     it(@"Should get correctly using initializer", ^ {
-        SDLButtonPress *testRequest = [[SDLButtonPress alloc] initWithButtonName:SDLButtonNameAC moduleType:SDLModuleTypeClimate moduleId:@"123"];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLButtonPressSpec.m:57]: Deprecated initializers still need tests

Comment (lapinskijw) [reply SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLButtonPressSpec.m:57]: Added tests for deprecated initializers.
