### PR TITLE
HTTP alterations in SDLURLSession to use NSURLComponents

### LINKED ISSUE #432: HTTP limitation with ATS
### Bug Report
Apple is making ATS exceptions more strict to app developers (see https://forums.developer.apple.com/thread/48979). Still exceptions are possible developers need reasonably justifications.

Due to the fact that the head unit delivers URLs for policy tables, lock screen icons etc. those head units may still deliver HTTP based URLs.

The SDK should fix this issue by "auto repeat over https" in case a http request failed. This would allow a head unit to try at least once to fetch the data over the original URL before it retries it over https. This would make it necessary to put effort and alter the logic inside the SDK.

Example from SDLProxy.m:469 (4.1.4 release):
```
 - (void)handleSystemRequestLockScreenIconURL:(SDLOnSystemRequest *)request {
+    NSURL *url = [NSURL URLWithString:request.url];
-     [[SDLURLSession defaultSession] dataFromURL:[NSURL URLWithString:request.url]
+     [[SDLURLSession defaultSession] dataFromURL:url
                                completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
                                    if (error != nil) {
                                        NSString *logMessage = [NSString stringWithFormat:@"OnSystemRequest failure (HTTP response), download task failed: %@", error.localizedDescription];
                                        [SDLDebugTool logInfo:logMessage withType:SDLDebugType_RPC toOutput:SDLDebugOutput_All toGroup:self.debugConsoleGroupName];
+                                       if ([url.scheme isEqualToString:@"http"]) {
+                                           NSURLComponents *components = [NSURLComponents componentsWithURL:url resolvingAgainstBaseURL:YES];
+                                           components.scheme = @"https";
+                                           request.url = components.string; // this alters the original request which could be just copied before
+                                           [self handleSystemRequestLockScreenIconURL:request]; // weakify & strongify missing in this example
+                                       }    
                                        return;
                                    }

                                    UIImage *icon = [UIImage imageWithData:data];
                                    [self invokeMethodOnDelegates:@selector(onReceivedLockScreenIcon:) withObject:icon];
                                }];
 }
```

As an alternative any URL related request could be modified directly to https before fetching any data. This would reduce the effort for this issue to almost nothing. Then technically the SDK would not fetch data over the exact URL (this can be accepted as it's still contacting the same host).

Example:
```
 - (void)handleSystemRequestLockScreenIconURL:(SDLOnSystemRequest *)request {
+   NSURLComponents *components = [NSURLComponents componentsWithString:request.url];
+   if ([components.scheme isEqualToString:@"http"]) {
+       components.scheme = @"https";
+   }
+   NSURL *url = components.URL;
-   [[SDLURLSession defaultSession] dataFromURL:[NSURL URLWithString:request.url]
+   [[SDLURLSession defaultSession] dataFromURL:url
                              completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
                                  if (error != nil) {
                                      NSString *logMessage = [NSString stringWithFormat:@"OnSystemRequest failure (HTTP response), download task failed: %@", error.localizedDescription];
                                      [SDLDebugTool logInfo:logMessage withType:SDLDebugType_RPC toOutput:SDLDebugOutput_All toGroup:self.debugConsoleGroupName];
                                      return;
                                  }

                                  UIImage *icon = [UIImage imageWithData:data];
                                  [self invokeMethodOnDelegates:@selector(onReceivedLockScreenIcon:) withObject:icon];
                            }];
 }
```

##### OS & Version Information
* iOS Version: Any (it's not iOS10 specific)
* SDL iOS Version: 4.1.4

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #432

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
A unit test has been included

### Summary
This PR fixes some possible bugs with HTTP -> HTTPS conversion in SDLURLSession

##### Bug Fixes
* If the URL contains more than one "http" in its URL, only the scheme will be modified instead of all of them.

### CODE REVIEW

File: SmartDeviceLink/SDLURLSession.m [hunk 1]
```diff
@@ -64,7 +64,7 @@ - (instancetype)init {
 - (void)dataFromURL:(NSURL *)url completionHandler:(SDLURLConnectionRequestCompletionHandler)completionHandler {
     // Apple no longer allows HTTP URLs without a special exception as of Jan. 2017
     if ([url.scheme isEqualToString:@"http"]) {
-        url = [NSURL URLWithString:[url.absoluteString stringByReplacingOccurrencesOfString:@"http://" withString:@"https://"]];
+         url = [NSURL URLWithString:[url.absoluteString stringByReplacingCharactersInRange:NSMakeRange(0, 4) withString:@"https"]];
```
Comment (asm09fsu) [inline SmartDeviceLink/SDLURLSession.m]: unnecessary space here.

**Comment by asm09fsu** [comment]
LGTM 👍
