### PR TITLE
Fix overwriting alert view images not being shown

### LINKED ISSUE #2109: Alert images that are flagged for overwrite fail to display
### Bug Summary

The `SDLPresentAlertOperation` fails to display an image marked for overwrite because of this line:

```objc
- (SDLAlert *)alertRPC {
...
    alert.alertIcon = ([self sdl_supportsAlertIcon] && ![self.fileManager fileNeedsUpload:self.alertView.icon]) ? self.alertView.icon.imageRPC : nil;
...
}
```

The check for `fileNeedsUpload` returns true if the image is flagged for overwrite, which results in a failure to display the image.

Additional options were considered, like mixing `hasUploadedFile` and `isStaticIcon` checks, but those have an issue where if an overwrite file upload fails the old image will be shown, when it should not show any image instead.

### Reproduction Steps

1. Upload an image with name "test"
2. Create an `AlertView` with an icon artwork overwriting "test"
3. Present the image through the screen manager

Expected Behavior:
The overwriting image should be shown

Observed Behavior:
No image is shown

### iOS Version(s)

n/a

### sdl_ios Version

7.5.0

### Testing Environment(s)

```markdown
Observed through code
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #2109

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Updated the present alert operation tests to handle the new checks.

#### Core Tests
* Uploaded an image with a particular name, then tried to present an alert with a new overwriting image with the same name.

[sdl_ios-9-18-01-AM.patch.zip](https://github.com/smartdevicelink/sdl_ios/files/9626109/sdl_ios-9-18-01-AM.patch.zip)

Core version / branch / commit hash / module tested against: Manticore (Core v8.1)
HMI name / version / branch / commit hash / module tested against: Manticore (Generic_HMI v0.12.0

### Summary
This PR changes some logic around how the present alert operation handles showing the alert icon image to fix an issue with showing overwriting images.

##### Bug Fixes
* Fixes screen manager present alert not showing the icon if it was marked to overwrite another.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by joeljfischer** [comment]
[sdl_ios-9-18-01-AM.patch.zip](https://github.com/smartdevicelink/sdl_ios/files/9626109/sdl_ios-9-18-01-AM.patch.zip)

Attached the patch I used to test. This fails on develop and succeeds on this branch.

File: SmartDeviceLink/private/SDLPresentAlertOperation.m [hunk 1]
```diff
@@ -193,8 +195,14 @@ - (void)sdl_uploadAudioFilesWithCompletionHandler:(void (^)(void))handler {
...
-    if ([self sdl_supportsAlertIcon] && [self.fileManager fileNeedsUpload:self.alertView.icon]) {
-        [artworksToBeUploaded addObject:self.alertView.icon];
+    if ([self sdl_supportsAlertIcon] && (self.alertView.icon != nil)) {
+        if ([self.fileManager fileNeedsUpload:self.alertView.icon]) {
+            // If the file is not uploaded, attempt to upload it
+            [artworksToBeUploaded addObject:self.alertView.icon];
+        } else if ([self.fileManager hasUploadedFile:self.alertView.icon] || self.alertView.icon.isStaticIcon) {
+            // If the file is already uploaded, add it to the uploaded set so we can show it
+            self.alertIconUploaded = YES;
+        }
```
Comment (jshivabeharry) [inline SmartDeviceLink/private/SDLPresentAlertOperation.m:205]: L204 is not covered in any of the unit tests. If possible should add or modify in unit tests to get full test coverage.

**Review by jshivabeharry — CHANGES_REQUESTED** [review]
Code looks good overall, I only put in one comment suggesting a change. I did notice that their is not a unit test that covers L204 of **SDLPresentAlertOperation**  when a file is already uploaded it should be added to the uploaded set. If possible we should try to test for that case.

File: SmartDeviceLinkTests/SDLPresentAlertOperationSpec.m [hunk 2]
```diff
@@ -635,6 +636,25 @@ - (SDLAlert *)alertRPC;
                 OCMVerifyAll(strictMockSystemCapabilityManager);
                 OCMVerifyAll(strictMockCurrentWindowCapability);
             });
+
+            fit(@"should not upload the image if the alert icon is a static icon", ^{
```
Comment (jshivabeharry) [inline SmartDeviceLinkTests/SDLPresentAlertOperationSpec.m:640]:
```suggestion
            it(@"should not upload the image if the alert icon is a static icon", ^{
```
`fit` made it so only this test ran and caused it fail the codecov check.

**Review by jshivabeharry — CHANGES_REQUESTED** [review]
Typo on line 640. Change `fit` to `it`

**Review by jshivabeharry — APPROVED** [review]
