### PR TITLE
Fix to avoid deleting and setting identical voice commands

### LINKED ISSUE #1855: Avoid deleting and setting identical voice commands
### Bug Report
Currently, setting voice commands doesn't check for a diff of which voice commands are in the old and new lists. This results in a case where if voice commands are set like so:

```
voiceCommands = [command1, command2, command3]
voiceCommands = [command1, command2, command3, command 4]
```

What will happen is `command1/2/3` will be set to the head unit, then `command1/2/3` will be deleted from the head unit, then `command1/2/3/4` will be set to the head unit.

Because voice commands can be so slow to process, we should diff and only set / delete what is necessary instead of taking an all-or-nothing approach.

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1855 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit test added in `SDLVoiceCommandUpdateOperationSpec`

#### Core Tests
Test applied on the example app:
1. The following voiceCommands defined: `voiceCommandA = ["Test 1", "Test 2"], voiceCommandB = ["Test 3", "Test 4"]`
2. Modified ProxyManager to set the voiceCommandA initial state.
3. Added a cell in the MenuManager that sends voiceCommandA and voiceCommandB in its completion block
voiceCommandA was not deleted and re-uploaded in step 3

Core version / branch / commit hash / module tested against: 7.1.0
HMI name / version / branch / commit hash / module tested against: generic_hmi -> release/0.10.0, sdl_hmi -> release -> 5.5.0, SYNC3

### Summary
Handle deleting and adding unnecessary voiceCommands

##### Breaking Changes
* N/A

##### Enhancements
* Handle deleting and adding unnecessary voiceCommands

##### Bug Fixes
* N/A

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by joeljfischer** [comment]
You note on the PR description that you have not tested this against Core. Please test against Core and Sync 3 before review.

**Comment by joeljfischer** [comment]
The last comment was not addressed. In addition, `n/a` is not correct for the unit tests section.

**Comment by joeljfischer** [comment]
You still have not listed the tests you performed on SDL Core. Additionally, please test on both SDL Core v7.1.0 final (not RC1) and a final version of HMI, which you did not list the version of, and also test on Sync.

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 1]
```diff
@@ -244,6 +250,15 @@ @interface SDLVoiceCommand()
...
     });
+
+    // should test voiceCommandsInArray and return the difference between two arrays
+    it(@"should have a priority of 'normal'", ^{
+        testOp = [[SDLVoiceCommandUpdateOperation alloc] init];
+        NSArray<SDLVoiceCommand *> *voiceCommands = [testOp voiceCommandsInArray:@[newVoiceCommand1, newVoiceCommand2] notInSecondArray:@[newVoiceCommand1]];
+
+        expect(voiceCommands).to(haveCount(1));
+        expect(voiceCommands.firstObject).to(equal(newVoiceCommand2));
+    });
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:261]: This should not be the only test added (also the title is wrong).

You should add a test to set up the voice command update operation with (1) a pending array identical to the old array, (2) with the same but fewer so that it should only delete, (3) with the same and a few more so that it should only add, (4) with completely different so that it deletes and adds.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m [hunk 2]
```diff
@@ -76,12 +76,14 @@ - (void)start {
 /// Send DeleteCommand RPCs for voice commands that should be deleted
 /// @param completionHandler A handler called when all DeleteCommands have completed
 - (void)sdl_sendDeleteCurrentVoiceCommands:(void(^)(void))completionHandler {
-    if (self.oldVoiceCommands.count == 0) {
+    NSArray *voiceCommandsToDelete = [self.class sdl_voiceCommandsInArray:self.oldVoiceCommands notInSecondArray:self.pendingVoiceCommands];
+
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m:80]:
```suggestion
```

File: SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m [hunk 3]
```diff
@@ -109,12 +111,14 @@ - (void)sdl_sendDeleteCurrentVoiceCommands:(void(^)(void))completionHandler {
 /// Send AddCommand RPCs for voice commands that should be added
 /// @param completionHandler A handler called when all AddCommands have completed
 - (void)sdl_sendCurrentVoiceCommands:(void(^)(void))completionHandler {
-    if (self.pendingVoiceCommands.count == 0) {
+    NSArray *voiceCommandsToAdd = [self.class sdl_voiceCommandsInArray:self.pendingVoiceCommands notInSecondArray:self.oldVoiceCommands];
+
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m:115]:
```suggestion
```

File: SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m [hunk 4]
```diff
@@ -173,6 +177,28 @@ - (void)sdl_sendCurrentVoiceCommands:(void(^)(void))completionHandler {
     return [mutableCommands copy];
 }
 
+/// Create array of unique SDLVoiceCommand after comparison between firstArray and secondArray
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m:180]:
```suggestion
/// Create array of SDLVoiceCommands that exist in the first array but not in the second array. Items in the second array that are not in the first array will not be included. For example, if the arrays [A, B, C] and [A, B, D] are passed, the array [C] will be returned.
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 5]
```diff
@@ -244,6 +250,46 @@ @interface SDLVoiceCommand()
             });
         });
     });
+
+    // should test voiceCommandsInArray with pendingVoiceCommands being the same as oldVoiceCommands but fewer so that it should only delete
+    it(@"should test voiceCommandsInArray with pendingVoiceCommands being the same as oldVoiceCommands but fewer so that it should only delete", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:255]: It's not good enough to test an internal method. You have to test the _entire_ operation from start to finish that it properly uses the internal method. Please refactor these tests to test the operation, not the internal method.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — CHANGES_REQUESTED** [review]
**Additional Issues**

1. Voice commands are being stored with a different `cmdId` than it is being sent with. This results with the voice command handler never being called when the voice command is triggered. This can most easily be seen using Manticore, which lets you trigger voice commands with a click. You can breakpoint in `SDLVoiceCommandManager.sdl_commandNotification` to see the issue.

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 6]
```diff
@@ -166,6 +166,128 @@ @interface SDLVoiceCommand()
...
+
+            it(@"Should not delete or upload the voiceCommands", ^{
+                expect(testConnectionManager.receivedRequests).to(haveCount(0));
+                expect(callbackCurrentVoiceCommands).to(haveCount(2));
+                expect(callbackError).to(beNil());
+            });
+        });
+
+        // going from voice commands [A] to [AB]
+        context(@"going from voice commands [A] to [AB]", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:187]:
```suggestion
        // going from voice commands [AB] to [A]
        context(@"going from voice commands [AB] to [A]", ^{
```

Correct me if I'm wrong, but I think this is right

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 7]
```diff
@@ -166,6 +166,128 @@ @interface SDLVoiceCommand()
...
+            beforeEach(^{
+                testOp = [[SDLVoiceCommandUpdateOperation alloc] initWithConnectionManager:testConnectionManager pendingVoiceCommands:@[newVoiceCommand1] oldVoiceCommands:@[newVoiceCommand1, newVoiceCommand2] updateCompletionHandler:^(NSArray<SDLVoiceCommand *> * _Nonnull newCurrentVoiceCommands, NSError * _Nullable error) {
+                    callbackCurrentVoiceCommands = newCurrentVoiceCommands;
+                    callbackError = error;
+                }];
+                [testOp start];
+            });
+
+            // and the delete succeeds
+            context(@"and the delete succeeds", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:197]:
```suggestion
            describe(@"and the delete succeeds", ^{
```

If there's not more than one parallel sub-group, it's a describe

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 8]
```diff
@@ -166,6 +166,128 @@ @interface SDLVoiceCommand()
...
+            beforeEach(^{
+                testOp = [[SDLVoiceCommandUpdateOperation alloc] initWithConnectionManager:testConnectionManager pendingVoiceCommands:@[newVoiceCommand1, newVoiceCommand2] oldVoiceCommands:@[newVoiceCommand1] updateCompletionHandler:^(NSArray<SDLVoiceCommand *> * _Nonnull newCurrentVoiceCommands, NSError * _Nullable error) {
+                    callbackCurrentVoiceCommands = newCurrentVoiceCommands;
+                    callbackError = error;
+                }];
+                [testOp start];
+            });
+
+            // and the add succeeds
+            context(@"and the add succeeds", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:227]:
```suggestion
            describe(@"and the add succeeds", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 9]
```diff
@@ -166,6 +166,128 @@ @interface SDLVoiceCommand()
...
+                    expect(callbackCurrentVoiceCommands).to(haveCount(1));
+                    expect(callbackError).to(beNil());
+                    expect(testConnectionManager.receivedRequests).to(haveCount(1));
+                });
+            });
+        });
+
+
+        // going from voice commands [AB] to [A]
+        context(@"going from voice commands [AB] to [A]", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:217]:
```suggestion
        // going from voice commands [A] to [AB]
        context(@"going from voice commands [A] to [AB]", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 10]
```diff
@@ -166,6 +166,128 @@ @interface SDLVoiceCommand()
...
+                beforeEach(^{
+                    SDLAddCommandResponse *addNew1 = [[SDLAddCommandResponse alloc] init];
+                    addNew1.success = @YES;
+                    addNew1.resultCode = SDLResultSuccess;
+
+                    [testConnectionManager respondToRequestWithResponse:addNew1 requestNumber:0 error:nil];
+                    [testConnectionManager respondToLastMultipleRequestsWithSuccess:YES];
+                });
+
+                it(@"Should only upload the voiceCommand thats not in common and not delete anything", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:237]:
```suggestion
                it(@"should only upload the voiceCommand thats not in common and not delete anything", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 11]
```diff
@@ -166,6 +166,128 @@ @interface SDLVoiceCommand()
...
+            beforeEach(^{
+                testOp = [[SDLVoiceCommandUpdateOperation alloc] initWithConnectionManager:testConnectionManager pendingVoiceCommands:@[newVoiceCommand1, newVoiceCommand2] oldVoiceCommands:@[oldVoiceCommand1, oldVoiceCommand2] updateCompletionHandler:^(NSArray<SDLVoiceCommand *> * _Nonnull newCurrentVoiceCommands, NSError * _Nullable error) {
+                    callbackCurrentVoiceCommands = newCurrentVoiceCommands;
+                    callbackError = error;
+                }];
+                [testOp start];
+            });
+
+            // the delete and add commands succeeds
+            context(@"the delete and add commands succeeds", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:256]:
```suggestion
            describe(@"the delete and add commands succeeds", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 12]
```diff
@@ -166,6 +166,128 @@ @interface SDLVoiceCommand()
...
+                    SDLAddCommandResponse *addNew2 = [[SDLAddCommandResponse alloc] init];
+                    addNew2.success = @YES;
+                    addNew2.resultCode = SDLResultSuccess;
+
+                    [testConnectionManager respondToRequestWithResponse:addNew1 requestNumber:2 error:nil];
+                    [testConnectionManager respondToRequestWithResponse:addNew2 requestNumber:3 error:nil];
+                    [testConnectionManager respondToLastMultipleRequestsWithSuccess:YES];
+                });
+
+                it(@"Should delete and upload the voiceCommands", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:283]:
```suggestion
                it(@"should delete and upload the voiceCommands", ^{
```

File: SmartDeviceLink/private/SDLVoiceCommandManager.m [hunk 13]
```diff
@@ -151,7 +151,7 @@ - (void)sdl_updateIdsOnVoiceCommands:(NSArray<SDLVoiceCommand *> *)voiceCommands
 - (void)sdl_commandNotification:(SDLRPCNotificationNotification *)notification {
     SDLOnCommand *onCommand = (SDLOnCommand *)notification.notification;
 
-    for (SDLVoiceCommand *voiceCommand in self.voiceCommands) {
+    for (SDLVoiceCommand *voiceCommand in self.currentVoiceCommands) {
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLVoiceCommandManager.m:154]: Did you test this? It didn't fix the problem and the array you changed it to is empty at this point.

All I'm doing is setting two voice commands:

```objc
SDLVoiceCommand *vc1 = [[SDLVoiceCommand alloc] initWithVoiceCommands:@[@"Test 1"] handler:^{
    NSLog(@"VC 1 selected");
}];
SDLVoiceCommand *vc2 = [[SDLVoiceCommand alloc] initWithVoiceCommands:@[@"Test 2"] handler:^{
    NSLog(@"VC 2 selected");
}];
self.sdlManager.screenManager.voiceCommands = @[vc1, vc2];
```

**Review by joeljfischer — COMMENTED** [review]
Please also fix:

1. `sdlex_showInitialData` should not be called from `startManager` in Obj-C example app.

**Review by joeljfischer — APPROVED** [review]

**Comment by JulianKast** [comment]
If you upload a voiceCommand with string "Command one", then later on you create a new voiceCommand with that same string "Command one" and upload it, When selected is it going to hit the handler for the first one uploaded?

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 14]
```diff
@@ -254,10 +255,11 @@ @interface SDLVoiceCommandUpdateOperation()
                     [testConnectionManager respondToLastMultipleRequestsWithSuccess:YES];
                 });
 
-                it(@"should only upload the voiceCommand thats not in common and not delete anything", ^{
+                fit(@"should only upload the voiceCommand thats not in common and update the handler for voiceCommand in common", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:258]:
```suggestion
                it(@"should only upload the voiceCommand thats not in common and update the handler for voiceCommand in common", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 15]
```diff
@@ -254,10 +255,11 @@ @interface SDLVoiceCommandUpdateOperation()
...
                     expect(callbackCurrentVoiceCommands).to(haveCount(2));
                     expect(callbackError).to(beNil());
                     expect(testConnectionManager.receivedRequests).to(haveCount(1));
+                    XCTAssertEqual(testOp.currentVoiceCommands.firstObject.handler, newVoiceCommand3.handler);
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:262]: Use the Quick/Nimble expect system, not XCT system

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 16]
```diff
@@ -31,10 +31,13 @@ @interface SDLVoiceCommandUpdateOperation()
...
 __block SDLAddCommandResponse *successAdd = nil;
 __block SDLAddCommandResponse *failAdd = nil;
+__block BOOL handlerTest = NO;
 
 __block SDLVoiceCommand *newVoiceCommand1 = [[SDLVoiceCommand alloc] initWithVoiceCommands:@[@"NewVC1"] handler:^{}];
 __block SDLVoiceCommand *newVoiceCommand2 = [[SDLVoiceCommand alloc] initWithVoiceCommands:@[@"NewVC2"] handler:^{}];
-__block SDLVoiceCommand *newVoiceCommand3 = [[SDLVoiceCommand alloc] initWithVoiceCommands:@[@"OldVC1"] handler:^{}];
+__block SDLVoiceCommand *newVoiceCommand3 = [[SDLVoiceCommand alloc] initWithVoiceCommands:@[@"OldVC1"] handler:^{
+    handlerTest = YES;
+}];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:40]: Revert to what you had and rename to `oldVoiceCommand1Dupe`

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 17]
```diff
@@ -255,11 +258,12 @@ @interface SDLVoiceCommandUpdateOperation()
...
                 });
 
-                fit(@"should only upload the voiceCommand thats not in common and update the handler for voiceCommand in common", ^{
+                it(@"should only upload the voiceCommand thats not in common and update the handler for voiceCommand in common", ^{
                     expect(callbackCurrentVoiceCommands).to(haveCount(2));
                     expect(callbackError).to(beNil());
                     expect(testConnectionManager.receivedRequests).to(haveCount(1));
-                    XCTAssertEqual(testOp.currentVoiceCommands.firstObject.handler, newVoiceCommand3.handler);
+                    testOp.currentVoiceCommands.firstObject.handler();
+                    expect(handlerTest).to(equal(YES));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:266]: Remove and replace with:

```
expect(testOp.currentVoiceCommands.firstObject.handler == oldVoiceCommand1Dupe.handler).to(beTrue());
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 18]
```diff
@@ -31,10 +31,13 @@ @interface SDLVoiceCommandUpdateOperation()
 __block SDLDeleteCommandResponse *failDelete = nil;
 __block SDLAddCommandResponse *successAdd = nil;
 __block SDLAddCommandResponse *failAdd = nil;
+__block BOOL handlerTest = NO;
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:34]: Remove

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m [hunk 19]
```diff
@@ -56,6 +57,15 @@ - (void)start {
...
     }
 
+    // Check if a voiceCommand has already been uploaded and update its handler to prevent calling the wrong listener in a case where a voice command was uploaded and then its handler was updated without any changes to the voice command strings in a later update.
+    for (SDLVoiceCommand *voiceCommand in self.pendingVoiceCommands) {
+        for (SDLVoiceCommand *currentVoiceCommand in self.currentVoiceCommands) {
+            if ([voiceCommand isEqual:currentVoiceCommand]) {
+                currentVoiceCommand.handler = voiceCommand.handler;
+            }
+        }
+    }
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLVoiceCommandUpdateOperation.m:67]:
```suggestion
    for (NSUInteger i = 0; i < self.pendingVoiceCommands.count; i++) {
        for (NSUInteger j = i; j < self.currentVoiceCommands.count; j++) {
            if ([self.pendingVoiceCommands[i] isEqual:self.currentVoiceCommands[j]]) {
                self.currentVoiceCommands[j].handler = self.pendingVoiceCommands[i].handler;
            }
        }
    }
```

In doing my final passthrough, I noticed that the number of operations can be substantially improved from O(n^2) to O(n*log(n)) by using ordinary for loops.

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m (hunk 18 above)
Comment (joeljfischer) [reply SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:34]: You marked this as resolved but it wasn't done

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m (hunk 16 above)
Comment (joeljfischer) [reply SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:40]: You marked this as resolved but it wasn't done

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m (hunk 17 above)
Comment (joeljfischer) [reply SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:266]: You marked this as resolved but this wasn't done

**Review by joeljfischer — CHANGES_REQUESTED** [review]
It appears that you didn't make any of the requested changes

**Review by joeljfischer — CHANGES_REQUESTED** [review]
There are two test failures in the voice command manager that don't exist on develop

**Review by joeljfischer — APPROVED** [review]
