### PR TITLE
Handle System Request type HTTP according to PTU

### LINKED ISSUE #364: Support for the HTTP requestType is missing
### Bug Report
HTTP RequestType support is missing - this is required for unencrypted policy table updates to work in SDL Core.

##### Reproduction Steps
https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m#L314-L326

##### Expected Behavior
Working on it.... I don't know yet

##### Observed Behavior
Requests are just dropped

### PR DESCRIPTION
**Pull request by justinjdickow**
Fixes #364 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Jack and I tested this to make sure policy tables are updated

### Summary
* Now builds dictionaries for bulk data request types rather than returning nil
* Handles HTTP system requests by uploading bulk data as body of POST to specified URL and returning the response as a putFile according to HMI Integration Guidelines GENIVI Policy Table Update

##### Bug Fixes
* fixes #364 

### Tasks Remaining:
- [x] Fix the thing

### CODE REVIEW

File: SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m [hunk 1]
```diff
@@ -322,6 +322,8 @@ - (void)handleSystemRequest:(NSDictionary *)dict {
         [self handleSystemRequestProprietary:systemRequest];
     } else if (requestType == [SDLRequestType LOCK_SCREEN_ICON_URL]) {
         [self handleSystemRequestLockScreenIconURL:systemRequest];
+    } else if (requestType == [SDLRequestType HTTP]) {
```
Comment (joeljfischer) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m]: Are we doing anything for other types?

File: SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m [hunk 2]
```diff
@@ -427,6 +429,51 @@ - (void)handleSystemRequestLockScreenIconURL:(SDLOnSystemRequest *)request {
                               }];
 }
 
+- (void)handleSystemRequestHttp:(SDLOnSystemRequest *)request {
```
Comment (joeljfischer) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m]: HTTP should be all caps?

File: SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m [hunk 3]
```diff
@@ -427,6 +429,51 @@ - (void)handleSystemRequestLockScreenIconURL:(SDLOnSystemRequest *)request {
...
+    if (nil == request.bulkData) {
```
Comment (joeljfischer) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m]: I would check bulkData.length instead, in case it creates an NSData but it's empty

File: SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m [hunk 4]
```diff
@@ -427,6 +429,51 @@ - (void)handleSystemRequestLockScreenIconURL:(SDLOnSystemRequest *)request {
...
+                        if (data == nil || data.length == 0) {
+                            [SDLDebugTool logInfo:@"OnSystemRequest (HTTP response) failure: no data returned" withType:SDLDebugType_RPC toOutput:SDLDebugOutput_All toGroup:self.debugConsoleGroupName];
+                            return;
+                        }
+                        
+                        // Show the HTTP response
+                        [SDLDebugTool logInfo:@"OnSystemRequest (HTTP response)" withType:SDLDebugType_RPC toOutput:SDLDebugOutput_All toGroup:self.debugConsoleGroupName];
+                        
+                        // Create the SystemRequest RPC to send to module.
+                        SDLPutFile *putFile = [[SDLPutFile alloc] init];
```
Comment (joeljfischer) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m]: @Heath-FoMoCo @asm09fsu Is this going to fail because of the large putfile issue we've seen before?

File: SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m [hunk 5]
```diff
@@ -427,6 +429,51 @@ - (void)handleSystemRequestLockScreenIconURL:(SDLOnSystemRequest *)request {
...
+                        putFile.fileType = [SDLFileType JSON];
+                        putFile.correlationID = [NSNumber numberWithInt:POLICIES_CORRELATION_ID];
```
Comment (joeljfischer) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m]: Can just be `@(whatever)`

File: SmartDeviceLink-iOS/SmartDeviceLink/SDLV2ProtocolMessage.m [hunk 6]
```diff
@@ -21,8 +21,9 @@ - (instancetype)initWithHeader:(SDLProtocolHeader *)header andPayload:(NSData *)
 
 // Convert RPC payload to dictionary (for consumption by RPC layer)
 - (NSDictionary *)rpcDictionary {
+    
     // Only applicable to RPCs
-    if (self.header.serviceType != SDLServiceType_RPC) {
+    if (self.header.serviceType != SDLServiceType_RPC && self.header.serviceType != SDLServiceType_BulkData) {
```
Comment (joeljfischer) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLV2ProtocolMessage.m]: Please change to `(self.header.serviceType != SDLServiceType_RPC) && (self.header.serviceType != SDLServiceType_BulkData)` so that there isn't a merge conflict with #360

File: SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m (hunk 1 above)
Comment (justinjdickow) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m]: Not in this PR

Comment (joeljfischer) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m]: Do we need an issue?

File: SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m [hunk 7]
```diff
@@ -427,6 +429,51 @@ - (void)handleSystemRequestLockScreenIconURL:(SDLOnSystemRequest *)request {
...
+        NSLog(@"error creating body from bulk data: %@", error.localizedDescription);
+        return;
+    }
+    
+    [self uploadForBodyDataDictionary:body
+                            URLString:request.url
+                    completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
+                        NSString *logMessage = nil;
+                        if (error) {
+                            logMessage = [NSString stringWithFormat:@"OnSystemRequest (HTTP response) = ERROR: %@", error];
```
Comment (joeljfischer) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m]: May want to print the response in these error cases

File: SmartDeviceLink-iOS/SmartDeviceLink/SDLV2ProtocolMessage.m [hunk 8]
```diff
@@ -21,8 +21,9 @@ - (instancetype)initWithHeader:(SDLProtocolHeader *)header andPayload:(NSData *)
 
 // Convert RPC payload to dictionary (for consumption by RPC layer)
 - (NSDictionary *)rpcDictionary {
+
```
Comment (joeljfischer) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLV2ProtocolMessage.m]: Remove the blank line, please :)

File: SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m (hunk 4 above)
Comment (asm09fsu) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m]: If the data is large (couple MBs), then most likely yes. Otherwise should be fine. HTTP responses usually aren't more than a couple hundred KBs, right?

Comment (joeljfischer) [inline SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m]: :+1:

**Comment by joeljfischer** [comment]
:+1:
