### PR TITLE
Fix a crash when RPC encryption starts and callback when RPCs fail due to RPC encryption

### LINKED ISSUE #1966: Post-Connection RPC StartService w/ Encryption Causes a Crash
### Bug Report
When connecting an encrypted connection, there's a persistent crash.

##### Reproduction Steps
1. Create an encrypted connection to Core
2. Connect

##### Expected Behavior
No crash

##### Observed Behavior
Crash in Lifecycle Manager when the second RPC StartServiceACK is received.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 7.1-develop
* Testing Against: Core v7.1-develop

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1966, #1971

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit tests were updated to ensure that the callback is handled correctly.

#### Core Tests
Tested an RPC encrypted app with `PutFile` encrypted. Ensured that no crashes occurred and the app set up correctly.

Core version / branch / commit hash / module tested against: v7.1.0-RC.1 (0df66080512cbe76ee5d4872910a54adf3ca1f36)
HMI name / version / branch / commit hash / module tested against: sdl_hmi v5.5.0

### Summary
1. `SDLLifecycleManager` now ignores RPC `StartServiceACK` if we're already connected instead of crashing.
1. Updates `SDLProtocol sendRPC:` to pass back an error and return a success BOOL so that the handler can be called in the `SDLLifecycleManager` if the RPC fails to send in the protocol layer.

##### Bug Fixes
* Fixed RPC encryption causing a crash when the second RPC `StartServiceACK` is received.
* Fixed not calling an RPC request handler if the message failed to send in the protocol layer of the library.

### Tasks Remaining:
- [x] Add a unit test for the RPC failing to send in the protocol layer should call the handler.
- [x] Smoke test on Core v7.1.0
- [x] Smoke test on Sync 3.4

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLProtocol.h [hunk 1]
```diff
@@ -136,8 +136,9 @@ extern NSString *const SDLProtocolSecurityErrorDomain;
  *  Sends an unencrypted RPC to Core
  *
  *  @param message A SDLRPCMessage message
+ *  @returns YES if the RPC was sent, NO if it was not
```
Comment (NicoleYarroch) [inline SmartDeviceLink/private/SDLProtocol.h:139]: Can you add docs for the `error` param?

**Review by NicoleYarroch — CHANGES_REQUESTED** [review]
I small documentation fix requested.

**Review by NicoleYarroch — APPROVED** [review]
