### PR TITLE
Fix for sending voiceCommand with duplicate strings

### LINKED ISSUE #1961: Send voiceCommand with duplicate strings
### Bug Report
When a voice command contains the same string multiple times, it should reduce that to one of the duplicate string

##### Reproduction Steps
1. Send a voiceCommandA with duplicate strings

##### Expected Behavior
All duplicate strings in voiceCommandA needs to be reduced to one

##### Observed Behavior
All voiceCommandA strings are not changed

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1961 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Unit test added to cover the mentioned issue in `SDLVoiceCommandUpdateOperationSpec` file

#### Core Tests
Added a menu cell that uploads a voiceCommand with duplicate strings

Core version / branch / commit hash / module tested against: 7.1.0-RC1
HMI name / version / branch / commit hash / module tested against: Generic

### Summary
Reduce voiceCommand with duplicate strings to one

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Reduce voiceCommand with duplicate strings to one

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 1]
```diff
@@ -243,6 +244,32 @@ @interface SDLVoiceCommand()
                 });
             });
         });
+
+        context(@"if it has voiceCommand to upload with the same string multiple times", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:248]:
```suggestion
        context(@"if it multiple of the same command string", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 2]
```diff
@@ -243,6 +244,32 @@ @interface SDLVoiceCommand()
...
+
+                    [testConnectionManager respondToRequestWithResponse:addNew1 requestNumber:0 error:nil];
+                    [testConnectionManager respondToLastMultipleRequestsWithSuccess:YES];
+                });
+
+                it(@"should return the uploaded voiceCommand with reduced strings to 1 count", ^{
+                    expect(callbackError).toEventually(beNil());
+                    expect(callbackCurrentVoiceCommands.firstObject.voiceCommands.count).to(equal(1));
+                });
+            });
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:271]:
```suggestion
            it(@"should reduce the command string to have no duplicates", ^{
                expect(testCommand.voiceCommands).to(haveCount(1));
            });
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m [hunk 3]
```diff
@@ -243,6 +244,32 @@ @interface SDLVoiceCommand()
...
             });
         });
+
+        context(@"if it has voiceCommand to upload with the same string multiple times", ^{
+            beforeEach(^{
+                testOp = [[SDLVoiceCommandUpdateOperation alloc] initWithConnectionManager:testConnectionManager pendingVoiceCommands:@[newVoiceCommand3] oldVoiceCommands:@[] updateCompletionHandler:^(NSArray<SDLVoiceCommand *> * _Nonnull newCurrentVoiceCommands, NSError * _Nullable error) {
+                    callbackCurrentVoiceCommands = newCurrentVoiceCommands;
+                    callbackError = error;
+                }];
+                [testOp start];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandUpdateOperationSpec.m:254]:
```suggestion
                testCommand = // TODO
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/public/SDLVoiceCommand.m [hunk 4]
```diff
@@ -22,12 +23,21 @@ - (instancetype)initWithVoiceCommands:(NSArray<NSString *> *)voiceCommands handl
...
 }
 
+- (void)setVoiceCommands:(NSArray<NSString *> *)voiceCommands {
+    if (voiceCommands.count > 0) {
+        NSSet *voiceCommandsSet = [[NSSet alloc] initWithArray:voiceCommands];
+        _voiceCommands = [voiceCommandsSet allObjects];
+    } else {
+        _voiceCommands = voiceCommands;
+    }
+}
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLVoiceCommand.m:39]: Because this is publicly not settable, I don't think it's best to create a setter and a private readwrite property. Instead, make a class method called `sdl_removeDuplicateStrings:`. Then in the initializer, you can do `_voiceCommands = [self.class sdl_removeDuplicateStrings:voiceCommands];`

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/public/SDLVoiceCommand.m [hunk 5]
```diff
@@ -22,12 +22,17 @@ - (instancetype)initWithVoiceCommands:(NSArray<NSString *> *)voiceCommands handl
...
-    _voiceCommands = voiceCommands;
+    _voiceCommands = [self.class sdl_removeDuplicateStrings:voiceCommands];
     _handler = handler;
 
     return self;
 }
 
++ (NSArray<NSString *> *)sdl_removeDuplicateStrings:(NSArray<NSString *> *)voiceCommands {
+    NSSet *voiceCommandsSet = [[NSSet alloc] initWithArray:voiceCommands];
+    return [voiceCommandsSet allObjects];
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLVoiceCommand.m:33]:
```suggestion
    return [[[NSSet alloc] initWithArray:voiceCommands] allObjects];
```

Just suggesting a slight simplification

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]
