### PR TITLE
Pan gesture blocks single taps

### LINKED ISSUE #879: Single tap registered as a pan gesture
### Bug Report
If the head unit registers a small movement of the finger it is immediately recognised as a pan event instead of a single tap. This means that the iOS SDL SDK never sends our app single tap events.

##### Reproduction Steps
1. Perform single tap on head unit display
2. `[SDLTouchManager sdl_handleTouchMoved]` is called which sets
    `_performingTouchType = SDLPerformingTouchTypePanningTouch;`
3. Single tap delegate method is never called
`[strongSelf.touchEventDelegate touchManager:strongSelf didReceiveSingleTapForView:hitView atPoint:point];`

##### Expected Behavior
There should be a threshold movement level below which pan gestures are not recognised to prevent them interfering with single tap touch events.

##### Observed Behavior
Pan gesture recogniser prevents single taps from being recognised.

##### OS & Version Information
* iOS Version: 11.0.3
* SDL iOS Version: v5.1
* Testing Against: Head unit

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### PR DESCRIPTION
**Pull request by Lievesley**
Fixes #879 

This PR is ready for review.

### Risk
This PR makes minor API changes.

### Testing Plan
I already added the test case: 'when receiving a single tap with small movement'

### Summary
Added a pan threshold distance to prevent pan gestures being recognised for small movements.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by Lievesley** [comment]
This PR is ready for review

**Comment by Lievesley** [comment]
@joeljfischer please review this PR.

**Comment by joeljfischer** [comment]
Hi @Lievesley, thanks for the revised PR. Everything looks good from an overview. I just need some advice on if we can merge this as a bug or if we need an SDLC proposal. I'll let you know.

**Comment by Lievesley** [comment]
@joeljfischer  what is the process for approving the SDLC request and how long will this take?

File: SmartDeviceLink/SDLTouchManager.m [hunk 1]
```diff
@@ -235,6 +243,13 @@ - (void)sdl_handleTouchMoved:(SDLTouch *)touch {
         return; // no-op
     }
 #pragma clang diagnostic pop
+    
+    CGFloat xDelta = fabs(touch.location.x - self.firstTouch.location.x);
+    CGFloat yDelta = fabs(touch.location.y - self.firstTouch.location.y);
+    if (xDelta <= self.panDistanceThreshold && yDelta <= self.panDistanceThreshold)
+    {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLTouchManager.m]: Stylistically, this project uses braces on the same line.

**Comment by Lievesley** [comment]
@joeljfischer requested change to opening brace is ready for review.
