### PR TITLE
Fixed the choice set manager not handling failed preload choices correctly

### LINKED ISSUE #1941: Choice fails to preload - not properly handled
### Bug Report
When a choice fails to preload, the choice is still added to the list of preloaded choices. This may lead to a choice set being presented with choices that are not loaded.

##### Reproduction Steps
1. Attempt to preload 3 cells
2. Once cell fails in the `SDLPreloadChoicesOperation` phase

##### Expected Behavior
Cell is not available in the `SDLChoiceSetManager.preloadedMutableChoices` set.

##### Observed Behavior
Cell is available in the `SDLChoiceSetManager.preloadedMutableChoices` set.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 7.1.0-develop
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App
n/a

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #1941 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Test cases were added to `SDLChoiceSetManagerSpec` to test:
* All the choice items failing to upload
* Only one of the choice items failing to upload
* Presenting the same choice item again after it fails to uploads 
* Presenting the same choice item again after it uploads successfully

#### Core Tests
1. Presenting a choice set with a choice item that fails (this can be done by setting `menuName` with a string with 500+ characters). Then present the same choice set again. The failed choice item should be preloaded again. 

Core version / branch / commit hash / module tested against: 
* SYNC 3.0 (Build 17276_DEVTEST)
* Manticore (SDL Core v7.1.1)

HMI name / version / branch / commit hash / module tested against:
* SYNC 3.0 (Build 17276_DEVTEST)
* Manticore (Generic HMI v0.10.0)

### Summary
Fixed the `SDLChoiceSetManager` sending a `SDLPresentChoiceSetOperation` if one more more of the choice set items fails to upload. The failed choice set items are no longer added to the list of preloaded choices so they can be sent to the module again if previous attempts to upload the choice item failed.   

##### Bug Fixes
* Added error handling for failed choice set items to `SDLChoiceSetManager`.

### Tasks Remaining:
- [x] Smoke test with SYNC 3

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/private/SDLChoiceSetManager.m [hunk 1]
```diff
@@ -268,6 +267,18 @@ - (void)preloadChoices:(NSArray<SDLChoiceCell *> *)choices withCompletionHandler
...
 
+        NSMutableSet *failedChoiceUploads = [NSMutableSet set];
+        if (weakPreloadOp.error != nil) {
+            NSDictionary *failedChoices = weakPreloadOp.error.userInfo;
+            for (SDLCreateInteractionChoiceSet *request in failedChoices) {
+                NSUInteger failedChoiceUploadIndex = [choicesToUpload indexOfObjectPassingTest:^BOOL(SDLChoiceCell * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
+                    return (obj.choiceId == request.choiceSet.firstObject.choiceID.intValue);
+                }];
+                if (failedChoiceUploadIndex == NSNotFound) { continue; }
+                [failedChoiceUploads addObject:[choicesToUpload objectAtIndex:failedChoiceUploadIndex]];
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLChoiceSetManager.m:278]: Use subscripting instead of `objectAtIndex`

File: SmartDeviceLink/private/SDLChoiceSetManager.m [hunk 2]
```diff
@@ -268,6 +267,18 @@ - (void)preloadChoices:(NSArray<SDLChoiceCell *> *)choices withCompletionHandler
         __strong typeof(weakSelf) strongSelf = weakSelf;
         SDLLogD(@"Choices finished preloading");
 
+        NSMutableSet *failedChoiceUploads = [NSMutableSet set];
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLChoiceSetManager.m:270]: Use generics for all collections

File: SmartDeviceLink/private/SDLChoiceSetManager.m [hunk 3]
```diff
@@ -268,6 +267,18 @@ - (void)preloadChoices:(NSArray<SDLChoiceCell *> *)choices withCompletionHandler
...
+        if (weakPreloadOp.error != nil) {
+            NSDictionary *failedChoices = weakPreloadOp.error.userInfo;
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLChoiceSetManager.m:272]: See above about generics

**Review by joeljfischer — CHANGES_REQUESTED** [review]
😅

File: SmartDeviceLink/private/SDLChoiceSetManager.m [hunk 4]
```diff
@@ -268,6 +267,18 @@ - (void)preloadChoices:(NSArray<SDLChoiceCell *> *)choices withCompletionHandler
         __strong typeof(weakSelf) strongSelf = weakSelf;
         SDLLogD(@"Choices finished preloading");
 
+        NSMutableSet<SDLChoiceCell *> *failedChoiceUploads = [NSMutableSet set];
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLChoiceSetManager.m:270]: Add a comment explaining this set of code

Comment (joeljfischer) [inline SmartDeviceLink/private/SDLChoiceSetManager.m:270]: This shouldn't happen in `preloadOp.completionBlock`, the completion block only occurs after the next operation starts running, which means if there's a preload then a present, the present will start before this code runs, which means that the present will be unaware of the failures. There needs to be another block passed to the operation which runs before completion in which code like this would run. See voice command manager for example.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLChoiceSetManager.m [hunk 5]
```diff
@@ -278,15 +280,48 @@ - (void)preloadChoices:(NSArray<SDLChoiceCell *> *)choices withCompletionHandler
...
+/// Update currently pending preload choice operations with the failed choice commands so a re-upload can be attempted.
+/// @param failedPreloadedChoices The failed choice commands
+- (void)sdl_updatePendingOperationsWithFailedPreloadedChoices:(NSSet<SDLChoiceCell *> *)failedPreloadedChoices {
+    for (NSOperation *operation in self.transactionQueue.operations) {
+        if (operation.isExecuting || ![operation isKindOfClass:SDLPreloadChoicesOperation.class]) { continue; }
+
+        SDLPreloadChoicesOperation *updateOp = (SDLPreloadChoicesOperation *)operation;
+        [updateOp addFailedChoicesToUpload:failedPreloadedChoices];
+    }
+}
```
Comment (joeljfischer) [inline SmartDeviceLink/private/SDLChoiceSetManager.m:323]: I don't think this is the right approach. It's complicated, and it adds potentially unnecessary choices to all future operations. Instead:

1. If there was an attached `present`, it will fail because some of the needed choices are not available.
2. If the preload was standalone, some of the choices will have simply failed to upload. If a future present occurs attempting to use some of those choices and some others that failed, they will be re-attempted automatically then with the current setup.

I think that most of these changes, then, should be reverted.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLChoiceSetManager.m (hunk 5 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/private/SDLChoiceSetManager.m]: Fixed. Removed.

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m [hunk 6]
```diff
@@ -297,6 +308,121 @@
...
+                testCell1 = [[SDLChoiceCell alloc] initWithText:@"Cell1" artwork:nil voiceCommands:nil];
+                testCell2 = [[SDLChoiceCell alloc] initWithText:@"Cell2" secondaryText:nil tertiaryText:nil voiceCommands:nil artwork:nil secondaryArtwork:[SDLArtwork artworkWithStaticIcon:SDLStaticIconNameClock]];
+                testCells = [[NSOrderedSet alloc] initWithArray:@[testCell1, testCell2]];
+            });
+
+            context(@"if a choice item is removed", ^{
+                it(@"should be removed if the removal is attempted while the operation is pending", ^{
+                    SDLTextField *primaryTextField = [[SDLTextField alloc] init];
+                    primaryTextField.name = SDLTextFieldNameMenuName;
+                    windowCapability.textFields = @[primaryTextField];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m:327]: I think that this can be moved from this it and the below to the above context

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m [hunk 7]
```diff
@@ -297,6 +308,121 @@
...
+            __block SDLChoiceCell *testCell2 = nil;
+            __block NSOrderedSet<SDLChoiceCell *> *testCells = nil;
+
+            beforeEach(^{
+                testCell1 = [[SDLChoiceCell alloc] initWithText:@"Cell1" artwork:nil voiceCommands:nil];
+                testCell2 = [[SDLChoiceCell alloc] initWithText:@"Cell2" secondaryText:nil tertiaryText:nil voiceCommands:nil artwork:nil secondaryArtwork:[SDLArtwork artworkWithStaticIcon:SDLStaticIconNameClock]];
+                testCells = [[NSOrderedSet alloc] initWithArray:@[testCell1, testCell2]];
+            });
+
+            context(@"if a choice item is removed", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m:323]:
```suggestion
            describe(@"if a choice item is removed", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m [hunk 8]
```diff
@@ -297,6 +308,121 @@
...
+                    NSArray<SDLCreateInteractionChoiceSet *> *receivedRequests = (NSArray<SDLCreateInteractionChoiceSet *> *)testConnectionManager.receivedRequests;
+
+                    expect(receivedRequests).to(haveCount(2));
+                    expect(receivedRequests[0].choiceSet[0].menuName).to(equal(testCell1.text));
+                    expect(receivedRequests[1].choiceSet[0].menuName).to(equal(testCell2.text));
+                });
+            });
+        });
+
+        context(@"the module's response to choice uploads", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m:357]:
```suggestion
        describe(@"the module's response to choice uploads", ^{
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m [hunk 9]
```diff
@@ -297,6 +308,121 @@
...
+                testGoodResponse = [[SDLCreateInteractionChoiceSetResponse alloc] init];
+                testGoodResponse.success = @YES;
+                testGoodResponse.resultCode = SDLResultSuccess;
+            });
+
+            context(@"when a bad response comes back", ^{
+                 it(@"should add the choiceID of the failed choice item to the failedChoiceUploadIDs array", ^{
+                    SDLTextField *primaryTextField = [[SDLTextField alloc] init];
+                    primaryTextField.name = SDLTextFieldNameMenuName;
+                    windowCapability.textFields = @[primaryTextField];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m:384]: This seems to be the same setup as above (below as well) so maybe the setup should go even higher up than my previous comment described?

File: SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m [hunk 10]
```diff
@@ -440,105 +457,384 @@ - (void)sdl_addUniqueNamesToCells:(NSMutableSet<SDLChoiceCell *> *)choices;
...
+                    }]]);
+                    OCMExpect([strickMockOperationQueue addOperation:[OCMArg checkWithBlock:^BOOL(id value) {
+                        SDLPresentChoiceSetOperation *presentChoicesOperation = (SDLPresentChoiceSetOperation *)value;
+                        presentChoicesOperation.selectedCell = testSelectedCell;
+                        presentChoicesOperation.selectedTriggerSource = testMode;
+                        presentChoicesOperation.selectedCellRow = testSelectedCellRow;
+                        presentChoicesOperation.internalError = nil;
+                        presentChoicesOperation.completionBlock();
+                        return [value isKindOfClass:[SDLPresentChoiceSetOperation class]];
+                    }]]);
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m:503]: Isn't the second expect here just overriding the first since it's on the same method? I'm not sure.

File: SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m [hunk 11]
```diff
@@ -440,105 +457,384 @@ - (void)sdl_addUniqueNamesToCells:(NSMutableSet<SDLChoiceCell *> *)choices;
...
+                }]]);
+                OCMExpect([choiceDelegate choiceSet:testChoiceSet didSelectChoice:testSelectedCell withSource:testMode atRowIndex:testSelectedCellRow]);
+
+                [testManager presentChoiceSet:testChoiceSet mode:testMode withKeyboardDelegate:keyboardDelegate];
+
+                OCMVerifyAllWithDelay(strickMockOperationQueue, 0.5);
+                OCMVerifyAllWithDelay(choiceDelegate, 0.5);
+            });
+
+            it(@"It should upload choices that failed to upload in previous presentations", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m:680]:
```suggestion
            it(@"should upload choices that failed to upload in previous presentations", ^{
```

I think this needs more information. It shouldn't upload them unless another presentation is created, right?

File: SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m [hunk 12]
```diff
@@ -440,105 +457,384 @@ - (void)sdl_addUniqueNamesToCells:(NSMutableSet<SDLChoiceCell *> *)choices;
...
+
+                    expect(testManager.pendingPresentationSet).toNot(beNil());
+                    expect(testManager.pendingPresentOperation).toNot(beNil());
+
+                    expect(testManager.preloadedMutableChoices).to(beEmpty());
+                    expect(testManager.pendingMutablePreloadChoices).to(beEmpty());
                 });
             });
 
+            it(@"It should skip preloading the choices if all choice items have already been uploaded", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m:629]:
```suggestion
            it(@"should skip preloading the choices if all choice items have already been uploaded", ^{
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLink/private/SDLPreloadChoicesOperation.m [hunk 13]
```diff
@@ -135,6 +139,8 @@ - (void)sdl_preloadCells {
     [self.connectionManager sendRequests:[choiceRPCs copy] progressHandler:^(__kindof SDLRPCRequest * _Nonnull request, __kindof SDLRPCResponse * _Nullable response, NSError * _Nullable error, float percentComplete) {
         if (error != nil) {
             errors[request] = error;
+            SDLCreateInteractionChoiceSet *sentRequest = (SDLCreateInteractionChoiceSet *)request;
+            [self.failedChoiceUploadIDs insertObject:sentRequest.choiceSet.firstObject.choiceID atIndex:0];
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/private/SDLPreloadChoicesOperation.m]: Fixed.

File: SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m (hunk 10 above)
Comment (NicoleYarroch) [reply SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m:503]: The first `OCMExpect` is needed to trigger the `finishOperation` for the `SDLPreloadChoicesOperation` so the `SDLPresentChoiceSetOperation` can be created and sent. If you comment out either `OCMExpect`, the test fails.

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m (hunk 6 above)
Comment (NicoleYarroch) [reply SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m:327]: I removed the code as it was unnecessary.

File: SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m (hunk 9 above)
Comment (NicoleYarroch) [reply SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m:384]: I removed the code as it was not necessary for the test to run.

File: SmartDeviceLink/private/SDLChoiceSetManager.m [hunk 14]
```diff
@@ -373,13 +394,28 @@ - (void)presentChoiceSet:(SDLChoiceSet *)choiceSet mode:(SDLInteractionMode)mode
...
         if (error != nil) {
+            SDLLogE(@"Error preloading choice cells. Aborting presentation.");
             [choiceSet.delegate choiceSet:choiceSet didReceiveError:error];
             return;
         }
+
+        if ([strongSelf.currentState isEqualToString:SDLChoiceManagerStateShutdown]) {
+            SDLLogD(@"Cancelling presenting choices because the manager has shut down");
+            return;
+        }
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/private/SDLChoiceSetManager.m]: Fixed. Added

**Review by joeljfischer — APPROVED** [review]
