### PR TITLE
Keep File Manager from Error State on disallowed

### LINKED ISSUE #1454: ListsFiles rpc returns DISALLOWED should not call SDLFileManagerStateStartupError
### Bug Report
When ListsFiles returns DISALLOWED we should transition to SDLFileManagerStateReady and not SDLFileManagerStateStartupError

### PR DESCRIPTION
**Pull request by justingluck93**
Fixes #1454 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Test against example app using Xcode 11. Make sure to remove `ListFiles`RPC from cores policy table in order to recreate a `disallowed`

### Summary
This PR adds a check to see if the error was `disallowed`. If it is `disallowed` we no longer want to Error but rather continue with the setup process. 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLFileManager.m [hunk 1]
```diff
@@ -204,6 +209,10 @@ - (void)sdl_listRemoteFilesWithCompletionHandler:(SDLFileManagerListFilesComplet
     __weak typeof(self) weakSelf = self;
     SDLListFilesOperation *listOperation = [[SDLListFilesOperation alloc] initWithConnectionManager:self.connectionManager completionHandler:^(BOOL success, NSUInteger bytesAvailable, NSArray<NSString *> *_Nonnull fileNames, NSError *_Nullable error) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLFileManager.m]: Instead of checking the description, the operation should return the `resultCode` in the error `userInfo`.

File: SmartDeviceLink/SDLFileManager.m [hunk 2]
```diff
@@ -204,6 +209,10 @@ - (void)sdl_listRemoteFilesWithCompletionHandler:(SDLFileManagerListFilesComplet
...
         if (error != nil || !success) {
+            if([error.localizedDescription isEqualToString:@"DISALLOWED"]) {
+                [weakSelf.mutableRemoteFileNames addObjectsFromArray:fileNames];
+                weakSelf.bytesAvailable = bytesAvailable;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLFileManager.m]: Why are you setting this data here?

File: SmartDeviceLink/SDLFileManager.m [hunk 3]
```diff
@@ -179,8 +179,13 @@ - (void)didEnterStateFetchingInitialList {
             BLOCK_RETURN;
         }
 
-        // If there was an error, we'll pass the error to the startup handler and cancel out
+        // If there was an error, we'll pass the error to the startup handler and cancel out other then in case of DISALLOWED
         if (error != nil) {
+            // In the case we are DISALLOWED we still want to transition to a ready state
+            if([error.localizedDescription isEqualToString:@"DISALLOWED"]) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLFileManager.m]: Needs a log, and see below for passing along the `resultCode`.

File: SmartDeviceLink/SDLFileManager.m (hunk 2 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLFileManager.m]: because if we don't and we let the setup continue bytesAvailable will be 0

Comment (joeljfischer) [reply SmartDeviceLink/SDLFileManager.m]: It'll still be 0 because a failed RPC will either return 0 or nil.

File: SmartDeviceLink/SDLFileManager.m (hunk 1 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLFileManager.m]: fixed

File: SmartDeviceLink/SDLFileManager.m (hunk 2 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLFileManager.m]: removed

File: SmartDeviceLink/SDLListFilesOperation.m [hunk 4]
```diff
@@ -59,7 +59,15 @@ - (void)sdl_listFiles {
...
 
         if (weakSelf.completionHandler != nil) {
-            weakSelf.completionHandler(success, bytesAvailable, fileNames, error);
+            if([response.resultCode isEqualToEnum:SDLResultDisallowed]) {
+                NSMutableDictionary *results = [error.userInfo mutableCopy];
+                results[@"resultCode"] = SDLResultDisallowed;
+                NSError *resultError = [NSError errorWithDomain:error.domain code:error.code userInfo:results];
+                weakSelf.completionHandler(success, bytesAvailable, fileNames, resultError);
+            }
+            else {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLListFilesOperation.m]: Follow the formatting of the project with if / else

File: SmartDeviceLink/SDLFileManager.m [hunk 5]
```diff
@@ -202,6 +207,7 @@ - (void)didEnterStateReady {
 
 - (void)sdl_listRemoteFilesWithCompletionHandler:(SDLFileManagerListFilesCompletionHandler)handler {
     __weak typeof(self) weakSelf = self;
+
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLFileManager.m]:
```suggestion
```

File: SmartDeviceLink/SDLFileManager.m (hunk 3 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLFileManager.m]: added

File: SmartDeviceLink/SDLListFilesOperation.m (hunk 4 above)
Comment (justingluck93) [reply SmartDeviceLink/SDLListFilesOperation.m]: fixed

File: SmartDeviceLink/SDLFileManager.m [hunk 6]
```diff
@@ -179,8 +179,14 @@ - (void)didEnterStateFetchingInitialList {
             BLOCK_RETURN;
         }
 
-        // If there was an error, we'll pass the error to the startup handler and cancel out
+        // If there was an error, we'll pass the error to the startup handler and cancel out other then in case of DISALLOWED
         if (error != nil) {
+            // In the case we are DISALLOWED we still want to transition to a ready state
+            if([error.userInfo[@"resultCode"] isEqualToEnum:SDLResultDisallowed]) {
+                SDLLogW(@"ListFiles is disallowed. Certain file RPC may not work properly.");
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLFileManager.m]:
```suggestion
                SDLLogW(@"ListFiles is disallowed. Certain file manager APIs may not work properly.");
```

File: SmartDeviceLink/SDLListFilesOperation.m [hunk 7]
```diff
@@ -59,7 +59,14 @@ - (void)sdl_listFiles {
         NSUInteger bytesAvailable = listFilesResponse.spaceAvailable != nil ? listFilesResponse.spaceAvailable.unsignedIntegerValue : 2000000000;
 
         if (weakSelf.completionHandler != nil) {
-            weakSelf.completionHandler(success, bytesAvailable, fileNames, error);
+            if([response.resultCode isEqualToEnum:SDLResultDisallowed]) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLListFilesOperation.m]: Instead of this, just always set the `resultCode` into the error if an error exists.

File: SmartDeviceLinkTests/DevAPISpecs/SDLListFilesOperationSpec.m [hunk 8]
```diff
@@ -92,13 +92,24 @@
...
             
             it(@"should have called completion handler with error", ^{
+                [testConnectionManager respondToLastRequestWithResponse:badResponse error:[NSError sdl_lifecycle_unknownRemoteErrorWithDescription:responseErrorDescription andReason:responseErrorReason]];
+
+                expect(errorResult.localizedDescription).to(match(responseErrorDescription));
+                expect(errorResult.localizedFailureReason).to(match(responseErrorReason));
+                expect(@(successResult)).to(equal(@NO));
+            });
+
+            it(@"should have called completion handler with error including a resultCode ", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLListFilesOperationSpec.m]: Based on the above change request, I think that this `it` is the only one needed?

File: SmartDeviceLink/SDLFileManager.m [hunk 9]
```diff
@@ -179,8 +179,14 @@ - (void)didEnterStateFetchingInitialList {
             BLOCK_RETURN;
         }
 
-        // If there was an error, we'll pass the error to the startup handler and cancel out
+        // If there was an error, we'll pass the error to the startup handler and cancel out other then in case of DISALLOWED
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLFileManager.m]:
```suggestion
        // If there was an error, we'll pass the error to the startup handler and cancel out
```

File: SmartDeviceLink/SDLFileManager.m [hunk 10]
```diff
@@ -179,8 +179,14 @@ - (void)didEnterStateFetchingInitialList {
...
         if (error != nil) {
+            // In the case we are DISALLOWED we still want to transition to a ready state
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLFileManager.m]:
```suggestion
            // HAX: In the case we are DISALLOWED we still want to transition to a ready state. Some head units return DISALLOWED for this RPC but otherwise work.
```
