### PR TITLE
Numerous fixes to SDLVideoStreamingRange

### LINKED ISSUE #2011: Fix SDLVideoStreamingRange Class
### Bug Report
This class has several problems: (1) documentation is not applied due to not being formatted correctly, (2) there is no initializer for all parameters, (3) `minimumDiagonal` is marked as required, but the initializer doesn't create a value for this parameter.

##### Reproduction Steps
n/a

##### Expected Behavior
n/a

##### Observed Behavior
n/a

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: v7.2.0-rc.1
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App
n/a

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #2011 

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Added unit tests for SDLVideoStreamingRange

#### Core Tests
Ran on Sync 3 TDK with ranges, ran on Core 7.1.1 with ranges that disabled some support.

Core version / branch / commit hash / module tested against: Sync 3.4 | Core v7.1.1
HMI name / version / branch / commit hash / module tested against: Sync 3.4 | Generic HMI v0.10.0

### Summary
* Add tests
* Fix comments not being documentation comments
* Add a full initializer
* Fix nullability
* Add to module map
* Add setters to enforce minimums

##### Bug Fixes
* Fixed missing documentation and initializers in `SDLVideoStreamingRange`.

### Tasks Remaining:
- [x] Run Smoke Tests on Core

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLinkTests/DevAPISpecs/SDLVideoStreamingRangeSpec.m [hunk 1]
```diff
@@ -0,0 +1,221 @@
...
+        });
+
+        context(@"when the resolution is in the range", ^{
+            it(@"should return YES", ^{
+                expect([testRange isImageResolutionInRange:[[SDLImageResolution alloc] initWithWidth:2 height:2]]).to(beTrue());
+            });
+        });
+    });
+
+    describe(@"checking if the aspect ratio is in a given range", ^{
```
Comment (FrankElias77) [inline SmartDeviceLinkTests/DevAPISpecs/SDLVideoStreamingRangeSpec.m:176]: Tests in this section are missing the expected result `to(beTrue())` or `to(beFalse())`

**Review by FrankElias77 — COMMENTED** [review]
There are 2 minor tests failing in SDLSupportedStreamingRangeSpec that are related to this PR and 2 failing tests SDLStreamingVideoLifecycleManagerSpec

File: SmartDeviceLinkTests/DevAPISpecs/SDLVideoStreamingRangeSpec.m (hunk 1 above)
Comment (joeljfischer) [reply SmartDeviceLinkTests/DevAPISpecs/SDLVideoStreamingRangeSpec.m:176]: Fixed

**Review by FrankElias77 — APPROVED** [review]
