### PR TITLE
Fix SDLAudioStreamManager doesn't have human readable error messages

### LINKED ISSUE #1622: Add userInfo to error returned by the SDLAudioStreamManager
### Bug Report
The error returned by the `SDLAudioStreamManager` if the transport has disconnected does not contain any useful clues as to what error occurred other than to return the error code. 

The error should be moved to the `SDLError` class and the `userInfo` field should be filled out and returned. 

##### Reproduction Steps
1. Connect a video and audio streaming app to a module. Launch the SDL app and wait for video and audio to start playing.
1. Disconnect the transport.

##### Expected Behavior
1. The logs should say that there was an error playing the audio file due to the transport disconnecting. 

##### Observed Behavior
1. The logs say that there was an error playing the audio file but do not offer any more information. 

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.5
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1622

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Tests were run, fixed an import error

#### Core Tests
N/A, error string updates only

Core version / branch / commit hash / module tested against: n/a
HMI name / version / branch / commit hash / module tested against: n/a

### Summary
Updated the `SDLAudioStreamManager` to move its error domain and code to `SDLError`. This is just declarations of an enum and constant, so moving them isn't a major change. Also updated the human-readable string values on an error, and a few other code cleanup items.

##### Bug Fixes
* Updated an SDLAudioStreamManager error to have a human-readable message.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLError.m [hunk 1]
```diff
@@ -128,8 +129,8 @@ + (NSError *)sdl_lifecycle_startedWithBadResult:(SDLResult)result info:(NSString
 
 + (NSError *)sdl_lifecycle_startedWithWarning:(SDLResult)result info:(NSString *)info {
     NSDictionary<NSString *, NSString *> *userInfo = @{
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLError.m:131]: Tests are failing here when `result` is `nil`. 
> -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]"

File: SmartDeviceLink/SDLErrorConstants.h [hunk 2]
```diff
@@ -199,3 +199,11 @@ typedef NS_ENUM(NSInteger, SDLCacheFileManagerError) {
      */
     SDLCacheManagerErrorUpdateIconArchiveFileFailure = -1,
 };
+
+typedef NS_ENUM(NSInteger, SDLAudioStreamManagerError) {
+    /// The audio stream is not currently connected
+    SDLAudioStreamManagerErrorNotConnected = -1,
+
+    /// Attempted to play but there's no audio in the queue
+    SDLAudioStreamManagerErrorNoQueuedAudio = -2
```
Comment (NicoleYarroch) [inline SmartDeviceLink/SDLErrorConstants.h:208]: `SDLAudioStreamManagerErrorNoQueuedAudio` does not seem to be used anywhere.

Comment (joeljfischer) [reply SmartDeviceLink/SDLErrorConstants.h:208]: I know, but it's a public API so removing it is a major version change.

File: SmartDeviceLink/SDLError.m (hunk 1 above)
Comment (joeljfischer) [reply SmartDeviceLink/SDLError.m:139]: Fixed
