### PR TITLE
Fix Release Script Bugs

### LINKED ISSUE #2098: Release Script Bugs
### Description

- Need to add a check before the stash message.
- Versions are displaying flipped.
	- line 112
	- rps and protocol versions
- "please update protocol versions" -> "please update versions"
- It might be nice to add a template to the changelog.
- The script is not built for M1 architecture
	- Jazzy failed to run
	- what if we added a prompt that reminds people to run with rosetta?
		- Check architecture and set arch command according to what is needed
- Merge back to develop did not work.  Please investigate.
	- did not merge to develop
	- did not change to develop
- Before opening GitHub page, make sure to push master and tag.
- Github release create is still very manual.
	- Can we provide copy/paste templates?
	- Can we automatically open directories for drag and drop?
- Script failed to change smartdevicelink.podspec
- There could be cases where you would not want to automatically check out develop
	- add a prompt "would you like to checkout develop before making changes?"
	- maybe remove the "develop has been checked out for you" line as this can cause confusion.
- zip file was empty!!!  Investigate how that happened?  Manual run did work as intended.

### PR DESCRIPTION
**Pull request by Swift2568**
Fixes #2098

### Risk
This PR makes **no** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A - release script only

#### Core Tests
N/A - release script only

Core version / branch / commit hash / module tested against: n/a
HMI name / version / branch / commit hash / module tested against: n/a

### Summary
Fixes a number of release script bugs identified during the June release.

##### Bug Fixes
* Added check before stash message
* Fixed versions displaying flipped
*  "please update protocol versions" -> "please update versions"
* Added commands to account for M1 architecture.
* Fixed merge commands
* Adjusted message for push/tag before Github page
* Podspec edits should now stick (related to merge fix)
* Adjusted logic around checkout of develop
* Fixed Zip command

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: scripts/release.sh [hunk 1]
```diff
@@ -43,16 +41,54 @@ fi
...
+            else
+                # Dump local changes to prevent issues with checkout
+                git reset --hard
+            fi
+        fi
+        
+        # Do a fetch to make sure we are up to date.
+        # git fetch
+        git config pull.ff only
+        git pull
```
Comment (joeljfischer) [inline scripts/release.sh:78]: This doesn't look right. I don't think we want to permanently update the user's config. Is there a `git pull` modifier to only do a fast-forward? And what will you do if the fast-forward fails?

File: scripts/release.sh [hunk 2]
```diff
@@ -146,12 +182,11 @@ if [ ! -z "$submodule_info" ]; then
...
 
 # Update changelog
-# TODO - insert a template into the changelog that includes the version the users have selected above.
-#echo "A template for this release has been inserted into the changelog. Please update it."
+# TODO - we could insert a template into the changelog that includes the version the users have selected above.
 echo 
 echo "Please update CHANGELOG.md, then return here and press enter..."
 read user_input
-# TODO - check modified info before and after so we can detect if the user failed to update the file.
+# TODO - check modified info before and after so we can detect if the user did update the file.
```
Comment (joeljfischer) [inline scripts/release.sh:189]:
```suggestion
# TODO - check modified info before and after so we can detect if the user updated the file.
```

File: scripts/release.sh [hunk 3]
```diff
@@ -164,7 +199,12 @@ if [[ $? == 1 ]]; then
 
     # This runs Jazzy to generate the documentation.
     echo "Running Jazzy to generate documentation..."
-    jazzy --clean --objc --framework-root SmartDeviceLink --sdk iphonesimulator --umbrella-header SmartDeviceLink/public/SmartDeviceLink.h --theme theme --output docs
+    # TODO - I do not know if this will work as intended.
```
Comment (joeljfischer) [inline scripts/release.sh:202]: I'll have to test this on my M1 to ensure it works, then we should remove this TODO.

File: scripts/release.sh [hunk 4]
```diff
@@ -174,63 +214,81 @@ echo "If there is, please update the rpc_spec submodule to point to the newest c
...
 
-        # Merge develop with master
-        git merge $main_branch $develop_branch
 
-        echo "Please check that everything is correct. Then, assuming you have permissions, push to master, then press enter..."
-    else
-        echo "Aborting script!"
-        exit 0
-    fi
+        # Merge release to master (update master from)
```
Comment (joeljfischer) [inline scripts/release.sh:238]:
```suggestion
        # Merge release to master (update master from develop)
```

File: scripts/release.sh [hunk 5]
```diff
@@ -174,63 +214,81 @@ echo "If there is, please update the rpc_spec submodule to point to the newest c
...
+        prompt_user "Would you like to merge this release to master? (This will not push to master)"
```
Comment (joeljfischer) [inline scripts/release.sh:239]:
```suggestion
        prompt_user "Would you like to merge this release from develop to master? (This will not push to master)"
```

File: scripts/release.sh [hunk 6]
```diff
@@ -174,63 +214,81 @@ echo "If there is, please update the rpc_spec submodule to point to the newest c
...
+        if [[ $? == 1 ]]; then
+            # Checkout master
+            git checkout $main_branch
+
+            # Merge develop with master.
+            # This updates the checked out master with the contents of develop
+            git merge $develop_branch $main_branch
+
+            echo "Please check that everything is correct. "
```
Comment (joeljfischer) [inline scripts/release.sh:248]:
```suggestion
            echo "Please check that everything is correct."
```

File: scripts/release.sh [hunk 7]
```diff
@@ -174,63 +214,81 @@ echo "If there is, please update the rpc_spec submodule to point to the newest c
...
+        
+            # Tag it
+            prompt_user "Would you like to tag this release with $new_version_number? (This will not push the tag)"
+            if [[ $? == 1 ]]; then
+                git tag $new_version_number
+                # git push --set-upstream origin $main_branch
```
Comment (joeljfischer) [inline scripts/release.sh:254]:
```suggestion
```

File: scripts/release.sh [hunk 8]
```diff
@@ -174,63 +214,81 @@ echo "If there is, please update the rpc_spec submodule to point to the newest c
...
+            exit 0
+        fi
 
-    # Tag it
-    prompt_user "Would you like to tag this release with $new_version_number? (This will not push the tag)"
-    if [[ $? == 1 ]]; then
-        git tag $new_version_number
-        # IDEA - else condition that allows the user to enter a different tag
+        # Merge master back to develop
+        prompt_user "Would you like to merge master back into develop (This will not push the branch)"
```
Comment (joeljfischer) [inline scripts/release.sh:270]: This should either push or prompt the user to push

File: scripts/release.sh [hunk 9]
```diff
@@ -164,7 +199,12 @@ if [[ $? == 1 ]]; then
 
     # This runs Jazzy to generate the documentation.
     echo "Running Jazzy to generate documentation..."
-    jazzy --clean --objc --framework-root SmartDeviceLink --sdk iphonesimulator --umbrella-header SmartDeviceLink/public/SmartDeviceLink.h --theme theme --output docs
+    # TODO - I do not know if this will work as intended.
+    if [ $(uname -m) == "x86_64" ]; then
+        jazzy --clean --objc --framework-root SmartDeviceLink --sdk iphonesimulator --umbrella-header SmartDeviceLink/public/SmartDeviceLink.h --theme theme --output docs
+    else
+        arch -x86_64 jazzy --clean --objc --framework-root SmartDeviceLink --sdk iphonesimulator --umbrella-header SmartDeviceLink/public/SmartDeviceLink.h --theme theme --output docs
+    fi
```
Comment (joeljfischer) [inline scripts/release.sh:207]: Should this call `generate_documentation.sh` and can this fix be applied there?

File: scripts/release.sh [hunk 10]
```diff
@@ -43,16 +41,54 @@ fi
...
-prompt_user "Would you like to stash any local changes"
-if [[ $? == 1 ]]; then
-    # Stash local changes to prevent issues with checkout
-    git stash
-    echo "use \"git stash pop\" when this script is complete to restore your changes"
+
+
+# Checkout develop - so we can update versions.
+# We need to checkout the branch before we start modifying files.
+current_branch=$(git branch --show-current)
```
Comment (joeljfischer) [inline scripts/release.sh:48]: Screen Shot 2022-07-25 at 1 49 38 PM

File: scripts/release.sh [hunk 11]
```diff
@@ -43,16 +41,54 @@ fi
...
+        # git fetch
+        git config pull.ff only
+        git pull
+        
+        # Now do the checkout
+        git checkout $develop_branch
+        
+        # check if the checkout was successful
+        current_branch=$(git branch --show-current)
+        if [ $current_branch == $develop_branch ]; then
```
Comment (joeljfischer) [inline scripts/release.sh:85]: Screen Shot 2022-07-25 at 1 50 50 PM

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: scripts/release.sh (hunk 1 above)
Comment (Swift2568) [reply scripts/release.sh:78]: I'll do soem testing with git pull --ff and see if that will work.

File: scripts/release.sh (hunk 10 above)
Comment (Swift2568) [reply scripts/release.sh:48]: That command works for me.  I can look for an alternative command that will work in more cases.

File: scripts/release.sh (hunk 11 above)
Comment (Swift2568) [reply scripts/release.sh:85]: This is related to the one above.  If I can find a different command for detecting the current branch that is checked out, this should resolve.

File: scripts/release.sh (hunk 9 above)
Comment (Swift2568) [reply scripts/release.sh:207]: I think we were at one time, and then we decided to copy the contents into the release script.  Then we decided to keep the generate script jsut in case we needed it.

I am testing calling it now and I may need to fix it before we can call it.

Comment (Swift2568) [reply scripts/release.sh:207]: I've got that fixed.

File: scripts/release.sh [hunk 12]
```diff
@@ -164,7 +192,15 @@ if [[ $? == 1 ]]; then
 
     # This runs Jazzy to generate the documentation.
     echo "Running Jazzy to generate documentation..."
-    jazzy --clean --objc --framework-root SmartDeviceLink --sdk iphonesimulator --umbrella-header SmartDeviceLink/public/SmartDeviceLink.h --theme theme --output docs
+    # generate-documentation.sh throws an error if we are not in the correct directorywhen we run it.
```
Comment (joeljfischer) [inline scripts/release.sh:195]:
```suggestion
    # generate-documentation.sh throws an error if we are not in the correct directory when we run it.
```

File: scripts/release.sh [hunk 13]
```diff
@@ -164,7 +192,15 @@ if [[ $? == 1 ]]; then
...
+    cd scripts
+    chmod u+x ./generate-documentation.sh
+    if [ $(uname -m) == "x86_64" ]; then
+        ./generate-documentation.sh
+    else
+        arch -x86_64 /bin/bash ./scripts/generate-documentation.sh
```
Comment (joeljfischer) [inline scripts/release.sh:201]: Why does one call `./generate-documentation.sh` and the other `./scripts/generate-documentation.sh`?

EDIT: Yup, looks like it fails on M1
Screen Shot 2022-07-28 at 9 24 01 AM

File: scripts/release.sh [hunk 14]
```diff
@@ -244,7 +297,11 @@ if [[ $? == 1 ]]; then
     # We pass in the version so that the framework script does not need to ask
     # Give the user permissions to the framework script, then run the script.
     chmod u+x ./scripts/create_framework.sh
-    ./scripts/create_framework.sh $new_version_number
+    if [ $(uname -m) == "x86_64" ]; then
+        ./scripts/create_framework.sh $new_version_number
+    else
+        arch -x86_64 /bin/bash ./scripts/create_framework.sh $new_version_number
```
Comment (joeljfischer) [inline scripts/release.sh:303]: This is not working on M1 at least:
Screen Shot 2022-07-28 at 9 35 52 AM

File: scripts/release.sh [hunk 15]
```diff
@@ -174,63 +210,80 @@ echo "If there is, please update the rpc_spec submodule to point to the newest c
...
+
+            echo "Please check that everything is correct."
+        
+            # Tag it
+            prompt_user "Would you like to tag this release with $new_version_number? (This will not push the tag)"
+            if [[ $? == 1 ]]; then
+                git tag $new_version_number
+            fi
+            
+
```
Comment (joeljfischer) [inline scripts/release.sh:252]:
```suggestion
```

File: scripts/release.sh [hunk 16]
```diff
@@ -174,63 +210,80 @@ echo "If there is, please update the rpc_spec submodule to point to the newest c
...
+            echo "If these changes are correct, please commit them manually and then push them to master..."
+            read user_input
+            # TODO - here are the commands if we decide to automate this.
+            # git commit -m "commit message here "
+            # git push --set-upstream origin $main_branch
+
```
Comment (joeljfischer) [inline scripts/release.sh:258]:
```suggestion
```

File: scripts/release.sh [hunk 17]
```diff
@@ -174,63 +210,80 @@ echo "If there is, please update the rpc_spec submodule to point to the newest c
...
+    echo
+    echo "$develop_branch has already been checked out for you."
 
-    # Merge release to master
-    prompt_user "Would you like to merge this release to master? (This will not push to master)"
+    prompt_user "Would you like to walk through the git commands for this release"
     if [[ $? == 1 ]]; then
-        # Checkout master
-        git checkout $main_branch
+
```
Comment (joeljfischer) [inline scripts/release.sh:221]:
```suggestion
```

File: scripts/release.sh [hunk 18]
```diff
@@ -43,31 +41,62 @@ fi
...
-    git reset --hard
+    echo
+    echo "Checkout of $develop_branch is required for some steps"
+    prompt_user "Would you like to automatically checkout $develop_branch"
+    if [[ $? == 1 ]]; then
+
+        # Stash any local changes to avoid errors during checkout
+        changes=$(git diff-files)
+        if [ ! -z "$changes" ]; then   
+            #git status
```
Comment (joeljfischer) [inline scripts/release.sh:59]:
```suggestion
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: scripts/release.sh (hunk 13 above)
Comment (Swift2568) [reply scripts/release.sh:197]: it looks like I added the cd to shorten the paths and then failed to fix both paths.  good catch.

File: scripts/release.sh (hunk 14 above)
Comment (Swift2568) [reply scripts/release.sh:296]: I think I have fixed this by using tar instead of zip.

File: scripts/release.sh [hunk 19]
```diff
@@ -43,31 +41,58 @@ fi
...
+    echo "Checkout of $develop_branch is required for some steps"
+    prompt_user "Would you like to automatically checkout $develop_branch"
+    if [[ $? == 1 ]]; then
+
+        # Stash any local changes to avoid errors during checkout
+        changes=$(git diff-files)
+        if [ ! -z "$changes" ]; then   
+            echo "There are unstaged changes in these files"
+            echo $changes
+            prompt_user "Would you like to stash these local changes before checkout of $develop_branch"
```
Comment (joeljfischer) [inline scripts/release.sh:61]: Screen Shot 2022-08-02 at 2 12 46 PM

After saying no to this prompt, this is what I saw. Don't know if it's expected.

File: scripts/create_framework.sh [hunk 20]
```diff
@@ -71,23 +71,23 @@ xcodebuild -create-xcframework -framework './SmartDeviceLink-Device.xcarchive/Pr
...
+framework_folder="SmartDeviceLink.xcframework"
 zip_file_name="SmartDeviceLink-$new_version_number.xcframework.zip"
 # Kill the old zip if present. Useful for re-running the script
 if [ -f $zip_file_name ]; then rm $zip_file_name; fi
-# Verify folder exists before acting on it.
-if [ -d "$folder" ]; then 
-    zip $zip_file_name $folder
+# Verify framework_folder exists and create a zip from it.
+if [ -d "$framework_folder" ]; then 
+    tar -cf $zip_file_name $framework_folder
```
Comment (joeljfischer) [inline scripts/create_framework.sh:80]: Screen Shot 2022-08-02 at 2 23 33 PM

No change :(

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: scripts/release.sh [hunk 21]
```diff
@@ -43,31 +41,58 @@ fi
...
+current_branch=$(git branch --show-current)
+if [ $current_branch == $develop_branch ]; then
+    echo
+    echo "$develop_branch is already checked out."
 else
-    # Dump local changes to prevent issues with checkout
-    git reset --hard
+    echo
+    echo "Checkout of $develop_branch is required for some steps"
+    prompt_user "Would you like to automatically checkout $develop_branch"
```
[the remark this answers is not in the document]
Comment (Swift2568) [reply scripts/release.sh:53]: 1. That text is the output of the git file-diff command.  I do not know what it means.  I can filter the output, but I figured it was not critical to the work we are doing.

2. Good question.  Clearly git file-diff thinks you do have changes.  Maybe I can find a better command, or write soem code to analyze and filter the file-diff output?

File: scripts/release.sh (hunk 19 above)
Comment (Swift2568) [reply scripts/release.sh:61]: This is expected.  The prompt is for stashing changes.  After stashing changes there is a checkout.  This is the checkout output.  I can maybe add some message in-between to give the user a sense that the "no" option did as expected.

Comment (Swift2568) [reply scripts/release.sh:61]: More accurately, a pull, and then a checkout of develop.

File: scripts/release.sh (hunk 21 above)
[the remark this answers is not in the document]
Comment (Swift2568) [reply scripts/release.sh:53]: I think I have fixed this.  I use `git status` instead of `git diff-files`.  Then I use `sed` to look for a 'dirty' response from `git status`.  I wasn't sure how to manipulate the `git status` into giving me a file list, so I went ahead and added the `sed` command to the `git diff-file` that will clean up the file list.  I also briefly considered a `git clean` but I think it is unnecessary for the checkout.

File: scripts/release.sh [hunk 22]
```diff
@@ -43,31 +41,58 @@ fi
...
+                git stash
+                echo "use \"git stash pop\" when this script is complete to restore your changes"
+            else
+                # Dump local changes to prevent issues with checkout
+                git reset --hard
+            fi
+        fi
+        
+        # Do a pull to make sure we are up to date.
+        git pull --ff
```
[the remark this answers is not in the document]
Comment (Swift2568) [reply scripts/release.sh]: It would probably be better to detect any kind of `git pull` failure, so I have added detection for that.  `git-pull` already reports out the failure, so I do not need an extra `echo` for that.

File: scripts/create_framework.sh (hunk 20 above)
Comment (Swift2568) [reply scripts/create_framework.sh:80]: We need to look closer at this.  In my testing the script did produce a good zip.  A diff of the contents to the original shows no changes.  They are identical.  I also tested manually running the command and right click-compress.

**Review by joeljfischer — APPROVED** [review]
I didn't want to actually commit, so I'll have to test the git commands during the next release 😄
