### PR TITLE
Fixed providing error info if video session is not started

### LINKED ISSUE #609: If starting video session fails, error is always nil
### The problem
When [SDLStreamingMediaManager startVideoSessionWithTLS:startBlock:] fails, error is never provided in the result block.

##### Suggestion:
I expect the problem is in sdl_configureVideoEncoderWithError method of SDLStreamingMediaManager.m (lines 419, 433, 442)

it’s

> if (*error != nil)

but I think it should be

> if (error != nil)

### PR DESCRIPTION
**Pull request by alexanderlavrushko**
Fixes #609 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Probably the only way to simulate a fail of VTCompressionSessionCreate (and other VideoToolbox functions) is to feed incorrect video session attributes to VideoToolbox, then we can expect a non-empty error in start video result block.

### Summary
Fixed the incorrect check of the error pointer - actually the code was always thinking that "there is no need to provide an error".

### CODE REVIEW

File: SmartDeviceLink/SDLStreamingMediaManager.m [hunk 1]
```diff
@@ -416,7 +416,7 @@ - (BOOL)sdl_configureVideoEncoderWithError:(NSError *__autoreleasing *)error {
 
     if (status != noErr) {
         // TODO: Log the error
-        if (*error != nil) {
+        if (error != nil) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLStreamingMediaManager.m]: These should be `if (error != NULL)` because we are comparing a reference pointer, not an Objective-C object.
