### PR TITLE
Fix SystemCapabilityManager windowID, screenParams nil, and mediaClockFormats empty when updating DisplayCapability

### LINKED ISSUE #2105: SystemCapabilityManager screenParams nil, mediaClockFormats empty, and windowID nil when they shouldn't be
### Bug Summary

When accessing `displayCapabilities` via the `systemCapabilityManager` screenParams and mediaClockFormats are empty. In `SDLSystemCapabilityManager` [line 710](https://github.com/smartdevicelink/sdl_ios/blob/develop/SmartDeviceLink/public/SDLSystemCapabilityManager.m#L710) the screenParams are not nil and mediaClockFormats are not empty. windowID is also nil from `defaultMainWindowCapability`

screenParams should not be nil in the `systemCapabilityManager`.
mediaClockFormats should not be in the `systemCapabilityManager`.
windowID should not be nil in `systemCapabilityManager`.

Java Suite had a similar [issue](https://github.com/smartdevicelink/sdl_java_suite/issues/1824) for screenParams.

### Reproduction Steps

1. Connect application to manticore.
2. Get the `displayCapabilities` property from the `systemCapabilityManager`.
3. Check the value of the `screenParams` and `mediaClockFormats`

```swift
let displayCapabilities = sdlManager.systemCapabilityManager.displayCapabilities
let windowCapability = sdlManager.systemCapabilityManager.defaultMainWindowCapability
let screenParams = displayCapabilities?.screenParams
let mediaClockFormats = displayCapabilities?.mediaClockFormats
let windowID = windowCapability?.windowID
```

Expected Behavior:
`screenParams` should not be nil.
`mediaClockFormats` should not be empty.
`windowID` should not be nil

Observed Behavior:
`screenParams` are nil.
`mediaClockFormats` are empty
`windowID` is nil

### iOS Version(s)

_No response_

### sdl_ios Version

7.5.0

### Testing Environment(s)

```markdown
Manticore v2.10.0
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jshivabeharry**
Fixes #2105 

### Risk
This PR makes no API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
- Added unit test in `SDLSystemCapabilityManagerSpec` to verify when updated `displayCapabilities` properties `screenParams` and `mediaClockFormats` stays the same.
- Unit test for if `windowID` is nil in `windowCapabilities` returns the `windowID` in `defaultMainWindowCapability` and `windowCapabilityWithWindowID`

#### Core Tests
- Accessed `screenParams` and `mediaClockFormats` from `systemCapabilityManager`
- Accessed `windowID` from `defaultMainWindowCapabilty` and `windowCapabiltyWithWindowID`

Core version / branch / commit hash / module tested against: sdl_core 8.1.0 (manticore)
HMI name / version / branch / commit hash / module tested against: generic_hmi 0.12.0 (manticore)

### Summary
- `sdl_updateDeprecatedDisplayCapabilities` sets the mediaClockFormats and screenParams to the initialized values.
- `windowCapabiltyWithWindowID` sets the windowID property before returning the `windowCapabilty`
- Unit test added in `SDLSystemCapabilityManagerSpec` for verifying `displayCapabilities` after update.
- Unit test added in `SDLSystemCapabiltyManagerSpec` to verify `windowID` was returned if set to nil

##### Breaking Changes
* NA

##### Enhancements
* NA

##### Bug Fixes
* windowID, screenParams, and mediaClockFormats are not nil or empty

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by jshivabeharry** [comment]
Updated  pull request and pushed change to reflect windowID is `nil` issue

File: SmartDeviceLink/public/SDLSystemCapabilityManager.m [hunk 1]
```diff
@@ -157,6 +157,7 @@ - (nullable SDLWindowCapability *)windowCapabilityWithWindowID:(NSUInteger)windo
         NSUInteger currentWindowID = windowCapability.windowID != nil ? windowCapability.windowID.unsignedIntegerValue : SDLPredefinedWindowsDefaultWindow;
         if (currentWindowID != windowID) { continue; }
 
+        windowCapability.windowID = [NSNumber<SDLUInt> numberWithUnsignedLong:windowID];
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLSystemCapabilityManager.m:160]:
```suggestion
        // A nil windowID is assumed to be the DefaultWindow according to the spec, but that can be hard for developers to check, so set it explicitly.
        windowCapability.windowID = [NSNumber numberWithUnsignedLong:currentWindowID];
```

I think this is a little clearer

File: SmartDeviceLink/public/SDLSystemCapabilityManager.m [hunk 2]
```diff
@@ -255,8 +256,10 @@ - (void)sdl_updateDeprecatedDisplayCapabilities {
     convertedCapabilities.imageFields = [defaultMainWindowCapabilities.imageFields copy];
     convertedCapabilities.templatesAvailable = [defaultMainWindowCapabilities.templatesAvailable copy];
     convertedCapabilities.numCustomPresetsAvailable = [defaultMainWindowCapabilities.numCustomPresetsAvailable copy];
-    convertedCapabilities.mediaClockFormats = @[]; // mandatory field but allows empty array
+    // Set to an empty list if no formats are available
+    convertedCapabilities.mediaClockFormats = self.displayCapabilities.mediaClockFormats ? self.displayCapabilities.mediaClockFormats : @[];
```
Comment (joeljfischer) [inline SmartDeviceLink/public/SDLSystemCapabilityManager.m:260]:
```suggestion
    convertedCapabilities.mediaClockFormats = self.displayCapabilities.mediaClockFormats ?: @[];
```

I didn't check, but I believe this is equivalent.

File: SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m [hunk 3]
```diff
@@ -702,6 +713,14 @@ @interface SDLSystemCapabilityManager ()
                 expect(testSystemCapabilityManager.defaultMainWindowCapability.textFields).to(haveCount(38));
                 expect(testSystemCapabilityManager.defaultMainWindowCapability.imageFields).to(haveCount(18));
             });
+
+            it(@"should retrieve window id if window id is missing in window capabilities", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m:717]:
```suggestion
            it(@"should set the default window id if window id is missing", ^{
```

File: SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m [hunk 4]
```diff
@@ -702,6 +713,14 @@ @interface SDLSystemCapabilityManager ()
...
+                // set window id to nil. windowID can be potentialy nil in real applications
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m:718]:
```suggestion
                // Set window id to nil. windowID can be potentially nil in real applications
```

File: SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m [hunk 5]
```diff
@@ -702,6 +713,14 @@ @interface SDLSystemCapabilityManager ()
...
+                testSystemCapabilityManager.displays[0].windowCapabilities[0].windowID = nil;
+
+                expect(testSystemCapabilityManager.defaultMainWindowCapability.windowID).to(equal(0));
+                expect([testSystemCapabilityManager windowCapabilityWithWindowID:0].windowID).to(equal(0));
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m:722]:
```suggestion
                expect(testSystemCapabilityManager.defaultMainWindowCapability.windowID).to(equal(SDLPredefinedWindowsDefaultWindow));
                expect([testSystemCapabilityManager windowCapabilityWithWindowID:0].windowID).to(equal(SDLPredefinedWindowsDefaultWindow));
```

File: SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m [hunk 6]
```diff
@@ -744,6 +763,40 @@ @interface SDLSystemCapabilityManager ()
 #pragma clang diagnostic pop
             }
         });
+
+        it(@"it should keep maintain screenParams and mediaClockFormats values in display capabilities", ^{
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m:767]: I feel like this should just be a part of the test above it?

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m [hunk 7]
```diff
@@ -702,18 +710,28 @@ @interface SDLSystemCapabilityManager ()
...
+                expect([testSystemCapabilityManager windowCapabilityWithWindowID:0].windowID).to(equal(SDLPredefinedWindowsDefaultWindow));
+            });
         });
     });
 
     // when updating display capabilities with OnSystemCapabilityUpdated
     describe(@"when updating display capabilities with OnSystemCapabilityUpdated", ^{
         it(@"should properly update display capability including conversion two times", ^{
+            // Set to display capabilities that have screenParams and mediaClockFormats set
+            testSystemCapabilityManager.displayCapabilities = testDisplayCapabilities;
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m:728]: Doesn't look like you have an expect for screen params or media clock formats?

**Review by joeljfischer — CHANGES_REQUESTED** [review]

**Review by joeljfischer — APPROVED** [review]
