### PR TITLE
Lockscreen bug fixes

### LINKED ISSUE #1480: "_lockWindow.rootViewController = _screenshotViewController" is set too early
_lockWindow.rootViewController = _screenshotViewController
this line code set too early, it caused our app UIWindow(should not be can rotated) changed to be can rotated.

Root cause from the code:
- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
if (self.currentAppWindow == nil) {
return UIInterfaceOrientationMaskAll;
}

- (BOOL)shouldAutorotate {
if (self.currentAppWindow == nil) {
return YES;
}

Suggetion to fix :
only when present viewcontroller, set the value.
when dissmiss, _lockWindow.rootViewController = nil.

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #1480, #1492, #1496, #1501 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Fixed unit test cases for the lock screen.

#### Core Tests
Smoke tests performed

Core version / branch / commit hash / module tested against: SYNC 3 v.3.4
HMI name / version / branch / commit hash / module tested against: SYNC 3 v3.4

### Summary
Fixed numerous issues with showing and dismissing the lock screen when the app has multiple `UIWindow`s. 
* Removed the `SDLScreenshotViewController` class  as no screenshot is needed to animate the transition and replaced it with the `SDLLockScreenRootViewController` class as it is needed to fix the status bar rotation bug.
* The lockscreen `UIWindow` is now created the first time the lock screen is presented and it is hidden when the lock screen is dismissed. When the session with the head unit is closed, the lock screen window is destroyed. Doing this means we don't have to keep track of the window over which the lock screen is being presented (Apple adds it's own private `UIWindow` for the keyboard to the app  so it is not as simple as grabbing the last window on the `UIApplication`'s `windows` array. Also there is no guarantee the top-most window is the currently visible content as the window could be clear or offscreen).  

##### Bug Fixes
* Fixed the wrong `UIWindow` being set when the lock screen was dismissed.
* Fixed the lock screen `UIWindow` being created as soon as the SDL app was started. Now it is created on the first presentation of the lock screen and destroyed when the session is closed.
* Fixed the lock screen sometimes having a wrong frame. 

### Tasks Remaining:
- [x] Fix test cases]
- [x] Comprehensive smoke tests - iOS 12
- [x] Comprehensive smoke tests - iOS 13

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SmartDeviceLink/SDLLockScreenRootViewController.m [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+- (void)viewDidLoad {
+    [super viewDidLoad];
+    self.view.backgroundColor = UIColor.clearColor;
+}
+
+#pragma mark - Orientation
+
+// HAX: https://github.com/smartdevicelink/sdl_ios/issues/1250
+- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
+    UIViewController *viewController = [self sdl_topMostControllerForWindow:[UIApplication sharedApplication].windows[0]];
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLockScreenRootViewController.m]: Should be fixed.

File: SmartDeviceLink/SDLLockScreenRootViewController.m [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+    if (viewController != nil) {
+        return viewController.supportedInterfaceOrientations;
+    }
+
+    return super.supportedInterfaceOrientations;
+}
+
+// HAX: https://github.com/smartdevicelink/sdl_ios/issues/1250
+- (BOOL)shouldAutorotate {
+    UIViewController *viewController = [self sdl_topMostControllerForWindow:[UIApplication sharedApplication].windows[0]];
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLockScreenRootViewController.m]: Should be fixed.

**Comment by NicoleYarroch** [comment]
> I was still able to get it into a state where the TDK says DD on but the lock screen is not displayed by pressing the button quickly.

After looking into this I think this should be a separate issue as it would require a revamp of the lock screen presenter to ensure presentation/dismissal of the lock screen is atomic. Otherwise, if the lock screen is present, dismissed and presented again in quick succession the lock screen will not show up on the last presentation because it is already presenting. If I ignore the check to see if the lock screen is already presenting, sometimes the app crashes with the error `Application tried to present modally an active controller`. 
 
Currently:
1. This bug only happens when I click on the "moving/parked" button as fast as I possibly can.
1. The lock screen does show up the next time I toggle the "moving/parked" button.

File: SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m [hunk 3]
```diff
@@ -80,7 +80,7 @@ @interface SDLLockScreenManager ()
                 });
                 
                 it(@"should not have presented the lock screen", ^{
-                    expect(@(fakePresenter.presented)).to(beFalsy());
+                     expect(fakePresenter.presented).toEventually(beFalse());
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]:
```suggestion
                    expect(fakePresenter.presented).toEventually(beFalse());
```

File: SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m [hunk 4]
```diff
@@ -48,7 +48,7 @@ @interface SDLLockScreenManager ()
         
         it(@"should set properties correctly", ^{
             // Note: We can't check the "lockScreenPresented" flag on the Lock Screen Manager because it's a computer property checking the window
-            expect(fakePresenter.presented).to(beFalse());
+            expect(fakePresenter.presented).toEventually(beFalse());
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]: I tested keeping these as `to` and they still work. Why were they moved to `toEventually`?

File: SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m [hunk 5]
```diff
@@ -409,13 +409,13 @@ @interface SDLLockScreenManager ()
 
         beforeEach(^{
             mockViewControllerPresenter = OCMClassMock([SDLFakeViewControllerPresenter class]);
+            //OCMClassMock([SDLFakeViewControllerPresenter class]);
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]: Remove?

File: SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m [hunk 6]
```diff
@@ -433,11 +433,12 @@ @interface SDLLockScreenManager ()
 
             it(@"should present the lock screen if not already presented", ^{
                 OCMStub([mockViewControllerPresenter lockViewController]).andReturn([OCMArg any]);
-                OCMStub([mockViewControllerPresenter presented]).andReturn(false);
 
                 [[NSNotificationCenter defaultCenter] postNotification:testLockStatusNotification];
 
-                OCMVerify([mockViewControllerPresenter present]);
+                // Since lock screen must be presented/dismissed on the main thread, force the test to execute manually on the main thread. If this is not done, the test case may fail.
+                [[NSRunLoop mainRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:0.01]];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]: Does `dispatch_sync` work for this case?

File: SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m [hunk 7]
```diff
@@ -455,11 +456,12 @@ @interface SDLLockScreenManager ()
 
             it(@"should dismiss the lock screen if already presented", ^{
                 OCMStub([mockViewControllerPresenter lockViewController]).andReturn([OCMArg any]);
-                OCMStub([mockViewControllerPresenter presented]).andReturn(true);
 
                 [[NSNotificationCenter defaultCenter] postNotification:testLockStatusNotification];
 
-                OCMVerify([mockViewControllerPresenter dismiss]);
+                // Since lock screen must be presented/dismissed on the main thread, force the test to execute manually on the main thread. If this is not done, the test case may fail.
+                [[NSRunLoop mainRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:0.01]];
```
Comment (joeljfischer) [inline SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]: See above

File: SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m (hunk 4 above)
Comment (NicoleYarroch) [reply SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]: They are failing for me if I keep them as `to`s. The old code did not wait for the main thread, but the new code does. Maybe it depends on how fast your computer is?

Comment (joeljfischer) [reply SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]: Odd. It shouldn't. `to`s are synchronous so it shouldn't be dependent on the speed of the computer.

File: SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m (hunk 6 above)
Comment (NicoleYarroch) [reply SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]: I tried it and it crashed.

File: SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m (hunk 7 above)
Comment (NicoleYarroch) [reply SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]: I tried it and it crashed.

File: SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m (hunk 6 above)
Comment (joeljfischer) [reply SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]: Is that because it's already on the main queue?

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 8]
```diff
@@ -31,241 +31,168 @@ - (instancetype)init {
...
-
-    // We let ourselves know that the lockscreen will present, because we have to pause streaming video for that 0.3 seconds or else it will be very janky.
-    [[NSNotificationCenter defaultCenter] postNotificationName:SDLLockScreenManagerWillPresentLockScreenViewController object:nil];
+    SDLLogD(@"Presenting the lockscreen window");
+    [self.lockWindow makeKeyAndVisible];
 
-    CGRect firstFrame = appWindow.frame;
-    firstFrame.origin.x = CGRectGetWidth(firstFrame);
-    appWindow.frame = firstFrame;
+    if ([self sdl_isPresented]) {
```
[the remark this answers is not in the document]
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLockScreenPresenter.m]: I renamed `sdl_isPresented` to `sdl_isPresentedOrPresenting` and `sdl_isBeingDismissed` to `sdl_isDismissing`. I also renamed `presented` to `showLockScreen`

File: SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m (hunk 4 above)
Comment (NicoleYarroch) [reply SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]: They fail on Travis too if I use `to`

File: SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m (hunk 5 above)
Comment (NicoleYarroch) [reply SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]: Fixed.

File: SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m (hunk 4 above)
Comment (joeljfischer) [reply SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m]: Weird. I don't know why it worked for me then.

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 9]
```diff
@@ -8,17 +8,17 @@
...
 
 
 NS_ASSUME_NONNULL_BEGIN
 
 @interface SDLLockScreenPresenter ()
 
-@property (strong, nonatomic) SDLScreenshotViewController *screenshotViewController;
-@property (strong, nonatomic) UIWindow *lockWindow;
+@property (strong, nonatomic, nullable) UIWindow *lockWindow;
+@property (assign, nonatomic) BOOL showLockScreen;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLockScreenPresenter.m]:
```suggestion
@property (assign, nonatomic) BOOL shouldShowLockScreen;
```

Would this be a more appropriate name?

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 10]
```diff
@@ -31,241 +31,173 @@ - (instancetype)init {
...
-        }
-    });
-}
+- (void)stop {
+    self.showLockScreen = NO;
 
-- (void)sdl_presentIOS12 {
-    if (self.lockWindow.isKeyWindow) {
-        SDLLogW(@"Attempted to present lock window when it is already presented");
+    if (!self.lockWindow) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLockScreenPresenter.m]:
```suggestion
    if (self.lockWindow == nil) {
```

In general, I prefer when checking nil to do the explicit check. This isn't entirely consistent across the project, but I think it reads more clearly.

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 11]
```diff
@@ -31,241 +31,173 @@ - (instancetype)init {
...
+        [weakSelf sdl_presentLockscreenWithCompletionHandler:completionHandler];
+    });
 }
 
-- (void)sdl_presentWithAppWindow:(nullable UIWindow *)appWindow {
-    if (appWindow == nil) {
-        SDLLogW(@"Attempted to present lock window but app window is nil");
-        return;
+- (void)sdl_presentLockscreenWithCompletionHandler:(void (^ _Nullable)(void))completionHandler {
+    if (!self.lockWindow) {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLockScreenPresenter.m]:
```suggestion
    if (self.lockWindow == nil) {
```

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 12]
```diff
@@ -31,241 +31,173 @@ - (instancetype)init {
...
-        });
-    }
+/// Returns whether or not the lockViewController is presented or currently animating
+- (BOOL)sdl_isPresentedOrPresenting {
+    return (self.lockViewController.isViewLoaded && (self.lockViewController.view.window || self.lockViewController.isBeingPresented) && self.lockWindow.isKeyWindow);
+}
 
-    return isPresented;
+/// Returns whether or not the lockViewController is currently animating
+- (BOOL)sdl_isDismissing {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLockScreenPresenter.m]: Instead of private functions, this could be a private property with this as the getter. Then you can get rid of the `sdl_` and refer to it with dot-syntax.

File: SmartDeviceLink/SDLLockScreenPresenter.m [hunk 13]
```diff
@@ -31,241 +31,173 @@ - (instancetype)init {
...
-    __block BOOL isPresented = NO;
-    if ([NSThread isMainThread]) {
-        isPresented = [self sdl_presented];
-    } else {
-        dispatch_sync(dispatch_get_main_queue(), ^{
-            isPresented = [self sdl_presented];
-        });
-    }
+/// Returns whether or not the lockViewController is presented or currently animating
+- (BOOL)sdl_isPresentedOrPresenting {
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLockScreenPresenter.m]: Instead of private functions, this could be a private property with this as the getter. Then you can get rid of the `sdl_` and refer to it with dot-syntax.

File: SmartDeviceLink/SDLViewControllerPresentable.h [hunk 14]
```diff
@@ -8,15 +8,24 @@
...
+/// A protocol used to tell a view controller to present another view controller. This makes testing of modal VCs' presentation easier.
 @protocol SDLViewControllerPresentable <NSObject>
 
-@property (strong, nonatomic) UIViewController *lockViewController;
-@property (assign, nonatomic, readonly) BOOL presented;
+/// The view controller to be presented as a lockscreen
+@property (strong, nonatomic, nullable) UIViewController *lockViewController;
+
+/// Whether or not the lockscreen should be presented
+@property (assign, nonatomic, readonly) BOOL showLockScreen;
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLViewControllerPresentable.h]: This would need to be updated if the above is updated.

File: SmartDeviceLink/SDLLockScreenPresenter.m (hunk 9 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLockScreenPresenter.m]: Fixed. Renamed.

File: SmartDeviceLink/SDLLockScreenPresenter.m (hunk 10 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLockScreenPresenter.m]: Fixed.

File: SmartDeviceLink/SDLLockScreenPresenter.m (hunk 11 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLockScreenPresenter.m]: Fixed.

File: SmartDeviceLink/SDLLockScreenPresenter.m (hunk 12 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLockScreenPresenter.m]: Fixed.

File: SmartDeviceLink/SDLLockScreenPresenter.m (hunk 13 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLockScreenPresenter.m]: Fixed.

File: SmartDeviceLink/SDLViewControllerPresentable.h (hunk 14 above)
Comment (NicoleYarroch) [reply SmartDeviceLink/SDLViewControllerPresentable.h]: Fixed.

File: SmartDeviceLink/SDLLockScreenManager.h [hunk 15]
```diff
@@ -15,6 +15,19 @@
 
 NS_ASSUME_NONNULL_BEGIN
 
+/// Manages presenting and dismissing the lock screen based on several settings:
+/// 1. The lock screen configuration set by the developer. If the set to the default configuration, the lock screen manager will show or hide the lockscreen based on the the current `hmiLevel` of the SDL app and the current driver distraction (DD) status. However, the developer can also set the lockscreen to always show or not show at all.
+/// 2. Whether the passenger has dismissed the lockscreen (RPC v.6.0+). Once the passenger has dismissed the lockscreen, it will not be shown again during the same session.
+///
+/// | LockScreenStatus | HMILevel       | DD  |
```
Comment (joeljfischer) [inline SmartDeviceLink/SDLLockScreenManager.h]: It seems like DD and LockScreenStatus columns should change? DD and HMILevel are the input and LockScreenStatus is the output, right?

Comment (NicoleYarroch) [reply SmartDeviceLink/SDLLockScreenManager.h]: Fixed.
